### ISSUE TITLE
Pytorch's nn.BatchNorm2d does not work in TorchModel()

### ISSUE THREAD

**Issue by AustinApple** [secretflow/secretflow#1009]
### Issue Type

Bug

### Source

binary

### Secretflow Version

SecretFlow 1.2.0.dev20231009

### OS Platform and Distribution

macOS 13.2.1 (22D68)

### Python version

Python 3.8.18

### What happend and What you expected to happen.
It seems that Pytorch's nn.BatchNorm2d does not work in TorchModel(). I found if nn.BatchNorm2d is included in the model, the following error would occur. While I removed them from the model, the code can run normally.
```shell
Traceback (most recent call last):
  File "batchnorm_error_reproduce.py", line 187, in <module>
    history = fl_model.fit(
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 453, in fit
    initial_weight = self.initialize_weights()
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 123, in initialize_weights
    initial_weight = self._aggregator.average(clients_weights, axis=0)
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/security/aggregation/secure_aggregator.py", line 297, in average
    return self._device(_average)(
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 98, in wrapper
    sfd.remote(self._run)
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 107, in _remote
    args, kwargs = _resolve_args(*args, **kwargs)
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 97, in _resolve_args
    actual_vals = ray.get(list(refs.values()))
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::_Masker.mask() (pid=94879, ip=127.0.0.1, repr=<secretflow.security.aggregation.secure_aggregator._Masker object at 0x7f934f471bb0>)
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/Users/mwu11/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/security/aggregation/secure_aggregator.py", line 76, in mask
    assert (
AssertionError: Data should have same dtypes but got int64 float32.
```

### Reproduction code to reproduce the issue.

```shell
from tqdm import tqdm
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data as data
import torchvision.transforms as transforms

import medmnist
from medmnist import INFO, Evaluator


import secretflow as sf
from secretflow.ml.nn.utils import BaseModule, TorchModel
from secretflow.ml.nn.fl.utils import metric_wrapper, optim_wrapper
from secretflow.ml.nn import FLModel
from torchmetrics.classification import Accuracy, Precision
from secretflow.security.aggregation import SecureAggregator
from secretflow.utils.simulation.datasets import load_mnist
from torch.nn import functional as F
from secretflow.data.ndarray import load

data_flag = 'dermamnist'
# data_flag = 'breastmnist'
download = True

NUM_EPOCHS = 3
BATCH_SIZE = 128
lr = 0.001

info = INFO[data_flag]
task = info['task']
n_channels = info['n_channels']
n_classes = len(info['label'])

print(f'n_channels: {n_channels}')
print(f'n_classes: {n_classes}')

DataClass = getattr(medmnist, info['python_class'])

# preprocessing
data_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[.5], std=[.5])
])

# load the data
train_dataset = DataClass(split='train', transform=data_transform, download=download)
val_dataset = DataClass(split='val', transform=data_transform, download=download)
test_dataset = DataClass(split='test', transform=data_transform, download=download)

# encapsulate data into dataloader form
train_loader = data.DataLoader(dataset=train_dataset, batch_size=BATCH_SIZE, shuffle=True)
train_loader_at_eval = data.DataLoader(dataset=train_dataset, batch_size=2*BATCH_SIZE, shuffle=False)
val_loader = data.DataLoader(dataset=val_dataset, batch_size=2*BATCH_SIZE, shuffle=False)
test_loader = data.DataLoader(dataset=test_dataset, batch_size=2*BATCH_SIZE, shuffle=False)


class Net(BaseModule):
    def __init__(self):
        super(Net, self).__init__()

        self.layer1 = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3),
            nn.BatchNorm2d(16),
            nn.ReLU())

        self.layer2 = nn.Sequential(
            nn.Conv2d(16, 16, kernel_size=3),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))

        self.layer3 = nn.Sequential(
            nn.Conv2d(16, 64, kernel_size=3),
            nn.BatchNorm2d(64),
            nn.ReLU())
        
        self.layer4 = nn.Sequential(
            nn.Conv2d(64, 64, kernel_size=3),
            nn.BatchNorm2d(64),
            nn.ReLU())

        self.layer5 = nn.Sequential(
            nn.Conv2d(64, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))

        self.fc = nn.Sequential(
            nn.Linear(64 * 4 * 4, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, 7))

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        x = self.layer5(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x
    


# Check the version of your SecretFlow
print('The version of SecretFlow: {}'.format(sf.__version__))

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob', 'charlie'], address='local')
alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')


train_x_alice = train_dataset.imgs[:len(train_dataset)//2]
train_x_bob = train_dataset.imgs[len(train_dataset)//2:]

train_x_alice = np.transpose(train_x_alice, (0, 3, 1, 2))
train_x_bob = np.transpose(train_x_bob, (0, 3, 1, 2))


train_y_alice = train_dataset.labels[:len(train_dataset)//2]
train_y_bob = train_dataset.labels[len(train_dataset)//2:]


val_x_alice = val_dataset.imgs[:len(val_dataset)//2]
val_x_bob = val_dataset.imgs[len(val_dataset)//2:]

val_x_alice = np.transpose(val_x_alice, (0, 3, 1, 2))
val_x_bob = np.transpose(val_x_bob, (0, 3, 1, 2))


val_y_alice = val_dataset.labels[:len(val_dataset)//2]
val_y_bob = val_dataset.labels[len(val_dataset)//2:]



np.save('train_x_alice.npy', train_x_alice)
np.save('train_x_bob.npy', train_x_bob)
np.save('train_y_alice.npy', train_y_alice)
np.save('train_y_bob.npy', train_y_bob)

np.save('val_x_alice.npy', val_x_alice)
np.save('val_x_bob.npy', val_x_bob)
np.save('val_y_alice.npy', val_y_alice)
np.save('val_y_bob.npy', val_y_bob)


train_x = load({alice: 'train_x_alice.npy', bob: 'train_x_bob.npy'}, partition_way='horizontal')
train_y = load({alice: 'train_y_alice.npy', bob: 'train_y_bob.npy'}, partition_way='horizontal')

val_x = load({alice: 'val_x_alice.npy', bob: 'val_x_bob.npy'}, partition_way='horizontal')
val_y = load({alice: 'val_y_alice.npy', bob: 'val_y_bob.npy'}, partition_way='horizontal')


loss_fn = nn.CrossEntropyLoss

optim_fn = optim_wrapper(optim.Adam, lr=1e-3)


model_def = TorchModel(model_fn=Net, 
                       loss_fn=loss_fn, 
                       optim_fn=optim_fn,
                       metrics=[
                           metric_wrapper(Accuracy, task="multiclass", num_classes=7, average='micro'),
                           metric_wrapper(Precision, task="multiclass", num_classes=7, average='micro')
                       ],)

device_list = [alice, bob]
server = charlie
aggregator = SecureAggregator(server, [alice, bob])

# spcify params
fl_model = FLModel(
    server=server,
    device_list=device_list,
    model=model_def,
    aggregator=aggregator,
    strategy='fed_avg_w',  # fl strategy
    backend="torch",  # backend support ['tensorflow', 'torch']
)

history = fl_model.fit(
    train_x,
    train_y,
    validation_data=(val_x, val_y),
    epochs=1,
    batch_size=128,
    aggregate_freq=1,
)
```

**Comment by wangyixianggogo** [comment]
Hello, we will reply to you after internal discussion

**Comment by fy222fy** [comment]
When using nn.BatchNorm2d, the num_batches_tracked model weight's type is torch.int64 while other weight is torch.float32. The SecureAggregator (same in PlainAggregator) does not support different types in average. 

In fact, BN is different from other models. In the scenario of federated learning, the BN model should only be operated locally and should not be aggregated. There are currently relevant solutions ([https://arxiv.org/abs/2102.07623](https://arxiv.org/abs/2102.07623) , also see [https://zhuanlan.zhihu.com/p/551722592](https://zhuanlan.zhihu.com/p/551722592)), and the main idea is to extract the BN layer from the model and not perform aggregation.

You can try write your own Aggregator for processing. BTW, we have plans to implement and release the task of FedBN in secretflow. If you are interested, you are welcome to participate!
