### ISSUE TITLE
[FL/TensorFlow] 联邦学习微调大模型GPT-2报错

### ISSUE THREAD

**Issue by Mingbo-Lee** [secretflow/secretflow#1018]
### Issue Type

Bug

### Source

binary

### Secretflow Version

SecretFlow  1.2.0.dev20231009

### OS Platform and Distribution

Linux Ubuntu 20.04.6 LTS

### Python version

3.8

### Bazel version

/

### GCC/Compiler version

/

### What happend and What you expected to happen.

```shell
基于将单机模型迁移到隐语的联邦学习环境之下，试着微调GPT-2模型，出现报错。
看起来，隐语的联邦学习没有完全实现tensorflow的一些函数调用
```

### Reproduction code to reproduce the issue.

```shell
模型定义代码：
```
```python
def create_gpt2_llm():
    def create_model():
        from tensorflow import keras

        # Create model
        preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset(
            "gpt2_base_en",
            sequence_length=MAX_SEQUENCE_LENGTH,
        )

        gpt2_lm = keras_nlp.models.GPT2CausalLM.from_preset(
            "gpt2_base_en", preprocessor=preprocessor
        )

        optimizer, loss = get_optimizer_and_loss()

        # Compile model
        gpt2_lm.compile(
            optimizer=optimizer,
            loss=loss,
            weighted_metrics=["accuracy"],
        )
        return model

    return create_model
```

涉及函数的定义：
```python

def get_optimizer_and_loss():
    optimizer = keras.optimizers.AdamW(
        learning_rate=5e-5,
        weight_decay=0.01,
        epsilon=1e-6,
        global_clipnorm=1.0,  # Gradient clipping.
    )
    # Exclude layernorm and bias terms from weight decay.
    optimizer.exclude_from_weight_decay(var_names=["bias"])
    optimizer.exclude_from_weight_decay(var_names=["gamma"])
    optimizer.exclude_from_weight_decay(var_names=["beta"])

    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    return optimizer, loss

```
后续代码：
```python
# keras model
model = create_gpt2_llm()


fed_model = FLModel(
    device_list=device_list,
    model=model,
    aggregator=aggregator,
    backend="tensorflow",
    strategy="fed_avg_w",
    random_seed=1234,
)

epochs = 1
batch_size = 16
aggregate_freq = 2
sampler_method = "batch"
random_seed = 1234
dp_spent_step_freq = 1
history = fed_model.fit(
    data,
    None,
    validation_data=data,
    epochs=epochs,
    batch_size=batch_size,
    aggregate_freq=aggregate_freq,
    sampler_method=sampler_method,
    random_seed=random_seed,
    dp_spent_step_freq=dp_spent_step_freq,
    dataset_builder=data_builder_dict,
    # callbacks=[gpu_memory_callback],
)

```

出现报错：
```
---------------------------------------------------------------------------
RayTaskError(AttributeError)              Traceback (most recent call last)
/home/limingbo/project/oscp/GPT2/parameter_efficient_finetuning_of_gpt2_with_lora.ipynb 单元格 59 line 1
----> 1 history = fed_model.fit(
      2     data,
      3     None,
      4     validation_data=data,
      5     epochs=epochs,
      6     batch_size=batch_size,
      7     aggregate_freq=aggregate_freq,
      8     sampler_method=sampler_method,
      9     random_seed=random_seed,
     10     dp_spent_step_freq=dp_spent_step_freq,
     11     dataset_builder=data_builder_dict,
     12     # callbacks=[gpu_memory_callback],
     13 )

File /opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py:453, in FLModel.fit(self, x, y, batch_size, batch_sampling_rate, epochs, verbose, callbacks, validation_data, shuffle, class_weight, sample_weight, validation_freq, aggregate_freq, label_decoder, max_batch_size, prefetch_buffer_size, sampler_method, random_seed, dp_spent_step_freq, audit_log_dir, dataset_builder, wait_steps)
    439     train_steps_per_epoch = self._handle_data(
    440         train_x,
    441         train_y,
ref='/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py:0'>0</a>;32m   (...)
    449         dataset_builder=dataset_builder,
    450     )
    451 history = History()
--> 453 initial_weight = self.initialize_weights()
    454 logging.debug(f"initial_weight: {initial_weight}")
    455 server_weight = None

File /opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py:123, in FLModel.initialize_weights(self)
    121     clients_weights.append(weights)
    122 if self._aggregator is not None:
--> 123     initial_weight = self._aggregator.average(clients_weights, axis=0)
    124     for device, worker in self._workers.items():
    125         weights = (
    126             initial_weight.to(device) if initial_weight is not None else None
    127         )

File /opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/security/aggregation/secure_aggregator.py:294, in SecureAggregator.average(self, data, axis, weights)
    292 masked_data = [d.to(self._device) for d in masked_data]
    293 dtypes = [dtype.to(self._device) for dtype in dtypes]
--> 294 return self._device(_average)(
    295     *masked_data, dtypes=dtypes, weights=_weights, fxp_bits=self._fxp_bits
    296 )

File /opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/device/device/pyu.py:98, in PYU.__call__.<locals>.wrapper(*args, **kwargs)
     92 args_, kwargs_ = jax.tree_util.tree_map(
     93     lambda arg: try_get_data(arg, self), (args, kwargs)
     94 )
     96 _num_returns = check_num_returns(fn) if num_returns is None else num_returns
     97 data = (
---> 98     sfd.remote(self._run)
     99     .party(self.party)
    100     .options(num_returns=_num_returns)
    101     .remote(fn, *args_, **kwargs_)
    102 )
    103 logging.debug(
    104     (
    105         f'PYU remote function: {fn}, num_returns={num_returns}, '
    106         f'args len: {len(args)}, kwargs len: {len(kwargs)}.'
    107     )
    108 )
    109 if _num_returns == 1:

File /opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/ray/remote_function.py:226, in RemoteFunction.options.<locals>.FuncWrapper.remote(self, *args, **kwargs)
    225 def remote(self, *args, **kwargs):
--> 226     return func_cls._remote(args=args, kwargs=kwargs, **updated_options)

File /opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py:107, in RemoteFunctionWrapper._remote(self, *args, **kwargs)
    106 def _remote(self, *args, **kwargs):
--> 107     args, kwargs = _resolve_args(*args, **kwargs)
    108     return super()._remote(*args, **kwargs)

File /opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py:97, in _resolve_args(*args, **kwargs)
     92 arg_flat, arg_tree = jax.tree_util.tree_flatten((args, kwargs))
     93 refs = {
     94     pos: arg for pos, arg in enumerate(arg_flat) if isinstance(arg, ray.ObjectRef)
     95 }
---> 97 actual_vals = ray.get(list(refs.values()))
     98 for pos, actual_val in zip(refs.keys(), actual_vals):
     99     arg_flat[pos] = actual_val

File /opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File /opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
   2307     worker.core_worker.dump_object_store_memory_usage()
   2308 if isinstance(value, RayTaskError):
-> 2309     raise value.as_instanceof_cause()
   2310 else:
   2311     raise value

RayTaskError(AttributeError): ray::_Masker.mask() (pid=1427667, ip=10.24.93.11, repr=<secretflow.security.aggregation.secure_aggregator._Masker object at 0x7f5e6faf5ee0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::PYUFedAvgW.get_weights() (pid=1430402, ip=10.24.93.11, repr=<secretflow.ml.nn.fl.backend.tensorflow.strategy.fed_avg_w.PYUFedAvgW object at 0x7f22a5f2d4c0>)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  [Previous line repeated 7 more times]
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/tensorflow/fl_base.py", line 211, in get_weights
    return self.model.get_weights()
AttributeError: 'function' object has no attribute 'get_weights'
```
```

**Comment by zhangxingmeng** [comment]
![image](https://github.com/secretflow/secretflow/assets/103552200/4bf8de75-ccb9-4530-ad82-cf0d4a0f08fa)
这里好像不太对，x细节辛苦先检查下？这里说的问题就是内部获取到的model不是个model是个funciton

**Comment by Mingbo-Lee** [comment]
单机模式下的代码：
```python
import keras_nlp
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_datasets as tfds
import time

from tensorflow import keras

policy = keras.mixed_precision.Policy("mixed_float16")
keras.mixed_precision.set_global_policy(policy)


# General hyperparameters
BATCH_SIZE = 16
NUM_BATCHES = 500
EPOCHS = 1  # Can be set to a higher value for better results
MAX_SEQUENCE_LENGTH = 128
MAX_GENERATION_LENGTH = 200

GPT2_PRESET = "gpt2_base_en"

# LoRA-specific hyperparameters
RANK = 4
ALPHA = 32.0

reddit_ds = tfds.load("reddit_tifu", split="train", as_supervised=True)

for document, title in reddit_ds:
    print(document.numpy())
    print(title.numpy())
    break


train_ds = (
    reddit_ds.map(lambda document, _: document)
    .batch(BATCH_SIZE)
    .cache()
    .prefetch(tf.data.AUTOTUNE)
)
train_ds = train_ds.take(NUM_BATCHES)

len(train_ds)



def generate_text(model, input_text, max_length=200):
    start = time.time()

    output = model.generate(input_text, max_length=max_length)
    print("\nOutput:")
    print(output)

    end = time.time()
    print(f"Total Time Elapsed: {end - start:.2f}s")


def get_optimizer_and_loss():
    optimizer = keras.optimizers.AdamW(
        learning_rate=5e-5,
        weight_decay=0.01,
        epsilon=1e-6,
        global_clipnorm=1.0,  # Gradient clipping.
    )
    # Exclude layernorm and bias terms from weight decay.
    optimizer.exclude_from_weight_decay(var_names=["bias"])
    optimizer.exclude_from_weight_decay(var_names=["gamma"])
    optimizer.exclude_from_weight_decay(var_names=["beta"])

    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    return optimizer, loss


preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset(
    "gpt2_base_en",
    sequence_length=MAX_SEQUENCE_LENGTH,
)
gpt2_lm = keras_nlp.models.GPT2CausalLM.from_preset(
    "gpt2_base_en", preprocessor=preprocessor
)

gpt2_lm.summary()



optimizer, loss = get_optimizer_and_loss()

gpt2_lm.compile(
    optimizer=optimizer,
    loss=loss,
    weighted_metrics=["accuracy"],
)


gpt2_lm.fit(train_ds, epochs=EPOCHS)

```

可以在 jupyter notebook 环境正常运行

![2023-11-09_162728](https://github.com/secretflow/secretflow/assets/51162830/900da33c-c229-40e6-a6a9-68d9a5b027aa)
