### ISSUE TITLE
b'GCS has started but no raylets have registered yet

### ISSUE THREAD

**Issue by wind-and-falling-maple-leaf** [secretflow/secretflow#102]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow        0.6.13b1

### OS Platform and Distribution

centos 7.6

### Python version

Python 3.8.11

### GCC/Compiler version

gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

### What happend and What you expected to happen.

```shell
1.我在本地两台虚拟机上运行了一个Ray集群：启动命令：
头节点 
ray start --head --node-ip-address="192.168.14.132" --port="6379" --resources='{"alice": 4}' --include-dashboard=False --disable-usage-stats
(ray) [root@localhost ~]# lsof -i:6379
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python    18883 root   17u  IPv6 137780      0t0  TCP localhost.localdomain:38194->localhost.localdomain:6379 (ESTABLISHED)
python    18883 root   21u  IPv6 141456      0t0  TCP localhost.localdomain:38218->localhost.localdomain:6379 (ESTABLISHED)
gcs_serve 19305 root   16u  IPv6 141427      0t0  TCP *:6379 (LISTEN)
gcs_serve 19305 root   20u  IPv6 140596      0t0  TCP localhost.localdomain:6379->localhost.localdomain:38194 (ESTABLISHED)
gcs_serve 19305 root   21u  IPv6 137850      0t0  TCP localhost.localdomain:6379->localhost.localdomain:38216 (ESTABLISHED)
gcs_serve 19305 root   22u  IPv6 137852      0t0  TCP localhost.localdomain:6379->localhost.localdomain:38218 (ESTABLISHED)
gcs_serve 19305 root   26u  IPv6 140650      0t0  TCP localhost.localdomain:6379->localhost.localdomain:38206 (ESTABLISHED)
gcs_serve 19305 root   27u  IPv6 140652      0t0  TCP localhost.localdomain:6379->localhost.localdomain:38208 (ESTABLISHED)
gcs_serve 19305 root   28u  IPv6 139967      0t0  TCP localhost.localdomain:6379->localhost.localdomain:38210 (ESTABLISHED)
python    19323 root   10u  IPv6 140649      0t0  TCP localhost.localdomain:38206->localhost.localdomain:6379 (ESTABLISHED)
python    19323 root   14u  IPv6 137831      0t0  TCP localhost.localdomain:38208->localhost.localdomain:6379 (ESTABLISHED)
python    19330 root   12u  IPv6 140675      0t0  TCP localhost.localdomain:38216->localhost.localdomain:6379 (ESTABLISHED)
python    19348 root   11u  IPv6 141448      0t0  TCP localhost.localdomain:38210->localhost.localdomain:6379 (ESTABLISHED)
工作节点：
ray start --address='192.168.14.132:6379' --resources='{"bob": 4}' --disable-usage-stats

2.当我在头节点的Python编译器中
>>> import secretflow as sf
>>> sf.init(address='192.168.14.132:6379')
2022-08-28 23:21:47,545 INFO worker.py:1333 -- Connecting to existing Ray cluster at address: 192.168.14.132:6379...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/secretflow/device/driver.py", line 228, in init
    ray.init(
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/worker.py", line 1475, in init
    _global_node = ray._private.node.Node(
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/node.py", line 226, in __init__
    node_info = ray._private.services.get_node_to_connect_for_driver(
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/services.py", line 395, in get_node_to_connect_for_driver
    return global_state.get_node_to_connect_for_driver(node_ip_address)
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/state.py", line 729, in get_node_to_connect_for_driver
    node_info_str = self.global_state_accessor.get_node_to_connect_for_driver(
  File "python/ray/includes/global_state_accessor.pxi", line 155, in ray._raylet.GlobalStateAccessor.get_node_to_connect_for_driver
RuntimeError: b'GCS has started but no raylets have registered yet.'

3.我不知道该怎么进行下去了，求教！！
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf
sf.init(address='192.168.14.132:6379')
```

**Comment by wind-and-falling-maple-leaf** [comment]
> 可以检查下你的ray启动是否成功，在两个节点上分别执行ray status看下状态。

1 当我马上执行ray status时看起来没有任何节点被启动了
(ray) [root@localhost ~]# ray status
No cluster status.

2我尝试stop后再start，再次执行 ray status
(ray) [root@localhost ~]# ray status
======== Autoscaler status: 2022-08-28 23:58:46.723929 ========
Node status
---------------------------------------------------------------
Healthy:

Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/4.0 CPU
 0.0/4.0 alice
 0.00/3.392 GiB memory
 0.00/1.696 GiB object_store_memory

Demands:
 (no resource demands)
(ray) [root@localhost ~]# ray status
======== Autoscaler status: 2022-08-28 23:59:57.010107 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_f08a3a65c24d42dea6df9adfd2fe22ba49078745bc94cafe6e2f8874
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:


Demands:
 (no resource demands)
3.我继续到头节点的Python编译器执行sf.init(address='192.168.14.132:6379')时
sf.init(address='192.168.14.132:6379')
2022-08-29 00:00:13,483 INFO worker.py:1333 -- Connecting to existing Ray cluster at address: 192.168.14.132:6379...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/secretflow/device/driver.py", line 228, in init
    ray.init(
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/worker.py", line 1475, in init
    _global_node = ray._private.node.Node(
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/node.py", line 226, in __init__
    node_info = ray._private.services.get_node_to_connect_for_driver(
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/services.py", line 395, in get_node_to_connect_for_driver
    return global_state.get_node_to_connect_for_driver(node_ip_address)
  File "/root/miniconda3/envs/ray/lib/python3.8/site-packages/ray/_private/state.py", line 729, in get_node_to_connect_for_driver
    node_info_str = self.global_state_accessor.get_node_to_connect_for_driver(
  File "python/ray/includes/global_state_accessor.pxi", line 155, in ray._raylet.GlobalStateAccessor.get_node_to_connect_for_driver
RuntimeError: b'GCS has started but no raylets have registered yet.'

4. Ray集群在执行sf.init(address='192.168.14.132:6379')之前，应该是运行的，执行sf.init(address='192.168.14.132:6379')之后不知道为何就查询不到ray节点的信息了。

**Comment by wind-and-falling-maple-leaf** [comment]
即在执行 ` sf.init(address='192.168.14.132:6379')` 之前ray集群是能查询到node节点信息的
```
======== Autoscaler status: 2022-08-28 23:58:46.723929 ========
Node status
---------------------------------------------------------------
Healthy:

Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/4.0 CPU
 0.0/4.0 alice
 0.00/3.392 GiB memory
 0.00/1.696 GiB object_store_memory

Demands:
 (no resource demands)
(ray) [root@localhost ~]# ray status
======== Autoscaler status: 2022-08-28 23:59:57.010107 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_f08a3a65c24d42dea6df9adfd2fe22ba49078745bc94cafe6e2f8874
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:


Demands:
 (no resource demands)
```

**Comment by zhouaihui** [comment]
我能想到的一些办法
1. 先停掉已有的集群（执行ray stop），然后执行`ray start --head`（注意不带其他参数），启动之后，再执行sf.init看下是否成功。 -> 如果这个方式没问题，至少证明你的机器上可以运行ray。那么可能要检查下node-ip-address是否有问题，比如先换成127.0.0.1再试试。
2. 尝试在`/tmp/ray/session_xxx/logs/raylet.out`看下是否有有用的信息。`xxx`应该和你启动ray的时间匹配。

**Comment by magic-hya** [comment]
我也遇到同样的问题，容器刚启动，ray status是能看到有节点的，过段时间节点就消失了
我是使用镜像启动的，映射了端口
