### ISSUE TITLE
docker中，spu-ci里编译的spu包在secrectflow-anolis中不能用

### ISSUE THREAD

**Issue by ues1df** [secretflow/secretflow#1029]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secrectflow1.2.0b0

### OS Platform and Distribution

docker ubuntu(spu-ci)/anolis(secretflow-anolis8)

### Python version

3.8.17(spu-ci)/ 3.8.15(secretflow-anolis)

### Bazel version

5.4.1(spu-ci)

### GCC/Compiler version

11.3.0(spu-ci)

### What happend and What you expected to happen.

```shell
docker中的spu-ci，是ubuntu 22.04系统, glibc版本2.35。

secretflow-anolis8是anolis8系统, glibc版本2.28。

在spu-ci中编译的spu在secretflow-anolis8中不可用。
```

### Reproduction code to reproduce the issue.

```shell
# 通过 pip install dist/*.whl --force-reinstall 安装自己编译的spu后
>>> import spu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/spu/__init__.py", line 16, in <module>
    from . import pir, psi
  File "/usr/local/lib/python3.8/site-packages/spu/pir.py", line 19, in <module>
    from . import libspu  # type: ignore
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/python3.8/site-packages/spu/libspu.so)
```

**Comment by anakinxc** [comment]
Hi @ues1df 

如果要发给其他发行版用的包，请用 release-ci 来打
