### ISSUE TITLE
本地仿真模式启动报错

### ISSUE THREAD

**Issue by liyuu127** [secretflow/secretflow#1053]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.3.0.dev20231120

### OS Platform and Distribution

macboook m2 pro

### Python version

3.8.18

### What happend and What you expected to happen.

```shell
本地启动仿真环境时 ray启动报错。 python 环境由conda管理，查询ray官方issue 进行pip uninstall grpcio; conda install grpcio.依旧报错，请问有遇到过种情况是否解决了么。
3.8.18 (default, Sep 11 2023, 08:17:16) 
[Clang 14.0.6 ]
The version of SecretFlow: 1.3.0.dev20231120

2023-11-23 12:51:56,526	ERROR services.py:1195 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2023-11-

23_12-51-55_385555_93471/logs/dashboard.log'
2023-11-23 12:51:56,527	ERROR services.py:1196 -- Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2023-11-23_12-51-55_385555_93471/logs/dashboard.log'
Traceback (most recent call last):
  File "/Users/liyu/anaconda3/envs/secretflow-example/lib/python3.8/site-packages/ray/_private/services.py", line 1167, in start_api_server
    with open(dashboard_log, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2023-11-23_12-51-55_385555_93471/logs/dashboard.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liyu/anaconda3/envs/secretflow-example/lib/python3.8/site-packages/ray/_private/services.py", line 1178, in start_api_server
    raise Exception(err_msg + f"\nFailed to read dashboard log: {e}")
Exception: Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2023-11-23_12-51-55_385555_93471/logs/dashboard.log'
2023-11-23 12:51:56,666	INFO worker.py:1538 -- Started a local Ray instance.


grpcio更新后
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf
import sys
print(sys.version)
# Check the version of your SecretFlow
print('The version of SecretFlow: {}'.format(sf.__version__))

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob', 'carol'], address='local')
```

**Comment by ian-huu** [comment]
隐语在 Apple Silicon 的支持还没有完整测试，相关上游依赖建议用官方文档的方式尝试一下：https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support

**Comment by zhouaihui** [comment]
secretflow自带的secretflow-ray是2.2版本，可以尝试安装开源的ray，记得先卸载secretflow-ray。
```
pip uninstall secretflow-ray
```
之后的操作可以参考 @ian-huu 的链接
