### ISSUE TITLE
横向联邦学习训练无法结束

### ISSUE THREAD

**Issue by chenhuanan** [secretflow/secretflow#1058]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

CentOS Linux release 7.6.1810 (Core)

### Python version

Python 3.8.0 

### What happend and What you expected to happen.

```shell
我用代码改了一个两方的联邦学习，可以训练，并且都能看到进度条，但100%后就一直没反应，不报错也不结束，感觉像是卡在了度量方法metris这里,以下是运行中的结果。
补充其他信息：数据是五个特征，做二分类，大约几十万条
(spu-0.7) [root@westone million_dataset]# python secretflow_横向联邦_big_data.py 
2023-11-28 16:20:35.721635: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(881280, 6)
iris_data:(881280, 5)
iris_label:(881280, 2)
train_iris_data:(705024, 5)
test_iris_data:(176256, 5)
train_iris_label:(705024, 2)
test_iris_label:(176256, 2)
columns:Index(['0', '1', '2', '3', '4'], dtype='object')
columns-len:5
iris_label_class:2
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 689/689 [00:19<00:00, 124.19it/s
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf
import numpy as np
import pandas as pd
import tensorflow as tf
from secretflow.ml.nn.fl.backend.torch.utils import BaseModule, TorchModel
from secretflow.ml.nn.fl.utils import metric_wrapper, optim_wrapper
from secretflow.ml.nn import FLModel
from torchmetrics import Accuracy, Precision,AUROC
from secretflow.security.aggregation import SecureAggregator,SPUAggregator
from secretflow.utils.simulation.datasets import load_mnist
from torch import nn, optim
from torch.nn import functional as F

from secretflow.data.horizontal import read_csv as h_read_csv
from secretflow.security.aggregation import PlainAggregator
from secretflow.security.compare import PlainComparator
from secretflow.data.split import train_test_split
from secretflow.preprocessing.encoder import OneHotEncoder
import time
t1 = time.time()
sf.shutdown()
#sf.init(parties=['promoter', 'provider'],address='192.168.207.246:6379',_node_ip_address='192.168.207.246')
sf.init(address='192.168.207.246:6379')

promoter = sf.PYU('promoter')
provider = sf.PYU('provider')

spu = sf.SPU(
    {'nodes': [{'party': 'promoter', 'id': 'local:0', 'address': '192.168.207.246:6317','listen_address': '0.0.0.0:6317'},
               {'party': 'provider', 'id': 'local:1', 'address': '192.168.207.249:6327','listen_address': '0.0.0.0:6327'}],
     'runtime_config': {'protocol': 2, 'field': 3}})
promoter_input_path = r'/root/dataset/augmented_sensor_440640.csv'
provider_input_path = r'/root/dataset/augmented_sensor_440640.csv'

aggregator =SPUAggregator(spu)
#aggregator =PlainAggregator(promoter)
all_hdf = h_read_csv({promoter: promoter_input_path, provider: provider_input_path},aggregator=aggregator)
print(all_hdf.shape)

#iris_data=all_hdf.drop(columns="target")
iris_label=all_hdf["0.1"]

encoder = OneHotEncoder()
iris_label = encoder.fit_transform(iris_label)

iris_data = all_hdf.drop(columns="0.1",inplace=False)
#iris_data = iris_data.fillna(iris_data.mean(numeric_only=True).to_dict())

train_iris_data, test_iris_data = train_test_split(iris_data,train_size=0.8,test_size=0.2,shuffle=False)
train_iris_label, test_iris_label = train_test_split(iris_label,train_size=0.8,test_size=0.2,shuffle=False)

print("iris_data:{}".format(iris_data.shape))
print("iris_label:{}".format(iris_label.shape))
print("train_iris_data:{}".format(train_iris_data.shape))
print("test_iris_data:{}".format(test_iris_data.shape))
print("train_iris_label:{}".format(train_iris_label.shape))
print("test_iris_label:{}".format(test_iris_label.shape))

print("columns:{}".format(iris_data.columns))
print("columns-len:{}".format(len(iris_data.columns)))
print("iris_label_class:{}".format(iris_label.shape[-1]))

class MlpNet(BaseModule):
    """Small mlp network for Iris"""

    def __init__(self):
        super(MlpNet, self).__init__()
        self.layer1 = nn.Linear(5, 1)
        #self.layer2 = nn.Linear(50, 50)
        #self.layer3 = nn.Linear(50, 3)

    def forward(self, x):
        #x = F.relu(self.layer1(x))
        #x = F.relu(self.layer2(x))
        #x = F.relu(self.layer3(x))
        #x = F.softmax(self.layer1, dim=1)
        x = F.sigmoid
        return x

loss_fn = nn.CrossEntropyLoss
optim_fn = optim_wrapper(optim.Adam, lr=5e-3)
model_def = TorchModel(
    model_fn=MlpNet,
    loss_fn=loss_fn,
    optim_fn=optim_fn,
    metrics=[#tf.keras.metrics.AUC(),
        metric_wrapper(Accuracy, num_classes=2, average='micro'),
        #metric_wrapper(Precision, num_classes=2, average='micro'),
        #metric_wrapper(AUROC, num_classes=2, average='micro')
    ],
)

device_list = [promoter, provider]
server = None

fl_model = FLModel(
    server=server,
    device_list=device_list,
    model=model_def,
    aggregator=aggregator,
    sparsity=0.0,
    strategy="fed_prox",
    backend="torch",
)
history = fl_model.fit(
    train_iris_data,
    train_iris_label,
    validation_data=(test_iris_data, test_iris_label),
    epochs=1,
    batch_size=512,
    aggregate_freq=1,
)
print("总共消耗时间：",time.time()-t1)
```

**Comment by chenhuanan** [comment]
如果有其他的方式可以实现**两方**的**横向**联邦学习也行，不限版本

**Comment by zhangxingmeng** [comment]
麻烦帮忙确认下您这边用的secretflow是什么版本的？

**Comment by chenhuanan** [comment]
Secretflow Version
0.7.7b1

OS Platform and Distribution
CentOS Linux release 7.6.1810 (Core)

Python version
Python 3.8.0

**Comment by zhangxingmeng** [comment]
麻烦更新一下版本吧，用最新的版本试试。之前有过这种情况已修复

**Comment by chenhuanan** [comment]
我试了secretflow版本1.2.0、0.8.2b1都报以下错误：
Traceback (most recent call last):
  File "secretflow_big_data_221_222_1.0版本.py", line 110, in <module>
    history = fl_model.fit(
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 421, in fit
    initial_weight = self.initialize_weights()
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 117, in initialize_weights
    initial_weight = self._aggregator.average(clients_weights, axis=0)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/security/aggregation/spu_aggregator.py", line 88, in average
    data = [d.to(self.device) for d in data]
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/security/aggregation/spu_aggregator.py", line 88, in <listcomp>
    data = [d.to(self.device) for d in data]
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/device/base.py", line 68, in to
    return dispatch(_name_of_to(device.device_type), self, device, *args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/kernels/pyu.py", line 76, in pyu_to_spu
    shares_chunk_count = self.device(get_shares_chunk_count)(
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 98, in wrapper
    sfd.remote(self._run)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 107, in _remote
    args, kwargs = _resolve_args(*args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 97, in _resolve_args
    actual_vals = ray.get(list(refs.values()))
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PYUFedProx.__init__() (pid=15724, ip=192.168.207.221, repr=<secretflow.ml.nn.fl.backend.torch.strategy.fed_prox.PYUFedProx object at 0x7f224a8330a0>)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/fl_base.py", line 63, in __init__
    [m() for m in builder_base.metrics]
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/fl_base.py", line 63, in <listcomp>
    [m() for m in builder_base.metrics]
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/ml/nn/fl/utils.py", line 96, in wrapped_func
    return func(*args, **kwargs)
TypeError: __new__() missing 1 required positional argument: 'task'

**Comment by zhangxingmeng** [comment]
这是torchmetric版本更新了，可以参考下torchmetric的文档 https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html#binaryaccuracy

**Comment by chenhuanan** [comment]
现在这种两方的横向联邦是否在现在可行的呢，我之前同事在0.7的版本跑过。按照上面修改metrics参数之后，在几个版本上试了，都报以下错误：
Traceback (most recent call last):
  File "secretflow_big_data_221_222_1.0版本.py", line 111, in <module>
    history = fl_model.fit(
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 456, in fit
    model_params = self._aggregator.average(
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/security/aggregation/spu_aggregator.py", line 88, in average
    data = [d.to(self.device) for d in data]
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/security/aggregation/spu_aggregator.py", line 88, in <listcomp>
    data = [d.to(self.device) for d in data]
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/device/base.py", line 68, in to
    return dispatch(_name_of_to(device.device_type), self, device, *args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/kernels/pyu.py", line 76, in pyu_to_spu
    shares_chunk_count = self.device(get_shares_chunk_count)(
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 98, in wrapper
    sfd.remote(self._run)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 107, in _remote
    args, kwargs = _resolve_args(*args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 97, in _resolve_args
    actual_vals = ray.get(list(refs.values()))
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::PYUFedProx.train_step() (pid=24652, ip=192.168.207.221, repr=<secretflow.ml.nn.fl.backend.torch.strategy.fed_prox.PYUFedProx object at 0x7f00d1ad40a0>)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/strategy/fed_prox.py", line 97, in train_step
    loss = self.loss(y_pred, y)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
TypeError: cross_entropy_loss(): argument 'input' (position 1) must be Tensor, not function
Exception ignored in: <function SPUObject.__del__ at 0x7f5d4a72b3a0>
Traceback (most recent call last):
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 190, in __del__
    actor.del_share.remote(self.shares_name[i])
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/actor.py", line 138, in remote
    return self._remote(args, kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 425, in _start_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/actor.py", line 184, in _remote
    return invocation(args, kwargs)
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/actor.py", line 171, in invocation
    return actor._actor_method_call(
  File "/home/pengxizi/miniconda3/envs/secretflow-1.0/lib/python3.8/site-packages/ray/actor.py", line 1172, in _actor_method_call
    object_refs = worker.core_worker.submit_actor_task(
AttributeError: 'Worker' object has no attribute 'core_worker'
  0%|▎                                                                                                                                                                                                                          | 1/689 [00:01<17:02,  1.49s/it
