### ISSUE TITLE
secretflow-lite==1.3.0.dev20231212 安装后测试ray异常

### ISSUE THREAD

**Issue by hy928302776** [secretflow/secretflow#1087]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow-lite==1.3.0.dev20231212

### OS Platform and Distribution

mac/m1 8c16g

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
在mac/m1系统中安装secretflow环境：
pip install secretflow-lite==1.3.0.dev20231212
执行测试案例，ray读取log日志异常
```

### Reproduction code to reproduce the issue.

```shell
执行测试案例

import secretflow as sf

sf.init(parties=['alice', 'bob'], address='local')
alice_device = sf.PYU('alice')
message_from_alice = alice_device(lambda x: x)("Hello World!")
print(message_from_alice)

出现异常：

/Users/huangying/miniconda3/envs/sf/bin/python /Users/huangying/PycharmProjects/django-vue-admin-main/backend/dvadmin/test.py 
2023-12-19 14:08:39,340	ERROR services.py:1195 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2023-12-19_14-08-38_184512_70104/logs/dashboard.log'
2023-12-19 14:08:39,340	ERROR services.py:1196 -- Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2023-12-19_14-08-38_184512_70104/logs/dashboard.log'
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/services.py", line 1167, in start_api_server
    with open(dashboard_log, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2023-12-19_14-08-38_184512_70104/logs/dashboard.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/services.py", line 1178, in start_api_server
    raise Exception(err_msg + f"\nFailed to read dashboard log: {e}")
Exception: Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2023-12-19_14-08-38_184512_70104/logs/dashboard.log'
2023-12-19 14:08:39,472	INFO worker.py:1538 -- Started a local Ray instance.
[2023-12-19 14:08:48,634 E 70104 27111613] core_worker_process.cc:219: Failed to get the system config from raylet because it is dead. Worker will terminate. Status: GrpcUnavailable: RPC Error message: failed to connect to all addresses; RPC Error details:  .Please see `raylet.out` for more details.

Process finished with exit code 1
```

**Comment by hy928302776** [comment]
![Uploading image.png…]()
异常图片

**Comment by hy928302776** [comment]
<img width="1187" alt="image" src="https://github.com/secretflow/secretflow/assets/26709680/66c82d14-eed6-4982-9c8f-e36836a9b8bd">

**Comment by xiushuiguande** [comment]
@hy928302776
 1、
pip show ray
pip show secretflow-ray
看下是否是重复装了ray/secretflow-ray
2、检查下 /tmp/ray/session_latest/sockets 是否存在以及权限是否能正常访问；
 如果没问题的话麻烦提供下 Ray 的日志，在 /tmp/ray/session_latest/logs 目录下

**Comment by hy928302776** [comment]
ray的error日志：
~                                                                                                                                                                     
~                                                                                                                                                                     
~                                                                                                                                                                     
"raylet.err" 20L, 1749B
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/dashboard/agent.py", line 11, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
[2023-12-19 14:15:39,595 E 71711 27122989] (raylet) agent_manager.cc:135: The raylet exited immediately because the Ray agent failed. The raylet fate shares with the agent. This can happen because the Ray agent was unexpectedly killed or failed. See `dashboard_agent.log` for the root cause.

ray的依赖：
<img width="1443" alt="image" src="https://github.com/secretflow/secretflow/assets/26709680/0a3920fb-a667-449f-997a-aea63f871b4c">
<img width="1443" alt="image" src="https://github.com/secretflow/secretflow/assets/26709680/0a3920fb-a667-449f-997a-aea63f871b4c">

**Comment by hy928302776** [comment]
<img width="1443" alt="image" src="https://github.com/secretflow/secretflow/assets/26709680/121d9203-17fc-4467-8214-b5b048bd10d4">

<img width="822" alt="image" src="https://github.com/secretflow/secretflow/assets/26709680/77658886-7fac-48a9-b1cc-7cf1366e441e">

没看到日志文件：
<img width="1020" alt="image" src="https://github.com/secretflow/secretflow/assets/26709680/f0bfb102-c9d7-4630-b735-fd1ae872965e">

console的日志是：
/Users/huangying/miniconda3/envs/sf/bin/python /Users/huangying/PycharmProjects/django-vue-admin-main/backend/dvadmin/test.py 
2023-12-19 16:48:52,160	ERROR services.py:1195 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2023-12-19_16-48-51_021816_95797/logs/dashboard.log'
2023-12-19 16:48:52,160	ERROR services.py:1196 -- Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2023-12-19_16-48-51_021816_95797/logs/dashboard.log'
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/services.py", line 1167, in start_api_server
    with open(dashboard_log, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2023-12-19_16-48-51_021816_95797/logs/dashboard.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/services.py", line 1178, in start_api_server
    raise Exception(err_msg + f"\nFailed to read dashboard log: {e}")
Exception: Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2023-12-19_16-48-51_021816_95797/logs/dashboard.log'
2023-12-19 16:48:52,294	INFO worker.py:1538 -- Started a local Ray instance.
[2023-12-19 16:48:52,440 E 95797 27312831] core_worker.cc:179: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory

Process finished with exit code 1

**Comment by hy928302776** [comment]
看错了有日志文件：
<img width="947" alt="image" src="https://github.com/secretflow/secretflow/assets/26709680/54f107f9-c533-43eb-9cbc-fcd30dc6eb0e">
ka看哪个呢

**Comment by xiushuiguande** [comment]
@hy928302776 把raylet.err发一下

**Comment by hy928302776** [comment]
~                                                                                                                                                                     
1、python-core-driver-01000000ffffffffffffffffffffffffffffffffffffffffffffffff_95797.log的内容                                                                                                                                                      
~                                                                                                                                                                     
"python-core-driver-01000000ffffffffffffffffffffffffffffffffffffffffffffffff_95797.log" 3L, 470B
[2023-12-19 16:48:52,298 I 95797 27312831] core_worker_process.cc:107: Constructing CoreWorkerProcess. pid: 95797
[2023-12-19 16:48:52,299 I 95797 27312831] io_service_pool.cc:35: IOServicePool is running with 1 io_service.
[2023-12-19 16:48:52,440 E 95797 27312831] core_worker.cc:179: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
~                      

2、raylet.err的内容
(sf) huangying@MacBook-Pro-2 logs % cat raylet.err 
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/dashboard/agent.py", line 11, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
[2023-12-19 16:48:52,311 E 95830 27313209] (raylet) agent_manager.cc:135: The raylet exited immediately because the Ray agent failed. The raylet fate shares with the agent. This can happen because the Ray agent was unexpectedly killed or failed. See `dashboard_agent.log` for the root cause.
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
    from grpc import _compression    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>

  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    import grpc  # noqa: F401
    from grpc import _compression
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    from grpc._cython import cygrpc
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
    from grpc._cython import cygrpc
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
    Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
_configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError:     import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 63, in _configure_system
    import grpc  # noqa: F401
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 8, in <module>
    import ray
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 101, in <module>
    _configure_system()
  File "/Users/huangying/miniconda3/envs/sf/lib/python3.8/site-packages/ray/__init__.py", line 65, in _configure_system
    raise ImportError(
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.

**Comment by xiushuiguande** [comment]
`ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try pip uninstall grpcio; conda install grpcio. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.`
@hy928302776 根据报错提示，在ray 的installation.html尝试解决一下

**Comment by hy928302776** [comment]
可以了，谢谢
