### ISSUE TITLE
报错信息RuntimeError： ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.pir_setup() (pid=1321, ip=192.168.92.11, repr=SPURuntime(device_id=None, party=party_a))

### ISSUE THREAD

**Issue by relinda2019** [secretflow/secretflow#1124]
### Issue Type

Bug

### Source

binary

### Secretflow Version

version=secretflow/secretflow-lite-anolis8:latest

### OS Platform and Distribution

mac

### Python version

3.7.13

### What happend and What you expected to happen.

```shell
Traceback (most recent call last):
  File "test.py", line 187, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "test.py", line 139, in main
    reports = spu.pir_setup(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 2176, in pir_setup
    return dispatch(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 519, in pir_setup
    return sfd.get(res)
  File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 158, in get
    return ray.get(object_refs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.pir_setup() (pid=1321, ip=192.168.92.11, repr=SPURuntime(device_id=None, party=party_a))
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1233, in pir_setup
    report = pir.pir_setup(config)
  File "/usr/local/lib/python3.8/site-packages/spu/pir.py", line 32, in pir_setup
    report_str = libpsi.libs.pir_setup(config.SerializeToString())
RuntimeError
```

### Reproduction code to reproduce the issue.

```shell
# -*- coding: utf-8 -*-

import sys
import time
import logging
import multiprocess
from absl import app
import spu
import secretflow as sf
#import random
# init log
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

# SPU settings
# alice as pir client
# bob as pir server
cluster_def = {
    'nodes': [
        {
            'party': 'client9394',
            'id': 'local:4',
            'address': '192.168.92.14:16258', 
            'tls_opts': {
                'server_ssl_opts': {
                    'certificate_path': '/grpc_ssl/ssl/server.pem',
                    'private_key_path': '/grpc_ssl/ssl/server-key.pem',
                    # The options used for verify peer's client certificate
                    'ca_file_path': '/grpc_ssl/ssl/ca.pem',
                    # Maximum depth of the certificate chain for verification
                    'verify_depth': 1
                },
                'client_ssl_opts': {
                    'certificate_path': '/grpc_ssl/ssl/client.pem',
                    'private_key_path': '/grpc_ssl/ssl/client-key.pem',
                    # The options used for verify peer's server certificate
                    'ca_file_path': '/grpc_ssl/ssl/ca.pem',
                    # Maximum depth of the certificate chain for verification
                    'verify_depth': 1
                }
            }
        },
        {
            'party': 'party_a', 
            'id': 'local:1',
            'address': '192.168.92.11:17671', 
            'tls_opts': {
                'server_ssl_opts': {
                    'certificate_path': '/grpc_ssl/ssl/server.pem',
                    'private_key_path': '/grpc_ssl/ssl/server-key.pem',
                    # The options used for verify peer's client certificate
                    'ca_file_path': '/grpc_ssl/ssl/ca.pem',
                    # Maximum depth of the certificate chain for verification
                    'verify_depth': 1
                },
                'client_ssl_opts': {
                    'certificate_path': '/grpc_ssl/ssl/client.pem',
                    'private_key_path': '/grpc_ssl/ssl/client-key.pem',
                    # The options used for verify peer's server certificate
                    'ca_file_path': '/grpc_ssl/ssl/ca.pem',
                    # Maximum depth of the certificate chain for verification
                    'verify_depth': 1
                }
            }
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}

print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
print("cluster_def:{}".format(cluster_def))
print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")

link_desc = {
    'recv_timeout_ms': 5000,
}

# def get_k_c(path):
#     import pandas as pd
#     data = pd.read_csv(path)
#     cols = data.columns.tolist()
#     return cols[0], cols[1:]

import argparse

def getOptions():
    parser = argparse.ArgumentParser(description='python *.py [option]')
    parser.add_argument('--server_data', help="server_data",
                        default='dataset_A.csv')
    parser.add_argument('--client_data', help="client_data",
                         default='dataset_query.csv')
    parser.add_argument('--output_data', help="output_data",
                         default='test_out.csv')
    args = parser.parse_args()
    return args

def main(_):
    args = getOptions()
    # sf init
    sf.init(['client9394','party_a'], address='192.168.92.14:9394',
            log_to_driver=True,omp_num_threads=multiprocess.cpu_count())

    # init log
    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

    alice = sf.PYU('client9394')
    bob = sf.PYU('party_a')

    # key_columns = ['id']
    # label_columns = ['id1', 'label', 'label1']
    spu = sf.SPU(cluster_def, link_desc)

    pir_input_path = "/data/Container1/" + args.server_data
    pir_oprf_key_path = '/grpc_ssl/oprf_key.bin'
    pir_setup_path = '/data/logs/pir_setup_dir'

    # key_columns, label_columns = get_k_c(pir_input_path)
    key_columns = "用户id"
    label_columns = ["手机号数量", "是否在黑名单中"]
    print("=================================================================")
    print("key:{}".format(key_columns))
    print("features:{}".format(label_columns))
    print("=================================================================")

    start = time.time()

    # server setup
    print("**************************************************************")
    print("server_name: party_a, pir_input_path:{}, key_columns:{}, label_columns:{}," \
          "pir_oprf_key_path:{}, pir_setup_path:{}".format(pir_input_path, key_columns,label_columns, pir_oprf_key_path, pir_setup_path))
    print("**************************************************************")

    reports = spu.pir_setup(
        server='party_a',
        input_path=pir_input_path,
        key_columns=key_columns,
        label_columns=label_columns,
        oprf_key_path=pir_oprf_key_path,
        setup_path=pir_setup_path,
        num_per_query=1,
        label_max_len=80,  # need  label_max_len > len(real value of in csv for all label_columns)
    )

    #print(f"psi reports: {reports}")
    logging.info(f"offline psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")
    
    alice_input_path = "/data/Container4/" + args.client_data

    # client config
    alice_config = {
        'input_path': alice_input_path,
        'key_columns': key_columns,
        'output_path': "/data/Container4/" + args.output_data,
    }

    # server config
    bob_config = {
        'oprf_key_path': pir_oprf_key_path,
        'setup_path': pir_setup_path,
    }

    query_config = {
        alice: alice_config,
        bob: bob_config,
    }

    start = time.time()

    reports = spu.pir_query(
        server='bob',
        config=query_config,
    )

    logging.info(f"online pir reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")

    sf.shutdown()

if __name__ == '__main__':
    app.run(main)

向各位大佬请教一下，这个错误是什么原因造成的呢？ 多谢
```

**Comment by Chrisdehe** [comment]
hey，我们的环境要求是Python=3.8
请参考[环境要求](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started/installation#environment)来配置机器哈
