### ISSUE TITLE
load_model报错 

### ISSUE THREAD

**Issue by hacker-jerry** [secretflow/secretflow#1128]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.14.03dev

### OS Platform and Distribution

ubuntu18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
Traceback (most recent call last):
  File "main.py", line 331, in <module>
    model= load_model(saving_path_dict, alice)
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/model.py", line 270, in load_model
    return from_dict(from_json_to_dict(device_path_dict, label_holder))
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/model.py", line 240, in from_json_to_dict
    leaf_weights = [
TypeError: 'PYUObject' object is not iterable

我在三个节点上各自保存模型之后（可以正常保存），使用load_model函数，传入alice 这个pyu
但是报错。
alice是标签持有方
```

### Reproduction code to reproduce the issue.

```shell
saving_path_dict = {
        device: "/workspace/" + device.party
        for device in X_train.partitions.keys()
    }
model.save_model(saving_path_dict)

model= load_model(saving_path_dict, alice) # 报错

from secretflow.data.ndarray import load
fed_npz = load({ carol: 'data/test.npz'}, allow_pickle=True)

yp = model.predict(fed_npz['test_x'], alice)

```
```

**Comment by da-niao-dan** [comment]
你好，感谢你的反馈。 目前tree 数量为1的时候会有这个bug， 后续我们会修复。

**Comment by Chrisdehe** [comment]
@hacker-jerry BUG已修复，随下一个版本更新
