### ISSUE TITLE
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.pir_setup() (pid=6590, ip=192.168.19.130, actor_id=77e2c70f6ee45bcef03c807b01000000, repr=SPURuntime(device_id=None, party=bob))

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretflow#1220]
### Issue Type

Others

### Source

source

### Secretflow Version

1.5.0

### OS Platform and Distribution

centos 7.9

### Python version

3.10

### Bazel version

6.5.0

### GCC/Compiler version

11.2

### What happend and What you expected to happen.

```shell
(secretflow) [root@secretflow20240314 secretflow-1.5.0.dev240319]# python testPIR.py
/usr/local/anaconda3/envs/secretflow/lib/python3.10/subprocess.py:1796: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = _posixsubprocess.fork_exec(
2024-04-01 14:16:54,390 INFO worker.py:1724 -- Started a local Ray instance.
(SPURuntime(device_id=None, party=bob) pid=6590) WARNING:root:config=mode: MODE_SERVER_SETUP
(SPURuntime(device_id=None, party=bob) pid=6590) pir_protocol: PIR_PROTOCOL_KEYWORD_PIR_APSI
(SPURuntime(device_id=None, party=bob) pid=6590) pir_server_config {
(SPURuntime(device_id=None, party=bob) pid=6590)   input_path: "/home/pir/csv/gonghang.csv"
(SPURuntime(device_id=None, party=bob) pid=6590)   setup_path: "/home/pir/result/"
(SPURuntime(device_id=None, party=bob) pid=6590)   key_columns: "\350\257\201\344\273\266\345\217\267\347\240\201"
(SPURuntime(device_id=None, party=bob) pid=6590)   label_columns: "\345\247\223\345\220\215"
(SPURuntime(device_id=None, party=bob) pid=6590)   label_columns: "\350\257\201\344\273\266\347\261\273\345\236\213"
(SPURuntime(device_id=None, party=bob) pid=6590)   label_columns: "\350\257\201\344\273\266\345\217\267\347\240\201"
(SPURuntime(device_id=None, party=bob) pid=6590)   label_columns: "\351\223\266\350\241\214\345\215\241\345\217\267"
(SPURuntime(device_id=None, party=bob) pid=6590)   label_columns: "\344\275\217\345\235\200"
(SPURuntime(device_id=None, party=bob) pid=6590)   label_max_len: 18
(SPURuntime(device_id=None, party=bob) pid=6590)   bucket_size: 10
(SPURuntime(device_id=None, party=bob) pid=6590)   apsi_server_config {
(SPURuntime(device_id=None, party=bob) pid=6590)     oprf_key_path: "/home/pir/bin/oprf_key.bin"
(SPURuntime(device_id=None, party=bob) pid=6590)     num_per_query: 1
(SPURuntime(device_id=None, party=bob) pid=6590)   }
(SPURuntime(device_id=None, party=bob) pid=6590) }
(SPURuntime(device_id=None, party=bob) pid=6590) 
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.593] [info] [pir.cc:245] table_params hash_func_count:1
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.593] [info] [pir.cc:247] table_params max_items_per_bin:20
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.593] [info] [pir.cc:250] seal_params poly_modulus_degree:2048
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.593] [info] [pir.cc:252] query_params query_powers size:20
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.596] [info] [pir.cc:267] bucket:0 bucket_setup_path:/home/pir/result//bucket_0
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.598] [info] [ecdh_oprf_selector.cc:33] use fourq
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.606] [info] [leveldb_kvstore.cc:73] key not found
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.606] [info] [sender_kvdb.cc:599] key item_count no value
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.608] [info] [sender_kvdb.cc:735] OPRF FullEvaluate and EncryptLabel batch_count: 0
(SPURuntime(device_id=None, party=bob) pid=6590) [2024-04-01 14:16:58.608] [info] [thread_pool.cc:30] Create a fixed thread pool with size 3
Traceback (most recent call last):
  File "/home/secretflow-1.5.0.dev240319/testPIR.py", line 96, in <module>
    app.run(main)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/secretflow-1.5.0.dev240319/testPIR.py", line 48, in main
    reports = spu.pir_setup(
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/device/spu.py", line 1990, in pir_setup
    return dispatch(
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/kernels/spu.py", line 521, in pir_setup
    return sfd.get(res)
  File "/home/secretflow-1.5.0.dev240319/secretflow/distributed/primitive.py", line 158, in get
    return ray.get(object_refs)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.pir_setup() (pid=6590, ip=192.168.19.130, actor_id=77e2c70f6ee45bcef03c807b01000000, repr=SPURuntime(device_id=None, party=bob))
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/device/spu.py", line 1245, in pir_setup
    report = psi.pir(config)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/spu/psi.py", line 148, in pir
    report_str = libpsi.libs.pir(config.SerializeToString(), link)
RuntimeError: what: 
        [Enforce fail at external/psi/psi/apsi/padding.cc:24] (data.size() + 4) <= max_len. data_size:82 max_len:18
Stacktrace:
#0 std::_Function_handler<>::_M_invoke()+0x7f3e69174772
#1 std::_Function_handler<>::_M_invoke()+0x7f3e6906c14b
#2 std::_Function_handler<>::_M_invoke()+0x7f3e6a46dbf5
#3 std::__future_base::_State_baseV2::_M_do_set()+0x7f3e690584fe
#4 __pthread_once_slow+0x7f3f1682a20b

stacktrace: 
#0 std::_Function_handler<>::_M_invoke()+0x7f3e69174772
#1 std::_Function_handler<>::_M_invoke()+0x7f3e6906c14b
#2 std::_Function_handler<>::_M_invoke()+0x7f3e6a46dbf5
#3 std::__future_base::_State_baseV2::_M_do_set()+0x7f3e690584fe
#4 __pthread_once_slow+0x7f3f1682a20b
(secretflow) [root@secretflow20240314 secretflow-1.5.0.dev240319]#
```

### Reproduction code to reproduce the issue.

```shell
import sys
import time
import logging
from absl import app
import spu
import secretflow as sf
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
# SPU 设置
cluster_def = {
    # SPU节点(IP为虚机IP，端口为未被使用端口)：alice、bob
    'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address': '127.0.0.1:3022'},
        {'party': 'bob',   'id': 'local:1', 'address': '127.0.0.1:3032'},
    ],
    'runtime_config': {
	    # 协议 Semi2k-SPDZ：一个半诚实NPC协议。
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}

link_desc = {
    # 接收超时毫秒
    'recv_timeout_ms': 3600000,
}

def main(_):
    # 将节点初始化到隐语框架中，address为ray的主节点IP + port，记录到驱动程序
    sf.init(['alice','bob'],address='local')
    # 初始化PYU角色alice、bob  pyu会通过__call__方法将本地py数据映射到ray object store中
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')
    # 查询字段id，如果是多字段匹配查询，这里填写多个字段中间用逗号隔开
    key_columns = ['证件号码']
    # 查询结果展示字段(查询字段也会展示到查询结果对应数据上)
    label_columns = ['姓名','证件类型','证件号码','银行卡号','住址']
	# 启动SPU
    spu = sf.SPU(cluster_def, link_desc)
    # 服务器端数据文件路径
    pir_input_path = '/home/pir/csv/gonghang.csv'
    # 服务器端随机密钥路径 用于将服务端数据初始化成数据库数据 (生成方式：dd if=/dev/urandom of=/home/pir/bin/oprf_key.bin bs=32 count=1)
    pir_oprf_key_path = '/home/pir/bin/oprf_key.bin'
    # 服务端数据生成数据库文件生成路径
    pir_setup_path = '/home/pir/result/'
    # 记录开始时间
    start = time.time()
    # 服务器端设置
    reports = spu.pir_setup(
        server='bob',
        input_path=pir_input_path,
        key_columns=key_columns,
        label_columns=label_columns,
        oprf_key_path=pir_oprf_key_path,
        setup_path=pir_setup_path,
        num_per_query=1, # 查询次数
        label_max_len=18,  # 查询结果过字段总和最大长度
        bucket_size=10,
    )
    # 日志打印服务器设置后 reports 内容
    logging.info(f"offline psi reports: {reports}")
    # 日志打印服务器设置运行时间
    logging.info(f"cost time: {time.time() - start}")
    # alice查询数据路径
    alice_input_path = '/home/pir/csv/nonghang.csv'
    # 客户端配置
    alice_config = {
        'input_path': alice_input_path,
        'key_columns': key_columns,
        'output_path': '/home/pir/result/nonghang_pir.csv',  # 查询结果输出路径
    }
    # 服务端配置
    bob_config = {
        'oprf_key_path': pir_oprf_key_path,
        'setup_path': pir_setup_path,
    }
    # 查询配置
    query_config = {
        alice: alice_config,
        bob: bob_config,
    }
    # 记录开始时间
    start = time.time()
    # 调用spu的匿踪查询方法
    reports = spu.pir_query(
        server='bob',
        config=query_config,
    )
    # 日志打印查询完成后的 reports 内容
    logging.info(f"online pir reports: {reports}")
    # 日志打印查询动作运行时间
    logging.info(f"cost time: {time.time() - start}")
	# 关闭sf
    sf.shutdown()
# 调用main方法
if __name__ == '__main__':
    app.run(main)
```

**Comment by Chrisdehe** [comment]
@coderSun20201112 
请问你的数据维度是多少？
‘        label_max_len=18,  # 查询结果过字段总和最大长度
’
从报错信息上来看，字段综合最大长度需要包含到你所有数据的列数。

**Comment by coderSun20201112** [comment]
是 label_max_len 参数值太小了，修改参数后，问题解决了，
