### ISSUE TITLE
仿真集群模式下报错AttributeError: 'SPURuntime' object has no attribute 'id'

### ISSUE THREAD

**Issue by circlekkk** [secretflow/secretflow#1225]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 1.4.0b0，spu 0.7.0.dev20231229, ray 2.4.0

### OS Platform and Distribution

centos7.9

### Python version

3.8.0

### What happend and What you expected to happen.

```shell
仿真集群模式进行FL逻辑回归模型训练，单机模拟跑没有问题，集群模式下报属性错误。spu源码里没有改属性的说明
控制台报错：python he_logisticregression_cluster.py 
2024-04-01 17:58:29,755	INFO worker.py:1432 -- Connecting to existing Ray cluster at address: 22.189.51.21:6666...
2024-04-01 17:58:29,786	INFO worker.py:1625 -- Connected to Ray cluster.
(SPURuntime(device_id=None, party=bob) pid=27789, ip=22.189.51.22) [2024-04-01 18:02:56.522] [info] [bucket_psi.cc:285] bucket size set to 1048576
(SPURuntime(device_id=None, party=bob) pid=27789, ip=22.189.51.22) [2024-04-01 18:02:56.522] [info] [bucket_psi.cc:131] Begin sanity check for input file: /root/100w100f_x_4.csv, precheck_switch:true
2024-04-01 17:58:44,122	WARNING worker.py:1986 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 870, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 921, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "/usr/local/python380/lib/python3.8/site-packages/ray/_private/function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/usr/local/python380/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/usr/local/python380/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 370, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what: 
	[external/yacl/yacl/link/transport/brpc_link.cc:101] brpc server failed start
stacktrace: 
#0 yacl::link::FactoryBrpc::CreateContext()+0x7fcf26ed3efd
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fcf25a29524
#2 pybind11::cpp_function::dispatcher()+0x7fcf25a0885e
#3 cfunction_call_varargs+0x437495



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1197, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1100, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1001, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 601, in ray._raylet.store_task_errors
  File "/usr/local/python380/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/usr/local/python380/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 379, in __repr__
    return f"SPURuntime(device_id={self.id}, party={self.party})"
AttributeError: 'SPURuntime' object has no attribute 'id'
An unexpected internal error occurred while the worker was executing a task.
SPU日志：2024-04-02 08:47:26.324 [error] [server.cpp:BRPC:1054] Fail to listen 22.189.51.22:9896
2024-04-02 08:47:26.339 [warning] [channel.h:~Channel:160] Channel destructor is called before WaitLinkTaskFinish, try stop send thread
已验证端口未被占用
```

### Reproduction code to reproduce the issue.

```shell
import spu
from secretflow.data.vertical import read_csv
import secretflow as sf
from secretflow.security.aggregation import SecureAggregator
from secretflow.ml.linear import FlLogisticRegressionVertical


alice_ip = '22.189.51.21'
bob_ip = '22.189.51.22'
ip_party_map = {bob_ip: 'bob', alice_ip: 'alice'}

_system_config = {'lineage_pinning_enabled': False}
sf.shutdown()
# init cluster
sf.init(
    ['alice', 'bob'],
    address='22.89.51.21:6666'
)
# SPU settingsS
cluster_def = {
    'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address': alice_ip + ':12945'},
        {'party': 'bob', 'id': 'local:1', 'address': bob_ip + ':12946'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}
# HEU settings
heu_config = {
    'sk_keeper': {'party': 'alice'},
    'evaluators': [{'party': 'bob'}],
    'mode': 'PHEU',
    'he_parameters': {
        # ou is a fast encryption schema that is as secure as paillier.
        'schema': 'ou',
        'key_pair': {
            'generate': {
                # bit size should be 2048 to provide sufficient security.
                'bit_size': 2048,
            },
        },
    },
    'encoding': {
        'cleartext_type': 'DT_I32',
        'encoder': "IntegerEncoder",
        'encoder_args': {"scale": 1},
    },
}
alice = sf.PYU('alice')
bob = sf.PYU('bob')
heu = sf.HEU(heu_config, cluster_def['runtime_config']['field'])
my_spu = sf.SPU(cluster_def)
# Prepare Data
train_df = read_csv(filepath={alice: './data/data_500_y.csv',
                              bob: './data/data_500_x.csv'},
                    keys='id', drop_keys='id', spu=my_spu,
                    psi_protocl='KKRT_PSI_2PC')

v_data = train_df.drop(columns=['y'])
label_data = train_df['y']
# Run lr
import time
start = time.time()
aggreator=SecureAggregator(alice, [alice, bob])
LR=FlLogisticRegressionVertical([alice,bob],aggreator,heu)
LR.fit(v_data, label_data,batch_size=1024,learning_rate=0.01,epochs=4)
print(f"train time: {time.time() - start}")
```

**Comment by circlekkk** [comment]
SPU日志的端口可替换为代码的12945/12946，后面换了9895端口尝试

**Comment by circlekkk** [comment]
ray启动命令：
ray start --head --node-ip-address="22.189.51.21" --port="6666" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats

ray start --address="22.189.51.21:6666" --resources='{"bob": 16}' --disable-usage-stats

**Comment by Chrisdehe** [comment]
请问ip是在引号内吗？
辛苦确认一下这里应该是：
'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address':  'alice_ip:12945'},
        {'party': 'bob', 'id': 'local:1', 'address': 'bob_ip:12946'},
    ],

**Comment by circlekkk** [comment]
这个是字符串连接应该不会影响。。
按你说的改了，没有解决

**Comment by Chrisdehe** [comment]
复现后未发生连接问题，以下为复现步骤：

1. ray启动：
Alice： ray start --head --node-ip-address="ip" --port="9394" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats
bob：ray start --address="ip:9394" --resources='{"bob": 16}' --disable-usage-stats
2、代码
`import spu
from secretflow.data.vertical import read_csv
import secretflow as sf
from secretflow.security.aggregation import SecureAggregator
from secretflow.ml.linear import FlLogisticRegressionVertical


_system_config = {'lineage_pinning_enabled': False}
sf.shutdown()
# init cluster
sf.init(
    ['alice', 'bob'],
    address='ip:9394'
)
# SPU settingsS
cluster_def = {
    'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address':'ip:12945'},
        {'party': 'bob', 'id': 'local:1', 'address':'ip:12946'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}
# HEU settings
heu_config = {
    'sk_keeper': {'party': 'alice'},
    'evaluators': [{'party': 'bob'}],
    'mode': 'PHEU',
    'he_parameters': {
        # ou is a fast encryption schema that is as secure as paillier.
        'schema': 'ou',
        'key_pair': {
            'generate': {
                # bit size should be 2048 to provide sufficient security.
                'bit_size': 2048,
            },
        },
    },
    'encoding': {
        'cleartext_type': 'DT_I32',
        'encoder': "IntegerEncoder",
        'encoder_args': {"scale": 1},
    },
}
alice = sf.PYU('alice')
bob = sf.PYU('bob')
heu = sf.HEU(heu_config, cluster_def['runtime_config']['field'])
my_spu = sf.SPU(cluster_def)
# Prepare Data
train_df = read_csv(filepath={alice: '/root/fuxian/psi_1.csv',
                              bob: '/root/fuxian/psi_2.csv'},
                    keys='id', drop_keys='id', spu=my_spu,
                    psi_protocl='KKRT_PSI_2PC')

v_data = train_df.drop(columns=['y'])
label_data = train_df['y']
# Run lr
import time
start = time.time()
aggreator=SecureAggregator(alice, [alice, bob])
LR=FlLogisticRegressionVertical([alice,bob],aggreator,heu)
LR.fit(v_data, label_data,batch_size=1024,learning_rate=0.01,epochs=4)
print(f"train time: {time.time() - start}")
`
另外，brpc server failed start多为连接问题，尤其是端口占用及重复。

**Comment by Chrisdehe** [comment]
你好，经复现后未发生连接问题， brpc server failed start多为端口占用及端口重复的连接问题，以下为复现步骤：
1、ray启动：
ray start --head --node-ip-address="172.19.245.231" --port="9394" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats
ray start --address="172.19.245.231:9394" --resources='{"bob": 16}' --disable-usage-stats

2、代码
```
import spu
from secretflow.data.vertical import read_csv
import secretflow as sf
from secretflow.security.aggregation import SecureAggregator
from secretflow.ml.linear import FlLogisticRegressionVertical


_system_config = {'lineage_pinning_enabled': False}
sf.shutdown()
sf.init(
    ['alice', 'bob'],
    address='172.19.245.231:9394'
)
cluster_def = {
    'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address':'172.19.245.231:12945'},
        {'party': 'bob', 'id': 'local:1', 'address':'172.19.245.232:12946'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}
heu_config = {
    'sk_keeper': {'party': 'alice'},
    'evaluators': [{'party': 'bob'}],
    'mode': 'PHEU',
    'he_parameters': {
        # ou is a fast encryption schema that is as secure as paillier.
        'schema': 'ou',
        'key_pair': {
            'generate': {
                # bit size should be 2048 to provide sufficient security.
                'bit_size': 2048,
            },
        },
    },
    'encoding': {
        'cleartext_type': 'DT_I32',
        'encoder': "IntegerEncoder",
        'encoder_args': {"scale": 1},
    },
}
alice = sf.PYU('alice')
bob = sf.PYU('bob')
heu = sf.HEU(heu_config, cluster_def['runtime_config']['field'])
my_spu = sf.SPU(cluster_def)
train_df = read_csv(filepath={alice: '/root/fuxian/psi_1.csv',
                              bob: '/root/fuxian/psi_2.csv'},
                    keys='id', drop_keys='id', spu=my_spu,
                    psi_protocl='KKRT_PSI_2PC')

v_data = train_df.drop(columns=['y'])
label_data = train_df['y']
import time
start = time.time()
aggreator=SecureAggregator(alice, [alice, bob])
LR=FlLogisticRegressionVertical([alice,bob],aggreator,heu)
LR.fit(v_data, label_data,batch_size=1024,learning_rate=0.01,epochs=4)
print(f"train time: {time.time() - start}")

```

**Comment by circlekkk** [comment]
已解决。是由于仿真模式两边都运行了代码导致报错。
