### ISSUE TITLE
单机运行PIR报错

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretflow#1226]
### Issue Type

Others

### Source

source

### Secretflow Version

1.5.0.dev240319

### OS Platform and Distribution

centos 7.9

### Python version

3.10

### Bazel version

6.5.0

### GCC/Compiler version

11.2

### What happend and What you expected to happen.

```shell
/usr/local/anaconda3/envs/secretflow/lib/python3.10/subprocess.py:1796: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = _posixsubprocess.fork_exec(
2024-04-02 09:54:05,660	INFO worker.py:1724 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/home/secretflow-1.5.0.dev240319/testPIR.py", line 88, in <module>
    app.run(main)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/secretflow-1.5.0.dev240319/testPIR.py", line 48, in main
    reports = spu.pir_setup(
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/device/spu.py", line 1990, in pir_setup
    return dispatch(
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/kernels/spu.py", line 521, in pir_setup
    return sfd.get(res)
  File "/home/secretflow-1.5.0.dev240319/secretflow/distributed/primitive.py", line 158, in get
    return ray.get(object_refs)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.pir_setup() (pid=6086, ip=192.168.19.130, actor_id=7f63eaa637584cf1cfba647301000000, repr=SPURuntime(device_id=None, party=bob))
  File "/home/secretflow-1.5.0.dev240319/secretflow/device/device/spu.py", line 1245, in pir_setup
    report = psi.pir(config)
  File "/usr/local/anaconda3/envs/secretflow/lib/python3.10/site-packages/spu/psi.py", line 148, in pir
    report_str = libpsi.libs.pir(config.SerializeToString(), link)
RuntimeError
(SPURuntime(device_id=None, party=bob) pid=6086) WARNING:root:config=mode: MODE_SERVER_SETUP
(SPURuntime(device_id=None, party=bob) pid=6086) pir_protocol: PIR_PROTOCOL_KEYWORD_PIR_APSI
(SPURuntime(device_id=None, party=bob) pid=6086) pir_server_config {
(SPURuntime(device_id=None, party=bob) pid=6086)   input_path: "/home/pir/csv/gonghang.csv"
(SPURuntime(device_id=None, party=bob) pid=6086)   setup_path: "/home/pir/set/"
(SPURuntime(device_id=None, party=bob) pid=6086)   key_columns: "\350\257\201\344\273\266\345\217\267\347\240\201"
(SPURuntime(device_id=None, party=bob) pid=6086)   label_columns: "\345\247\223\345\220\215"
(SPURuntime(device_id=None, party=bob) pid=6086)   label_columns: "\350\257\201\344\273\266\347\261\273\345\236\213"
(SPURuntime(device_id=None, party=bob) pid=6086)   label_columns: "\350\257\201\344\273\266\345\217\267\347\240\201"
(SPURuntime(device_id=None, party=bob) pid=6086)   label_columns: "\351\223\266\350\241\214\345\215\241\345\217\267"
(SPURuntime(device_id=None, party=bob) pid=6086)   label_columns: "\344\275\217\345\235\200"
(SPURuntime(device_id=None, party=bob) pid=6086)   label_max_len: 100
(SPURuntime(device_id=None, party=bob) pid=6086)   bucket_size: 100
(SPURuntime(device_id=None, party=bob) pid=6086)   apsi_server_config {
(SPURuntime(device_id=None, party=bob) pid=6086)     oprf_key_path: "/home/pir/bin/oprf_key.bin"
(SPURuntime(device_id=None, party=bob) pid=6086)     num_per_query: 1
(SPURuntime(device_id=None, party=bob) pid=6086)   }
(SPURuntime(device_id=None, party=bob) pid=6086) }
(SPURuntime(device_id=None, party=bob) pid=6086)
```

### Reproduction code to reproduce the issue.

```shell
import sys
import time
import logging
from absl import app
import spu
import secretflow as sf
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
# SPU 设置
cluster_def = {
    # SPU节点(IP为虚机IP，端口为未被使用端口)：alice、bob
    'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address': '127.0.0.1:3022'},
        {'party': 'bob',   'id': 'local:1', 'address': '127.0.0.1:3032'},
    ],
    'runtime_config': {
	    # 协议 Semi2k-SPDZ：一个半诚实NPC协议。
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}

link_desc = {
    # 接收超时毫秒
    'recv_timeout_ms': 3600000,
}

def main(_):
    # 将节点初始化到隐语框架中，address为ray的主节点IP + port，记录到驱动程序
    sf.init(['alice','bob'], address='local', log_to_driver=True)
    # 初始化PYU角色alice、bob  pyu会通过__call__方法将本地py数据映射到ray object store中
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')
    # 查询字段id，如果是多字段匹配查询，这里填写多个字段中间用逗号隔开
    key_columns = ['证件号码']
    # 查询结果展示字段(查询字段也会展示到查询结果对应数据上)
    label_columns = ['姓名','证件类型','证件号码','银行卡号','住址']
	# 启动SPU
    spu = sf.SPU(cluster_def, link_desc)
    # 服务器端数据文件路径
    pir_input_path = '/home/pir/csv/gonghang.csv'
    # 服务器端随机密钥路径 用于将服务端数据初始化成数据库数据 (生成方式：dd if=/dev/urandom of=/home/pir/bin/oprf_key.bin bs=32 count=1)
    pir_oprf_key_path = '/home/pir/bin/oprf_key.bin'
    # 服务端数据生成数据库文件生成路径
    pir_setup_path = '/home/pir/set/'
    # 记录开始时间
    start = time.time()
    # 服务器端设置
    reports = spu.pir_setup(
        server='bob',# Which party is pir server
        input_path=pir_input_path,# Server's CSV file path
        key_columns=key_columns,# Column(s) used as pir key
        label_columns=label_columns,# Column(s) used as pir label
        oprf_key_path=pir_oprf_key_path,# Ecc oprf secret key path
        setup_path=pir_setup_path,# Offline/Setup phase output data dir. Use an absolute path.
        num_per_query=1, # 查询次数 Items number per query
        label_max_len=100,  # 查询结果过字段总和最大长度 Max number bytes of label, padding data to label_max_len
        bucket_size=100,# Split data bucket to do pir query
    )
    # 日志打印服务器设置后 reports 内容
    logging.info(f"offline psi reports: {reports}")
    # 日志打印服务器设置运行时间
    logging.info(f"cost time: {time.time() - start}")
    # alice查询数据路径
    alice_input_path = '/home/pir/csv/nonghang.csv'
    # 记录开始时间
    start = time.time()
    # 调用spu的匿踪查询方法
    reports = spu.pir_query(
        server='bob',# server (str): Which party is pir server
        client='alice',# client (str): Which party is pir client.
        server_setup_path=pir_setup_path,# Setup path for sever
        client_key_columns=key_columns,# Column(s) used as pir key
        client_input_path=alice_input_path,# Client's query input path
        client_output_path='/home/pir/result/nonghang_pir.csv',# Client's query output path
    )
    # 日志打印查询完成后的 reports 内容
    logging.info(f"online pir reports: {reports}")
    # 日志打印查询动作运行时间
    logging.info(f"cost time: {time.time() - start}")
	# 关闭sf
    sf.shutdown()
# 调用main方法
if __name__ == '__main__':
    app.run(main)
```

**Comment by Chrisdehe** [comment]
hey，请问数据是怎样呢？从报错来看是数据的格式有问题。

**Comment by coderSun20201112** [comment]
确实是数据问题，
我用JAVA生成csv之后，用wps再打开，wps把身份证号、银行卡号进行了科学计数法表示，后面我在用txt打开，还是科学计数法，这就导致csv文件不可用，重新生成一份csvn就没问题了
