### ISSUE TITLE
SecretPad模型训练组件报错

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/secretflow#1242]
### Issue Type

Bug

### Source

binary

### Secretflow Version

SecretPad

### OS Platform and Distribution

SecretPad

### Python version

SecretPad

### What happend and What you expected to happen.

```shell
您好，我在尝试使用SecretPad训练简单的逻辑回归模型时一直无法跑通模型训练组件。数据集选用的是Breast-Cancer，特征由两方均分。组件仅添加了样本表读入、PSI和逻辑回归训练。在模型训练时会出现以下错误：
2024-04-10 10:36:17 INFO the jobId=uwky, taskId=uwky-cwhtjlug-node-4 start ...
2024-04-10 10:36:30 INFO the jobId=uwky, taskId=uwky-cwhtjlug-node-4 failed: party alice failed msg: container[secretflow] terminated state reason "Error", message: "tionAgent pid=1670)\x1b[0m   File \"python/ray/_raylet.pyx\", line 945, in ray._raylet.execute_task
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m   File \"python/ray/_raylet.pyx\", line 575, in ray._raylet.store_task_errors
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m   File \"/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py\", line 466, in _resume_span
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m     return method(self, *_args, **_kwargs)
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m   File \"/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py\", line 76, in wrapper
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m     return method(*args, **kwargs)
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m TypeError: __len__() missing 1 required positional argument: 'idx'
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m 
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m During handling of the above exception, another exception occurred:
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m 
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m Traceback (most recent call last):
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m   File \"python/ray/_raylet.pyx\", line 1176, in ray._raylet.task_execution_handler
\x1b[2m\x1b[36m(PartitionAgent pid=1670)\x1b[0m SystemExit
Traceback (most recent call last):
  File \"/usr/local/lib/python3.8/runpy.py\", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File \"/usr/local/lib/python3.8/runpy.py\", line 87, in _run_code
    exec(code, run_globals)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py\", line 530, in <module>
    main()
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1157, in __call__
    return self.main(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1078, in main
    rv = self.invoke(ctx)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 783, in invoke
    return __callback(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py\", line 510, in main
    res = comp_eval(sf_node_eval_param, storage_config, sf_cluster_config)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/entry.py\", line 164, in comp_eval
    res = comp.eval(
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/component.py\", line 1091, in eval
    raise e from None
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/component.py\", line 1086, in eval
    ret = self.__eval_callback(**kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/ml/linear/ss_sgd.py\", line 191, in ss_sgd_train_eval_fn
    x = load_table(
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/data_utils.py\", line 364, in load_table
    vdf = read_csv(filepaths, dtypes=dtypes, nrows=nrows)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/data/vertical/io.py\", line 182, in read_csv
    parties_length[device.party] = len(part)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/data/core/partition.py\", line 152, in __len__
    return reveal(self.part_agent.__len__(self.agent_idx))
  File \"/usr/local/lib/python3.8/site-packages/secretflow/device/driver.py\", line 162, in reveal
    all_object = sfd.get(all_object_refs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py\", line 156, in get
    return fed.get(object_refs)
  File \"/usr/local/lib/python3.8/site-packages/fed/api.py\", line 621, in get
    values = ray.get(ray_refs)
  File \"/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper
    return func(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/ray/_private/worker.py\", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
\tclass_name: PartitionAgent
\tactor_id: e89ecee123bf386b2e84b62001000000
\tpid: 1670
\tnamespace: 9a26233c-de6a-4857-b81b-bc0aff9c9912
\tip: uwky-cwhtjlug-node-4-0-global.alice.svc
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File \"python/ray/_raylet.pyx\", line 823, in ray._raylet.execute_task
  File \"python/ray/_raylet.pyx\", line 875, in ray._raylet.execute_task
  File \"python/ray/_raylet.pyx\", line 830, in ray._raylet.execute_task
  File \"python/ray/_raylet.pyx\", line 834, in ray._raylet.execute_task
  File \"python/ray/_raylet.pyx\", line 780, in ray._raylet.execute_task.function_executor
  File \"/usr/local/lib/python3.8/site-packages/ray/_private/function_manager.py\", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py\", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py\", line 76, in wrapper
    return method(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/data/core/agent.py\", line 63, in append_data
    source = source(**kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/data/core/io.py\", line 68, in read_csv_wrapper
    df = _read_csv(filepath, read_backend, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/data/core/io.py\", line 51, in _read_csv
    return read_pandas_csv(_filepath, *_args, **_kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/data/core/pandas/util.py\", line 38, in read_pandas_csv
    df = pd.read_csv(open(filepath), *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py\", line 211, in wrapper
    return func(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py\", line 331, in wrapper
    return func(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py\", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File \"/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py\", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File \"/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py\", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File \"/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py\", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File \"/usr/local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File \"/usr/local/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py\", line 917, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['texture_error', 'mean_concavity', 'mean_symmetry', 'smoothness_error', 'mean_perimeter', 'perimeter_error', 'mean_fractal_dimension', 'mean_compactness', 'radius_error', 'area_error', 'mean_area', 'mean_smoothness', 'mean_concave_points', 'mean_radius', 'mean_texture']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"python/ray/_raylet.pyx\", line 1135, in ray._raylet.task_execution_handler
  File \"python/ray/_raylet.pyx\", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File \"python/ray/_raylet.pyx\", line 782, in ray._raylet.execute_task
  File \"python/ray/_raylet.pyx\", line 945, in ray._raylet.execute_task
  File \"python/ray/_raylet.pyx\", line 575, in ray._raylet.store_task_errors
  File \"/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py\", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py\", line 76, in wrapper
    return method(*args, **kwargs)
TypeError: __len__() missing 1 required positional argument: 'idx'
An unexpected internal error occurred while the worker was executing a task.
"

然后我以为需要选择主键，但是在特征中加入主键之后还是报错：
2024-04-10 10:50:12 INFO the jobId=cnah, taskId=cnah-cwhtjlug-node-4 start ...
2024-04-10 10:50:22 INFO the jobId=cnah, taskId=cnah-cwhtjlug-node-4 failed: party alice failed msg: container[secretflow] terminated state reason "Error", message: ", arg.party=alice
2024-04-10 02:50:18.999 DEBUG fed_actor.py:104 [alice] -- [Anonymous_job] Actor method call: __len__, num_returns: 1
\x1b[2m\x1b[33m(raylet)\x1b[0m [2024-04-10 02:50:19,482 I 1321 1321] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
\x1b[2m\x1b[33m(raylet)\x1b[0m [2024-04-10 02:50:19,518 I 1323 1323] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
2024-04-10 02:50:20.506 DEBUG proxy.py:45 [alice] -- [Anonymous_job] Run method columns of actor <class 'secretflow.data.core.agent.PartitionAgent'>, num_returns=1, args len: 1, kwargs len: 0.
2024-04-10 02:50:20.506 DEBUG utils.py:63 [alice] -- [Anonymous_job] Insert fed object, arg.party=alice
2024-04-10 02:50:20.506 DEBUG fed_actor.py:104 [alice] -- [Anonymous_job] Actor method call: columns, num_returns: 1
2024-04-10 02:50:20.507 DEBUG proxy.py:45 [alice] -- [Anonymous_job] Run method shape of actor <class 'secretflow.data.core.agent.PartitionAgent'>, num_returns=1, args len: 1, kwargs len: 0.
2024-04-10 02:50:20.507 DEBUG utils.py:63 [alice] -- [Anonymous_job] Insert fed object, arg.party=alice
2024-04-10 02:50:20.507 DEBUG fed_actor.py:104 [alice] -- [Anonymous_job] Actor method call: shape, num_returns: 1
2024-04-10 02:50:20.508 INFO data_utils.py:367 [alice] -- [Anonymous_job] loaded VDataFrame, shape (569, 1)
2024-04-10 02:50:20.509 ERROR component.py:1089 [alice] -- [Anonymous_job] eval on domain: \"ml.train\"
name: \"ss_sgd_train\"
version: \"0.0.1\"
attr_paths: \"input/train_dataset/feature_selects\"
attr_paths: \"input/train_dataset/label\"
attr_paths: \"epochs\"
attr_paths: \"learning_rate\"
attr_paths: \"batch_size\"
attr_paths: \"sig_type\"
attr_paths: \"reg_type\"
attr_paths: \"penalty\"
attr_paths: \"l2_norm\"
attr_paths: \"eps\"
attrs {
  ss: \"mean_area\"
  ss: \"worst_area\"
  ss: \"mean_radius\"
  ss: \"mean_texture\"
  ss: \"mean_perimeter\"
  ss: \"mean_smoothness\"
  ss: \"mean_compactness\"
  ss: \"mean_concavity\"
  ss: \"mean_concave_points\"
  ss: \"mean_symmetry\"
  ss: \"mean_fractal_dimension\"
  ss: \"radius_error\"
  ss: \"texture_error\"
  ss: \"perimeter_error\"
  ss: \"area_error\"
  ss: \"smoothness_error\"
  ss: \"compactness_error\"
  ss: \"concavity_error\"
  ss: \"concave_points_error\"
  ss: \"symmetry_error\"
  ss: \"fractal_dimension_error\"
  ss: \"worst_radius\"
  ss: \"worst_texture\"
  ss: \"worst_perimeter\"
  ss: \"worst_smoothness\"
  ss: \"worst_compactness\"
  ss: \"worst_concavity\"
  ss: \"worst_concave_points\"
  ss: \"worst_symmetry\"
  ss: \"worst_fractal_dimension\"
  ss: \"uid\"
}
attrs {
  ss: \"target\"
}
attrs {
  i64: 10
}
attrs {
  f: 0.10000000149011612
}
attrs {
  i64: 1024
}
attrs {
  s: \"t1\"
}
attrs {
  s: \"logistic\"
}
attrs {
  s: \"None\"
}
attrs {
  f: 0.5
}
attrs {
  f: 0.0010000000474974513
}
inputs {
  name: \"cnah-cwhtjlug-node-3-output-0\"
  type: \"sf.table.vertical_table\"
  system_info {
  }
  meta {
    type_url: \"type.googleapis.com/secretflow.spec.v1.VerticalTable\"
    value: \"\
\\357\\002\
\\003uid\\022\\006target\\022\\013mean_radius\\022\\014mean_texture\\022\\016mean_perimeter\\022\\tmean_area\\022\\017mean_smoothness\\022\\020mean_compactness\\022\\016mean_concavity\\022\\023mean_concave_points\\022\\rmean_symmetry\\022\\026mean_fractal_dimension\\022\\014radius_error\\022\\rtexture_error\\022\\017perimeter_error\\022\
area_error\\022\\020smoothness_error\\\"\\003int*\\003int*\\005float*\\005float*\\005float*\\003int*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float\
\\203\\003\
\\003uid\\022\\021compactness_error\\022\\017concavity_error\\022\\024concave_points_error\\022\\016symmetry_error\\022\\027fractal_dimension_error\\022\\014worst_radius\\022\\rworst_texture\\022\\017worst_perimeter\\022\
worst_area\\022\\020worst_smoothness\\022\\021worst_compactness\\022\\017worst_concavity\\022\\024worst_concave_points\\022\\016worst_symmetry\\022\\027worst_fractal_dimension\\\"\\003int*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float*\\003int*\\005float*\\005float*\\005float*\\005float*\\005float*\\005float\\020\\271\\004\"
  }
  data_refs {
    uri: \"cnah-cwhtjlug-node-3-output-0\"
    party: \"alice\"
    format: \"csv\"
  }
  data_refs {
    uri: \"cnah-cwhtjlug-node-3-output-0\"
    party: \"bob\"
    format: \"csv\"
  }
}
output_uris: \"cnah-cwhtjlug-node-4-output-0\"
 failed, error <unknown cols {'uid'} in col_selects>
2024-04-10 02:50:20.509 INFO api.py:342 [alice] -- [Anonymous_job] Shutdowning rayfed intendedly...
2024-04-10 02:50:20.509 INFO api.py:356 [alice] -- [Anonymous_job] No wait for data sending.
2024-04-10 02:50:20.510 DEBUG message_queue.py:98 [alice] -- [Anonymous_job] Killing thread[DataSendingQueueThread].
2024-04-10 02:50:20.510 INFO message_queue.py:72 [alice] -- [Anonymous_job] Notify message polling thread[DataSendingQueueThread] to exit.
2024-04-10 02:50:20.510 DEBUG message_queue.py:98 [alice] -- [Anonymous_job] Killing thread[ErrorSendingQueueThread].
2024-04-10 02:50:20.510 INFO message_queue.py:72 [alice] -- [Anonymous_job] Notify message polling thread[ErrorSendingQueueThread] to exit.
2024-04-10 02:50:20.510 INFO api.py:384 [alice] -- [Anonymous_job] Shutdowned rayfed.
\x1b[2m\x1b[36m(SenderReceiverProxyActor pid=1025)\x1b[0m 2024-04-10 02:50:20.506 DEBUG barriers.py:397 [alice] -- [Anonymous_job] Sending send data to seq_id 9 of bob from 8#0 without credentials.
\x1b[2m\x1b[36m(SenderReceiverProxyActor pid=1025)\x1b[0m 2024-04-10 02:50:20.507 DEBUG barriers.py:408 [alice] -- [Anonymous_job] Succeeded to send data to seq_id 9 of bob from 8#0. Response is True
\x1b[2m\x1b[36m(SenderReceiverProxyActor pid=1025)\x1b[0m 2024-04-10 02:50:20.507 DEBUG barriers.py:397 [alice] -- [Anonymous_job] Sending send data to seq_id 11 of bob from 10#0 without credentials.
\x1b[2m\x1b[36m(SenderReceiverProxyActor pid=1025)\x1b[0m 2024-04-10 02:50:20.508 DEBUG barriers.py:408 [alice] -- [Anonymous_job] Succeeded to send data to seq_id 11 of bob from 10#0. Response is True
\x1b[2m\x1b[36m(SenderReceiverProxyActor pid=1025)\x1b[0m 2024-04-10 02:50:20.508 DEBUG barriers.py:397 [alice] -- [Anonymous_job] Sending send data to seq_id 13 of bob from 12#0 without credentials.
\x1b[2m\x1b[36m(SenderReceiverProxyActor pid=1025)\x1b[0m 2024-04-10 02:50:20.509 DEBUG barriers.py:408 [alice] -- [Anonymous_job] Succeeded to send data to seq_id 13 of bob from 12#0. Response is True
Traceback (most recent call last):
  File \"/usr/local/lib/python3.8/runpy.py\", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File \"/usr/local/lib/python3.8/runpy.py\", line 87, in _run_code
    exec(code, run_globals)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py\", line 530, in <module>
    main()
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1157, in __call__
    return self.main(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1078, in main
    rv = self.invoke(ctx)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 783, in invoke
    return __callback(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py\", line 510, in main
    res = comp_eval(sf_node_eval_param, storage_config, sf_cluster_config)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/entry.py\", line 164, in comp_eval
    res = comp.eval(
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/component.py\", line 1091, in eval
    raise e from None
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/component.py\", line 1086, in eval
    ret = self.__eval_callback(**kwargs)
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/ml/linear/ss_sgd.py\", line 191, in ss_sgd_train_eval_fn
    x = load_table(
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/data_utils.py\", line 337, in load_table
    v_headers = extract_table_header(
  File \"/usr/local/lib/python3.8/site-packages/secretflow/component/data_utils.py\", line 301, in extract_table_header
    raise AttributeError(f\"unknown cols {col_selects_set} in col_selects\")
AttributeError: unknown cols {'uid'} in col_selects
"
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by zimu-yuxi** [comment]
看报错是找不到uid，看下你的数据格式

**Comment by zzx-QDU** [comment]
Alice方数据为主键：uid、标签：target以及其余特征列；
Bob方数据为主键：uid以及其余特征列。

**Comment by zimu-yuxi** [comment]
两方的主键label改为不同的试一下呢，比如alice：uid1，bob：uid2

**Comment by zzx-QDU** [comment]
仍然不行，是否是主键必须为String？我用内置的葡萄牙银行数据集是可以进行训练的，但是同样的流程下换了数据集就不行，唯一的区别就是新数据集主键类型为int。

**Comment by zzx-QDU** [comment]
将主键类型设置为String也没有效果，报错依旧是：
TypeError: __len__() missing 1 required positional argument: 'idx'

**Comment by zimu-yuxi** [comment]
可以提供下测试数据吗？我们复现下

**Comment by zzx-QDU** [comment]
[cancer_alice.csv](https://github.com/secretflow/secretflow/files/14928365/cancer_alice.csv)
[cancer_bob.csv](https://github.com/secretflow/secretflow/files/14928366/cancer_bob.csv)

**Comment by zzx-QDU** [comment]
您好，我还遇到了一个问题。用内置数据集训练完模型后，进行二分类评估时总是失败。其中组件的标签选项我选择的时数据集的标签，预测选项选择的是模型预测得到的结果，即默认的pred列，其余为默认项。报错信息为
AttributeError: unknown cols {'y'} in col_selects

**Comment by zimu-yuxi** [comment]
配置截图发一下吧

**Comment by Chrisdehe** [comment]
> 您好，我还遇到一个问题。用内置数据集训练完成模型后，进行二分类评估时总是失败。其中组件的标签选项我选择时数据集的标签，预测选项选择是模型预测得到的结果，即默认的pred列，其余为默认项。报错信息为 AttributeError:known cols {'y'} in col_selects

你好@zzx-QDU ，通过报错信息查看你的数据后发现缺少Y标签，关于Y标签的介绍可以参考[#48](https://github.com/secretflow/secretpad/issues/48)

添加Y标签方法参考：
``
import pandas as pd
import numpy as np

# Read the CSV file
df = pd.read_csv('your_file.csv')

# Generate random 0s and 1s
random_values = np.random.randint(0, 2, len(df))

# Add the new column "y" with random values
df['y'] = random_values

# Save the modified dataframe to a new CSV file
df.to_csv('your_file_with_y.csv', index=False)
``

**Comment by Chrisdehe** [comment]
可以按照@zimu-yuxi的建议发一下配置截图

**Comment by zzx-QDU** [comment]
我们把输入样本表的位置交换了一下就能跑通了，感谢帮助。

**Comment by zzx-QDU** [comment]
我们把输入样本表的位置交换了一下就能跑通了，感谢帮助。

**Comment by coffee1110** [comment]
@您好，我碰到上述idx的问题，不过我实在随机分割的环节出现的，请问是如何解决的
`
![image](https://github.com/secretflow/secretflow/assets/20594628/7841d265-e300-40f4-8724-2972dffb4a6a)
`

**Comment by coffee1110** [comment]
日志如下
`2024-04-22T15:51:07.623594245+08:00 stderr F The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
2024-04-22T15:51:07.623596122+08:00 stderr F  Traceback (most recent call last):
2024-04-22T15:51:07.623597969+08:00 stderr F   File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
2024-04-22T15:51:07.623622194+08:00 stderr F   File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
2024-04-22T15:51:07.6236242+08:00 stderr F   File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
2024-04-22T15:51:07.623626081+08:00 stderr F   File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
2024-04-22T15:51:07.623628123+08:00 stderr F   File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
2024-04-22T15:51:07.623632031+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
2024-04-22T15:51:07.623634213+08:00 stderr F     return method(__ray_actor, *args, **kwargs)
2024-04-22T15:51:07.623636237+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
2024-04-22T15:51:07.623671843+08:00 stderr F     return method(self, *_args, **_kwargs)
2024-04-22T15:51:07.623680317+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py", line 76, in wrapper
2024-04-22T15:51:07.623682612+08:00 stderr F     return method(*args, **kwargs)
2024-04-22T15:51:07.62368475+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/data/core/agent.py", line 63, in append_data
2024-04-22T15:51:07.623686831+08:00 stderr F     source = source(**kwargs)
2024-04-22T15:51:07.623688716+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/data/core/io.py", line 68, in read_csv_wrapper
2024-04-22T15:51:07.623690715+08:00 stderr F     df = _read_csv(filepath, read_backend, **kwargs)
2024-04-22T15:51:07.623692531+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/data/core/io.py", line 51, in _read_csv
2024-04-22T15:51:07.623694388+08:00 stderr F     return read_pandas_csv(_filepath, *_args, **_kwargs)
2024-04-22T15:51:07.623696205+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/data/core/pandas/util.py", line 38, in read_pandas_csv
2024-04-22T15:51:07.623698098+08:00 stderr F     df = pd.read_csv(open(filepath), *args, **kwargs)
2024-04-22T15:51:07.623699958+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
2024-04-22T15:51:07.623701828+08:00 stderr F     return func(*args, **kwargs)
2024-04-22T15:51:07.623703682+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
2024-04-22T15:51:07.623705545+08:00 stderr F     return func(*args, **kwargs)
2024-04-22T15:51:07.623707388+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
2024-04-22T15:51:07.623709249+08:00 stderr F     return _read(filepath_or_buffer, kwds)
2024-04-22T15:51:07.623711091+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 611, in _read
2024-04-22T15:51:07.623712973+08:00 stderr F     return parser.read(nrows)
2024-04-22T15:51:07.623714833+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1778, in read
2024-04-22T15:51:07.623716672+08:00 stderr F     ) = self._engine.read(  # type: ignore[attr-defined]
2024-04-22T15:51:07.623718522+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
2024-04-22T15:51:07.6237204+08:00 stderr F     chunks = self._reader.read_low_memory(nrows)
2024-04-22T15:51:07.623722285+08:00 stderr F   File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
2024-04-22T15:51:07.623726304+08:00 stderr F   File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader._read_rows
2024-04-22T15:51:07.623728268+08:00 stderr F   File "pandas/_libs/parsers.pyx", line 1037, in pandas._libs.parsers.TextReader._convert_column_data
2024-04-22T15:51:07.623730144+08:00 stderr F   File "pandas/_libs/parsers.pyx", line 1068, in pandas._libs.parsers.TextReader._convert_tokens
2024-04-22T15:51:07.623732011+08:00 stderr F   File "pandas/_libs/parsers.pyx", line 1187, in pandas._libs.parsers.TextReader._convert_with_dtype
2024-04-22T15:51:07.623733876+08:00 stderr F ValueError: Integer column has NA values in column 3
2024-04-22T15:51:07.623735663+08:00 stderr F 
2024-04-22T15:51:07.623737681+08:00 stderr F During handling of the above exception, another exception occurred:
2024-04-22T15:51:07.6237395+08:00 stderr F 
2024-04-22T15:51:07.62374137+08:00 stderr F Traceback (most recent call last):
2024-04-22T15:51:07.62374584+08:00 stderr F   File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
2024-04-22T15:51:07.623747913+08:00 stderr F   File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
2024-04-22T15:51:07.623749839+08:00 stderr F   File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
2024-04-22T15:51:07.623751732+08:00 stderr F   File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
2024-04-22T15:51:07.62375361+08:00 stderr F   File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
2024-04-22T15:51:07.623755472+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
2024-04-22T15:51:07.623757376+08:00 stderr F     return method(self, *_args, **_kwargs)
2024-04-22T15:51:07.623759258+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py", line 76, in wrapper
2024-04-22T15:51:07.623762663+08:00 stderr F     return method(*args, **kwargs)
2024-04-22T15:51:07.623764582+08:00 stderr F TypeError: __len__() missing 1 required positional argument: 'idx'
2024-04-22T15:51:07.623766479+08:00 stderr F An unexpected internal error occurred while the worker was executing a task.
`

**Comment by Chrisdehe** [comment]
@coffee1110 看报错信息是缺少了一个参数的配置，辛苦参考[平台组建说明](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/pf7woou4dzgc90ol#dnMWc)操作

**Comment by coffee1110** [comment]
您好，我的参数配置如下
隐私求交
![Dingtalk_20240422160558](https://github.com/secretflow/secretflow/assets/20594628/fbd83152-cf0b-45d8-bf43-243d112c5d21)
随机分割
![分割](https://github.com/secretflow/secretflow/assets/20594628/cb9d7e4e-801b-4f79-9015-d8075532c698)
参数都配置了吧，只是换了样本表更换后就出现这个问题

**Comment by coffee1110** [comment]
样本表alice也存在uid2,bob表有uid3的数据，但是随机分割的时候就出现了idx异常

**Comment by zzx-QDU** [comment]
@coffee1110  secretpad内置的数据集好像时bob的带标签，我们没有跑通的设置都是将alice的数据放在第一个样本表，之后我们误打误撞地将bob的数据放到第一个就没有出错。似乎带标签的数据应该放到第一个样本表上，您可以检查下标签是否在第一个样本表上。

**Comment by coffee1110** [comment]
您的意思是交换样本表的位置是吗？我这这边使用的数据集是Bank Marketing Data Set的数据集

**Comment by zzx-QDU** [comment]
是的 应该是那个内置的数据集吧，那应该将bob的数据放到第一个样本表里。

**Comment by coffee1110** [comment]
交换之后还是出现一样的问题，是不是我的数据集有问题
![bob](https://github.com/secretflow/secretflow/assets/20594628/dfa0c86b-bc8f-4612-86c0-2f99fd7009da)
第二个样本表
![alice](https://github.com/secretflow/secretflow/assets/20594628/5b4c2483-18b4-4db0-a9d6-849d05730672)
求交
![求交](https://github.com/secretflow/secretflow/assets/20594628/b201c94d-d7d5-491a-a609-83a79b83c4f2)
我目前使用的数据集如下
[alice.csv](https://github.com/secretflow/secretflow/files/15059855/alice.csv)
[bob.csv](https://github.com/secretflow/secretflow/files/15059856/bob.csv)

**Comment by zzx-QDU** [comment]
是内置的数据集吗？

**Comment by coffee1110** [comment]
不是secretpad的内置数据集，是金融分控场景方案中提供的数据集
https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.5.0b0/tutorial/risk_control_scenario

**Comment by zzx-QDU** [comment]
不好意思，这我就不清楚了。我只是简单体验了一下，只用了内置数据集。

**Comment by coffee1110** [comment]
好的，好的，没关系，我在测试下，谢谢了

**Comment by coffee1110** [comment]
找到原因了，是我这边的alice数据集特征列存在空值导致的分割出现idx异常
