### ISSUE TITLE
为什么trustedflow框架里面，alice上传密钥，会出错？

### ISSUE THREAD

**Issue by joaquinboss** [secretflow/secretflow#1293]
### Issue Type

Bug

### Source

binary

### Secretflow Version

trustedflow 0.2.0b0.post0

### OS Platform and Distribution

ubuntu20.04

### Python version

3.10.14

### What happend and What you expected to happen.

```shell
执行到trustedflow框架的步骤二，第三步，仿真模式，第5的alice上传密钥"cms --config-file alice.yaml register-data-keys"命令后，报错。我检查了，第4的"register_data_keys"配置alice.yaml文件，格式和内容都没有错，密钥也对应上了。
```

### Reproduction code to reproduce the issue.

```shell
报错信息如下：
Traceback (most recent call last):
 File "/root/miniconda3/envs/capsule-manager-sdk/bin/cms", line 8, in <module>
  sys.exit(cms())
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
  return self.main(*args, **kwargs)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1078, in main
  rv = self.invoke(ctx)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1685, in invoke
  super().invoke(ctx)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 783, in invoke
  return __callback(*args, **kwargs)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
  return f(get_current_context(), *args, **kwargs)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/cli/cms.py", line 55, in cms
  config = file.read_yaml_file(CONFIG_FILE)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/sdc/util/file.py", line 38, in read_yaml_file
  res = yaml.load(f)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/main.py", line 451, in load
  return constructor.get_single_data()
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 114, in get_single_data
  node = self.composer.get_single_node()
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 72, in get_single_node
  document = self.compose_document()
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 94, in compose_document
  node = self.compose_node(None, None)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 130, in compose_node
  node = self.compose_mapping_node(anchor)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
  item_value = self.compose_node(node, item_key)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 130, in compose_node
  node = self.compose_mapping_node(anchor)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
  item_value = self.compose_node(node, item_key)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 128, in compose_node
  node = self.compose_sequence_node(anchor)
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 172, in compose_sequence_node
  while not self.parser.check_event(SequenceEndEvent):
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 141, in check_event
  self.current_event = self.state()
 File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 546, in parse_block_sequence_entry
  raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a block collection
 in "alice.yaml", line 52, column 5
expected <block end>, but found '<scalar>'
 in "alice.yaml", line 56, column 7

alice.yaml文件只做了以下变动：
register_data_keys:
  data_keys:
    - 
      # (required) str
      resource_uri: breast_cancer_alice
      # (required) str
      data_key_b64: xxxx###对应上没问题的
```

**Comment by joaquinboss** [comment]
该问题已解决，麻烦大佬们帮我看下最新的问题，感激不尽
[https://github.com/secretflow/trustedflow/issues/53](url)
