### ISSUE TITLE
基于secretflow/secretflow-lite-anolis8 二次打包，容器中运行ray start --head 异常

### ISSUE THREAD

**Issue by jianjew** [secretflow/secretflow#1310]
通过原生镜像 docker run -itd --network=host --name=alice secretflow/secretflow-lite-anolis8  起容器，进入容器运行
ray start --head \
--node-ip-address="192.168.1.128" \
--port="8090" \
--resources='{"server": 16}' \
--include-dashboard=False \
--disable-usage-stats
ray正常启动

但是基于secretflow/secretflow-lite-anolis8:latest镜像二次打包一个私有镜像，Dockerfile如下：

FROM secretflow/secretflow-lite-anolis8:latest

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /linkerpir
ADD . .
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.doubanio.com/simple/
ENV PATH=$PATH:/linkerpir
ENV PYTHONPATH /linkerpir
RUN ["chmod","+x","/start.sh"]

CMD ["/bin/bash","./start.sh"]

start.sh如下:
#!/bin/bash

# run main to get http request
python ./src/main.py

此时进入容器运行
ray start --head \
--node-ip-address="192.168.1.128" \
--port="8090" \
--resources='{"server": 16}' \
--include-dashboard=False \
--disable-usage-stats
ray启动异常，报错日志如下：
Usage stats collection is disabled.

Local node IP: 192.168.1.128
Traceback (most recent call last):
  File "/usr/local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2498, in main
    return cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/scripts/scripts.py", line 771, in start
    node = ray._private.node.Node(
  File "/usr/local/lib/python3.10/site-packages/ray/_private/node.py", line 306, in __init__
    self.start_head_processes()
  File "/usr/local/lib/python3.10/site-packages/ray/_private/node.py", line 1310, in start_head_processes
    assert self.get_gcs_client() is not None
  File "/usr/local/lib/python3.10/site-packages/ray/_private/node.py", line 677, in get_gcs_client
    self._init_gcs_client()
  File "/usr/local/lib/python3.10/site-packages/ray/_private/node.py", line 722, in _init_gcs_client
    raise RuntimeError(
RuntimeError: Failed to start GCS.  Last 0 lines of error files:

**Comment by Chrisdehe** [comment]
请问问题是否得到解决？
