### ISSUE TITLE
运行水平联邦学习任务报错

### ISSUE THREAD

**Issue by Klein920116** [secretflow/secretflow#1331]
### Issue Type

Bug

### Source

binary

### Secretflow Version

sceretflow 0.6.13b0

### OS Platform and Distribution

CentOS Linux release 7.9.2009

### Python version

3.10.14

### What happend and What you expected to happen.

```shell
3个节点运行水平联邦xgboost任务，运行不成功

python test.py
2024-06-13 16:30:39,627 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 10.0.70.34:30001...
2024-06-13 16:30:39,641 INFO worker.py:1724 -- Connected to Ray cluster.
2024-06-13 16:30:39.685 INFO api.py:233 [bob] -- [Anonymous_job] Started rayfed with {'CLUSTER_ADDRESSES': {'alice': '10.0.70.33:30003', 'bob': '0.0.0.0:30003', 'charlie': '10.0.70.35:30003'}, 'CURRENT_PARTY_NAME': 'bob', 'TLS_CONFIG': {}}
2024-06-13 16:30:41.649 INFO barriers.py:284 [bob] -- [Anonymous_job] Succeeded to create receiver proxy actor.
(ReceiverProxyActor pid=11456) 2024-06-13 16:30:41.642 INFO grpc_proxy.py:359 [bob] -- [Anonymous_job] ReceiverProxy binding port 30003, options: (('grpc.enable_retries', 1), ('grpc.so_reuseport', 0), ('grpc.max_send_message_length', 524288000), ('grpc.max_receive_message_length', 524288000), ('grpc.service_config', '{"methodConfig": [{"name": [{"service": "GrpcService"}], "retryPolicy": {"maxAttempts": 5, "initialBackoff": "5s", "maxBackoff": "30s", "backoffMultiplier": 2, "retryableStatusCodes": ["UNAVAILABLE"]}}]}'))...
(ReceiverProxyActor pid=11456) 2024-06-13 16:30:41.647 INFO grpc_proxy.py:379 [bob] -- [Anonymous_job] Successfully start Grpc service without credentials.
2024-06-13 16:30:43.342 INFO barriers.py:333 [bob] -- [Anonymous_job] SenderProxyActor has successfully created.
2024-06-13 16:30:43.342 INFO proxy.py:180 [bob] -- [Anonymous_job] Create proxy actor <class 'secretflow.security.aggregation.secure_aggregator._Masker'> with party alice.
2024-06-13 16:30:43.342 INFO proxy.py:180 [bob] -- [Anonymous_job] Create proxy actor <class 'secretflow.security.aggregation.secure_aggregator._Masker'> with party bob.
(raylet) [2024-06-13 16:30:45,707 E 31450 31476] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-06-12_17-33-52_739531_31314 is over 95% full, available space: 6912364544; capacity: 208270266368. Object creation will fail if spilling is required.
2024-06-13 16:30:46.338 INFO proxy.py:180 [bob] -- [Anonymous_job] Create proxy actor <class 'secretflow.data.core.agent.PartitionAgent'> with party alice.
2024-06-13 16:30:46.338 INFO proxy.py:180 [bob] -- [Anonymous_job] Create proxy actor <class 'secretflow.data.core.agent.PartitionAgent'> with party bob.
2024-06-13 16:30:51.542 INFO proxy.py:180 [bob] -- [Anonymous_job] Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party alice.
2024-06-13 16:30:51.543 INFO proxy.py:180 [bob] -- [Anonymous_job] Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party bob.
2024-06-13 16:30:51.591 INFO proxy.py:180 [bob] -- [Anonymous_job] Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party charlie.
(raylet) [2024-06-13 16:30:55,726 E 31450 31476] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-06-12_17-33-52_739531_31314 is over 95% full, available space: 6912008192; capacity: 208270266368. Object creation will fail if spilling is required.
(_run pid=31624) INFO:jax._src.xla_bridge:Unable to initialize backend 'cuda': 
(_run pid=31624) INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=31624) INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
2024-06-13 16:31:02.276 INFO proxy.py:180 [bob] -- [Anonymous_job] Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party alice.
2024-06-13 16:31:02.276 INFO proxy.py:180 [bob] -- [Anonymous_job] Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party bob.
2024-06-13 16:31:05.386 INFO homo_binning.py:153 [bob] -- [Anonymous_job] start recursive
2024-06-13 16:31:05.464 WARNING cleanup.py:154 [bob] -- [Anonymous_job] Failed to send ObjectRef(5eaed04c7808e6ac52e1e07f7035dde040a724eb0700000001000000) to alice, error: ray::SenderProxyActor.send() (pid=11506, ip=10.0.70.34, actor_id=52e1e07f7035dde040a724eb07000000, repr=<fed.proxy.barriers.SenderProxyActor object at 0x7f2010150f10>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::HomoBooster.homo_train() (pid=11681, ip=10.0.70.34, actor_id=208358a39adfeaf3c24d4d4b07000000, repr=<secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster object at 0x7f2828090b80>)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/device/proxy.py", line 76, in wrapper
    return method(*args, **kwargs)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/homo_booster_worker.py", line 146, in homo_train
    self.bst = train(
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 208, in train
    bst = _train_internal(
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 136, in _train_internal
    bst.federate_update(params, dtrain, hdata, global_bin, iter_round=i, fobj=obj)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/core.py", line 117, in federate_update
    grad, hess = fobj(pred, dtrain)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/tree_core/loss_function.py", line 114, in _softmaxobj
    grad = (prob - labels).astype(np.float64)
ValueError: operands could not be broadcast together with shapes (1000,6) (1000,2),upstream_seq_id: 198#0, downstream_seq_id: 201.
2024-06-13 16:31:05.464 INFO cleanup.py:161 [bob] -- [Anonymous_job] Sending error operands could not be broadcast together with shapes (1000,6) (1000,2)  to alice.
Traceback (most recent call last):
  File "/home/admin/secretflow/hello1.py", line 106, in <module>
2024-06-13 16:31:05.466 WARNING cleanup.py:127 [bob] -- [Anonymous_job] Signal SIGINT to exit.
2024-06-13 16:31:05.466 WARNING api.py:60 [bob] -- [Anonymous_job] Stop signal received (e.g. via SIGINT/Ctrl+C), try to shutdown fed. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip.
2024-06-13 16:31:05.466 WARNING api.py:344 [bob] -- [Anonymous_job] Shutdowning rayfed unintendedly...
2024-06-13 16:31:05.467 ERROR api.py:349 [bob] -- [Anonymous_job] Cross-silo sending error occured. ray::SenderProxyActor.send() (pid=11506, ip=10.0.70.34, actor_id=52e1e07f7035dde040a724eb07000000, repr=<fed.proxy.barriers.SenderProxyActor object at 0x7f2010150f10>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::HomoBooster.homo_train() (pid=11681, ip=10.0.70.34, actor_id=208358a39adfeaf3c24d4d4b07000000, repr=<secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster object at 0x7f2828090b80>)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/device/proxy.py", line 76, in wrapper
    return method(*args, **kwargs)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/homo_booster_worker.py", line 146, in homo_train
    self.bst = train(
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 208, in train
    bst = _train_internal(
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 136, in _train_internal
    bst.federate_update(params, dtrain, hdata, global_bin, iter_round=i, fobj=obj)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/core.py", line 117, in federate_update
    grad, hess = fobj(pred, dtrain)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/tree_core/loss_function.py", line 114, in _softmaxobj
    grad = (prob - labels).astype(np.float64)
ValueError: operands could not be broadcast together with shapes (1000,6) (1000,2)
2024-06-13 16:31:05.467 INFO api.py:356 [bob] -- [Anonymous_job] No wait for data sending.
2024-06-13 16:31:05.468 INFO message_queue.py:72 [bob] -- [Anonymous_job] Notify message polling thread[ErrorSendingQueueThread] to exit.
2024-06-13 16:31:05.469 INFO api.py:371 [bob] -- [Anonymous_job] Shutdowned rayfed.
2024-06-13 16:31:05.469 CRITICAL api.py:375 [bob] -- [Anonymous_job] Exit now due to the previous error.
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/homo_booster.py", line 194, in train
    reveal(self.fed_bst)  # wait all tasks done
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/device/driver.py", line 162, in reveal
    all_object = sfd.get(all_object_refs)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/distributed/primitive.py", line 156, in get
    return fed.get(object_refs)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/fed/api.py", line 621, in get
    values = ray.get(ray_refs)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::HomoBooster.homo_train() (pid=11681, ip=10.0.70.34, actor_id=208358a39adfeaf3c24d4d4b07000000, repr=<secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster object at 0x7f2828090b80>)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/device/proxy.py", line 76, in wrapper
    return method(*args, **kwargs)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/homo_booster_worker.py", line 146, in homo_train
    self.bst = train(
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 208, in train
    bst = _train_internal(
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 136, in _train_internal
    bst.federate_update(params, dtrain, hdata, global_bin, iter_round=i, fobj=obj)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/boost_core/core.py", line 117, in federate_update
    grad, hess = fobj(pred, dtrain)
  File "/root/.miniconda3/envs/myenv/lib/python3.10/site-packages/secretflow/ml/boost/homo_boost/tree_core/loss_function.py", line 114, in _softmaxobj
    grad = (prob - labels).astype(np.float64)
ValueError: operands could not be broadcast together with shapes (1000,6) (1000,2)
(HomoBooster pid=11681) [16:31:05] WARNING: ../src/learner.cc:767: 
(HomoBooster pid=11681) Parameters: { "colsample_by_tree" } are not used.
(HomoBooster pid=11681) 
(raylet) [2024-06-13 16:31:05,744 E 31450 31476] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-06-12_17-33-52_739531_31314 is over 95% full, available space: 6911897600; capacity: 208270266368. Object creation will fail if spilling is required.
```

### Reproduction code to reproduce the issue.

```shell
------------------------Alice--------------------------
from secretflow.data.horizontal import read_csv
from secretflow.security.aggregation import SecureAggregator
from secretflow.security.compare import SPUComparator
from secretflow.utils.simulation.datasets import load_dermatology
from secretflow.ml.boost.homo_boost import SFXgboost
import secretflow as sf
import spu

# In case you have a running secretflow runtime already.
sf.shutdown()

cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.0.70.33:30003',
            'listen_addr': '0.0.0.0:30003'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.0.70.34:30003',
            'listen_addr': '0.0.0.0:30003'
        },
        'charlie': {
            # replace with bob's real address.
            'address': '10.0.70.35:30003',
            'listen_addr': '0.0.0.0:30003'
        },
    },
    'self_party': 'alice'
}

sf.init(address='10.0.70.33:30001', cluster_config=cluster_config,cross_silo_comm_backend='grpc',enable_waiting_for_other_parties_ready=False)
alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            # Please choose an unused port.
            'address': '10.0.70.33:30002',
            'listen_addr': '10.0.70.33:30002'
        },
        {
            'party': 'bob',
            # Please choose an unused port.
            'address': '10.0.70.34:30002',
            'listen_addr': '10.0.70.34:30002'
        },
                {
            'party': 'charlie',
            # Please choose an unused port.
            'address': '10.0.70.35:30002',
            'listen_addr': '10.0.70.35:30002'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

# your code to run.

aggr = SecureAggregator(charlie, [alice, bob])
spu = sf.SPU(cluster_def=cluster_def)
comp = SPUComparator(spu)

path_dict = {alice: '/home/admin/secretflow/promoter.csv', bob: ''}
data = read_csv(filepath=path_dict, aggregator=aggr, comparator=comp)
data.fillna(value=0, inplace=True)
params = {
         # XGBoost parameter tutorial
         # https://xgboost.readthedocs.io/en/latest/parameter.html
         'max_depth': 4, # max depth
         'eta': 0.3, # learning rate
         'objective': 'multi:softmax', # objection function，support "binary:logistic","reg:logistic","multi:softmax","multi:softprob","reg:squarederror"
         'min_child_weight': 1, # The minimum value of weight
         'lambda': 0.1, # L2 regularization term on weights (xgb's lambda)
         'alpha': 0, # L1 regularization term on weights (xgb's alpha)
         'max_bin': 10, # Max num of binning
         'num_class':6, # Only required in multi-class classification
         'gamma': 0, # Same to min_impurity_split,The minimux gain for a split
         'subsample': 1.0, # Subsample rate by rows
         'colsample_by_tree': 1.0, # Feature selection rate by tree
         'colsample_bylevel': 1.0, # Feature selection rate by level
         'eval_metric': 'merror',  # supported eval metric：
                                    # 1. rmse
                                    # 2. rmsle
                                    # 3. mape
                                    # 4. logloss
                                    # 5. error
                                    # 6. error@t
                                    # 7. merror
                                    # 8. mlogloss
                                    # 9. auc
                                    # 10. aucpr
         # Special params in SFXgboost
         # Required
         'hess_key': 'hess', # Required, Mark hess columns, optionally choosing a column name that is not in the data set
         'grad_key': 'grad', # Required，Mark grad columns, optionally choosing a column name that is not in the data set
         'label_key': 'class', # Required，ark label columns, optionally choosing a column name that is not in the data set
}

bst = SFXgboost(server=charlie, clients=[alice, bob])
bst.train(data, data, params=params, num_boost_round = 6)

------------------------Bob--------------------------
from secretflow.data.horizontal import read_csv
from secretflow.security.aggregation import SecureAggregator
from secretflow.security.compare import SPUComparator
from secretflow.utils.simulation.datasets import load_dermatology
from secretflow.ml.boost.homo_boost import SFXgboost
import secretflow as sf
import spu

# In case you have a running secretflow runtime already.
sf.shutdown()

cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.0.70.33:30003',
            'listen_addr': '0.0.0.0:30003'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.0.70.34:30003',
            'listen_addr': '0.0.0.0:30003'
        },
        'charlie': {
            # replace with bob's real address.
            'address': '10.0.70.35:30003',
            'listen_addr': '0.0.0.0:30003'
        },
    },
    'self_party': 'bob'
}

sf.init(address='10.0.70.34:30001', cluster_config=cluster_config,cross_silo_comm_backend='grpc',enable_waiting_for_other_parties_ready=False)
alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            # Please choose an unused port.
            'address': '10.0.70.33:30002',
            'listen_addr': '10.0.70.33:30002'
        },
        {
            'party': 'bob',
            # Please choose an unused port.
            'address': '10.0.70.34:30002',
            'listen_addr': '10.0.70.34:30002'
        },
        {
            'party': 'charlie',
            # Please choose an unused port.
            'address': '10.0.70.35:30002',
            'listen_addr': '10.0.70.35:30002'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

# your code to run.

aggr = SecureAggregator(charlie, [alice, bob])
spu = sf.SPU(cluster_def=cluster_def)
comp = SPUComparator(spu)
path_dict = {alice: '', bob: '/home/admin/secretflow/provider.csv'}
data = read_csv(filepath=path_dict, aggregator=aggr, comparator=comp)
data.fillna(value=0, inplace=True)
params = {
         # XGBoost parameter tutorial
         # https://xgboost.readthedocs.io/en/latest/parameter.html
         'max_depth': 4, # max depth
         'eta': 0.3, # learning rate
         'objective': 'multi:softmax', # objection function，support "binary:logistic","reg:logistic","multi:softmax","multi:softprob","reg:squarederror"
         'min_child_weight': 1, # The minimum value of weight
         'lambda': 0.1, # L2 regularization term on weights (xgb's lambda)
         'alpha': 0, # L1 regularization term on weights (xgb's alpha)
         'max_bin': 10, # Max num of binning
         'num_class':6, # Only required in multi-class classification
         'gamma': 0, # Same to min_impurity_split,The minimux gain for a split
         'subsample': 1.0, # Subsample rate by rows
         'colsample_by_tree': 1.0, # Feature selection rate by tree
         'colsample_bylevel': 1.0, # Feature selection rate by level
         'eval_metric': 'merror',  # supported eval metric：
                                    # 1. rmse
                                    # 2. rmsle
                                    # 3. mape
                                    # 4. logloss
                                    # 5. error
                                    # 6. error@t
                                    # 7. merror
                                    # 8. mlogloss
                                    # 9. auc
                                    # 10. aucpr
         # Special params in SFXgboost
         # Required
         'hess_key': 'hess', # Required, Mark hess columns, optionally choosing a column name that is not in the data set
         'grad_key': 'grad', # Required，Mark grad columns, optionally choosing a column name that is not in the data set
         'label_key': 'class', # Required，ark label columns, optionally choosing a column name that is not in the data set
}

bst = SFXgboost(server=charlie, clients=[alice, bob])
bst.train(data, data, params=params, num_boost_round = 6)

------------------------Charlie--------------------------
from secretflow.data.horizontal import read_csv
from secretflow.security.aggregation import SecureAggregator
from secretflow.security.compare import SPUComparator
from secretflow.utils.simulation.datasets import load_dermatology
from secretflow.ml.boost.homo_boost import SFXgboost
import secretflow as sf
import spu

# In case you have a running secretflow runtime already.
sf.shutdown()

cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.0.70.33:30003',
            'listen_addr': '0.0.0.0:30003'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.0.70.34:30003',
            'listen_addr': '0.0.0.0:30003'
        },
        'charlie': {
            # replace with bob's real address.
            'address': '10.0.70.35:30003',
            'listen_addr': '0.0.0.0:30003'
        },
    },
    'self_party': 'charlie'
}

sf.init(address='10.0.70.35:30001', cluster_config=cluster_config,cross_silo_comm_backend='grpc',enable_waiting_for_other_parties_ready=False)
alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')

cluster_def={
    'nodes': [
        {
            'party': 'alice',
            # Please choose an unused port.
            'address': '10.0.70.33:30002',
            'listen_addr': '10.0.70.33:30002'
        },
        {
            'party': 'bob',
            # Please choose an unused port.
            'address': '10.0.70.34:30002',
            'listen_addr': '10.0.70.34:30002'
        },
        {
            'party': 'charlie',
            # Please choose an unused port.
            'address': '10.0.70.35:30002',
            'listen_addr': '10.0.70.35:30002'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

# your code to run.

aggr = SecureAggregator(charlie, [alice, bob])
spu = sf.SPU(cluster_def=cluster_def)
comp = SPUComparator(spu)
path_dict = {alice: '', bob: ''}
data = read_csv(filepath=path_dict, aggregator=aggr, comparator=comp)
data.fillna(value=0, inplace=True)
params = {
         # XGBoost parameter tutorial
         # https://xgboost.readthedocs.io/en/latest/parameter.html
         'max_depth': 4, # max depth
         'eta': 0.3, # learning rate
         'objective': 'multi:softmax', # objection function，support "binary:logistic","reg:logistic","multi:softmax","multi:softprob","reg:squarederror"
         'min_child_weight': 1, # The minimum value of weight
         'lambda': 0.1, # L2 regularization term on weights (xgb's lambda)
         'alpha': 0, # L1 regularization term on weights (xgb's alpha)
         'max_bin': 10, # Max num of binning
         'num_class':6, # Only required in multi-class classification
         'gamma': 0, # Same to min_impurity_split,The minimux gain for a split
         'subsample': 1.0, # Subsample rate by rows
         'colsample_by_tree': 1.0, # Feature selection rate by tree
         'colsample_bylevel': 1.0, # Feature selection rate by level
         'eval_metric': 'merror',  # supported eval metric：
                                    # 1. rmse
                                    # 2. rmsle
                                    # 3. mape
                                    # 4. logloss
                                    # 5. error
                                    # 6. error@t
                                    # 7. merror
                                    # 8. mlogloss
                                    # 9. auc
                                    # 10. aucpr
         # Special params in SFXgboost
         # Required
         'hess_key': 'hess', # Required, Mark hess columns, optionally choosing a column name that is not in the data set
         'grad_key': 'grad', # Required，Mark grad columns, optionally choosing a column name that is not in the data set
         'label_key': 'class', # Required，ark label columns, optionally choosing a column name that is not in the data set
}

bst = SFXgboost(server=charlie, clients=[alice, bob])
bst.train(data, data, params=params, num_boost_round = 6)
```

**Comment by Chrisdehe** [comment]
hey @Klein920116 
请问问题是否得到解决呢？如解决是因为什么问题导致的呢？
