### ISSUE TITLE
仿真模式下ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.

### ISSUE THREAD

**Issue by ChangtiWu** [secretflow/secretflow#1354]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow v1.6.1b0

### OS Platform and Distribution

Linux Ubuntu 20.04.5 LTS

### Python version

3.10

### What happend and What you expected to happen.

```shell
我在仿真模式下将我的单机pytorch深度学习代码迁移到secretflow的联邦学习模块中，参考https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.6.1b0/user_guide/federated_learning/how_to_use_gpu_in_fl 配置gpu后，报错：ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.

执行以下代码查看深度学习环境版本：
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.version.cuda)
print(torch.backends.cudnn.version())
结果为：
2.1.2+cu121
True
12.1
8902
```

### Reproduction code to reproduce the issue.

```shell
【代码】

def start_ray_header(head_ip, head_port, device, resources):
    '''start a ray node as a header node
    return 0 means success, otherwise fail'''
    return os.system('ray start --head --node-ip-address=\"{}\" --port=\"{}\" --resources=\'{{\"{}\": {}}}\' --include-dashboard=False --disable-usage-stats'.format(head_ip, head_port, device, resources))

def start_ray_slave(head_ip, head_port, device, resources):
    '''start a ray node as a slave node to connect to the header node
    return 0 means success, otherwise fail'''
    return os.system('ray start --address=\"{}:{}\" --resources=\'{{\"{}\": {}}}\' --disable-usage-stats'.format(head_ip, head_port, device, resources))


'''init'''
'''start a ray cluster consists of ray nodes (header node, slave nodes)'''
if ray_utils.start_ray_header('127.0.0.1', 8080, 'carol', 10) != 0: # carol as the ray header
    print('Error: start a ray header failed!')

if ray_utils.start_ray_slave('127.0.0.1', 8080, 'alice', 10) != 0:
    print('Error: start a ray slave failed!')

if ray_utils.start_ray_slave('127.0.0.1', 8080, 'bob', 10) != 0:
    print('Error: start a ray slave failed!')

'''address='local' means simulation mode in single machine
there are three parties: alice bob carol'''
print('The version of SecretFlow: {}'.format(sf.__version__)) # Check the version of your SecretFlow
sf.shutdown() # In case you have a running secretflow runtime already
sf.init(parties=['alice', 'bob', 'carol'], address='127.0.0.1:8080', log_to_driver=False, num_gpus=2) 

'''create logic devices'''
# create pyu
alice, bob, carol = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol')

'''dataset for training'''

(train_data, train_label), (test_data, test_label) = load_mnist(
    parts={alice: 0.4, bob: 0.6},
    normalized_x=True,
    categorical_y=True,
    is_torch=True,
)

'''config local model training'''
loss_fn = nn.CrossEntropyLoss
optim_fn = optim_wrapper(optim.Adam, lr=1e-2)
model_def = TorchModel(
    model_fn=ConvNet,
    loss_fn=loss_fn,
    optim_fn=optim_fn,
    metrics=[
        metric_wrapper(Accuracy, task="multiclass", num_classes=10, average='micro'),
        metric_wrapper(Precision, task="multiclass", num_classes=10, average='micro'),
    ],
)

'''config fl training strategy'''
aggregator = our_aggregator.SecureAggregator(device=carol, participants=[alice, bob])
# specify params
fl_model = FLModel(
    server=carol,
    device_list=[alice, bob],
    model=model_def,
    aggregator=aggregator,
    num_gpus=1,
    strategy='fed_avg_w',  # fl strategy
    backend="torch",  # backend support ['tensorflow', 'torch']
)

'''fl training'''
history = fl_model.fit(
    train_data,
    train_label,
    validation_data=(test_data, test_label),
    epochs=5,
    batch_size=32,
    aggregate_freq=1,
)

【报错如下】

2024-06-28 17:07:14,665 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 219.228.135.158:8080...
Traceback (most recent call last):
  File "/home/tmp/projects/FedSecMedSeg/test.py", line 36, in <module>
    sf.init(parties=['alice', 'bob', 'carol'], address='127.0.0.1:8080', log_to_driver=False, num_gpus=2) 
  File "/home/tmp/projects/anaconda3/envs/secretflow/lib/python3.10/site-packages/secretflow/device/driver.py", line 513, in init
    ray.init(
  File "/home/tmp/projects/anaconda3/envs/secretflow/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/tmp/projects/anaconda3/envs/secretflow/lib/python3.10/site-packages/ray/_private/worker.py", line 1627, in init
    raise ValueError(
ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.
```

**Comment by zhouaihui** [comment]
`ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.`
报错信心提示不要填写`num_cpus`和`num_cpus`参数。
对应`sf.init(parties=['alice', 'bob', 'carol'], address='127.0.0.1:8080', log_to_driver=False, num_gpus=2)`这行修改一下。

**Comment by ChenLiJie626** [comment]
> `ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.` 报错信息提示不要填写`num_cpus`和`num_cpus`参数。 对应`sf.init(parties=['alice', 'bob', 'carol'], address='127.0.0.1:8080', log_to_driver=False, num_gpus=2)`这行修改一下。

我想要使用我的gpu资源的话，那么应该怎么配置

**Comment by kaixin-haha** [comment]
请参考文档 https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.7.0b0/user_guide/federated_learning/how_to_use_gpu_in_fl#gpu

**Comment by zimu-yuxi** [comment]
> > `ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.` 报错信息提示不要填写`num_cpus`和`num_cpus`参数。 对应`sf.init(parties=['alice', 'bob', 'carol'], address='127.0.0.1:8080', log_to_driver=False, num_gpus=2)`这行修改一下。
> 
> 我想要使用我的gpu资源的话，那么应该怎么配置


可以使用gpu版的secretflow尝试一下，参考[此文档](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.6.1b0/getting_started/installation#gpu-support)
