### ISSUE TITLE
安装Secretflow使用方式 1: 从pypi报错

### ISSUE THREAD

**Issue by MoveLove** [secretflow/secretflow#136]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

secretlow 0.7.7b1

### OS Platform and Distribution

CentOS 7

### Python version

Python 3.8.13 

### What happend and What you expected to happen.

```shell
(base) [root@localhost ~]# conda create -n sf python=3.8
WARNING: A conda environment already exists at '/usr/lib64/anaconda3/envs/sf'
Remove existing environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.14.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /usr/lib64/anaconda3/envs/sf

  added / updated specs:
    - python=3.8


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  ca-certificates    pkgs/main/linux-64::ca-certificates-2022.07.19-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2022.9.14-py38h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  ncurses            pkgs/main/linux-64::ncurses-6.3-h5eee18b_3
  openssl            pkgs/main/linux-64::openssl-1.1.1q-h7f8727e_0
  pip                pkgs/main/linux-64::pip-22.1.2-py38h06a4308_0
  python             pkgs/main/linux-64::python-3.8.13-h12debd9_0
  readline           pkgs/main/linux-64::readline-8.1.2-h7f8727e_1
  setuptools         pkgs/main/linux-64::setuptools-63.4.1-py38h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.39.2-h5082296_0
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7f8727e_1
  zlib               pkgs/main/linux-64::zlib-1.2.12-h5eee18b_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate sf
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) [root@localhost ~]# conda activate sf
(sf) [root@localhost ~]# pip install -U secretflow
Collecting secretflow
  Using cached secretflow-0.7.7b1-cp38-cp38-manylinux2014_x86_64.whl (1.1 MB)
Collecting pandas==1.4.0
  Using cached pandas-1.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting absl-py==1.0.0
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)
Collecting networkx~=2.8
  Using cached networkx-2.8.6-py3-none-any.whl (2.0 MB)
Collecting loguru==0.6.0
  Using cached loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting flax==0.4.1
  Using cached flax-0.4.1-py3-none-any.whl (184 kB)
Collecting matplotlib==3.5.2
  Using cached matplotlib-3.5.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.3 MB)
Collecting validator.py==1.3.0
  Using cached validator.py-1.3.0-py2.py3-none-any.whl (8.2 kB)
Collecting numpy==1.22.3
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting dgl>=0.9.0
  Using cached dgl-0.9.1-cp38-cp38-manylinux1_x86_64.whl (4.9 MB)
Collecting protobuf==3.19.4
  Using cached protobuf-3.19.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting torchvision==0.11.2
  Using cached torchvision-0.11.2-cp38-cp38-manylinux1_x86_64.whl (23.3 MB)
Collecting torchmetrics==0.9.2
  Using cached torchmetrics-0.9.2-py3-none-any.whl (419 kB)
Collecting cloudpickle==2.0.0
  Using cached cloudpickle-2.0.0-py3-none-any.whl (25 kB)
Collecting psutil==5.9.0
  Using cached psutil-5.9.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (283 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting unittest-xml-reporting
  Using cached unittest_xml_reporting-3.2.0-py2.py3-none-any.whl (20 kB)
Collecting coverage
  Using cached coverage-6.4.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (213 kB)
Collecting cachetools==5.2.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting jax==0.3.7
  Using cached jax-0.3.7.tar.gz (944 kB)
  Preparing metadata (setup.py) ... done
Collecting dill==0.3.4
  Using cached dill-0.3.4-py2.py3-none-any.whl (86 kB)
Collecting tqdm==4.62.3
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting scikit-learn==1.0.2
  Using cached scikit_learn-1.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
Collecting spu==0.2.4b1
  Using cached spu-0.2.4b1-cp38-cp38-manylinux_2_17_x86_64.whl (14.7 MB)
Collecting statsmodels==0.13.2
  Using cached statsmodels-0.13.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
Collecting jaxlib==0.3.7
  Using cached jaxlib-0.3.7-cp38-none-manylinux2014_x86_64.whl (68.5 MB)
Collecting tensorflow-datasets==4.5.2
  Using cached tensorflow_datasets-4.5.2-py3-none-any.whl (4.2 MB)
Collecting sf-heu==0.2.0b0
  Using cached sf_heu-0.2.0b0-cp38-abi3-manylinux2014_x86_64.whl (860 kB)
Collecting tensorflow==2.7.1
  Using cached tensorflow-2.7.1-cp38-cp38-manylinux2010_x86_64.whl (495.1 MB)
Collecting secretflow-ray==2.0.0.dev1
  Using cached secretflow_ray-2.0.0.dev1-cp38-cp38-manylinux2014_x86_64.whl (29.5 MB)
Collecting pyarrow
  Using cached pyarrow-9.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.3 MB)
Collecting s3fs==2022.1.0
  Using cached s3fs-2022.1.0-py3-none-any.whl (25 kB)
Collecting torch==1.10.1
SystemError: deallocated bytearray object has exported buffers
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 341, in run
    requirement_set = resolver.resolve(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 291, in __init__
    super().__init__(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 473, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 155, in unpack_url
    file = get_http_url(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 96, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/network/download.py", line 133, in __call__
    resp = _http_get_download(self._session, link)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/network/download.py", line 116, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/network/session.py", line 456, in request
    return super().request(method, url, *args, **kwargs)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/cachecontrol/adapter.py", line 48, in send
    cached_response = self.controller.cached_request(request)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/cachecontrol/controller.py", line 155, in cached_request
    resp = self.serializer.loads(request, cache_data, body_file)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/cachecontrol/serialize.py", line 95, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data, body_file)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/cachecontrol/serialize.py", line 186, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 128, in unpackb
    ret = unpacker._unpack()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 592, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 592, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 546, in _unpack
    typ, n, obj = self._read_header()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 488, in _read_header
    obj = self._read(n)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 407, in _read
    ret = self._buffer[i : i + n]
MemoryError
```

### Reproduction code to reproduce the issue.

```shell
(sf) [root@localhost ~]# pip install -U secretflow
Collecting secretflow
  Using cached secretflow-0.7.7b1-cp38-cp38-manylinux2014_x86_64.whl (1.1 MB)
Collecting pandas==1.4.0
  Using cached pandas-1.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting absl-py==1.0.0
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)
Collecting networkx~=2.8
  Using cached networkx-2.8.6-py3-none-any.whl (2.0 MB)
Collecting loguru==0.6.0
  Using cached loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting flax==0.4.1
  Using cached flax-0.4.1-py3-none-any.whl (184 kB)
Collecting matplotlib==3.5.2
  Using cached matplotlib-3.5.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.3 MB)
Collecting validator.py==1.3.0
  Using cached validator.py-1.3.0-py2.py3-none-any.whl (8.2 kB)
Collecting numpy==1.22.3
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting dgl>=0.9.0
  Using cached dgl-0.9.1-cp38-cp38-manylinux1_x86_64.whl (4.9 MB)
Collecting protobuf==3.19.4
  Using cached protobuf-3.19.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting torchvision==0.11.2
  Using cached torchvision-0.11.2-cp38-cp38-manylinux1_x86_64.whl (23.3 MB)
Collecting torchmetrics==0.9.2
  Using cached torchmetrics-0.9.2-py3-none-any.whl (419 kB)
Collecting cloudpickle==2.0.0
  Using cached cloudpickle-2.0.0-py3-none-any.whl (25 kB)
Collecting psutil==5.9.0
  Using cached psutil-5.9.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (283 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting unittest-xml-reporting
  Using cached unittest_xml_reporting-3.2.0-py2.py3-none-any.whl (20 kB)
Collecting coverage
  Using cached coverage-6.4.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (213 kB)
Collecting cachetools==5.2.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting jax==0.3.7
  Using cached jax-0.3.7.tar.gz (944 kB)
  Preparing metadata (setup.py) ... done
Collecting dill==0.3.4
  Using cached dill-0.3.4-py2.py3-none-any.whl (86 kB)
Collecting tqdm==4.62.3
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting scikit-learn==1.0.2
  Using cached scikit_learn-1.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
Collecting spu==0.2.4b1
  Using cached spu-0.2.4b1-cp38-cp38-manylinux_2_17_x86_64.whl (14.7 MB)
Collecting statsmodels==0.13.2
  Using cached statsmodels-0.13.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
Collecting jaxlib==0.3.7
  Using cached jaxlib-0.3.7-cp38-none-manylinux2014_x86_64.whl (68.5 MB)
Collecting tensorflow-datasets==4.5.2
  Using cached tensorflow_datasets-4.5.2-py3-none-any.whl (4.2 MB)
Collecting sf-heu==0.2.0b0
  Using cached sf_heu-0.2.0b0-cp38-abi3-manylinux2014_x86_64.whl (860 kB)
Collecting tensorflow==2.7.1
  Using cached tensorflow-2.7.1-cp38-cp38-manylinux2010_x86_64.whl (495.1 MB)
Collecting secretflow-ray==2.0.0.dev1
  Using cached secretflow_ray-2.0.0.dev1-cp38-cp38-manylinux2014_x86_64.whl (29.5 MB)
Collecting pyarrow
  Using cached pyarrow-9.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.3 MB)
Collecting s3fs==2022.1.0
  Using cached s3fs-2022.1.0-py3-none-any.whl (25 kB)
Collecting torch==1.10.1
SystemError: deallocated bytearray object has exported buffers
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 341, in run
    requirement_set = resolver.resolve(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 291, in __init__
    super().__init__(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 473, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 155, in unpack_url
    file = get_http_url(
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 96, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/network/download.py", line 133, in __call__
    resp = _http_get_download(self._session, link)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/network/download.py", line 116, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_internal/network/session.py", line 456, in request
    return super().request(method, url, *args, **kwargs)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/cachecontrol/adapter.py", line 48, in send
    cached_response = self.controller.cached_request(request)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/cachecontrol/controller.py", line 155, in cached_request
    resp = self.serializer.loads(request, cache_data, body_file)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/cachecontrol/serialize.py", line 95, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data, body_file)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/cachecontrol/serialize.py", line 186, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 128, in unpackb
    ret = unpacker._unpack()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 592, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 592, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 546, in _unpack
    typ, n, obj = self._read_header()
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 488, in _read_header
    obj = self._read(n)
  File "/usr/lib64/anaconda3/envs/sf/lib/python3.8/site-packages/pip/_vendor/msgpack/fallback.py", line 407, in _read
    ret = self._buffer[i : i + n]
MemoryError
```

**Comment by zhouaihui** [comment]
`MemoryError`看起来是内存不足，可能你需要扩大内存再试试。
