### ISSUE TITLE
安装Secretflow使用方式 1: 从pypi报错

### ISSUE THREAD

**Issue by pythonloveing** [secretflow/secretflow#138]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

secretflow

### OS Platform and Distribution

Linux, Ubuntu 20

### Python version

3.7.10

### What happend and What you expected to happen.

```shell
安装命令：pip install -U secretflow
报错：
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting secretflow
  Downloading secretflow-0.7.7b0.tar.gz (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 920.7 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yvptbv1t/secretflow_ccea9566edbd499ba9e1490f43345bb2/setup.py", line 100, in <module>
          install_requires=read_requirements(),
        File "/tmp/pip-install-yvptbv1t/secretflow_ccea9566edbd499ba9e1490f43345bb2/setup.py", line 17, in read_requirements
          with open('./requirements.txt') as file:
      FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Reproduction code to reproduce the issue.

```shell
pip install -U secretflow
```

**Comment by anakinxc** [comment]
Hi,

我们现在提供的 pip 包只支持 python3.8 喔
你可以试一下用 conda 配置一个 python 3.8 的环境，然后再安装 secretflow

~Best

**Comment by pythonloveing** [comment]
> 
您好：
     非常感谢您的解决方案，目前已经可以正常安装。
祝好~
