### ISSUE TITLE
local模式联邦学习任务跑到一半报错Exception in thread Thread-1(rum fit)

### ISSUE THREAD

**Issue by ChangtiWu** [secretflow/secretflow#1391]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow v1.6.1b0

### OS Platform and Distribution

ubuntu22.04

### Python version

3.10

### What happend and What you expected to happen.

```shell
我在跑一个联邦学习图像分割任务，一共500epoch跑到第30个epoch报错：
Exception in thread Thread-1 (run fit):
Traceback (most recent call last):
File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  self.run()
File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
  self._target(*self._args, **self._kwargs)
File "/root/autodl-tmp/mnist-mlops-learning/backend/main.py", line 43, in run_fit
  model.fit(
File "/root/miniconda3/lib/python3.10/site_packages/secretflow/ml/nn/fl/fl_model.py", line 592, in fit
  global_eval, local_eval = self.evaluate(
File "/root/miniconda3/lib/python3.10/site-packages/secretflow/ml/nn/fl/fl_model,py", line 763, in evaluate
  metric_objs[device.party] = worker.evaluate(evaluate_steps)
File "/root/miniconda3/lib/python3.10/site-packages/secretflow/device/proxy.py", line 52, in wrapper
  res = handle.options(num_returns = _num_returns).remote(*args, **kwargs)
File "/root/miniconda3/lib/python3.10/site-packages/secretflow/distributed/memory_actor.py", line 80, in remote
  return self._mem_call_holder.internal_remote(*args, **kwargs)
File "/root/miniconda3/lib/python3.10/site-packages/secretflow/distributed/memory_function.py", line 48, in internal_remote

==========其他信息===========
secretflow local模式
模型参数量：17M
训练数据是3D图像数据，batchsize = 4
我是在autodl平台上租GPU跑的：
PyTorch  2.1.2
Python  3.10(ubuntu22.04)
Cuda  11.8
GPU  A100-SXM4-80GB(80GB) * 1
CPU  15 vCPU Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz
内存  120GB
硬盘  系统盘：30 GB；数据盘：50GB
网络  同一地区实例共享带宽
```

### Reproduction code to reproduce the issue.

```shell
@app.post("/train")
async def train_api( background_tasks: BackgroundTasks): # data: TrainApiData,
    """Creates a model based on hyperparameters and trains it."""
    sf.shutdown()
    sf.init(
        parties=['alice', 'bob', 'carol', 'dave'],
        address='local',
        log_to_driver=False,
        debug_mode=True,
        num_gpus=1
    )
    alice, bob, carol, dave, device_list, aggregator = create_devices()
    aggregator = SecureAggregator(device=dave, participants=[alice, bob, carol])
    fl_model = FLModel(
            server=dave,
            device_list=device_list,
            model=VNet,
            aggregator=aggregator,
            sparsity=0.0,
            strategy="fed_avg_w",
            backend="torch",
            random_seed=1234,
            num_gpus=2
        )
    #todo 这里设置需要考虑是否需要一个文件存储系统，目前就用本地路径  
    data = {
        alice: 'ml/LITS17/data0',
        bob: 'ml/LITS17/data1',
        carol: 'ml/LITS17/data2'
    }
    data_builder_dict = {
        alice: create_dataset_builderVNet(batch_size=4, random_seed=1234),
        bob: create_dataset_builderVNet(batch_size=4, random_seed=1234),
        carol: create_dataset_builderVNet(batch_size=4, random_seed=1234)
    }

    background_tasks.add_task(
        train_model_task, fl_model, data, data_builder_dict)

    return {"result": "Training task started"}
```

**Comment by aokaokd** [comment]
错误和你的num_gpus相关，改一下你的num_gpus

**Comment by ChangtiWu** [comment]
> 错误和你的num_gpus相关，改一下你的num_gpus

多谢！应该是这个原因，我再试一下。
