### ISSUE TITLE
PSI求交之后使用XGboost进行训练报错

### ISSUE THREAD

**Issue by SabYic** [secretflow/secretflow#1404]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secreflow1.7.0.dev

### OS Platform and Distribution

Ubuntu20.04

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
---------------------------------------------------------------------------
RayTaskError(TypeError)                   Traceback (most recent call last)
Cell In[8], line 2
      1 sgb = Sgb(heu_device)
----> 2 model = sgb.train(params, train_x, train_y)
      4 print("***************************************")
      5 print("training run success.")

File ~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:252, in SGBFactory.train(self, params, dtrain, label, checkpoint_data, dump_function, sample_weight)
    250 self.set_params(params)
    251 # TODO: unify data type before entering this algorithm
--> 252 return self.fit(
    253     dtrain,
    254     label,
    255     checkpoint_data=checkpoint_data,
    256     dump_function=dump_function,
    257     sample_weight=sample_weight,
    258 )

File ~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:211, in SGBFactory.fit(self, dataset, label, data_name, checkpoint_data, dump_function, sample_weight)
    208 metric_ = METRICS.get(self.factory_params.eval_metric, None)
    210 callbacks.append(Checkpointing(dump_function=dump_function))
--> 211 return booster.fit(
    212     dataset,
    213     label,
...
       [21.21      ,  0.34043953],
       ...,
       [19.1       ,  0.89958039],
       [19.66      ,  0.6950883 ],
       [22.57      ,  0.18198684]]), [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [21.9145, 0.4529392731, 22.66, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf], [0, 1, 2, 6, 13, 27, 55, 111, 223, 447, 895, 1791, 3583, 7167, 14335, 28671, 57343, 114687, 229375, 458751, 917503, 1835007, 3670015, 7340031, 14680063, 29360127, 58720255, 117440511, 234881023, 469762047, 939524095, 1879048191], [3, 4, 5, 14, 28, 56, 112, 224, 448, 896, 1792, 3584, 7168, 14336, 28672, 57344, 114688, 229376, 458752, 917504, 1835008, 3670016, 7340032, 14680064, 29360128, 58720256, 117440512, 234881024, 469762048, 939524096, 1879048192, 3758096383, 3758096384]
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
```

### Reproduction code to reproduce the issue.

```shell
导致错误代码如下：
vdf求交
vdf = v_read_csv(
    # use saved pre-processed data & raw alipay data
    {alice: f"{cur_dir}/.data/labeled_data.csv", bob: f"{cur_dir}/.data/unlabeled_data.csv"},
    spu=spu_device,
    keys="idx",
    drop_keys="idx",
    psi_protocl="KKRT_PSI_2PC",  # can use other protocol.
)
参数指定
params = get_classic_lightGBM_params()
params['num_boost_round'] = 5
params['max_leaf'] = 2**5
params['colsample_by_tree']=0.9
模型训练：
sgb = Sgb(heu_device)
model = sgb.train(params, train_x, train_y)
```

**Comment by SabYic** [comment]
求交后部分数据如下：Alice方：
absolute_magnitude,estimated_diameter_max,is_hazardous,idx
19.14,0.8831611957,0,0
18.5,1.1858779086,1,1
26.02,0.0371569432,0,10
22.7,0.1714115092,0,100
23.39,0.1247498347,0,1000
21.89,0.2489086439,1,1001
19.29,0.8242139842,0,1002
19.72,0.6761452148,0,1003
18.88,0.9954970531,0,1004
20.51,0.4699373665,1,1005
21.39,0.3133574171,0,1006
24.1,0.0899580388,0,1007
23.0,0.1492931834,0,1008
17.14,2.2184006242,0,1009
20.53,0.4656289548,1,101
20.28,0.5224442801,0,1010
22.39,0.1977151638,0,1011

**Comment by SabYic** [comment]
Bob方：neo_id,relative_velocity,miss_distance,idx
2162117,71745.4010476829,58143623.31916973,0
2349507,109949.7571484926,55801047.81819944,1
54245816,45125.6120486885,34223883.067873016,10
3313739,95158.4559638764,72935875.75431544,100
3893642,61250.7689770068,53131402.54466438,1000
2612509,73224.7409996755,12920392.227090772,1001
2217837,103007.2510021486,47491221.92707844,1002
2449107,67571.5628968762,36329973.223722,1003
2489900,107347.2260401969,57996634.16674636,1004
3605576,72162.314696533,64497296.571445785,1005
3736681,41113.1952555044,43542933.85875768,1006
3989082,11450.9124063338,28646491.653323688,1007
54110691,26440.3758711693,40766128.36970806,1008
2017182,38755.8242469684,38362846.097971134,1009
3392365,48519.0355801457,39526569.020765595,101
2365449,53092.6502447938,25599425.16557628,1010
2533990,15194.6691593106,24906115.183442112,1011

**Comment by SabYic** [comment]
Alice为持有label方

**Comment by lanyy9527** [comment]
您好，可以提供下报错日志的上下文信息吗？

**Comment by SabYic** [comment]
在执行```
sgb = Sgb(heu_device)
model = sgb.train(params, train_x, train_y)
```报错，全部报错信息如下：
INFO:root:Create proxy actor <class 'secretflow.ml.boost.sgb_v.factory.sgb_actor.SGBActor'> with party alice.
INFO:root:Create proxy actor <class 'secretflow.ml.boost.sgb_v.factory.sgb_actor.SGBActor'> with party bob.
INFO:root:training the first tree with label holder only.
INFO:root:train tree context set up.
INFO:root:begin train tree.
---------------------------------------------------------------------------
RayTaskError(TypeError)                   Traceback (most recent call last)
Cell In[8], [line 2](vscode-notebook-cell:?execution_count=8&line=2)
      [1](vscode-notebook-cell:?execution_count=8&line=1) sgb = Sgb(heu_device)
----> [2](vscode-notebook-cell:?execution_count=8&line=2) model = sgb.train(params, train_x, train_y)
      [4](vscode-notebook-cell:?execution_count=8&line=4) print("***************************************")
      [5](vscode-notebook-cell:?execution_count=8&line=5) print("training run success.")

File ~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:252, in SGBFactory.train(self, params, dtrain, label, checkpoint_data, dump_function, sample_weight)
    [250](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:250) self.set_params(params)
    [251](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:251) # TODO: unify data type before entering this algorithm
--> [252](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:252) return self.fit(
    [253](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:253)     dtrain,
    [254](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:254)     label,
    [255](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:255)     checkpoint_data=checkpoint_data,
    [256](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:256)     dump_function=dump_function,
    [257](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:257)     sample_weight=sample_weight,
    [258](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:258) )

File ~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:211, in SGBFactory.fit(self, dataset, label, data_name, checkpoint_data, dump_function, sample_weight)
    [208](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:208) metric_ = METRICS.get(self.factory_params.eval_metric, None)
    [210](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:210) callbacks.append(Checkpointing(dump_function=dump_function))
--> [211](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:211) return booster.fit(
    [212](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:212)     dataset,
    [213](https://vscode-remote+ssh-002dremote-002b10-002e102-002e33-002e135.vscode-resource.vscode-cdn.net/home/wjsun/secretflow/secretflow/~/secretflow/secretflow/secretflow/ml/boost/sgb_v/factory/factory.py:213)     label,
...
       [21.21      ,  0.34043953],
       ...,
       [19.1       ,  0.89958039],
       [19.66      ,  0.6950883 ],
       [22.57      ,  0.18198684]]), [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [21.9145, 0.4529392731, 22.66, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf], [0, 1, 2, 6, 13, 27, 55, 111, 223, 447, 895, 1791, 3583, 7167, 14335, 28671, 57343, 114687, 229375, 458751, 917503, 1835007, 3670015, 7340031, 14680063, 29360127, 58720255, 117440511, 234881023, 469762047, 939524095, 1879048191], [3, 4, 5, 14, 28, 56, 112, 224, 448, 896, 1792, 3584, 7168, 14336, 28672, 57344, 114688, 229376, 458752, 917504, 1835008, 3670016, 7340032, 14680064, 29360128, 58720256, 117440512, 234881024, 469762048, 939524096, 1879048192, 3758096383, 3758096384]
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?da705987-272d-4f90-befd-c8ce63358154) or open in a [text editor](command:workbench.action.openLargeOutput?da705987-272d-4f90-befd-c8ce63358154). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
2024-08-06 17:53:53,367	ERROR worker.py:409 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_run() (pid=4025696, ip=10.102.33.135)
  File "/home/wjsun/secretflow/secretflow/secretflow/device/device/pyu.py", line 156, in _run
    return fn(*args, **kwargs)
  File "/home/wjsun/secretflow/secretflow/secretflow/ml/boost/sgb_v/core/distributed_tree/distributed_tree.py", line 78, in <lambda>
    s = pyu(lambda split_tree, x: split_tree.predict_leaf_select(x))(
  File "/home/wjsun/secretflow/secretflow/secretflow/ml/boost/sgb_v/core/distributed_tree/split_tree.py", line 56, in predict_leaf_select
    return hnp.tree_predict_with_indices(
TypeError: tree_predict_with_indices(): incompatible function arguments. The following argument types are supported:
    1. (arg0: numpy.ndarray[numpy.float64[m, n], flags.c_contiguous], arg1: List[int], arg2: List[float], arg3: List[int], arg4: List[int]) -> numpy.ndarray[numpy.int8[m, n]]

Invoked with: array([[5.40488670e+07, 1.00015446e+05, 7.31851681e+07],
       [3.15231700e+06, 5.89531114e+04, 5.36051042e+07],
       [5.42285360e+07, 4.27882828e+04, 2.03693290e+07],
       ...,
       [3.44112900e+06, 1.79923011e+04, 4.17481398e+07],
       [2.36306900e+06, 6.98222299e+04, 4.61096275e+07],
       [3.74360700e+06, 6.68623632e+04, 6.82357388e+07]]), [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf], [0, 1, 2, 6, 13, 27, 55, 111, 223, 447, 895, 1791, 3583, 7167, 14335, 28671, 57343, 114687, 229375, 458751, 917503, 1835007, 3670015, 7340031, 14680063, 29360127, 58720255, 117440511, 234881023, 469762047, 939524095, 1879048191], [3, 4, 5, 14, 28, 56, 112, 224, 448, 896, 1792, 3584, 7168, 14336, 28672, 57344, 114688, 229376, 458752, 917504, 1835008, 3670016, 7340032, 14680064, 29360128, 58720256, 117440512, 234881024, 469762048, 939524096, 1879048192, 3758096383, 3758096384]

**Comment by SabYic** [comment]
这是代码上下文：
导致错误代码如下：
```
vdf = v_read_csv(
    # use saved pre-processed data & raw alipay data
    {alice: f"{cur_dir}/.data/labeled_data.csv", bob: f"{cur_dir}/.data/unlabeled_data.csv"},
    spu=spu_device,
    keys="idx",
    drop_keys="idx",
    psi_protocl="KKRT_PSI_2PC",  # can use other protocol.
)
参数指定
params = get_classic_lightGBM_params()
params['num_boost_round'] = 5
params['max_leaf'] = 2**5
params['colsample_by_tree']=0.9
模型训练：
sgb = Sgb(heu_device)
model = sgb.train(params, train_x, train_y)
```

**Comment by lanyy9527** [comment]
检查下 train_x 和 train_y 的数据是否符合预期，或者是否包含缺失值
