### ISSUE TITLE
执行PSI报错

### ISSUE THREAD

**Issue by cucumber32** [secretflow/secretflow#1411]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow v1.8.0b0

### OS Platform and Distribution

centOS7

### Python version

3.10

### What happend and What you expected to happen.

```shell
新手，在跟着文档做隐私求交的时候报错了，求助：
secretflow用的是pad all-in-one里面自带的secretflow-v1.8.0b0-lite版本。
使用的是官方文档的代码https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.8.0b0/tutorial/PSI_On_SPU这里面的，全按顺序照抄的，执行到spu.psi_csv('uid', input_path, output_path, 'alice')就报错
用pad图形化页面创建项目，也是隐私求交报错，用的都是自带的节点和数据
```

### Reproduction code to reproduce the issue.

```shell
>>> spu.psi_csv('uid', input_path, output_path, 'alice')
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.232] [info] [launch.cc:164] LEGACY PSI config: {"psi_type":"KKRT_PSI_2PC","broadcast_result":true,"input_params":{"path":".data/alice.csv","select_fields":["uid"],"precheck":true},"output_params":{"path":".data/alice_psi.csv","need_sort":true},"curve_type":"CURVE_25519","bucket_size":1048576}
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.232] [info] [bucket_psi.cc:400] bucket size set to 1048576
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.233] [info] [bucket_psi.cc:252] Begin sanity check for input file: .data/alice.csv, precheck_switch:true
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.240] [info] [csv_checker.cc:135] Executing duplicated scripts: LC_ALL=C sort --parallel=8 --buffer-size=1G --stable selected-keys.5deb192f-5231-4d5c-8074-79b3823cd5d9 | LC_ALL=C uniq -d > duplicate-keys.5deb192f-5231-4d5c-8074-79b3823cd5d9
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.277] [info] [bucket_psi.cc:265] End sanity check for input file: .data/alice.csv, size=135
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.280] [info] [bucket_psi.cc:427] Run psi protocol=2, self_items_count=135
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.280] [info] [bucket_psi.cc:516] psi protocol=2, rank=0 item_size=135
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.280] [info] [bucket_psi.cc:516] psi protocol=2, rank=1 item_size=120
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.280] [info] [bucket_psi.cc:541] psi protocol=2, bucket_count=1
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.285] [info] [arrow_csv_batch_provider.cc:75] Reach the end of csv file .data/alice.csv.
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.285] [info] [arrow_csv_batch_provider.cc:75] Reach the end of csv file .data/alice.csv.
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.286] [info] [bucket_psi.cc:553] run psi bucket_idx=0, bucket_item_size=135 
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.287] [info] [memory_psi.cc:67] psi protocol=2, rank=0, inputs_size=135
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.287] [info] [memory_psi.cc:67] psi protocol=2, rank=1, inputs_size=120
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37.288] [info] [thread_pool.cc:30] Create a fixed thread pool with size 7
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.233] [info] [bucket_psi.cc:252] Begin sanity check for input file: .data/bob.csv, precheck_switch:true
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.277] [info] [bucket_psi.cc:265] End sanity check for input file: .data/bob.csv, size=120
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.285] [info] [arrow_csv_batch_provider.cc:75] Reach the end of csv file .data/bob.csv.
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.285] [info] [arrow_csv_batch_provider.cc:75] Reach the end of csv file .data/bob.csv.
(SPURuntime(device_id=None, party=alice) pid=501) *** SIGILL received at time=1723203997 on cpu 5 ***
(SPURuntime(device_id=None, party=alice) pid=501) PC: @     0x7f65f0ab17f2  (unknown)  yacl::AvxTranspose128()
(SPURuntime(device_id=None, party=alice) pid=501)     @     0x7f67a3412ce0       1472  (unknown)
(SPURuntime(device_id=None, party=alice) pid=501)     @     0x7f65f0a0b18d       9536  yacl::crypto::IknpOtExtSend()
(SPURuntime(device_id=None, party=alice) pid=501)     @     0x7f65f0a05809        672  psi::kkrt::GetKkrtOtReceiverOptions()
(SPURuntime(device_id=None, party=alice) pid=501)     @     0x7f65f0a1670b         96  std::_Function_handler<>::_M_invoke()
(SPURuntime(device_id=None, party=bob) pid=502)     @     0x7fe19a1d7cf5      11136  yacl::crypto::IknpOtExtRecv()
(SPURuntime(device_id=None, party=bob) pid=502)     @     0x7fe19a1d0b29        672  psi::kkrt::GetKkrtOtSenderOptions()
(SPURuntime(device_id=None, party=alice) pid=501)     @     0x7f65f086c98e         48  std::__future_base::_State_baseV2::_M_do_set()
(SPURuntime(device_id=None, party=alice) pid=501)     @     0x7f67a340fe57  (unknown)  __pthread_once_slow
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37,534 E 501 615] logging.cc:361: *** SIGILL received at time=1723203997 on cpu 5 ***
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37,534 E 501 615] logging.cc:361: PC: @     0x7f65f0ab17f2  (unknown)  yacl::AvxTranspose128()
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37,535 E 501 615] logging.cc:361:     @     0x7f67a3412ce0       1472  (unknown)
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37,535 E 501 615] logging.cc:361:     @     0x7f65f0a0b18d       9536  yacl::crypto::IknpOtExtSend()
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37,535 E 501 615] logging.cc:361:     @     0x7f65f0a05809        672  psi::kkrt::GetKkrtOtReceiverOptions()
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37,536 E 501 615] logging.cc:361:     @     0x7f65f0a1670b         96  std::_Function_handler<>::_M_invoke()
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37,536 E 501 615] logging.cc:361:     @     0x7f65f086c98e         48  std::__future_base::_State_baseV2::_M_do_set()
(SPURuntime(device_id=None, party=alice) pid=501) [2024-08-09 11:46:37,536 E 501 615] logging.cc:361:     @     0x7f67a340fe57  (unknown)  __pthread_once_slow
(SPURuntime(device_id=None, party=alice) pid=501) Fatal Python error: Illegal instruction
(SPURuntime(device_id=None, party=alice) pid=501) 
(SPURuntime(device_id=None, party=alice) pid=501) 
(SPURuntime(device_id=None, party=alice) pid=501) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, ray._raylet, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, jaxlib.cpu_feature_guard, grpc._cython.cygrpc, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pyarrow.lib, pyarrow._hdfsio, pandas._libs.ops, pyarrow._compute, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations
(SPURuntime(device_id=None, party=alice) pid=501) , pandas._libs.window.indexers
(SPURuntime(device_id=None, party=alice) pid=501) , pandas._libs.reshape
(SPURuntime(device_id=None, party=alice) pid=501) , pandas._libs.tslibs.strptime, pandas._libs.groupby
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37,542 E 502 609] logging.cc:361:     @     0x7fe19a1d7cf5      11136  yacl::crypto::IknpOtExtRecv()
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37,542 E 502 609] logging.cc:361:     @     0x7fe19a1d0b29        672  psi::kkrt::GetKkrtOtSenderOptions()
(SPURuntime(device_id=None, party=bob) pid=502) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, ray._raylet, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, jaxlib.cpu_feature_guard
(SPURuntime(device_id=None, party=bob) pid=502) , grpc._cython.cygrpc, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.tslibs.timedeltas
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.tslibs.timestamps
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.properties
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.tslibs.offsets
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.tslibs.vectorized
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.ops_dispatch
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.missing
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.tslib
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.lib
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.hashing, pyarrow.lib, pyarrow._hdfsio, pandas._libs.ops, pyarrow._compute, pandas._libs.arrays
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.index
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.join
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.sparse
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.reduction
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.indexing
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.internals
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.writers
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.window.aggregations
(SPURuntime(device_id=None, party=alice) pid=501) , pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, sklearn.__check_build._check_build, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.interpolate._fitpack, scipy.interpolate._dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.special.cython_special, scipy.stats._stats, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy._lib._uarray._uarray, scipy.stats._ansari_swilk_statistics, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.stats._unuran.unuran_wrapper, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, sklearn.utils._isfinite, sklearn.utils.murmurhash, sklearn.utils._openmp_helpers, sklearn.utils._logistic_sigmoid, sklearn.utils.sparsefuncs_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.preprocessing._target_encoder_fast, pyarrow._json (total: 162)
(SPURuntime(device_id=None, party=bob) pid=502) , pandas._libs.reshape, pandas._libs.tslibs.strptime, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, sklearn.__check_build._check_build, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.interpolate._fitpack, scipy.interpolate._dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.special.cython_special, scipy.stats._stats, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy._lib._uarray._uarray, scipy.stats._ansari_swilk_statistics, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.stats._unuran.unuran_wrapper, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, sklearn.utils._isfinite, sklearn.utils.murmurhash, sklearn.utils._openmp_helpers, sklearn.utils._logistic_sigmoid, sklearn.utils.sparsefuncs_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.preprocessing._target_encoder_fast, pyarrow._json (total: 162)
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff7e3ed6ad8107a387e493ab3001000000 Worker ID: 0100348f81dc812f88063b8b7035f67e3f189f7e864bd73fa267748e Node ID: 20d7e5e8b5f64faf94b623bc06334870647fb59017948f0a9b44097a Worker IP address: 172.17.0.2 Worker port: 33393 Worker PID: 502 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py", line 1854, in psi_csv
    return dispatch(
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/kernels/spu.py", line 321, in psi_csv
    return sfd.get(res)
  File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/primitive.py", line 158, in get
    return ray.get(object_refs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 2626, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: SPURuntime
	actor_id: 7e3ed6ad8107a387e493ab3001000000
	pid: 502
	namespace: ee233dc4-a12e-4bc1-a819-5666b12a07c2
	ip: 172.17.0.2
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
>>> (SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.231] [info] [launch.cc:164] LEGACY PSI config: {"psi_type":"KKRT_PSI_2PC","broadcast_result":true,"input_params":{"path":".data/bob.csv","select_fields":["uid"],"precheck":true},"output_params":{"path":".data/bob_psi.csv","need_sort":true},"curve_type":"CURVE_25519","bucket_size":1048576}
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.231] [info] [bucket_psi.cc:400] bucket size set to 1048576
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.238] [info] [csv_checker.cc:135] Executing duplicated scripts: LC_ALL=C sort --parallel=8 --buffer-size=1G --stable selected-keys.e6111ba0-2820-40e3-aac0-af2f73ff9afc | LC_ALL=C uniq -d > duplicate-keys.e6111ba0-2820-40e3-aac0-af2f73ff9afc
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.278] [info] [bucket_psi.cc:427] Run psi protocol=2, self_items_count=120
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.286] [info] [memory_psi.cc:67] psi protocol=2, rank=1, inputs_size=120 [repeated 5x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.286] [info] [bucket_psi.cc:553] run psi bucket_idx=0, bucket_item_size=120 
(SPURuntime(device_id=None, party=bob) pid=502) [2024-08-09 11:46:37.287] [info] [thread_pool.cc:30] Create a fixed thread pool with size 7
```

**Comment by pchyuan** [comment]
1、上面基于文档的操作是在notebook上验证的吗？
2、在pad上跑流程的时候，如果数据是自己的，有提前验证数据是否有重复问题吗？

**Comment by zimu-yuxi** [comment]
@cucumber32 根据报错信息看是avx指令集问题，可以lscpu ｜ grep Flags看是是否有avx2等指令集

**Comment by cucumber32** [comment]
> 1、上面基于文档的操作是在notebook上验证的吗？ 2、在pad上跑流程的时候，如果数据是自己的，有提前验证数据是否有重复问题吗？

1、不是在notebook上，是直接进了secreflow容器里终端执行的
2、数据确定没有重复，用的系统自带的数据集和自己纯测试的两三行数据都试过，检查过没有重复的

**Comment by cucumber32** [comment]
> @cucumber32 根据报错信息看是avx指令集问题，可以lscpu ｜ grep Flags看是是否有avx2等指令集

查了一下cpu确实不支持avx2指令集，但支持avx。（cpu型号 E5-4603）
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 popcnt aes xsave avx hypervisor lahf_lm dtherm arat pln pts
请问下这种情况是需要更换服务器吗。

**Comment by lanyy9527** [comment]
是的，目前你的cpu型号是多少

**Comment by cucumber32** [comment]
> 是的，目前你的cpu型号是多少

好的谢谢，是 Intel(R) Xeon(R) CPU E5-4603 0 @ 2.00GHz
