### ISSUE TITLE
secretflow文档Component下的Feature Engineering demo运行不了

### ISSUE THREAD

**Issue by zhouhansheng** [secretflow/secretflow#142]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

secretflow0.6.13b1

### OS Platform and Distribution

redhat7

### Python version

3.8.0

### Bazel version

5.1.1

### GCC/Compiler version

12.0

### What happend and What you expected to happen.

```shell
secretflow文档Component下的Feature Engineering demo运行不了。
好像是因为目前下载版本是secretflow 0.6的，更新到secret 0.7应该就能运行特征工程的demo了吧。
目前pip可以安装secretflow 0.7吗
```

### Reproduction code to reproduce the issue.

```shell
>>> from secretflow.utils.simulation.datasets import load_linear
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>                                                                                           
ModuleNotFoundError: No module named 'secretflow.utils.simulation.datasets'                                                     
>>>
```

**Comment by anakinxc** [comment]
pip 可以安装 sf 0.7 的

**Comment by zhouhansheng** [comment]
> 

如何安装最新的sf0.7

**Comment by anakinxc** [comment]
`pip install secretflow==0.7.7b1`应该就可以安装上了

**Comment by zhouhansheng** [comment]
> 
Successfully installed secretflow-0.7.7b1 secretflow-ray-2.0.0.dev1 sf-heu-0.2.0b0 spu-0.2.4b1
已经安装好sf0.7，但是运行特征工程demo所需的datasets.py，好像仍然没有，目录：secretflow/utils/simulation/datasets.py

**Comment by zhouaihui** [comment]
一些建议
1. 确保你运行脚本的当前目录没有叫做secretflow的同名文件夹
2. 如果是用jupyter，则需要重启内核
3. 检查使用的python环境是否正确

**Comment by zhouhansheng** [comment]
> 一些建议
> 
> 1. 确保你运行脚本的当前目录没有叫做secretflow的同名文件夹
> 2. 如果是用jupyter，则需要重启内核
> 3. 检查使用的python环境是否正确

环境应该没有问题，其他demo运行正常；
需要把python第三方库site-packages中的secretflow文件夹先删除，再用pip安装吗

**Comment by zhouaihui** [comment]
`需要把python第三方库site-packages中的secretflow文件夹先删除，再用pip安装吗`不需要。
看起来是你的个例，我们无法复现你的问题。建议再认真检查

**Comment by zhouhansheng** [comment]
> 

我用docker下载了最新的sf0.7，容器中执行上述demo，出现以下问题：
**>>> from secretflow.utils.simulation.datasets import load_linear
>>> vdf = load_linear(parts={alice: (1, 4), bob: (18, 22)})**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/utils/simulation/datasets.py", line 318, in load_linear
    return create_vdf(source=filepath, parts=parts, shuffle=False)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/utils/simulation/data/dataframe.py", line 150, in create_vdf
    return create_df(source=source, parts=parts, axis=1, shuffle=shuffle)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/utils/simulation/data/dataframe.py", line 80, in create_df
    df = pd.read_csv(source, engine="pyarrow")
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1243, in read
    df = self._engine.read()
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/pandas/io/parsers/arrow_parser_wrapper.py", line 149, in read
    table = pyarrow_csv.read_csv(
  File "pyarrow/_csv.pyx", line 1217, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1226, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Empty CSV file

**Comment by zhouaihui** [comment]
你可以用我们的官方[docker镜像](https://hub.docker.com/r/secretflow/secretflow-anolis8/tags)来运行，参考文档[secretflow docker](https://secretflow.readthedocs.io/zh_CN/latest/getting_started/installation.html#option-2-from-docker)

**Comment by zhouhansheng** [comment]
> 你可以用我们的官方[docker镜像](https://hub.docker.com/r/secretflow/secretflow-anolis8/tags)来运行，参考文档[secretflow docker](https://secretflow.readthedocs.io/zh_CN/latest/getting_started/installation.html#option-2-from-docker)

就是按这个下载的，版本选了0.7.7b1

**Comment by usafchn** [comment]
> > 
> 
> 我用docker下载了最新的sf0.7，容器中执行上述demo，出现以下问题：

hi, @zhouhansheng 
看上去是数据集没有下载成功，你先确认一下你的环境中这个文件能下载吗 `https://secretflow-data.oss-accelerate.aliyuncs.com/datasets/linear/linear.csv`

**Comment by zhouhansheng** [comment]
> > > 
> > 
> > 
> > 我用docker下载了最新的sf0.7，容器中执行上述demo，出现以下问题：
> 
> hi, @zhouhansheng 看上去是数据集没有下载成功，你先确认一下你的环境中这个文件能下载吗 `https://secretflow-data.oss-accelerate.aliyuncs.com/datasets/linear/linear.csv`

可以下载，网络是通的，刚刚忘记说，在执行demo时，有如下警告，不知道是否有影响。
>>> import secretflow as sf

2022-09-26 08:35:20.300631: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
>>> 
>>> sf.shutdown()
>>> 
>>> sf.init(['alice', 'bob'])
2022-09-26 08:35:24,282 WARNING services.py:2010 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67088384 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=3.32gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.

**Comment by usafchn** [comment]
@zhouhansheng 
libcudart 和 /dev/shm 的 warning 都没有影响。 dataset 的缓存路径应该是`~/.secretflow/datasets/linear.csv`，你看下这个文件是否是一个空文件，如果是的话把缓存目录`~/.secretflow/datasets` 删掉重新跑一下 demo，第一次运行会触发下载

**Comment by zhouhansheng** [comment]
> @zhouhansheng libcudart 和 /dev/shm 的 warning 都没有影响。 dataset 的缓存路径应该是`~/.secretflow/datasets/linear.csv`，你看下这个文件是否是一个空文件，如果是的话把缓存目录`~/.secretflow/datasets` 删掉重新跑一下 demo，第一次运行会触发下载

问题解决，感谢回复！！！！

**Comment by usafchn** [comment]
@zhouhansheng 感谢对隐语的关注和支持，这个问题已经记录在案，后续我们会优化隐语的 cache 机制。
