### ISSUE TITLE
联邦学习中数据集label必须经过one-hot编码，否则报错

### ISSUE THREAD

**Issue by OkayYang** [secretflow/secretflow#1445]
### Issue Type

Bug

### Source

binary

### Secretflow Version

main分支

### OS Platform and Distribution

Ubuntu 22.04.3 LTS

### Python version

Python 3.10.14

### What happend and What you expected to happen.

```shell
Traceback (most recent call last):
  File "/home/yang/PycharmProjects/secretflow/test.py", line 210, in <module>
    history = fl_model.fit(
  File "/home/yang/PycharmProjects/secretflow/secretflow/ml/nn/fl/fl_model.py", line 536, in fit
    model_params = self._aggregator.average(
  File "/home/yang/PycharmProjects/secretflow/secretflow/security/aggregation/secure_aggregator.py", line 294, in average
    return self._device(_average)(
  File "/home/yang/PycharmProjects/secretflow/secretflow/device/device/pyu.py", line 100, in wrapper
    sfd.remote(self._run)
  File "/home/yang/anaconda3/envs/mysf/lib/python3.10/site-packages/ray/remote_function.py", line 246, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/home/yang/PycharmProjects/secretflow/secretflow/distributed/primitive.py", line 225, in _remote
    args, kwargs = _resolve_args(*args, **kwargs)
  File "/home/yang/PycharmProjects/secretflow/secretflow/distributed/primitive.py", line 215, in _resolve_args
    actual_vals = ray.get(list(refs.values()))
  File "/home/yang/anaconda3/envs/mysf/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/yang/anaconda3/envs/mysf/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/yang/anaconda3/envs/mysf/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::ActorPYUFedAvgW.train_step() (pid=111469, ip=172.26.198.224, actor_id=0a7c588cbace3a3d891be0dd01000000, repr=<abc.ActorPYUFedAvgW object at 0x7fb44033d2a0>)
  File "/home/yang/PycharmProjects/secretflow/secretflow/device/proxy.py", line 77, in wrapper
    return method(*args, **kwargs)
  File "/home/yang/PycharmProjects/secretflow/secretflow/ml/nn/fl/backend/torch/strategy/fed_avg_w.py", line 68, in train_step
    loss = self.model.training_step((x, y), cur_steps + step, sample_weight=s_w)
  File "/home/yang/PycharmProjects/secretflow/secretflow/ml/nn/core/torch/module.py", line 174, in training_step
    _, loss = self.forward_step(batch, batch_idx, dataloader_idx)
  File "/home/yang/PycharmProjects/secretflow/secretflow/ml/nn/core/torch/module.py", line 210, in forward_step
    loss = self.loss(y_pred, y)
  File "/home/yang/anaconda3/envs/mysf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yang/anaconda3/envs/mysf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yang/anaconda3/envs/mysf/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 1179, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/yang/anaconda3/envs/mysf/lib/python3.10/site-packages/torch/nn/functional.py", line 3053, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: expected scalar type Long but found Float
(pid=111482) 2024-08-22 23:16:37.176268: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Train Processing: :   0%|          | 0/375 [00:02<?, ?it/s]
ERROR conda.cli.main_run:execute(49): `conda run python /home/yang/PycharmProjects/secretflow/test.py` failed. (See above for error)
```

### Reproduction code to reproduce the issue.

```shell
(train_data, train_label), (test_data, test_label) = load_mnist(
    parts={alice: 0.2, bob: 0.8},
    normalized_x=True,
    categorical_y=True,
    is_torch=True,
)
#categorical_y: optional, do one hot encoding to y if True. Default to True.

categorical_y默认是进行one-hot编码 你们给的案例又采用nn.CrossEntropyLoss损失函数（label不需要编码的），之所以没报错是因为one-hot编码后的浮点型输入到CrossEntropyLoss不会报错，但是这样做正确吗？既然使用nn.CrossEntropyLoss 我取消编码设置categorical_y=Fasle反而报错说我数据类型不对。
```

**Comment by BrainWH** [comment]
你好，方便的话可以贴一下你改动的完整的代码

**Comment by OkayYang** [comment]
代码地址：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/tutorial/Federated_Learning_with_Pytorch_backend

这里面数据集加载换成,取消label的one-hot编码，还有个问题，这个案例中采用`nn.CrossEntropyLoss`损失函数并且 `categorical_y=True`合理吗？

修改数据集加载`categorical_y=Fasle`
```python
(train_data, train_label), (test_data, test_label) = load_mnist(
    parts={alice: 0.4, bob: 0.6},
    normalized_x=True,
    categorical_y=Fasle,
    is_torch=True,
)
```

**Comment by BrainWH** [comment]
你好，nn.CrossEntropyLoss损失函数不仅可以支持整型，也可以支持one-hot，是合理的

**Comment by BrainWH** [comment]
你好，目前fl_model内部用到了一个batch sampler的函数，这个函数内部有类型转换的操作，会把int类型的y转换成float类型，所以在categorical_y=Fasle的时候会报错

**Comment by OkayYang** [comment]
好的，这里没什么问题了，谢谢！
