### ISSUE TITLE
隐语非平衡(Unbalanced) PSI Benchmark白皮书中，第三步安装secretflow，执行pip install -U secretflow总失败，请问怎么解决？

### ISSUE THREAD

**Issue by wjwJack** [secretflow/secretflow#1467]
### Issue Type

Documentation Feature Request

### Source

binary

### Secretflow Version

secretflow环境安装

### OS Platform and Distribution

CentOS7

### Python version

3.10

### What happend and What you expected to happen.

```shell
参考https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b1/developer/benchmark/ubpsi_benchmark
在改链接中，执行到“三、安装secretflow”中的pip install -U secretflow，总是失败，具体报错如下：


(sf-benchmark) [root@bogon rootroot]# pip install -U secretflow
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/secretflow/
Collecting secretflow
  Using cached secretflow-1.9.0b1-cp310-cp310-manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting clean-text (from secretflow)
  Using cached clean_text-0.6.0-py3-none-any.whl.metadata (6.6 kB)
Collecting click (from secretflow)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting grpcio==1.56.2 (from secretflow)
  Using cached grpcio-1.56.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting jax<=0.4.26,>=0.4.16 (from jax[cpu]<=0.4.26,>=0.4.16->secretflow)
  Using cached jax-0.4.26-py3-none-any.whl.metadata (23 kB)
Collecting jaxlib<=0.4.26,>=0.4.16 (from secretflow)
  Using cached jaxlib-0.4.26-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting kuscia==0.0.3.b0 (from secretflow)
  Using cached kuscia-0.0.3b0-py3-none-any.whl.metadata (204 bytes)
Collecting multiprocess (from secretflow)
  Using cached multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting networkx==2.8.8 (from secretflow)
  Using cached networkx-2.8.8-py3-none-any.whl.metadata (5.1 kB)
Collecting numba==0.57.0 (from secretflow)
  Using cached numba-0.57.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.7 kB)
Collecting numpy (from secretflow)
  Using cached numpy-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting onnx==1.16.0 (from secretflow)
  Using cached onnx-1.16.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (16 kB)
Collecting pandas==1.5.3 (from secretflow)
  Using cached pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting tabulate (from secretflow)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting protobuf<5,>=4 (from secretflow)
  Using cached protobuf-4.25.4-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting pyarrow==14.0.2 (from secretflow)
  Using cached pyarrow-14.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting duckdb==1.0.0 (from secretflow)
  Using cached duckdb-1.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (762 bytes)
Collecting s3fs==2024.2.0 (from secretflow)
  Using cached s3fs-2024.2.0-py3-none-any.whl.metadata (1.6 kB)
Collecting scikit-learn==1.3.2 (from secretflow)
  Using cached scikit_learn-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting ray==2.9.3 (from secretflow)
  Using cached ray-2.9.3-cp310-cp310-manylinux2014_x86_64.whl.metadata (13 kB)
Collecting secretflow-rayfed==0.2.1a2 (from secretflow)
  Using cached secretflow_rayfed-0.2.1a2-py3-none-any.whl.metadata (7.8 kB)
Collecting aiohttp<4,>=3.9.4 (from secretflow)
  Using cached aiohttp-3.10.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.5 kB)
Collecting setuptools<70.0.0,>=65.5.1 (from secretflow)
  Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
Collecting certifi>=2024.7.4 (from secretflow)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting sparse>=0.14.0 (from secretflow)
  Using cached sparse-0.15.4-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting spu==0.9.2b0 (from secretflow)
  Using cached spu-0.9.2b0-cp310-cp310-manylinux2014_x86_64.whl.metadata (4.7 kB)
Collecting sf-heu==0.5.0.b0 (from secretflow)
  Using cached sf_heu-0.5.0b0-cp310-cp310-manylinux2014_x86_64.whl.metadata (2.8 kB)
Collecting secretflow-serving-lib==0.6.0b0 (from secretflow)
  Using cached secretflow_serving_lib-0.6.0b0-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting tf2onnx>=1.13.0 (from secretflow)
  Using cached tf2onnx-1.16.1-py3-none-any.whl.metadata (1.3 kB)
Collecting tqdm (from secretflow)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Collecting validator.py==1.3.0 (from secretflow)
  Using cached validator.py-1.3.0-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting xgboost==1.7.5 (from secretflow)
  Using cached xgboost-1.7.5-py3-none-manylinux2014_x86_64.whl.metadata (1.9 kB)
Requirement already satisfied: wheel>=0.38.1 in /root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages (from secretflow) (0.43.0)
Collecting torch==2.1.2 (from secretflow)
  Using cached torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl.metadata (25 kB)
Collecting torchmetrics==1.3.2 (from secretflow)
  Using cached torchmetrics-1.3.2-py3-none-any.whl.metadata (19 kB)
Collecting torchvision==0.16.2 (from secretflow)
  Using cached torchvision-0.16.2-cp310-cp310-manylinux1_x86_64.whl.metadata (6.6 kB)
Collecting torchaudio==2.1.2 (from secretflow)
  Using cached torchaudio-2.1.2-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting interconnection==0.2.0.dev0 (from secretflow)
  Using cached interconnection-0.2.0.dev0-py3-none-any.whl.metadata (7.7 kB)
Collecting sqlglot==25.5.1 (from secretflow)
  Using cached sqlglot-25.5.1-py3-none-any.whl.metadata (19 kB)
Collecting typing-extensions==4.12.2 (from secretflow)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sdc-apis==0.1.0.dev240320 (from secretflow)
  Using cached sdc_apis-0.1.0.dev240320-py3-none-any.whl.metadata (562 bytes)
Collecting sdc-sdk==0.1.0.dev240320 (from secretflow)
  Using cached sdc_sdk-0.1.0.dev240320-cp310-cp310-manylinux2014_x86_64.whl.metadata (587 bytes)
Collecting tensorflow<2.13,>=2.12 (from secretflow)
  Using cached tensorflow-2.12.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting llvmlite<0.41,>=0.40.0dev0 (from numba==0.57.0->secretflow)
  Using cached llvmlite-0.40.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.7 kB)
Collecting numpy (from secretflow)
  Using cached numpy-1.24.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting python-dateutil>=2.8.1 (from pandas==1.5.3->secretflow)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==1.5.3->secretflow)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting filelock (from ray==2.9.3->secretflow)
  Using cached filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema (from ray==2.9.3->secretflow)
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting msgpack<2.0.0,>=1.0.0 (from ray==2.9.3->secretflow)
  Using cached msgpack-1.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.1 kB)
Collecting packaging (from ray==2.9.3->secretflow)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pyyaml (from ray==2.9.3->secretflow)
  Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting aiosignal (from ray==2.9.3->secretflow)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting frozenlist (from ray==2.9.3->secretflow)
  Using cached frozenlist-1.4.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting requests (from ray==2.9.3->secretflow)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting aiobotocore<3.0.0,>=2.5.4 (from s3fs==2024.2.0->secretflow)
  Using cached aiobotocore-2.14.0-py3-none-any.whl.metadata (23 kB)
Collecting fsspec==2024.2.0 (from s3fs==2024.2.0->secretflow)
  Using cached fsspec-2024.2.0-py3-none-any.whl.metadata (6.8 kB)
Collecting scipy>=1.5.0 (from scikit-learn==1.3.2->secretflow)
  Using cached scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting joblib>=1.1.1 (from scikit-learn==1.3.2->secretflow)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn==1.3.2->secretflow)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Collecting cryptography (from sdc-sdk==0.1.0.dev240320->secretflow)
  Using cached cryptography-43.0.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.4 kB)
Collecting cloudpickle (from secretflow-rayfed==0.2.1a2->secretflow)
  Using cached cloudpickle-3.0.0-py3-none-any.whl.metadata (7.0 kB)
Collecting cachetools>=5.0.0 (from spu==0.9.2b0->secretflow)
  Using cached cachetools-5.5.0-py3-none-any.whl.metadata (5.3 kB)
Collecting termcolor>=2.0.0 (from spu==0.9.2b0->secretflow)
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
Collecting sympy (from torch==2.1.2->secretflow)
  Using cached sympy-1.13.2-py3-none-any.whl.metadata (12 kB)
Collecting jinja2 (from torch==2.1.2->secretflow)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.1.2->secretflow)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.1.2->secretflow)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.1.2->secretflow)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.1.2->secretflow)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.1.2->secretflow)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.1.2->secretflow)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.1.2->secretflow)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.1.2->secretflow)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.1.2->secretflow)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.18.1 (from torch==2.1.2->secretflow)
  Using cached nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.1.2->secretflow)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.1.0 (from torch==2.1.2->secretflow)
  Using cached triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting lightning-utilities>=0.8.0 (from torchmetrics==1.3.2->secretflow)
  Using cached lightning_utilities-0.11.7-py3-none-any.whl.metadata (5.2 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision==0.16.2->secretflow)
  Using cached pillow-10.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.1.2->secretflow)
  Using cached nvidia_nvjitlink_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp<4,>=3.9.4->secretflow)
  Using cached aiohappyeyeballs-2.4.0-py3-none-any.whl.metadata (5.9 kB)
Collecting attrs>=17.3.0 (from aiohttp<4,>=3.9.4->secretflow)
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.9.4->secretflow)
  Using cached multidict-6.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp<4,>=3.9.4->secretflow)
  Using cached yarl-1.9.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (43 kB)
Collecting async-timeout<5.0,>=4.0 (from aiohttp<4,>=3.9.4->secretflow)
  Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting ml-dtypes>=0.2.0 (from jax<=0.4.26,>=0.4.16->jax[cpu]<=0.4.26,>=0.4.16->secretflow)
  Using cached ml_dtypes-0.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting opt-einsum (from jax<=0.4.26,>=0.4.16->jax[cpu]<=0.4.26,>=0.4.16->secretflow)
  Using cached opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting dill>=0.3.8 (from multiprocess->secretflow)
  Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting absl-py>=1.0.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=2.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
Collecting gast<=0.4.0,>=0.2.1 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
Collecting google-pasta>=0.1.1 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting h5py>=2.9.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached h5py-3.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting keras<2.13,>=2.12.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached keras-2.12.0-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting libclang>=13.0.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting numpy (from secretflow)
  Using cached numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting six>=1.12.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting tensorboard<2.13,>=2.12 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached tensorboard-2.12.3-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow-estimator<2.13,>=2.12.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached tensorflow_estimator-2.12.0-py2.py3-none-any.whl.metadata (1.3 kB)
INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while.
Collecting tensorflow<2.13,>=2.12 (from secretflow)
  Using cached tensorflow-2.12.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting numpy (from secretflow)
  Using cached numpy-1.23.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Collecting wrapt<1.15,>=1.11.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached wrapt-1.14.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached tensorflow_io_gcs_filesystem-0.37.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
INFO: pip is looking at multiple versions of tf2onnx to determine which version is compatible with other requirements. This could take a while.
Collecting tf2onnx>=1.13.0 (from secretflow)
  Using cached tf2onnx-1.16.0-py3-none-any.whl.metadata (1.2 kB)
  Using cached tf2onnx-1.15.1-py3-none-any.whl.metadata (1.2 kB)
  Using cached tf2onnx-1.15.0-py3-none-any.whl.metadata (1.2 kB)
Collecting flatbuffers>=2.0 (from tensorflow<2.13,>=2.12->secretflow)
  Using cached flatbuffers-2.0.7-py2.py3-none-any.whl.metadata (872 bytes)
Collecting tf2onnx>=1.13.0 (from secretflow)
  Using cached tf2onnx-1.14.0-py3-none-any.whl.metadata (1.2 kB)
Collecting emoji<2.0.0,>=1.0.0 (from clean-text->secretflow)
  Using cached emoji-1.7.0.tar.gz (175 kB)
  Preparing metadata (setup.py) ... done
Collecting ftfy<7.0,>=6.0 (from clean-text->secretflow)
  Using cached ftfy-6.2.3-py3-none-any.whl.metadata (7.8 kB)
Collecting botocore<1.35.8,>=1.35.0 (from aiobotocore<3.0.0,>=2.5.4->s3fs==2024.2.0->secretflow)
  Using cached botocore-1.35.7-py3-none-any.whl.metadata (5.7 kB)
Collecting aioitertools<1.0.0,>=0.5.1 (from aiobotocore<3.0.0,>=2.5.4->s3fs==2024.2.0->secretflow)
  Using cached aioitertools-0.12.0-py3-none-any.whl.metadata (3.8 kB)
Collecting wcwidth<0.3.0,>=0.2.12 (from ftfy<7.0,>=6.0->clean-text->secretflow)
  Using cached wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
Collecting google-auth<3,>=1.6.3 (from tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached google_auth-2.34.0-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting markdown>=2.6.8 (from tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached Markdown-3.7-py3-none-any.whl.metadata (7.0 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached werkzeug-3.0.4-py3-none-any.whl.metadata (3.7 kB)
Collecting charset-normalizer<4,>=2 (from requests->ray==2.9.3->secretflow)
  Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->ray==2.9.3->secretflow)
  Using cached idna-3.8-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->ray==2.9.3->secretflow)
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting cffi>=1.12 (from cryptography->sdc-sdk==0.1.0.dev240320->secretflow)
  Using cached cffi-1.17.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.1.2->secretflow)
  Using cached MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->ray==2.9.3->secretflow)
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema->ray==2.9.3->secretflow)
  Using cached referencing-0.35.1-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema->ray==2.9.3->secretflow)
  Using cached rpds_py-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.1.2->secretflow)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from botocore<1.35.8,>=1.35.0->aiobotocore<3.0.0,>=2.5.4->s3fs==2024.2.0->secretflow)
  Using cached jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting pycparser (from cffi>=1.12->cryptography->sdc-sdk==0.1.0.dev240320->secretflow)
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached pyasn1_modules-0.4.0-py3-none-any.whl.metadata (3.4 kB)
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting pyasn1<0.7.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached pyasn1-0.6.0-py2.py3-none-any.whl.metadata (8.3 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow<2.13,>=2.12->secretflow)
  Using cached oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/1c/09/174478b1ba42836b473ee2ad099eeb0f7637484652cd0e620db1d976d8ed/secretflow-1.9.0b1-cp310-cp310-manylinux2014_x86_64.whl
Downloading secretflow-1.9.0b1-cp310-cp310-manylinux2014_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.7 MB ? eta -:--:--
ERROR: Exception:
Traceback (most recent call last):
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/http/client.py", line 466, in read
    s = self.fp.read(amt)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 554, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 469, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/network/download.py", line 184, in __call__
    for chunk in chunks:
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 55, in _rich_progress_bar
    for chunk in iterable:
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
(sf-benchmark) [root@bogon rootroot]#
```

### Reproduction code to reproduce the issue.

```shell
pip install -U secretflow
```

**Comment by Chrisdehe** [comment]
@wjwJack 尝试给到指定版本
例如：pip install secretflow==1.9.0b1
如果还是不行可以考虑“-i”选择一些源
