### ISSUE TITLE
非平衡求交，报ConnectionError问题

### ISSUE THREAD

**Issue by wjwJack** [secretflow/secretflow#1488]
### Issue Type

Bug

### Source

binary

### Secretflow Version

使用docker方式按latest方式安装的secretflow

### OS Platform and Distribution

CentOS 7

### Python version

3.10.13   docker方式安装

### What happend and What you expected to happen.

```shell
[ root@localhost ~]# python alice_offline.py
Since the GPL-licensed package unidecode is not installed, using Python's unicodedata package which yields worse result
s.
2024-09-13 02:04:56,845 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 10.2.11.72:3255...
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 1680, in init
_global_node = ray._private.node.Node(
File "/usr/local/lib/python3.10/site-packages/ray/_private/node.py", line 153, in init
self. init gcs client( )
File "/usr/local/lib/python3.10/site-packages/ray/_private/node.py", line 730, in _init_gcs_client
raise RuntimeError(
RuntimeError: Failed to connect to GCS.
During handling of the above exception,another exception occurred:
Traceback (most recent call last):
File "/root/alice_offline.py", line 87, in <module>
app.run(main)
File "/usr/local/lib/python3.10/site-packages/absl/app .py",line 308, in run
run main(main,args)
Fiie "/usr/local/Lib/python3.10/site-packages/absl/app .py",line 254, in _run_main
sys.exit(main(argv))
File "/root/alice offline.py", line 42,in main
sf.init(address='10.2.11 .72:3255'，cluster_config=cluster_config,log_to_driver=True,omp_num_threads=multiprocess.cpu_c
ount())
File "/usr/local/ib/python3.10/site-packages/sec ret flow/device/driver.py", line 557, in init
ray.init(
File "/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook .py", line 103, in wrapper
return func(*args,**kwargs)
File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py",line 1696, in init
raise ConnectionError
ConnectionError
```

### Reproduction code to reproduce the issue.

```shell
使用下方的代码做非平衡求交，对应的data10w和data500w csv数据，已放到root/input目录下，以及secret_key.bin也放到了root目录下。
使用docker创建容器时，使用了host主机模式，同时把脚本中涉及的四个端口也与主机端口映射。

使用非平衡求交的脚本代码如下：
import os
import sys
import time
import logging
import multiprocess
from absl import app
import spu
import secretflow as sf
#import random
# init log
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
cluster_config ={
    'parties': {
        'alice': {
            'address': '10.2.11.72:3255',       #ray proxy端口不可冲突
            'listen_addr': '0.0.0.0:3255'           #本地
        },
        'bob': {
            'address': '10.2.11.76:3256',       #ray proxy端口不可冲突
            'listen_addr': '0.0.0.0:3256'           #本地
        },
    },
    'self_party': 'alice'
}
# SPU settings
cluster_def = {
    'nodes': [
        {'party': 'alice', 'address': '10.2.11.72:12946', 'listen_address': '0.0.0.0:12946'},
        {'party': 'bob',   'address': '10.2.11.76:12947', 'listen_address': '0.0.0.0:12947'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}
link_desc = {
    'recv_timeout_ms': 3600000,
}
def main(_):
    # sf init
    sf.shutdown()
    sf.init(address='10.2.11.72:3255', cluster_config=cluster_config, log_to_driver=True,omp_num_threads=multiprocess.cpu_count())
    # init log
    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')
    offline_input_path = {
        alice: '/root/input/data10.csv', # alice作为小数据一方
        bob: '/root/input/data500.csv', # bob作为大数据一方
    }
    select_keys = {
        alice: ['x1'],
        bob: ['x1'],
    }
    offline_output_path = {
        alice: "/root/output/unbalanced_10w_out.csv",
        bob: "/root/output/unbalanced_500w_out.csv",
    }
    offline_preprocess_path = "/root/preprocess/offline_psi.csv"
    secret_key = "000102030405060708090a0b0c0d0e0ff0e0d0c0b0a090807060504030201000"
    secret_key_path = "/root/secret_key.bin"
    spu = sf.SPU(cluster_def, link_desc)
    # offline离线阶段
    print("=====offline phase====")
    start = time.time()
    with open(secret_key_path, 'wb') as f:
            f.write(bytes.fromhex(secret_key))
    reports = spu.psi_csv(
        key=select_keys,# 用于求交的列
        input_path=offline_input_path,# 用于求交的CSV文件，配置绝对路径
        output_path=offline_output_path,# 输出的CSV文件，配置绝对路径
        receiver='alice',  # 求交结果接收方if `broadcast_result=False`, only receiver can get output file.
        protocol='ECDH_OPRF_UB_PSI_2PC_OFFLINE',   # PSI求交协议，psi protocol，这里是离线阶段
        precheck_input=False,  # 是否在求交之前，检查列 will cost ext time if set True
        sort=False,  # 求交结果是否排序 cost ext time if set True
        broadcast_result=False,  # 是否给各方广播求交结果，will cost ext time if set True
        bucket_size=10000000,# PSI中指定哈希桶大小
        curve_type="CURVE_FOURQ",# ocdh的加密曲线
        preprocess_path=offline_preprocess_path,#在非平衡求交协议中，预处理文件路径
        ecdh_secret_key_path=secret_key_path,# ecdh_opf秘密密钥文件路径
    )
    #print(f"psi reports: {reports}")
    logging.info(f"offline psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")
    sf.shutdown()
if __name__ == '__main__':
    app.run(main)
```

**Comment by Chrisdehe** [comment]
@wjwJack 请注意
你的ray proxy端口和sf.init的端口重复了，也就是3255被ray proxy和sf.init同时使用。
可以看到代码已经备注ray proxy端口不可冲突

**Comment by wjwJack** [comment]
> @wjwJack 请注意 你的ray proxy端口和sf.init的端口重复了，也就是3255被ray proxy和sf.init同时使用。 可以看到代码已经备注ray proxy端口不可冲突

把sf.init用的端口换了3257，再次执行脚本，还是同样的错

**Comment by Chrisdehe** [comment]
看起来是Ray没有启动，先把Ray启动起来，注意端口号不要重复
``ray start --head --node-ip-address="10.2.11.72" --port="3155" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats``
``ray start --head --node-ip-address="10.2.11.76" --port="3155" --resources='{"bob": 16}' --include-dashboard=False --disable-usage-stats``

**Comment by wjwJack** [comment]
> 看起来是Ray没有启动，先把Ray启动起来，注意端口号不要重复 `ray start --head --node-ip-address="10.2.11.72" --port="3155" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats` `ray start --head --node-ip-address="10.2.11.76" --port="3155" --resources='{"bob": 16}' --include-dashboard=False --disable-usage-stats`

好的，谢谢
