### ISSUE TITLE
执行非平衡求交脚本问题

### ISSUE THREAD

**Issue by wjwJack** [secretflow/secretflow#1495]
### Issue Type

Bug

### Source

binary

### Secretflow Version

使用docker方式按latest方式安装的secretflow

### OS Platform and Distribution

麒麟V10

### Python version

3.10.13   docker方式安装

### What happend and What you expected to happen.

```shell
两台服务器在执行脚本前，分别执行了ray。
ray start --head --node-ip-address="10.2.11.72" --port="3256" --resources='{"bob": 16}' --include-dashboard=False --disable-usage-stats
ray start --head --node-ip-address="10.2.11.76" --port="3255" --resources='{"carol": 16}' --include-dashboard=False --disable-usage-stats
两台服务器使用docker方式创建，指定了四个端口创建容器：docker run -it --network=host -p 3255:3255 -p 3256:3256  -p 12946:12946  -p 12947:12947 secretflow_export /bin/bash

72服务器脚本：
import os
import sys
import time
import logging
import multiprocess
from absl import app
import spu
import secretflow as sf
#import random
# init log
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
cluster_config ={
    'parties': {
        'bob': {
            'address': '10.2.11.72:3255',       #端口不可冲突
            'listen_addr': '0.0.0.0:3255'           #本地
        },
        'carol': {
            'address': '10.2.11.76:3256',       #端口不可冲突
            'listen_addr': '0.0.0.0:3256'           #本地
        },
    },
    'self_party': 'bob'
}
# SPU settings
cluster_def = {
    'nodes': [
                
        {'party': 'bob', 'address': '10.2.11.72:12946', 'listen_address': '0.0.0.0:12946'},
        
        {'party': 'carol', 'address': '10.2.11.76:12947', 'listen_address': '0.0.0.0:12947'},

    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}
link_desc = {
    'recv_timeout_ms': 3600000,
}
def main(_):
    # sf init
    # <<< !!! >>> replace <192.168.0.1:9394> to your ray head
    sf.shutdown()
​    sf.init(address='10.2.11.72:3256', cluster_config=cluster_config, log_to_driver=True,omp_num_threads=multiprocess.cpu_count()) 

    # init log
    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
​
    bob = sf.PYU('bob')
    carol = sf.PYU('carol')

    offline_input_path = {
		#bob作为数据量小的一方
        bob: '/root/input_wjw/data10.csv',
		#carol作为数据量大的一方
        carol: '/root/input_wjw/data500.csv',
    }
    select_keys = {
        bob: ['ID'],
        carol: ['ID'],
    }
    spu = sf.SPU(cluster_def, link_desc)
​
    # offline 
    print("=====offline phase====")
    start = time.time()
​
    offline_output_path = {
        bob: "/root/output_wjw_offline/unbalanced_out_bob.csv",
        carol: "/root/output_wjw_offline/unbalanced_out_carol.csv",
    }
​
    offline_preprocess_path = "/root/offline_psi.csv"
    secret_key = "000102030405060708090a0b0c0d0e0ff0e0d0c0b0a090807060504030201000"
    secret_key_path = "/root/secret_key.bin"
    with open(secret_key_path, 'wb') as f:
            f.write(bytes.fromhex(secret_key))
​
    reports = spu.psi_csv(
        key=select_keys,
        input_path=offline_input_path,
        output_path=offline_output_path,
        receiver='carol',  # if `broadcast_result=False`, only receiver can get output file.
        protocol='ECDH_OPRF_UB_PSI_2PC_OFFLINE',        # psi protocol
        precheck_input=False,  # will cost ext time if set True
        sort=False,  # will cost ext time if set True
        broadcast_result=False,  # will cost ext time if set True
        bucket_size=10000000,
        curve_type="CURVE_FOURQ",
        preprocess_path=offline_preprocess_path,
        ecdh_secret_key_path=secret_key_path,
    )
    #print(f"psi reports: {reports}")
    logging.info(f"offline psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")
​
    sf.shutdown()

if __name__ == '__main__':
    app.run(main)

76服务器脚本：
import os
import sys
import time
import logging
import multiprocess
from absl import app
import spu
import secretflow as sf
#import random
# init log
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
cluster_config ={
    'parties': {
        'bob': {
            'address': '10.2.11.72:3255',       #端口不可冲突
            'listen_addr': '0.0.0.0:3255'           #本地
        },
        'carol': {
            'address': '10.2.11.76:3256',       #端口不可冲突
            'listen_addr': '0.0.0.0:3256'           #本地
        },
    },
    'self_party': 'carol'
}
# SPU settings
cluster_def = {
    'nodes': [
                
        {'party': 'bob', 'address': '10.2.11.72:12946', 'listen_address': '0.0.0.0:12946'},
        
        {'party': 'carol', 'address': '10.2.11.76:12947', 'listen_address': '0.0.0.0:12947'},

    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}
link_desc = {
    'recv_timeout_ms': 3600000,
}
def main(_):
    # sf init
    # <<< !!! >>> replace <192.168.0.1:9394> to your ray head
    sf.shutdown()
​    sf.init(address='10.2.11.76:3255', cluster_config=cluster_config, log_to_driver=True,omp_num_threads=multiprocess.cpu_count()) 

    # init log
    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
​
    bob = sf.PYU('bob')
    carol = sf.PYU('carol')

    offline_input_path = {
        #bob作为数据量小的一方
        bob: '/root/input_wjw/data10.csv',
        #carol作为数据量大的一方
        carol: '/root/input_wjw/data500.csv',
    }
    select_keys = {
        bob: ['ID'],
        carol: ['ID'],
    }
    spu = sf.SPU(cluster_def, link_desc)
​
    # offline 
    print("=====offline phase====")
    start = time.time()
​
    offline_output_path = {
        bob: "/root/output_wjw_offline/unbalanced_out_bob.csv",
        carol: "/root/output_wjw_offline/unbalanced_out_carol.csv",
    }
​
    offline_preprocess_path = "/root/offline_psi.csv"
    secret_key = "000102030405060708090a0b0c0d0e0ff0e0d0c0b0a090807060504030201000"
    secret_key_path = "/root/secret_key.bin"
    with open(secret_key_path, 'wb') as f:
            f.write(bytes.fromhex(secret_key))
​
    reports = spu.psi_csv(
        key=select_keys,
        input_path=offline_input_path,
        output_path=offline_output_path,
        receiver='carol',  # if `broadcast_result=False`, only receiver can get output file.
        protocol='ECDH_OPRF_UB_PSI_2PC_OFFLINE',        # psi protocol
        precheck_input=False,  # will cost ext time if set True
        sort=False,  # will cost ext time if set True
        broadcast_result=False,  # will cost ext time if set True
        bucket_size=10000000,
        curve_type="CURVE_FOURQ",
        preprocess_path=offline_preprocess_path,
        ecdh_secret_key_path=secret_key_path,
    )
    #print(f"psi reports: {reports}")
    logging.info(f"offline psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")
​
    sf.shutdown()

if __name__ == '__main__':
    app.run(main)

问题：
1，根据日志，我自己猜测可能是端口问题，但试了开通的四个端口中的几个，但还是报错。
2，根据我使用两台服务器的情况，脚本中是否有可优化的代码，如有，是否可以注释或删除不用的代码？

说明：input数据为10万和500万条数据。
```

### Reproduction code to reproduce the issue.

```shell
72服务器日志：
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:32.103558003+00:00", grpc_status:4}"
(SenderProxyActor pid=2069) >
2024-09-18 03:06:32.167 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 361 attemp, up to 3600 attemps.
(SenderProxyActor pid=2069) 2024-09-18 03:06:35.107 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=2069)     details = "Deadline Exceeded"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:35.106591672+00:00", grpc_status:4}"
(SenderProxyActor pid=2069) >
2024-09-18 03:06:35.171 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 362 attemp, up to 3600 attemps.
2024-09-18 03:06:38.173 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 363 attemp, up to 3600 attemps.
(SenderProxyActor pid=2069) 2024-09-18 03:06:38.110 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=2069)     details = "Deadline Exceeded"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:38.109567669+00:00", grpc_status:4}"
(SenderProxyActor pid=2069) >
(SenderProxyActor pid=2069) 2024-09-18 03:06:41.113 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=2069)     details = "Deadline Exceeded"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:41.112590637+00:00", grpc_status:4}"
(SenderProxyActor pid=2069) >
2024-09-18 03:06:41.176 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 364 attemp, up to 3600 attemps.
(SenderProxyActor pid=2069) 2024-09-18 03:06:44.117 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=2069)     details = "Deadline Exceeded"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:44.116569255+00:00", grpc_status:4}"
2024-09-18 03:06:44.181 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 365 attemp, up to 3600 attemps.
(SenderProxyActor pid=2069) >
2024-09-18 03:06:47.187 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 366 attemp, up to 3600 attemps.
(SenderProxyActor pid=2069) 2024-09-18 03:06:47.121 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=2069)     details = "Deadline Exceeded"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:47.120567663+00:00", grpc_status:4}"
(SenderProxyActor pid=2069) >
(SenderProxyActor pid=2069) 2024-09-18 03:06:50.124 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=2069)     details = "Deadline Exceeded"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:50.123570446+00:00", grpc_status:4}"
(SenderProxyActor pid=2069) >
2024-09-18 03:06:50.190 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 367 attemp, up to 3600 attemps.
2024-09-18 03:06:53.193 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 368 attemp, up to 3600 attemps.
(SenderProxyActor pid=2069) 2024-09-18 03:06:53.127 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=2069)     details = "Deadline Exceeded"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:53.126565371+00:00", grpc_status:4}"
(SenderProxyActor pid=2069) >
(SenderProxyActor pid=2069) 2024-09-18 03:06:56.131 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=2069)     details = "Deadline Exceeded"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:56.130564012+00:00", grpc_status:4}"
(SenderProxyActor pid=2069) >
2024-09-18 03:06:56.197 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 369 attemp, up to 3600 attemps.
(SenderProxyActor pid=2069) 2024-09-18 03:06:58.240 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.UNAVAILABLE
(SenderProxyActor pid=2069)     details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.2.11.76:3256: Failed to connect to remote host: No route to host"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:10.2.11.76:3256: Failed to connect to remote host: No route to host {grpc_status:14, created_time:"2024-09-18T03:06:58.239339987+00:00"}"
(SenderProxyActor pid=2069) >
(SenderProxyActor pid=2069) 2024-09-18 03:06:59.135 ERROR barriers.py:171 [bob] -- [Anonymous_job] Failed to send data to seq_id ping of carol from ping, error: <AioRpcError of RPC that terminated with:
(SenderProxyActor pid=2069)     status = StatusCode.DEADLINE_EXCEEDED
(SenderProxyActor pid=2069)     details = "Deadline Exceeded"
(SenderProxyActor pid=2069)     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-18T03:06:59.134567807+00:00", grpc_status:4}"
(SenderProxyActor pid=2069) >
2024-09-18 03:06:59.201 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 370 attemp, up to 3600 attemps.



76服务器日志：
[root@localhost ~]# python carol_offline_wjw.py 
Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.
2024-09-18 02:56:11,981 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 10.2.11.76:3255...
2024-09-18 02:56:11,995 INFO worker.py:1724 -- Connected to Ray cluster.
2024-09-18 02:56:12.031 INFO api.py:233 [carol] -- [Anonymous_job] Started rayfed with {'CLUSTER_ADDRESSES': {'bob': '10.2.11.72:3255', 'carol': '0.0.0.0:3256'}, 'CURRENT_PARTY_NAME': 'carol', 'TLS_CONFIG': {}}
Traceback (most recent call last):
  File "/root/carol_offline_wjw.py", line 102, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/root/carol_offline_wjw.py", line 46, in main
    sf.init(address='10.2.11.76:3255', cluster_config=cluster_config, log_to_driver=True,omp_num_threads=multiprocess.cpu_count()) 
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/driver.py", line 589, in init
    fed.init(
  File "/usr/local/lib/python3.10/site-packages/fed/api.py", line 267, in init
    _start_receiver_proxy(
  File "/usr/local/lib/python3.10/site-packages/fed/proxy/barriers.py", line 283, in _start_receiver_proxy
    assert server_state[0], server_state[1]
AssertionError: Grpc server failed to listen to port: 3256 Try another port by setting `listen_addr` into `cluster` config when calling `fed.init`. Grpc error msg: Failed to bind to address [::]:3256; set GRPC_VERBOSITY=debug environment variable to see detailed error message.
(ReceiverProxyActor pid=2283) 2024-09-18 02:56:13.796 INFO grpc_proxy.py:359 [carol] -- [Anonymous_job] ReceiverProxy binding port 3256, options: (('grpc.enable_retries', 1), ('grpc.so_reuseport', 0), ('grpc.max_send_message_length', 524288000), ('grpc.max_receive_message_length', 524288000), ('grpc.service_config', '{"methodConfig": [{"name": [{"service": "GrpcService"}], "retryPolicy": {"maxAttempts": 5, "initialBackoff": "5s", "maxBackoff": "30s", "backoffMultiplier": 2, "retryableStatusCodes": ["UNAVAILABLE"]}}]}'))...
(ReceiverProxyActor pid=2283) E0918 02:56:13.801573140    2314 chttp2_server.cc:1060]                UNKNOWN:No address added out of total 1 resolved for '[::]:3256' {created_time:"2024-09-18T02:56:13.80144475+00:00", children:[UNKNOWN:Failed to add any wildcard listeners {created_time:"2024-09-18T02:56:13.80142786+00:00", children:[UNKNOWN:Unable to configure socket {fd:50, created_time:"2024-09-18T02:56:13.80137863+00:00", children:[UNKNOWN:Address already in use {syscall:"bind", os_error:"Address already in use", errno:98, created_time:"2024-09-18T02:56:13.80134625+00:00"}]}, UNKNOWN:Unable to configure socket {created_time:"2024-09-18T02:56:13.80142129+00:00", fd:50, children:[UNKNOWN:Address already in use {syscall:"bind", os_error:"Address already in use", errno:98, created_time:"2024-09-18T02:56:13.80141564+00:00"}]}]}]}
[root@localhost ~]#
```

**Comment by Chrisdehe** [comment]
``AssertionError: Grpc server failed to listen to port: 3256 Try another port by setting `listen_addr` into `cluster` config when calling `fed.init`. Grpc error msg: Failed to bind to address [::]:3256; set GRPC_VERBOSITY=debug environment variable to see detailed error message.``
报错是监听的端口号重复，辛苦将Ray启动的端口号换两个与目前RayFed不重复且未被占用的

例如之前的bob是3155，carol是3156.

**Comment by wjwJack** [comment]
> `` AssertionError: Grpc server failed to listen to port: 3256 Try another port by setting `listen_addr` into `cluster` config when calling `fed.init`. Grpc error msg: Failed to bind to address [::]:3256; set GRPC_VERBOSITY=debug environment variable to see detailed error message. `` 报错是监听的端口号重复，辛苦将Ray启动的端口号换两个与目前RayFed不重复且未被占用的
> 
> 例如之前的bob是3155，carol是3156.

好的，我重新建docker，然后多预留几个端口出来，再试试。

**Comment by wjwJack** [comment]
![图片](https://github.com/user-attachments/assets/b8626fc8-fd9a-4799-a2c7-7eef14315c0a)
![图片](https://github.com/user-attachments/assets/659549cb-887b-470e-9bb3-348ea09f713f)

重建了镜像、容器以及设置了不同的端口，上面两张图是不是说明在求交中了？

**Comment by wjwJack** [comment]
![72](https://github.com/user-attachments/assets/3f242cb6-b858-4afc-857e-eb54e3d78a3c)
![76](https://github.com/user-attachments/assets/83e41af4-3046-4ae8-b09a-d3ea2c073e5f)

重新使用docker部署了镜像和容器，以及设置了多个预留端口，上面两个截图中，是不是正在隐私求交中了？

**Comment by zimu-yuxi** [comment]
@wjwJack 可以把上方的报错信息贴出来吗？

**Comment by wjwJack** [comment]
> @wjwJack 可以把上方的报错信息贴出来吗？

哪一个？

**Comment by Chrisdehe** [comment]
对 这两个机器的运行日志通过文字形式贴出来，现在看不完整也不清晰

**Comment by wjwJack** [comment]
> 对 这两个机器的运行日志通过文字形式贴出来，现在看不完整也不清晰 目前运行结束了吗，结束后可以贴一下

[72.txt](https://github.com/user-attachments/files/17040541/72.txt)
[76.txt](https://github.com/user-attachments/files/17040542/76.txt)
日志还在跳，由于日志打印一直跳，已尽可能多的复制日志内容了

**Comment by Chrisdehe** [comment]
``(SenderProxyActor pid=625)      details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.2.11.76:3256: Failed to connect to remote host: No route to host"``
``2024-09-18 07:49:32.473 INFO barriers.py:520 [bob] -- [Anonymous_job] Try ping ['carol'] at 1160 attemp, up to 3600 attemps.``

日志并不是在执行任务，而是在rayfed中也就是3255，3256端口未能连接到，一直在重试连接中

**Comment by wjwJack** [comment]
背景：我把两个脚本放在一台服务器上执行了，修改了脚本中的ip，目前报FedRemoteError问题，不知道是不是数据的问题，还请老师帮忙解决。 
为方便老师查看 @Chrisdehe ，我整理了个文档，如下
[FedRemoteError问题.docx](https://github.com/user-attachments/files/17052779/FedRemoteError.docx)

**Comment by wjwJack** [comment]
> 背景：我把两个脚本放在一台服务器上执行了，修改了脚本中的ip，目前报FedRemoteError问题，不知道是不是数据的问题，还请老师帮忙解决。 为方便老师查看 @Chrisdehe ，我整理了个文档，如下 [FedRemoteError问题.docx](https://github.com/user-attachments/files/17052779/FedRemoteError.docx)

@zimu-yuxi @BrainWH 辛苦两位老师，帮忙解答下

**Comment by zimu-yuxi** [comment]
@wjwJack 你的数据里没有ID这一列，确认下你的求交键是否有问题。
在你给的代码中看到
select_keys = {
        bob: ['ID'],
        carol: ['ID'],
    }，但你的数据中不存在ID

**Comment by wjwJack** [comment]
> @wjwJack 你的数据里没有ID这一列，确认下你的求交键是否有问题。 在你给的代码中看到 select_keys = { bob: ['ID'], carol: ['ID'], }，但你的数据中不存在ID

好的，谢谢
