### ISSUE TITLE
打包隐语镜像，执行翻译脚本报错：translators.server.TranslatorError

### ISSUE THREAD

**Issue by magic-hya** [secretflow/secretflow#1521]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretpad all in one 1.9.0b2

### OS Platform and Distribution

CentOS Linux 7

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
脚本执行环境根据release-ci.DockerFile(https://github.com/secretflow/devtools/blob/main/dockerfiles/release-ci.DockerFile)制作的镜像

执行步骤参考：https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.9.0b2/more_tutorials/new_components

执行脚本env PYTHONPATH=$PYTHONPATH:$PWD/.. python update_meta.py时报错
```

### Reproduction code to reproduce the issue.

```shell
(base) [root@phy-10-1-252-122 docker]# env PYTHONPATH=$PYTHONPATH:$PWD/.. python update_meta.py
Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.
INFO:root:1. Update secretflow comp list.
INFO:root:2. Update translation.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 296, in _wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 117, in _wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 288, in _wrapper
    return func(*args, **{**kwargs, **{'query_text': query_text}})
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 738, in baidu_api
    return data if is_detail_result else '\n'.join([item['dst'] for item in data['data']])
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/secretflow/docker/update_meta.py", line 68, in <module>
    trans = translate(gettext(COMP_LIST, archieve), args.translator)
  File "/data/secretflow/docker/update_meta.py", line 45, in translate
    else ts.translate_text(k, to_language=LANG, translator=translator)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 5662, in translate_text
    return self.translators_dict[translator](query_text=query_text, from_language=from_language, to_language=to_language, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 301, in _wrapper
    raise TranslatorError(f'{raise_tips1} {raise_tips2}')
translators.server.TranslatorError: The function baidu() has been not certified yet. Please read for details: Status of Translator on this webpage(https://github.com/UlionTse/translators#supported-translation-services).
```
```

**Comment by wangzul** [comment]
手动安装一下pip install unidecode后重新尝试一下看看

**Comment by magic-hya** [comment]
安装后问题依然存在，报错还是跟上面一致

**Comment by magic-hya** [comment]
使用alibaba或者默认，执行测试代码不会报错
```
(base) [root@phy-10-1-252-122 docker]# python
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import translators as ts
>>> q_text = '季姬寂，集鸡，鸡即棘鸡。棘鸡饥叽，季姬及箕稷济鸡。'
>>> print(ts.translate_text(q_text))
Ji Ji lonely, set chickens, chickens are thorny chickens. The thorny chicken is hungry, Ji Ji and the Ji Ji chicken.
>>> print(ts.translate_text(q_text, translator='baidu'))
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 296, in _wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 117, in _wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 288, in _wrapper
    return func(*args, **{**kwargs, **{'query_text': query_text}})
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 738, in baidu_api
    return data if is_detail_result else '\n'.join([item['dst'] for item in data['data']])
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 5662, in translate_text
    return self.translators_dict[translator](query_text=query_text, from_language=from_language, to_language=to_language, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 301, in _wrapper
    raise TranslatorError(f'{raise_tips1} {raise_tips2}')
translators.server.TranslatorError: The function baidu() has been not certified yet. Please read for details: Status of Translator on this webpage(https://github.com/UlionTse/translators#supported-translation-services).
>>> print(ts.translate_text(q_text, translator='alibaba'))
Ji Ji Ji, set chicken, chicken is spined chicken. The spiny chicken is hungry, Ji Ji and Ji Ji Ji Ji Ji chicken.
```

**Comment by magic-hya** [comment]
将脚本update_meta.py中的baidu改成alibaba将会报如下错误：
最后进行翻译的key是user
```
...
input_data
Input table.
features
perform statistics on these columns
report
Output table statistics report.
user
Traceback (most recent call last):
  File "/data/secretflow/docker/update_meta.py", line 69, in <module>
    trans = translate(gettext(COMP_LIST, archieve), args.translator)
  File "/data/secretflow/docker/update_meta.py", line 46, in translate
    else ts.translate_text(k, to_language=LANG, translator=translator)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 5662, in translate_text
    return self.translators_dict[translator](query_text=query_text, from_language=from_language, to_language=to_language, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 117, in _wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 288, in _wrapper
    return func(*args, **{**kwargs, **{'query_text': query_text}})
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 1647, in alibaba_api
    from_language, to_language = self.check_language(from_language, to_language, self.language_map, self.output_zh)
  File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 200, in check_language
    raise TranslatorError(f'from_language[{from_language}] and to_language[{to_language}] should not be same.')
translators.server.TranslatorError: from_language[zh] and to_language[zh] should not be same.
```

**Comment by wangzul** [comment]
手动安装一下pip install unidecode后重新尝试一下看看

> 将脚本update_meta.py中的baidu改成alibaba将会报如下错误： 最后进行翻译的key是user
> 
> ```
> ...
> input_data
> Input table.
> features
> perform statistics on these columns
> report
> Output table statistics report.
> user
> Traceback (most recent call last):
>   File "/data/secretflow/docker/update_meta.py", line 69, in <module>
>     trans = translate(gettext(COMP_LIST, archieve), args.translator)
>   File "/data/secretflow/docker/update_meta.py", line 46, in translate
>     else ts.translate_text(k, to_language=LANG, translator=translator)
>   File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 5662, in translate_text
>     return self.translators_dict[translator](query_text=query_text, from_language=from_language, to_language=to_language, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 117, in _wrapper
>     return func(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 288, in _wrapper
>     return func(*args, **{**kwargs, **{'query_text': query_text}})
>   File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 1647, in alibaba_api
>     from_language, to_language = self.check_language(from_language, to_language, self.language_map, self.output_zh)
>   File "/root/miniconda3/lib/python3.10/site-packages/translators/server.py", line 200, in check_language
>     raise TranslatorError(f'from_language[{from_language}] and to_language[{to_language}] should not be same.')
> translators.server.TranslatorError: from_language[zh] and to_language[zh] should not be same.
> ```

env PYTHONPATH=$PYTHONPATH:$PWD/.. python  update_meta.py -t alibaba  试试

**Comment by magic-hya** [comment]
依然是上面的错误，代码里面我加了一个打印输出：
```
def translate(input, translator):
    output = {}

    for comp, comp_text in input.items():
        comp_translation = {}

        for k, v in comp_text.items():
            print(k)
            comp_translation[k] = (
                v
                if v != ""
                else ts.translate_text(k, to_language=LANG, translator=translator)
            )

        output[comp] = comp_translation

    return output
```
执行git比对结果如下
```
(base) [root@phy-10-1-252-122 docker]# git diff comp_list.json
diff --git a/docker/comp_list.json b/docker/comp_list.json
index abcd0c0..0406a5c 100644
--- a/docker/comp_list.json
+++ b/docker/comp_list.json
@@ -4409,6 +4409,67 @@
           ]
         }
       ]
+    },
+    {
+      "domain": "user",
+      "name": "ss_compare",
+      "desc": "compare two tables.",
+      "version": "0.0.1",
+      "attrs": [
+        {
+          "name": "tolerance",
+          "desc": "two numbers to be equal if they are within tolerance.",
+          "type": "AT_INT",
+          "atomic": {
+            "isOptional": true,
+            "defaultValue": {
+              "i64": "10"
+            },
+            "lowerBoundEnabled": true,
+            "lowerBound": {},
+            "lowerBoundInclusive": true
+          }
+        }
+      ],
+      "inputs": [
+        {
+          "name": "input_table",
+          "desc": "Input vertical table",
+          "types": [
+            "sf.table.vertical_table"
+          ],
+          "attrs": [
+            {
+              "name": "alice_value",
+              "desc": "Column(s) used to compare.",
+              "colMinCntInclusive": "1",
+              "colMaxCntInclusive": "1"
+            },
+            {
+              "name": "bob_value",
+              "desc": "Column(s) used to compare.",
+              "colMinCntInclusive": "1",
+              "colMaxCntInclusive": "1"
+            }
+          ]
```

**Comment by magic-hya** [comment]
问题解决了，目前应该是baidu不可用，我默认设置为alibaba

**Comment by magic-hya** [comment]
问题解决了，目前应该是baidu不可用，将默认设置为alibaba
    parser.add_argument(
        '-t', '--translator', type=str, required=False, default="alibaba"
    )

翻译的代码增加from_language='en'
ts.translate_text(k, from_language='en', to_language=LANG, translator=translator)

你看这个改动是否合理

**Comment by wangzul** [comment]
> 问题解决了，目前应该是baidu不可用，将默认设置为alibaba parser.add_argument( '-t', '--translator', type=str, required=False, default="alibaba" )
> 
> 翻译的代码增加from_language='en' ts.translate_text(k, from_language='en', to_language=LANG, translator=translator)
> 
> 你看这个改动是否合理

确认可用即可，调用翻译的文件主要就是翻译组件信息的。

**Comment by sabakioukenasai** [comment]
感谢！用同样的方法解决了相同的报错问题！
