### ISSUE TITLE
利用sf库自定义算法报错

### ISSUE THREAD

**Issue by Afive233** [secretflow/secretflow#1555]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow1.9.0b2

### OS Platform and Distribution

ubantu 18.04

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
参考https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/tutorial/Split_Learning_for_bank_marketing#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87   利用sf库添加自定义算子时 会报错找不到自定义的结构INFO:root:SL Train Params: {'self': <secretflow.ml.nn.sl.sl_model.SLModel object at 0x7fd8a60e2740>, 'x': VDataFrame(partitions={PYURuntime(alice): <secretflow.data.core.partition.Partition object at 0x7fd8a65fb5e0>, PYURuntime(bob): <secretflow.data.core.partition.Partition object at 0x7fd8a6389870>}, aligned=True), 'y': VDataFrame(partitions={PYURuntime(alice): <secretflow.data.core.partition.Partition object at 0x7fd8a63893f0>}, aligned=True), 'batch_size': 128, 'epochs': 10, 'verbose': 1, 'callbacks': None, 'validation_data': (VDataFrame(partitions={PYURuntime(alice): <secretflow.data.core.partition.Partition object at 0x7fd8a6389180>, PYURuntime(bob): <secretflow.data.core.partition.Partition object at 0x7fd8a638ad10>}, aligned=True), VDataFrame(partitions={PYURuntime(alice): <secretflow.data.core.partition.Partition object at 0x7fd8a638a8f0>}, aligned=True)), 'shuffle': True, 'sample_weight': None, 'validation_freq': 1, 'dp_spent_step_freq': 10, 'dataset_builder': None, 'audit_log_params': {}, 'early_stopping_batch_step': 0, 'early_stopping_warmup_step': 0, 'random_seed': 25846, 'audit_log_dir': None}
(pid=9050) 2024-10-25 16:54:41.393455: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(ActorPartitionAgent pid=8849) /root/miniconda3/lib/python3.10/site-packages/sklearn/base.py:458: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
(ActorPartitionAgent pid=8849)   warnings.warn(
(ActorPYUSLTFModel pid=9050) Unknown layer: 'residual_block'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
(ActorPYUSLTFModel pid=9050) Traceback (most recent call last):
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 404, in deserialize_objects
(ActorPYUSLTFModel pid=9050)     obj = self._deserialize_object(data, metadata, object_ref)
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 270, in _deserialize_object
(ActorPYUSLTFModel pid=9050)     return self._deserialize_msgpack_data(data, metadata_fields)
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 225, in _deserialize_msgpack_data
(ActorPYUSLTFModel pid=9050)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 215, in _deserialize_pickle5_data
(ActorPYUSLTFModel pid=9050)     obj = pickle.loads(in_band)
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 48, in deserialize_model_from_bytecode
(ActorPYUSLTFModel pid=9050)     raise e
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 46, in deserialize_model_from_bytecode
(ActorPYUSLTFModel pid=9050)     model = saving_lib.load_model(filepath, safe_mode=False)
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/saving_lib.py", line 277, in load_model
(ActorPYUSLTFModel pid=9050)     raise e
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/saving_lib.py", line 242, in load_model
(ActorPYUSLTFModel pid=9050)     model = deserialize_keras_object(
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/serialization_lib.py", line 502, in deserialize_keras_object
(ActorPYUSLTFModel pid=9050)     instance = cls.from_config(inner_config)
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/engine/training.py", line 3053, in from_config
(ActorPYUSLTFModel pid=9050)     inputs, outputs, layers = functional.reconstruct_from_config(
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/engine/functional.py", line 1483, in reconstruct_from_config
(ActorPYUSLTFModel pid=9050)     process_layer(layer_data)
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/engine/functional.py", line 1464, in process_layer
(ActorPYUSLTFModel pid=9050)     layer = deserialize_layer(layer_data, custom_objects=custom_objects)
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/layers/serialization.py", line 265, in deserialize
(ActorPYUSLTFModel pid=9050)     return legacy_serialization.deserialize_keras_object(
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/legacy/serialization.py", line 486, in deserialize_keras_object
(ActorPYUSLTFModel pid=9050)     (cls, cls_config) = class_and_config_for_serialized_keras_object(
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/legacy/serialization.py", line 368, in class_and_config_for_serialized_keras_object
(ActorPYUSLTFModel pid=9050)     raise ValueError(
(ActorPYUSLTFModel pid=9050) ValueError: Unknown layer: 'residual_block'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
(ActorPYUSLTFModel pid=9054) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::ActorPYUSLTFModel.__init__() (pid=9054, ip=192.168.227.111, actor_id=4a5d72347491a6d147dab66c01000000, repr=<abc.ActorPYUSLTFModel object at 0x7f868c037d90>)
(ActorPYUSLTFModel pid=9054)   At least one of the input arguments for this task could not be computed:
(ActorPYUSLTFModel pid=9054) ray.exceptions.RaySystemError: System error: Unknown layer: 'residual_block'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
(ActorPYUSLTFModel pid=9054) traceback: Traceback (most recent call last):
Traceback (most recent call last):
  File "/root/secretflow_dsj/secretflow/vfl_resnet_simple_test.py", line 214, in <module>
    history = sl_model.fit(
  File "/root/secretflow_dsj/secretflow/ml/nn/sl/sl_model.py", line 385, in fit
    self.basenet_output_num = {
  File "/root/secretflow_dsj/secretflow/ml/nn/sl/sl_model.py", line 386, in <dictcomp>
    device: reveal(worker.get_basenet_output_num())
  File "/root/secretflow_dsj/secretflow/device/driver.py", line 162, in reveal
    all_object = sfd.get(all_object_refs)
  File "/root/secretflow_dsj/secretflow/distributed/primitive.py", line 158, in get
    return ray.get(object_refs)
  File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 2626, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::ActorPYUSLTFModel.__init__() (pid=9050, ip=192.168.227.111, actor_id=fad19472ad3ee9e291d4d0a201000000, repr=<abc.ActorPYUSLTFModel object at 0x7f3a18f27dc0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: Unknown layer: 'residual_block'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
traceback: Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 48, in deserialize_model_from_bytecode
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 46, in deserialize_model_from_bytecode
    model = saving_lib.load_model(filepath, safe_mode=False)
  File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/saving_lib.py", line 277, in load_model
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/saving_lib.py", line 242, in load_model
    model = deserialize_keras_object(
  File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/serialization_lib.py", line 502, in deserialize_keras_object
    instance = cls.from_config(inner_config)
  File "/root/miniconda3/lib/python3.10/site-packages/keras/engine/training.py", line 3053, in from_config
    inputs, outputs, layers = functional.reconstruct_from_config(
  File "/root/miniconda3/lib/python3.10/site-packages/keras/engine/functional.py", line 1483, in reconstruct_from_config
    process_layer(layer_data)
  File "/root/miniconda3/lib/python3.10/site-packages/keras/engine/functional.py", line 1464, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/root/miniconda3/lib/python3.10/site-packages/keras/layers/serialization.py", line 265, in deserialize
    return legacy_serialization.deserialize_keras_object(
  File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/legacy/serialization.py", line 486, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/legacy/serialization.py", line 368, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown layer: 'residual_block'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
(ActorPYUSLTFModel pid=9050) WARNING:absl:Skipping variable loading for optimizer 'Adam', because it has 9 variables whereas the saved optimizer has 1 variables. 
(pid=9054) 2024-10-25 16:54:41.430614: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(ActorPYUSLTFModel pid=9054) Unknown layer: 'residual_block'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
(ActorPYUSLTFModel pid=9054) Traceback (most recent call last):
(ActorPYUSLTFModel pid=9054)   File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 404, in deserialize_objects
(ActorPYUSLTFModel pid=9054)     obj = self._deserialize_object(data, metadata, object_ref)
(ActorPYUSLTFModel pid=9054)   File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 270, in _deserialize_object
(ActorPYUSLTFModel pid=9054)     return self._deserialize_msgpack_data(data, metadata_fields)
(ActorPYUSLTFModel pid=9054)   File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 225, in _deserialize_msgpack_data
(ActorPYUSLTFModel pid=9054)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(ActorPYUSLTFModel pid=9054)   File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 215, in _deserialize_pickle5_data
(ActorPYUSLTFModel pid=9054)     obj = pickle.loads(in_band)
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 46, in deserialize_model_from_bytecode [repeated 6x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(ActorPYUSLTFModel pid=9050)     raise e [repeated 6x across cluster]
(ActorPYUSLTFModel pid=9050)     model = saving_lib.load_model(filepath, safe_mode=False) [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/saving_lib.py", line 242, in load_model [repeated 6x across cluster]
(ActorPYUSLTFModel pid=9050)     model = deserialize_keras_object( [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/legacy/serialization.py", line 486, in deserialize_keras_object [repeated 6x across cluster]
(ActorPYUSLTFModel pid=9050)     instance = cls.from_config(inner_config) [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/engine/training.py", line 3053, in from_config [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)     inputs, outputs, layers = functional.reconstruct_from_config( [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/engine/functional.py", line 1483, in reconstruct_from_config [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)     process_layer(layer_data) [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/engine/functional.py", line 1464, in process_layer [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)     layer = deserialize_layer(layer_data, custom_objects=custom_objects) [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/layers/serialization.py", line 265, in deserialize [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)     return legacy_serialization.deserialize_keras_object( [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)     (cls, cls_config) = class_and_config_for_serialized_keras_object( [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)   File "/root/miniconda3/lib/python3.10/site-packages/keras/saving/legacy/serialization.py", line 368, in class_and_config_for_serialized_keras_object [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050)     raise ValueError( [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050) ValueError: Unknown layer: 'residual_block'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details. [repeated 3x across cluster]
(ActorPYUSLTFModel pid=9050) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::ActorPYUSLTFModel.__init__() (pid=9050, ip=192.168.227.111, actor_id=fad19472ad3ee9e291d4d0a201000000, repr=<abc.ActorPYUSLTFModel object at 0x7f3a18f27dc0>)
(ActorPYUSLTFModel pid=9050)   At least one of the input arguments for this task could not be computed:
(ActorPYUSLTFModel pid=9050) ray.exceptions.RaySystemError: System error: Unknown layer: 'residual_block'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
(ActorPYUSLTFModel pid=9050) traceback: Traceback (most recent call last):
```

### Reproduction code to reproduce the issue.

```shell
/
```

**Comment by 1139763082** [comment]
麻烦发一下您自定义的算子和注册算子相关的代码。

**Comment by Afive233** [comment]
[vfl_resnet.txt](https://github.com/user-attachments/files/17536699/vfl_resnet.txt)
是想在在本地进行测试

**Comment by Afive233** [comment]
> 麻烦发一下您自定义的算子和注册算子相关的代码。


参考的;https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/tutorial/Split_Learning_for_bank_marketing#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87

**Comment by BrainWH** [comment]
可以参照官网上的示例代码进行修改，比如：base_model和fuse_model的定义方法。https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.9.0b2/tutorial/Split_Learning_for_bank_marketing#%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B
