### ISSUE TITLE
自定义数据，垂直联邦学习评估出现错误

### ISSUE THREAD

**Issue by ParisPig** [secretflow/secretflow#1558]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.9.0b2

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.10.15

### What happend and What you expected to happen.

```shell
The version of SecretFlow: 1.9.0b2
/root/miniconda3/envs/secretflow/lib/python3.10/subprocess.py:1796: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = _posixsubprocess.fork_exec(
2024-10-28 17:34:04,858 INFO worker.py:1724 -- Started a local Ray instance.
(SPURuntime(device_id=None, party=bob) pid=671374) [2024-10-28 17:34:12.957] [info] [launch.cc:164] LEGACY PSI config: {"psi_type":"KKRT_PSI_2PC","broadcast_result":true,"input_params":{"path":"bob_ele.csv","select_fields":["id"],"precheck":true},"output_params":{"path":"bob_ele.csv.psi_output_13167","need_sort":true},"curve_type":"CURVE_25519","bucket_size":1048576}
(SPURuntime(device_id=None, party=bob) pid=671374) [2024-10-28 17:34:12.957] [info] [bucket_psi.cc:400] bucket size set to 1048576
(SPURuntime(device_id=None, party=bob) pid=671374) [2024-10-28 17:34:12.957] [info] [bucket_psi.cc:252] Begin sanity check for input file: bob_ele.csv, precheck_switch:true
(SPURuntime(device_id=None, party=alice) pid=671357) [2024-10-28 17:34:12.957] [info] [bucket_psi.cc:252] Begin sanity check for input file: alice_ele.csv, precheck_switch:true
INFO:root:Create proxy actor <class 'secretflow.device.proxy.ActorPartitionAgent'> with party alice.
(SPURuntime(device_id=None, party=bob) pid=671374) [2024-10-28 17:34:12.975] [info] [csv_checker.cc:135] Executing duplicated scripts: LC_ALL=C sort --parallel=32 --buffer-size=1G --stable selected-keys.804083f5-a3af-4be4-829f-6e8168969153 | LC_ALL=C uniq -d > duplicate-keys.804083f5-a3af-4be4-829f-6e8168969153
(SPURuntime(device_id=None, party=bob) pid=671374) [2024-10-28 17:34:12.980] [info] [bucket_psi.cc:265] End sanity check for input file: bob_ele.csv, size=26472
(SPURuntime(device_id=None, party=bob) pid=671374) [2024-10-28 17:34:12.980] [info] [bucket_psi.cc:327] Skip doing psi, because dataset has been aligned!
(SPURuntime(device_id=None, party=bob) pid=671374) [2024-10-28 17:34:12.980] [info] [bucket_psi.cc:382] Begin post filtering, indices.size=26472, should_sort=true
(SPURuntime(device_id=None, party=bob) pid=671374) [2024-10-28 17:34:12.993] [info] [bucket_psi.cc:390] End post filtering, in=bob_ele.csv, out=bob_ele.csv.psi_output_13167
(SPURuntime(device_id=None, party=alice) pid=671357) [2024-10-28 17:34:12.980] [info] [bucket_psi.cc:265] End sanity check for input file: alice_ele.csv, size=26472
(SPURuntime(device_id=None, party=alice) pid=671357) [2024-10-28 17:34:12.983] [info] [bucket_psi.cc:390] End post filtering, in=alice_ele.csv, out=alice_ele.csv.psi_output_13167
INFO:root:Create proxy actor <class 'secretflow.device.proxy.ActorPartitionAgent'> with party bob.
{'audit_paths': {},
 'base_score': 0.0,
 'batch_encoding_enabled': True,
 'bottom_rate': 0.5,
 'colsample_by_tree': 1.0,
 'enable_early_stop': False,
 'enable_goss': False,
 'enable_monitor': False,
 'enable_packbits': False,
 'enable_quantization': False,
 'eval_metric': 'roc_auc',
 'first_tree_with_label_holder_feature': True,
 'fixed_point_parameter': 20,
 'gamma': 0.0,
 'learning_rate': 0.3,
 'max_depth': 3,
 'max_leaf': 15,
 'num_boost_round': 3,
 'objective': 'logistic',
 'quantization_scale': 10000.0,
 'reg_lambda': 1.0,
 'rowsample_by_tree': 1.0,
 'save_best_model': False,
 'seed': 1212,
 'sketch_eps': 0.1,
 'stopping_rounds': 1,
 'stopping_tolerance': 0.0,
 'top_rate': 0.3,
 'tree_growing_method': 'level',
 'tweedie_variance_power': 1.5,
 'validation_fraction': 0.1}
INFO:root:Create proxy actor <class 'secretflow.device.proxy.ActorSGBActor'> with party alice.
INFO:root:Create proxy actor <class 'secretflow.device.proxy.ActorSGBActor'> with party bob.
INFO:root:training the first tree with label holder only.
INFO:root:train tree context set up.
INFO:root:begin train tree.
INFO:root:epoch 0 time 5.590986441005953s
WARNING:root:no effective dump_function provided.
INFO:root:train tree context set up.
INFO:root:begin train tree.
(HEUSkKeeper(heu_id=135312283577520, party=bob) pid=671227) [2024-10-28 17:34:23.293] [info] [thread_pool.cc:30] Create a fixed thread pool with size 31
(SPURuntime(device_id=None, party=alice) pid=671357) [2024-10-28 17:34:12.957] [info] [launch.cc:164] LEGACY PSI config: {"psi_type":"KKRT_PSI_2PC","broadcast_result":true,"input_params":{"path":"alice_ele.csv","select_fields":["id"],"precheck":true},"output_params":{"path":"alice_ele.csv.psi_output_13167","need_sort":true},"curve_type":"CURVE_25519","bucket_size":1048576}
(SPURuntime(device_id=None, party=alice) pid=671357) [2024-10-28 17:34:12.957] [info] [bucket_psi.cc:400] bucket size set to 1048576
(SPURuntime(device_id=None, party=alice) pid=671357) [2024-10-28 17:34:12.967] [info] [csv_checker.cc:135] Executing duplicated scripts: LC_ALL=C sort --parallel=32 --buffer-size=1G --stable selected-keys.2d7184bf-4476-4a08-bfc3-eb7130c57ae2 | LC_ALL=C uniq -d > duplicate-keys.2d7184bf-4476-4a08-bfc3-eb7130c57ae2
(SPURuntime(device_id=None, party=alice) pid=671357) [2024-10-28 17:34:12.980] [info] [bucket_psi.cc:327] Skip doing psi, because dataset has been aligned!
(SPURuntime(device_id=None, party=alice) pid=671357) [2024-10-28 17:34:12.980] [info] [bucket_psi.cc:382] Begin post filtering, indices.size=26472, should_sort=true
(ActorSGBActor pid=672162) /root/miniconda3/envs/secretflow/lib/python3.10/site-packages/secretflow/ml/boost/sgb_v/core/pure_numpy_ops/grad.py:28: RuntimeWarning: divide by zero encountered in double_scalars
(ActorSGBActor pid=672162)   return min(1.0, scaling_factor / y_sum_abs)
INFO:root:epoch 1 time 3.399646999023389s
WARNING:root:no effective dump_function provided.
INFO:root:train tree context set up.
INFO:root:begin train tree.
INFO:root:epoch 2 time 0.44260325300274417s
WARNING:root:no effective dump_function provided.
(_run pid=669556) INFO:jax._src.xla_bridge:Unable to initialize backend 'cuda':
(_run pid=669556) INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=669556) INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
INFO:jax._src.xla_bridge:Unable to initialize backend 'cuda':
INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
(_run pid=669558) [2024-10-28 17:34:29.172] [info] [thread_pool.cc:30] Create a fixed thread pool with size 31 [repeated 4x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
Traceback (most recent call last):
  File "/root/ele-sf/h-test1.py", line 99, in <module>
    print(f"auc: {roc_auc_score(y, yhat)}")
  File "/root/miniconda3/envs/secretflow/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 604, in roc_auc_score
    y_type = type_of_target(y_true, input_name="y_true")
  File "/root/miniconda3/envs/secretflow/lib/python3.10/site-packages/sklearn/utils/multiclass.py", line 303, in type_of_target
    raise ValueError(
ValueError: Expected array-like (array or non-string sequence), got VDataFrame(partitions={PYURuntime(bob): <secretflow.data.core.partition.Partition object at 0x7b11c4871a50>}, aligned=True)
```

### Reproduction code to reproduce the issue.

```shell
import spu
from sklearn.metrics import roc_auc_score
import secretflow as sf
from secretflow.data import FedNdarray, PartitionWay
from secretflow.device.driver import reveal, wait
from secretflow.ml.boost.sgb_v import (
    Sgb,
    get_classic_XGB_params,
    get_classic_lightGBM_params,
)
from secretflow.ml.boost.sgb_v.model import load_model
import pprint
pp = pprint.PrettyPrinter(depth=4)

# Check the version of your SecretFlow
print('The version of SecretFlow: {}'.format(sf.__version__))

alice_ip = '127.0.0.1'
bob_ip = '127.0.0.1'
ip_party_map = {bob_ip: 'bob', alice_ip: 'alice'}
_system_config = {'lineage_pinning_enabled': False}
sf.shutdown()
# init cluster
sf.init(
    ['alice', 'bob'],
    address='local',
    _system_config=_system_config,
    object_store_memory=5 * 1024 * 1024 * 1024,
)

# SPU settings
cluster_def = {
    'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address': alice_ip + ':12945'},
        {'party': 'bob', 'id': 'local:1', 'address': bob_ip + ':12946'},
        # {'party': 'carol', 'id': 'local:2', 'address': '127.0.0.1:12347'},
    ],
    'runtime_config': {
        # SEMI2K support 2/3 PC, ABY3 only support 3PC, CHEETAH only support 2PC.
        # pls pay attention to size of nodes above. nodes size need match to PC setting.
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}

# HEU settings
heu_config = {
    'sk_keeper': {'party': 'bob'},
    'evaluators': [{'party': 'alice'}],
    'mode': 'PHEU',
    'he_parameters': {
        # ou is a fast encryption schema that is as secure as paillier.
        'schema': 'ou',
        'key_pair': {
            'generate': {
                # bit size should be 2048 to provide sufficient security.
                'bit_size': 2048,
            },
        },
    },
    'encoding': {
        'cleartext_type': 'DT_I32',
        'encoder': "IntegerEncoder",
        'encoder_args': {"scale": 1},
    },
}

alice = sf.PYU('alice')
bob = sf.PYU('bob')
heu = sf.HEU(heu_config, cluster_def['runtime_config']['field'])

#自定义数据
v_alice_path = 'alice_ele.csv'
v_bob_path = 'bob_ele.csv'

from secretflow.data.vertical import read_csv
from secretflow.data.split import train_test_split

path_dict = {
    alice: v_alice_path,  # The path that alice can access
    bob: v_bob_path,  # The path that bob can access
}

spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
vdf = read_csv(path_dict,spu=spu, keys='id', drop_keys="id")

#bob持有标签
y = vdf['29']
x = vdf.drop(columns="29")

params = get_classic_XGB_params()
params['num_boost_round'] = 3
params['max_depth'] = 3
pp.pprint(params)

sgb = Sgb(heu)
model = sgb.train(params, x, y)
yhat = model.predict(x)
yhat = reveal(yhat)

print(f"auc: {roc_auc_score(y, yhat)}")
```

**Comment by zimu-yuxi** [comment]
方便提供下您的数据吗

**Comment by zimu-yuxi** [comment]
方便提供下您的数据吗，我们内部验证下

**Comment by ParisPig** [comment]
如下：
[alice_ele.csv](https://github.com/user-attachments/files/17553314/alice_ele.csv)
[bob_ele.csv](https://github.com/user-attachments/files/17553315/bob_ele.csv)

**Comment by da-niao-dan** [comment]
hello, 请参考单测。 
![image](https://github.com/user-attachments/assets/d620973e-a1df-4a6e-8a55-41aa27c7a8e5)

原因：sklearn 只支持输入为array-like. vdataframe的y 需要先转化为array。

**Comment by ParisPig** [comment]
好的，已解决，谢谢
