### ISSUE TITLE
生产模式下双方跑隐私求交，查询问题

### ISSUE THREAD

**Issue by yaoyizhuo** [secretflow/secretflow#1563]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.10

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.10

### Bazel version

null

### GCC/Compiler version

null

### What happend and What you expected to happen.

```shell
同一个服务器内，启动了两个ray节点，命令如下
alice: ray start --head --node-ip-address="127.0.0.1" --port="9913" --include-dashboard=False --disable-usage-stats
bob: ray start --head --node-ip-address="127.0.0.1" --port="9914" --include-dashboard=False --disable-usage-stats

现在想要通过模拟双方来完成隐匿查询和隐私求交任务,同一台服务器上模拟是否可行？
```

### Reproduction code to reproduce the issue.

```shell
.
```

**Comment by Chrisdehe** [comment]
可以在同一台服务器的两个容器中

**Comment by yaoyizhuo** [comment]
alice: 
`ray start --head --node-ip-address="127.0.0.1" --port="9913" --include-dashboard=False --disable-usage-stats`


bob: 
`ray start --head --node-ip-address="127.0.0.1" --port="9914" --include-dashboard=False --disable-usage-stats
`


## psi_a.py代码如下:
`cluster_config ={
    'parties': {
        'alice': {
            'address': '127.0.0.1:9923'
        },
        'bob': {
            'address': '127.0.0.1:9924'
        }
    },
    'self_party': 'alice'
}

sf.init(address='127.0.0.1:9913', cluster_config=cluster_config)



link_desc = {
    'recv_timeout_ms': 3600000,
}
cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '127.0.0.1:9933'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '127.0.0.1:9934'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

alice = sf.PYU('alice')
bob = sf.PYU('bob')

spu = sf.SPU(cluster_def,link_desc)


input_path = {'alice': '../data/PIR-PSI用户数据A.csv', 'bob': '../data/PSI-用户数据B.csv'}

keys = {
    'alice': ['姓名'],  # Alice 的数据集中的列名
    'bob': ['姓名']     # Bob 的数据集中的列名
}

output_path = {'alice': '../data/psi_result/INNER_A_A.csv', 'bob': '../data/psi_result/INNER_B_A.csv'}
spu.psi(
    keys=keys,
    input_path=input_path,
    output_path=output_path,
    receiver='bob',
    protocol='PROTOCOL_ECDH',
    broadcast_result=False,
    disable_alignment=True,
    advanced_join_type="ADVANCED_JOIN_TYPE_INNER_JOIN" # 交集
)`



## psi_b.py代码如下:
`cluster_config ={
    'parties': {
        'alice': {
            'address': '127.0.0.1:9923',
            'listen_addr': '0.0.0.0:9923'
        },
        'bob': {
            'address': '127.0.0.1:9924',
            'listen_addr': '0.0.0.0:9924'
        }
    },
    'self_party': 'bob'
}

sf.init(address='127.0.0.1:9914', cluster_config=cluster_config)

link_desc = {
    'recv_timeout_ms': 3600000,
}
cluster_def={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '127.0.0.1:9933'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '127.0.0.1:9934'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

alice = sf.PYU('alice')
bob = sf.PYU('bob')
spu = sf.SPU(cluster_def,link_desc)

input_path = {'alice': '../data/PIR-PSI用户数据A.csv', 'bob': '../data/PSI-用户数据B.csv'}

keys = {
    'alice': ['姓名'],  # Alice 的数据集中的列名
    'bob': ['姓名']     # Bob 的数据集中的列名
}

output_path = {'alice': '../data/psi_result/INNER_A_B.csv', 'bob': '../data/psi_result/INNER_B_B.csv'}
spu.psi(
    keys=keys,
    input_path=input_path,
    output_path=output_path,
    receiver='alice',
    protocol='PROTOCOL_ECDH',
    broadcast_result=False,
    disable_alignment=True,
    advanced_join_type="ADVANCED_JOIN_TYPE_INNER_JOIN" # 交集
)`

同时运行两个代码，会有报错，感觉是我写的不太对。。
alice作为查询方,bob作为服务方，双方的代码是一样的吗？
psi_a.py报错如下：
`INFO:root:Try init sf in RAY_PRODUCTION mode
2024-10-31 15:02:09,537 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 10.10.10.223:9913...
2024-10-31 15:02:09,546 INFO worker.py:1724 -- Connected to Ray cluster.
2024-10-31 15:02:09.573 INFO api.py:233 [alice] -- [Anonymous_job] Started rayfed with {'CLUSTER_ADDRESSES': {'alice': '127.0.0.1:9923', 'bob': '127.0.0.1:9924'}, 'CURRENT_PARTY_NAME': 'alice', 'TLS_CONFIG': {}}
2024-10-31 15:02:10.547 INFO barriers.py:284 [alice] -- [Anonymous_job] Succeeded to create receiver proxy actor.
(ReceiverProxyActor pid=1245251) 2024-10-31 15:02:10.542 INFO grpc_proxy.py:359 [alice] -- [Anonymous_job] ReceiverProxy binding port 9923, options: (('grpc.enable_retries', 1), ('grpc.so_reuseport', 0), ('grpc.max_send_message_length', 524288000), ('grpc.max_receive_message_length', 524288000), ('grpc.service_config', '{"methodConfig": [{"name": [{"service": "GrpcService"}], "retryPolicy": {"maxAttempts": 5, "initialBackoff": "5s", "maxBackoff": "30s", "backoffMultiplier": 2, "retryableStatusCodes": ["UNAVAILABLE"]}}]}'))...
(ReceiverProxyActor pid=1245251) 2024-10-31 15:02:10.545 INFO grpc_proxy.py:379 [alice] -- [Anonymous_job] Successfully start Grpc service without credentials.
2024-10-31 15:02:11.458 INFO barriers.py:333 [alice] -- [Anonymous_job] SenderProxyActor has successfully created.
2024-10-31 15:02:11.458 INFO barriers.py:520 [alice] -- [Anonymous_job] Try ping ['bob'] at 0 attemp, up to 3600 attemps.
2024-10-31 15:02:18.711 WARNING cleanup.py:154 [alice] -- [Anonymous_job] Failed to send ObjectRef(151ce0a65cbee563699fc4a69fa001463d6079631400000001000000) to bob, error: ray::SenderProxyActor.send() (pid=1245310, ip=10.10.10.223, actor_id=699fc4a69fa001463d60796314000000, repr=<fed.proxy.barriers.SenderProxyActor object at 0x7f001486b3a0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SPURuntime.psi() (pid=1245366, ip=10.10.10.223, actor_id=09550a0539fade53eea89f8514000000, repr=SPURuntime(device_id=None, party=alice))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/secretflow/device/device/spu.py", line 1388, in psi
    report = spu.psi.psi(config, self.link)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/spu/psi.py", line 118, in psi
    report_str = libpsi.libs.psi(
RuntimeError: what: 
        [external/psi/psi/interface.cc:351] The role of parties must be different.
stacktrace: 
#0 psi::AbstractPsiParty::Init()+0x7f0846f27ee6
#1 psi::ecdh::EcdhPsiSender::Init()+0x7f0846efb8ce
#2 psi::RunPsi()+0x7f0846eeaa9c
#3 psi::BindLibs()::{lambda()#3}::operator()()+0x7f0846ee0205
#4 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f0846ee0483
#5 pybind11::cpp_function::dispatcher()+0x7f0846ec243d
#6 (unknown)+0x53b8c9,upstream_seq_id: 5#0, downstream_seq_id: 7.
2024-10-31 15:02:18.711 INFO cleanup.py:161 [alice] -- [Anonymous_job] Sending error what: 
        [external/psi/psi/interface.cc:351] The role of parties must be different.
stacktrace: 
#0 psi::AbstractPsiParty::Init()+0x7f0846f27ee6
#1 psi::ecdh::EcdhPsiSender::Init()+0x7f0846efb8ce
#2 psi::RunPsi()+0x7f0846eeaa9c
#3 psi::BindLibs()::{lambda()#3}::operator()()+0x7f0846ee0205
#4 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f0846ee0483
#5 pybind11::cpp_function::dispatcher()+0x7f0846ec243d
#6 (unknown)+0x53b8c9

 to bob.
Traceback (most recent call last):
  File "/home/ubuntu/secretflow/cluster/psi_a.py", line 64, in <module>
2024-10-31 15:02:18.713 WARNING cleanup.py:127 [alice] -- [Anonymous_job] Signal SIGINT to exit.
    spu.psi(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/secretflow/device/device/spu.py", line 2117, in psi
2024-10-31 15:02:18.714 WARNING api.py:60 [alice] -- [Anonymous_job] Stop signal received (e.g. via SIGINT/Ctrl+C), try to shutdown fed. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip.
2024-10-31 15:02:18.714 WARNING api.py:344 [alice] -- [Anonymous_job] Shutdowning rayfed unintendedly...
2024-10-31 15:02:18.714 ERROR api.py:349 [alice] -- [Anonymous_job] Cross-silo sending error occured. ray::SenderProxyActor.send() (pid=1245310, ip=10.10.10.223, actor_id=699fc4a69fa001463d60796314000000, repr=<fed.proxy.barriers.SenderProxyActor object at 0x7f001486b3a0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SPURuntime.psi() (pid=1245366, ip=10.10.10.223, actor_id=09550a0539fade53eea89f8514000000, repr=SPURuntime(device_id=None, party=alice))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/secretflow/device/device/spu.py", line 1388, in psi
    report = spu.psi.psi(config, self.link)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/spu/psi.py", line 118, in psi
    report_str = libpsi.libs.psi(
RuntimeError: what: 
        [external/psi/psi/interface.cc:351] The role of parties must be different.
stacktrace: 
#0 psi::AbstractPsiParty::Init()+0x7f0846f27ee6
#1 psi::ecdh::EcdhPsiSender::Init()+0x7f0846efb8ce
#2 psi::RunPsi()+0x7f0846eeaa9c
#3 psi::BindLibs()::{lambda()#3}::operator()()+0x7f0846ee0205
#4 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f0846ee0483
#5 pybind11::cpp_function::dispatcher()+0x7f0846ec243d
#6 (unknown)+0x53b8c9
2024-10-31 15:02:18.714 INFO api.py:356 [alice] -- [Anonymous_job] No wait for data sending.
2024-10-31 15:02:18.717 INFO message_queue.py:72 [alice] -- [Anonymous_job] Notify message polling thread[ErrorSendingQueueThread] to exit.
2024-10-31 15:02:18.717 INFO api.py:371 [alice] -- [Anonymous_job] Shutdowned rayfed.
2024-10-31 15:02:18.717 CRITICAL api.py:375 [alice] -- [Anonymous_job] Exit now due to the previous error.
  File "/home/ubuntu/.local/lib/python3.10/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/secretflow/device/kernels/spu.py", line 615, in psi
    return sfd.get(res)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/secretflow/distributed/primitive.py", line 162, in get
    return rayfed.get(object_refs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fed/api.py", line 621, in get
    values = ray.get(ray_refs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.psi() (pid=1245366, ip=10.10.10.223, actor_id=09550a0539fade53eea89f8514000000, repr=SPURuntime(device_id=None, party=alice))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/secretflow/device/device/spu.py", line 1388, in psi
    report = spu.psi.psi(config, self.link)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/spu/psi.py", line 118, in psi
    report_str = libpsi.libs.psi(
RuntimeError: what: 
        [external/psi/psi/interface.cc:351] The role of parties must be different.
stacktrace: 
#0 psi::AbstractPsiParty::Init()+0x7f0846f27ee6
#1 psi::ecdh::EcdhPsiSender::Init()+0x7f0846efb8ce
#2 psi::RunPsi()+0x7f0846eeaa9c
#3 psi::BindLibs()::{lambda()#3}::operator()()+0x7f0846ee0205
#4 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f0846ee0483
#5 pybind11::cpp_function::dispatcher()+0x7f0846ec243d
#6 (unknown)+0x53b8c9
(SPURuntime(device_id=None, party=alice) pid=1245366) [928.403]       perfetto.cc:45899 Configured tracing session 1, #sources:1, duration:0 ms, #buffers:1, total buffer size:1024 KB, total sessions:1, uid:0 session name: ""
(SPURuntime(device_id=None, party=alice) pid=1245366) [928.411]       perfetto.cc:47470 Tracing session 1 ended, total sessions:0
(SPURuntime(device_id=None, party=alice) pid=1245366) [2024-10-31 15:02:18.695] [info] [launch.cc:119] PSI config: {"protocol_config":{"protocol":"PROTOCOL_ECDH","role":"ROLE_SENDER","ecdh_config":{"curve":"CURVE_FOURQ"}},"input_config":{"type":"IO_TYPE_FILE_CSV","path":"../data/PIR-PSI用户数据A.csv"},"output_config":{"type":"IO_TYPE_FILE_CSV","path":"../data/psi_result/INNER_A_A.csv"},"keys":["姓名"],"disable_alignment":true,"advanced_join_type":"ADVANCED_JOIN_TYPE_INNER_JOIN","left_side":"ROLE_RECEIVER"}
(SPURuntime(device_id=None, party=alice) pid=1245366) [2024-10-31 15:02:18.695] [info] [sender.cc:43] [EcdhPsiSender::Init] start
(SPURuntime(device_id=None, party=alice) pid=1245366) [2024-10-31 15:02:18.695] [info] [interface.cc:78] [AbstractPsiParty::Init] start
(SPURuntime(device_id=None, party=alice) pid=1245366) [2024-10-31 15:02:18.695] [warning] [interface.cc:285] broadcast_result turns off while advanced join is enabled. broadcast_result is modified to true since intersection has to be sent to both parties.
(SPURuntime(device_id=None, party=alice) pid=1245366) [2024-10-31 15:02:18.695] [warning] [interface.cc:299] The check of duplicated items will be skiped while advanced join is enabled. `

**Comment by yaoyizhuo** [comment]
> 可以在同一台服务器的两个容器中

我在上面贴了我现在的代码，可以辛苦看下哪里有问题嘛？

**Comment by 6fj** [comment]
hi, @yaoyizhuo 

调用 `spu.psi`时,  两边的 `receiver` 字段需要保持一致。

**Comment by Chrisdehe** [comment]
Yep，receiver参数是输出结果的接收方、broadcast_result参数为判断一方接受结果数据或双方接受结果数据

broadcast_result参数为False，即其中一方接受数据，receiver参数需保持一致
broadcast_result参数为True，receiver参数不起作用。

**Comment by yaoyizhuo** [comment]
> hi, @yaoyizhuo
> 
> 调用 `spu.psi`时, 两边的 `receiver` 字段需要保持一致。

谢谢，跑出来了。

> Yep，receiver参数是输出结果的接收方、broadcast_result参数为判断一方接受结果数据或双方接受结果数据
> 
> broadcast_result参数为False，即其中一方接受数据，receiver参数需保持一致 broadcast_result参数为True，receiver参数不起作用。

谢谢，跑出来了。


我现在需要集成这个功能到我们这边的业务，，大概就是定时会通过页面出发一个任务。。
现有两个节点,node1,node2。
node1发起一个任务，现有的方法是两边都需要跑这个代码对嘛？

**Comment by 6fj** [comment]
有两种思路：
1. 你自己负责两边一起拉起任务
2. 在两边各自部署一个 secretflow/kuscia 节点，通过调用kuscia api发起任务，这种情况下kuscia会负责两边同时执行任务。

**Comment by yaoyizhuo** [comment]
> > hi, @yaoyizhuo
> > 调用 `spu.psi`时, 两边的 `receiver` 字段需要保持一致。
> 
> 谢谢，跑出来了。
> 
> > Yep，receiver参数是输出结果的接收方、broadcast_result参数为判断一方接受结果数据或双方接受结果数据
> > broadcast_result参数为False，即其中一方接受数据，receiver参数需保持一致 broadcast_result参数为True，receiver参数不起作用。
> 
> 谢谢，跑出来了。
> 
> 我现在需要集成这个功能到我们这边的业务，，大概就是定时会通过页面出发一个任务。。 现有两个节点,node1,node2。 node1发起一个任务，现有的方法是两边都需要跑这个代码对嘛？

**Comment by yaoyizhuo** [comment]
> 有两种思路：
> 
> 1. 你自己负责两边一起拉起任务
> 2. 在两边各自部署一个 secretflow/kuscia 节点，通过调用kuscia api发起任务，这种情况下kuscia会负责两边同时执行任务。


好的好的，，感觉我来做两边一起拉起任务，感觉有点复杂。
我试一下kuscia方式。。。
跑任务的话，需要双方节点能够正常通信嘛？有没有可以不通信的方式嘞？

**Comment by 6fj** [comment]
> > 有两种思路：
> > 
> > 1. 你自己负责两边一起拉起任务
> > 2. 在两边各自部署一个 secretflow/kuscia 节点，通过调用kuscia api发起任务，这种情况下kuscia会负责两边同时执行任务。
> 
> 好的好的，，感觉我来做两边一起拉起任务，感觉有点复杂。 我试一下kuscia方式。。。 跑任务的话，需要双方节点能够正常通信嘛？有没有可以不通信的方式嘞？

PSI两边肯定是需要通信的

**Comment by yaoyizhuo** [comment]
> > > 有两种思路：
> > > 
> > > 1. 你自己负责两边一起拉起任务
> > > 2. 在两边各自部署一个 secretflow/kuscia 节点，通过调用kuscia api发起任务，这种情况下kuscia会负责两边同时执行任务。
> > 
> > 
> > 好的好的，，感觉我来做两边一起拉起任务，感觉有点复杂。 我试一下kuscia方式。。。 跑任务的话，需要双方节点能够正常通信嘛？有没有可以不通信的方式嘞？
> 
> PSI两边肯定是需要通信的

好的好的
