### ISSUE TITLE
sl实现纵向联邦脚本报错

### ISSUE THREAD

**Issue by Afive233** [secretflow/secretflow#1592]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow1.9.0b2

### OS Platform and Distribution

ubantu 18.04

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
根据隐语官方给的分割学习实现纵向联邦的脚本写了个gru的进行测试，根据报错提示layer传入参数似乎也没问题，debug定位到了slmodel的fit函数中，好像是sf.reveal，反序列化相关的地方出了问题，请问如何排查和解决
```

### Reproduction code to reproduce the issue.

```shell
INFO:root:Create proxy actor <class 'abc.ActorPYUSLTFModel'> with party alice.
INFO:root:Create proxy actor <class 'abc.ActorPYUSLTFModel'> with party bob.
slmodel详情: <secretflow.ml.nn.sl.sl_model.SLModel object at 0x7f4a0066c8e0>
(pid=48503) 2024-11-20 16:56:39.877897: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(ActorPartitionAgent pid=48360) /root/miniconda3/lib/python3.10/site-packages/sklearn/base.py:458: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
(ActorPartitionAgent pid=48360)   warnings.warn(
(ActorPYUSLTFModel pid=48503) WARNING:absl:Skipping variable loading for optimizer 'Adam', because it has 11 variables whereas the saved optimizer has 1 variables. 
(ActorPYUSLTFModel pid=48527) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::ActorPYUSLTFModel.__init__() (pid=48527, ip=192.168.227.112, actor_id=65095d6fa9de9abefe207e7e01000000, repr=<abc.ActorPYUSLTFModel object at 0x7f6ed87d4bb0>)
(ActorPYUSLTFModel pid=48527)   File "/root/secretflow_dsj/secretflow/ml/nn/sl/backend/tensorflow/sl_base.py", line 87, in __init__
(ActorPYUSLTFModel pid=48527)     self.model_base = builder_base() if builder_base is not None else None
(ActorPYUSLTFModel pid=48527)   File "/root/miniconda3/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
(ActorPYUSLTFModel pid=48527)     raise e.with_traceback(filtered_tb) from None
(ActorPYUSLTFModel pid=48527)   File "/root/miniconda3/lib/python3.10/site-packages/keras/utils/layer_utils.py", line 809, in split_out_first_arg
(ActorPYUSLTFModel pid=48527)     raise ValueError(
(ActorPYUSLTFModel pid=48527) ValueError: The first argument to `Layer.call` must always be passed.
INFO:root:SL Train Params: {'self': <secretflow.ml.nn.sl.sl_model.SLModel object at 0x7f4a0066c8e0>, 'x': VDataFrame(partitions={PYURuntime(alice): <secretflow.data.core.partition.Partition object at 0x7f4a087eeb90>, PYURuntime(bob): <secretflow.data.core.partition.Partition object at 0x7f4a085f2260>}, aligned=True), 'y': VDataFrame(partitions={PYURuntime(alice): <secretflow.data.core.partition.Partition object at 0x7f4a085f3ac0>}, aligned=True), 'batch_size': 3, 'epochs': 10, 'verbose': 1, 'callbacks': None, 'validation_data': (VDataFrame(partitions={PYURuntime(alice): <secretflow.data.core.partition.Partition object at 0x7f4a085f32b0>, PYURuntime(bob): <secretflow.data.core.partition.Partition object at 0x7f4a086265f0>}, aligned=True), VDataFrame(partitions={PYURuntime(alice): <secretflow.data.core.partition.Partition object at 0x7f4a085f23e0>}, aligned=True)), 'shuffle': True, 'sample_weight': None, 'validation_freq': 1, 'dp_spent_step_freq': 10, 'dataset_builder': None, 'audit_log_params': {}, 'early_stopping_batch_step': 0, 'early_stopping_warmup_step': 0, 'random_seed': 99927, 'audit_log_dir': None, 'params': {...}}
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 2626, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::ActorPYUSLTFModel.__init__() (pid=48503, ip=192.168.227.112, actor_id=06acd85848b699927216376501000000, repr=<abc.ActorPYUSLTFModel object at 0x7f1145778c10>)
  File "/root/secretflow_dsj/secretflow/ml/nn/sl/backend/tensorflow/sl_base.py", line 87, in __init__
    self.model_base = builder_base() if builder_base is not None else None
  File "/root/miniconda3/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/root/miniconda3/lib/python3.10/site-packages/keras/utils/layer_utils.py", line 809, in split_out_first_arg
    raise ValueError(
ValueError: The first argument to `Layer.call` must always be passed.

源码：from tensorflow.keras import layers,Model
from tensorflow import keras
from secretflow.algorithm_poc.vfl_GRU.vfl_GRU_model import gru_base_model
from secretflow.data.split import train_test_split
import secretflow as sf
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
from typing import List
from secretflow.utils.simulation.datasets import dataset
from secretflow.ml.nn import SLModel
from secretflow.utils.simulation.datasets import load_bank_marketing
from secretflow.preprocessing.scaler import MinMaxScaler
from secretflow.preprocessing.encoder import LabelEncoder
from secretflow.utils.simulation.data import create_df , create_vdf
from tensorflow.keras.callbacks import TensorBoard
sf.shutdown()


'''
垂直场景的gru模型：
'''
# 初始化两方pyu对象
sf.init(['alice', 'bob'], address='local')
alice, bob = sf.PYU('alice'), sf.PYU('bob')

#把数据分给alice，bob 选用数据集：https://archive.ics.uci.edu/dataset/360/air+quality
df = pd.read_excel("./AirQualityUCI.xlsx")
alice_data = df[["Date", "Time", "PT08.S1(CO)","CO(GT)" ]]  #设定CO(GT)为标签预测值
bob_data = df[["Date", "Time","T", "RH" , "AH"]]
dataset = pd.concat([alice_data,bob_data.drop(["Date","Time"],axis=1)],axis=1)
dataset = dataset.iloc[:240]
print("合并后数据集：",dataset.head(5))

#创建测试用的spu集群对象
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

data = create_df(dataset,parts={alice:(0,3),bob:(4,6)},axis=1)
label = create_df(dataset,parts={alice: (3,4)}, axis=1)
label._check_parts()
print("标签列",label.columns)
#对生成的联邦表的类别标签进行编码；把（如字符串或分类特征）转换为整数值，适用于分类特征的预处理
encoder = LabelEncoder()
'''
 Examples:
        >>> from secretflow.preprocessing import LabelEncoder
        >>> le = LabelEncoder()
        >>> le.fit(df)
        >>> le.transform(df)
'''
data['Date'] = encoder.fit_transform(data['Date'])
data['Time'] = encoder.fit_transform(data['Time'])
data['PT08.S1(CO)'] = encoder.fit_transform(data['PT08.S1(CO)'])
data['T'] = encoder.fit_transform(data['T'])
data['RH'] = encoder.fit_transform(data['RH'])
# data['AH'] = encoder.fit_transform(data['AH'])
label['CO(GT)'] = encoder.fit_transform(label['CO(GT)'])

#通过MinMaxScaler做数据标准化 缩放特征
scaler = MinMaxScaler()
data = scaler.fit_transform(data)

#划分数据集
from secretflow.data.split import train_test_split

random_state = 1234
train_data, test_data = train_test_split(
    data, train_size=0.8, random_state=random_state
)
train_label, test_label = train_test_split(
    label, train_size=0.8, random_state=random_state
)

#创建本地模型 base model

#from secretflow.ml.nn.applications.sl_resnet_torch import ResNetBase,BasicBlock,ResNetFuse

# def create_base_model(units, input_shape, name='base_model'):
#
#     inputs = keras.Input(shape=input_shape)
#     # Create model
#     model = gru_base_model(units=units,input_shape=input_shape)
#     outputs = model(inputs)
#     model = Model(inputs=inputs,outputs=outputs)
#     # Compile model
#     model.compile(
#         loss='mean_squared_error',
#         optimizer='adam',
#         metrics=['mean_squared_error'],
#     )
#     return model

def create_gru_model(units, input_shape):
    inputs = keras.Input(shape=input_shape)
    x=layers.GRU(units,return_sequences=True)(inputs)
    x=layers.Dropout(rate=0.1)(x)
    output=layers.Dense(64)(x)
    model=keras.Model(inputs=inputs,outputs=output)
    model.summary()
    model.compile(
        loss='mean_squared_error',
        optimizer='Adam',
        metrics=['mean_squared_error'],
    )
    return model,output

hidden_size = 64
# 准备模型
model_base_alice,alice_base_output = create_gru_model(units=hidden_size,input_shape=(24,3))
model_base_bob,bob_base_output = create_gru_model(units=hidden_size,input_shape=(24,3))
print("alice模型:")
model_base_alice.summary()


#server端（含label）模型
def create_fuse_model(output_list:List[tf.Tensor]):
    merged_layer = layers.concatenate(output_list,axis=-1)
    print("merged layer:",merged_layer)
    fuse_layer = layers.Dense(128,activation="relu",)(merged_layer)
    hidden_layer = layers.GRU(128)(fuse_layer)
    output = layers.Dense(1,activation="linear")(hidden_layer)

    model = keras.Model(inputs=output_list, outputs=output)
    print("融合模型：")
    model.summary()

    model.compile(
        loss='mean_squared_error',
        optimizer='Adam',
        metrics=['mean_squared_error'],
    )
    return model

print("Base model output shape:", alice_base_output.shape)
print("Fuse model inputs:",alice_base_output)



fuse_model = create_fuse_model(output_list=[alice_base_output,bob_base_output]) #alice标签两类:yes/no


#创建拆分学习模型
base_model_dict = {alice: model_base_alice, bob: model_base_bob}

# Define DP operations
from secretflow.security.privacy import DPStrategy, LabelDP
from secretflow.security.privacy.mechanism.tensorflow import GaussianEmbeddingDP

train_batch_size = 3
gaussian_embedding_dp = GaussianEmbeddingDP(
    noise_multiplier=0.5,
    l2_norm_clip=1.0,
    batch_size=train_batch_size,
    num_samples=train_data.values.partition_shape()[alice][0],
    is_secure_generator=False,
)
label_dp = LabelDP(eps=64.0)
dp_strategy_alice = DPStrategy(label_dp=label_dp)
dp_strategy_bob = DPStrategy(embedding_dp=gaussian_embedding_dp)
dp_strategy_dict = {alice: dp_strategy_alice, bob: dp_strategy_bob}
dp_spent_step_freq = 10

sl_model = SLModel(
    base_model_dict=base_model_dict,
    device_y=alice,
    model_fuse=fuse_model,
    dp_strategy_dict=dp_strategy_dict,
    # backend="torch",
    strategy='split_nn',
    agg_method=None,
)
print("slmodel详情:",sl_model)

# sf.reveal(test_data.partitions[alice].data), sf.reveal(
#     test_label.partitions[alice].data
# )
#
# sf.reveal(train_data.partitions[alice].data), sf.reveal(
#     train_label.partitions[alice].data
# )


#tensorboard
log_dir = "./logs/fit"
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

history = sl_model.fit(
    train_data,
    train_label,
    validation_data=(test_data, test_label),
    epochs=10,
    batch_size=train_batch_size,
    shuffle=True,
    verbose=1,
    validation_freq=1,
    dp_spent_step_freq=dp_spent_step_freq,

    # callbacks=[tensorboard_callback]
)



# 可视化损失，准确度，auc
matplotlib.use('Agg')
plt.clf()

plt.plot(history['train_loss'])
plt.plot(history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='upper right')

plt.savefig('./algorithm_poc/vfl_GRU/evaluate/loss.png')
plt.show()
plt.pause(0.1)

plt.clf()
plt.plot(history['mse'])
plt.plot(history['val_mse'])
plt.title('MSE')
plt.ylable('mse')
plt.xlabel('epochs')
plt.legend(['mse','val_mse'])
plt.show()
plt.pause(0.1)
#评估函数
global_metric = sl_model.evaluate(test_data, test_label, batch_size=128)
```

**Comment by BrainWH** [comment]
这里base和fuse的定义有问题, 官网的用法是嵌套函数的形式。
def create_base_model():  
       def create_model():        
          .....  
       return create_model
