### ISSUE TITLE
component is not found, data_prep, psi, 0.0.5.

### ISSUE THREAD

**Issue by damo894127201** [secretflow/secretflow#1613]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.10.0b1

### OS Platform and Distribution

centos7

### Python version

3.10

### What happend and What you expected to happen.

```shell
2024-12-09T15:16:03.801976505+08:00 stderr F INFO:root:KusciaTaskConfig.from_json: {'task_id': 'secretflow-task-20241209151558-single-psi', 'task_input_config': {'sf_datasource_config': {'h800-p2p': {'id': 'default-data-source'}, 'dcu-p2p': {'id': 'default-data-source'}}, 'sf_cluster_desc': {'parties': ['h800-p2p', 'dcu-p2p'], 'devices': [{'name': 'spu', 'type': 'spu', 'parties': ['h800-p2p', 'dcu-p2p'], 'config': '{"runtime_config":{"protocol":"REF2K","field":"FM64"},"link_desc":{"connect_retry_times":60,"connect_retry_interval_ms":1000,"brpc_channel_protocol":"http","brpc_channel_connection_type":"pooled","recv_timeout_ms":1200000,"http_timeout_ms":1200000}}'}, {'name': 'heu', 'type': 'heu', 'parties': ['h800-p2p', 'dcu-p2p'], 'config': '{"mode": "PHEU", "schema": "paillier", "key_size": 2048}'}], 'ray_fed_config': {'cross_silo_comm_backend': 'brpc_link'}}, 'sf_node_eval_param': {'domain': 'data_prep', 'name': 'psi', 'version': '0.0.5', 'attr_paths': ['protocol', 'sort_result', 'allow_duplicate_keys', 'allow_duplicate_keys/yes/join_type', 'allow_duplicate_keys/yes/join_type/left_join/left_side', 'input/receiver_input/key', 'input/sender_input/key'], 'attrs': [{'s': 'PROTOCOL_RR22'}, {'b': True}, {'s': 'yes'}, {'s': 'left_join'}, {'ss': ['h800-p2p']}, {'ss': ['UserID']}, {'ss': ['UserID']}]}, 'sf_input_ids': ['h800-p2p-user-behavior-dataset-table', 'dcu-p2p-user-behavior-dataset-table'], 'sf_output_ids': ['psi-output'], 'sf_output_uris': ['psi-output.csv']}, 'task_cluster_def': '{"parties":[{"name":"h800-p2p", "role":"", "services":[{"portName":"inference", "endpoints":["secretflow-task-20241209151558-single-psi-0-inference.h800-p2p.svc"]}, {"portName":"spu", "endpoints":["secretflow-task-20241209151558-single-psi-0-spu.h800-p2p.svc"]}, {"portName":"fed", "endpoints":["secretflow-task-20241209151558-single-psi-0-fed.h800-p2p.svc"]}, {"portName":"global", "endpoints":["secretflow-task-20241209151558-single-psi-0-global.h800-p2p.svc:29519"]}]}, {"name":"dcu-p2p", "role":"", "services":[{"portName":"inference", "endpoints":["secretflow-task-20241209151558-single-psi-0-inference.dcu-p2p.svc"]}, {"portName":"spu", "endpoints":["secretflow-task-20241209151558-single-psi-0-spu.dcu-p2p.svc"]}, {"portName":"fed", "endpoints":["secretflow-task-20241209151558-single-psi-0-fed.dcu-p2p.svc"]}, {"portName":"global", "endpoints":["secretflow-task-20241209151558-single-psi-0-global.dcu-p2p.svc:20002"]}]}], "selfPartyIdx":0, "selfEndpointIdx":0}', 'allocated_ports': '{"ports":[{"name":"spu", "port":29524, "scope":"Cluster", "protocol":"GRPC"}, {"name":"fed", "port":29518, "scope":"Cluster", "protocol":"GRPC"}, {"name":"global", "port":29519, "scope":"Domain", "protocol":"GRPC"}, {"name":"node-manager", "port":29520, "scope":"Local", "protocol":"GRPC"}, {"name":"object-manager", "port":29521, "scope":"Local", "protocol":"GRPC"}, {"name":"client-server", "port":29522, "scope":"Local", "protocol":"GRPC"}, {"name":"inference", "port":29523, "scope":"Cluster", "protocol":"HTTP"}]}'}
......
2024-12-09T15:16:06.998462528+08:00 stdout F 2024-12-09 07:16:06,998|h800-p2p|ERROR|secretflow|entry.py:main:592| comp_eval exception
2024-12-09T15:16:06.998465635+08:00 stdout F Traceback (most recent call last):
2024-12-09T15:16:06.998467371+08:00 stdout F   File "/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py", line 590, in main
2024-12-09T15:16:06.998469713+08:00 stdout F     res = comp_eval(sf_node_eval_param, storage_config, sf_cluster_config)
2024-12-09T15:16:06.998474047+08:00 stdout F   File "/usr/local/lib/python3.10/site-packages/secretflow/component/entry.py", line 108, in comp_eval
2024-12-09T15:16:06.99847638+08:00 stdout F     return core_comp_eval(param, storage_config, cluster_config, tracer_report)
2024-12-09T15:16:06.998478568+08:00 stdout F   File "/usr/local/lib/python3.10/site-packages/secretflow/component/core/entry.py", line 142, in comp_eval
2024-12-09T15:16:06.998480076+08:00 stdout F     raise RuntimeError(
2024-12-09T15:16:06.998481595+08:00 stdout F RuntimeError: component is not found, data_prep, psi, 0.0.5.


--------------------------------------------------------------------------
KUSCIA_IMAGE=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:0.12.0b0
SECRETFLOW_IMAGE=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.10.0b1
```

### Reproduction code to reproduce the issue.

```shell
Is it that the versions of kuscia and secretflow do not correspond?
```

**Comment by damo894127201** [comment]
> 将sf_node_eval_param修改为如下重新执行
> 
> `"sf_node_eval_param": { "domain": "data_prep", "name": "psi", "version": "0.0.8", "attr_paths": ["input/input_table_1/key", "input/input_table_2/key", "protocol", "sort_result", "allow_empty_result", "allow_duplicate_keys", "allow_duplicate_keys/no/skip_duplicates_check", "allow_duplicate_keys/no/receiver_parties", "ecdh_curve"], "attrs": [{ "is_na": false, "ss": ["UserID"] }, { "is_na": false, "ss": ["UserID"] }, { "is_na": false, "s": "PROTOCOL_RR22" }, { "b": true, "is_na": false }, { "is_na": true }, { "is_na": false, "s": "no" }, { "is_na": true }, { "is_na": false, "ss": ["h800-p2p"] }, { "is_na": false, "s": "CURVE_FOURQ" }] },`
--------------------------------------------------------------------------------------------------------
The result is as follows:

2024-12-09T17:24:58.277020012+08:00 stderr F 2024-12-09 09:24:58.276 ERROR call_holder.py:95 [h800-p2p] -- TASK:[deal_null_from_csv@psi.py:306@PYU(h800-p2p), -ID- 8] throw exception
2024-12-09T17:24:58.277024433+08:00 stderr F Traceback (most recent call last):
2024-12-09T17:24:58.277026189+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/call_holder.py", line 91, in _task
2024-12-09T17:24:58.277027842+08:00 stderr F     ret = self._task_impl(*resolved)
2024-12-09T17:24:58.277029508+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/api.py", line 77, in _execute_impl
2024-12-09T17:24:58.277031291+08:00 stderr F     return self._func_body(*args, **kwargs)
2024-12-09T17:24:58.277032623+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/pyu.py", line 107, in pyu_fn
2024-12-09T17:24:58.277034116+08:00 stderr F     return self._run(fn, *args, **kwargs)
2024-12-09T17:24:58.277035511+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/pyu.py", line 164, in _run
2024-12-09T17:24:58.277036932+08:00 stderr F     return fn(*args, **kwargs)
2024-12-09T17:24:58.277038473+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/component/preprocessing/data_prep/psi.py", line 311, in deal_null_from_csv
2024-12-09T17:24:58.277040101+08:00 stderr F     table_info = extract_data_infos(
2024-12-09T17:24:58.277049471+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/component/data_utils.py", line 280, in extract_data_infos
2024-12-09T17:24:58.277051147+08:00 stderr F     raise NotSupportedError.not_supported_feature_type(feature_type=t)
2024-12-09T17:24:58.277052672+08:00 stderr F secretflow.error_system.exceptions.NotSupportedError: 
2024-12-09T17:24:58.27705419+08:00 stderr F *************************
2024-12-09T17:24:58.277055982+08:00 stderr F code        : 31001008
2024-12-09T17:24:58.277057508+08:00 stderr F reason      : Not supported feature type string
2024-12-09T17:24:58.277058881+08:00 stderr F description : NOT_SUPPORTED_FEATURE_TYPE
2024-12-09T17:24:58.277060319+08:00 stderr F explanation : The feature type is not supported.

**Comment by zimu-yuxi** [comment]
检查下你数据中是否有空值

**Comment by zimu-yuxi** [comment]
kusica容器内，kubectl get domaindata h800-p2p-user-behavior-dataset-table -n h800-p2p -oyaml 
kubectl get domaindata dcu-p2p-user-behavior-dataset-table -n dcu-p2p -oyaml ,提供一下

**Comment by damo894127201** [comment]
> kusica容器内，kubectl get domaindata h800-p2p-user-behavior-dataset-table -n h800-p2p -oyaml kubectl get domaindata dcu-p2p-user-behavior-dataset-table -n dcu-p2p -oyaml ,提供一下

空值问题解决了，是定义domaindata时，数据列的属性类型应该用str，实际用了string，但有新问题，如下

2024-12-10T09:27:26.011831543+08:00 stderr F 2024-12-10 01:27:26.011 INFO brpc_link.py:101 [h800-p2p] -- brpc options: {'proxy_max_restarts': 3, 'timeout_in_ms': 300000, 'recv_timeout_ms': 604800000, 'connect_retry_times': 3600, 'connect_retry_interval_ms': 1000, 'brpc_channel_protocol': 'http', 'brpc_channel_connection_type': 'pooled'}
2024-12-10T09:27:26.037471881+08:00 stderr F I1210 01:27:26.037432     7 external/com_github_brpc_brpc/src/brpc/server.cpp:1181] Server[yacl::link::transport::internal::ReceiverServiceImpl] is serving on port=20154.
2024-12-10T09:27:26.037475227+08:00 stderr F W1210 01:27:26.037449     7 external/com_github_brpc_brpc/src/brpc/server.cpp:1187] Builtin services are disabled according to ServerOptions.has_builtin_services
2024-12-10T09:27:30.499948187+08:00 stderr F 2024-12-10 01:27:30.499 INFO brpc_link.py:127 [h800-p2p] -- Succeeded to listen on 0.0.0.0:20154.
2024-12-10T09:27:30.570672867+08:00 stderr F 2024-12-10 01:27:30.569 ERROR component.py:1208 [h800-p2p] -- eval failed
2024-12-10T09:27:30.577363843+08:00 stderr F Traceback (most recent call last):
2024-12-10T09:27:30.577369768+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/component/component.py", line 1205, in eval
2024-12-10T09:27:30.577371974+08:00 stderr F     ret = self.__eval_callback(ctx=ctx, **kwargs)
2024-12-10T09:27:30.577373757+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/component/preprocessing/data_prep/psi.py", line 525, in two_party_balanced_psi_eval_fn
2024-12-10T09:27:30.577375383+08:00 stderr F     input_path = get_input_path(ctx, [receiver_info, sender_info], task_id)
2024-12-10T09:27:30.577377027+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/component/preprocessing/data_prep/psi.py", line 415, in get_input_path
2024-12-10T09:27:30.577378619+08:00 stderr F     wait(
2024-12-10T09:27:30.577380458+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/device/driver.py", line 212, in wait
2024-12-10T09:27:30.577381936+08:00 stderr F     reveal([o.device(lambda o: None)(o) for o in objs])
2024-12-10T09:27:30.57738329+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/device/driver.py", line 161, in reveal
2024-12-10T09:27:30.577392292+08:00 stderr F     all_object = sfd.get(all_object_refs)
2024-12-10T09:27:30.577393695+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/primitive.py", line 160, in get
2024-12-10T09:27:30.577395212+08:00 stderr F     return sf_fed.get(object_refs)
2024-12-10T09:27:30.577396496+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/api.py", line 307, in get
2024-12-10T09:27:30.577397936+08:00 stderr F     flattened_args[i] = copy.deepcopy(flattened_args[i].get_object())
2024-12-10T09:27:30.577399171+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py", line 117, in get_object
2024-12-10T09:27:30.577400591+08:00 stderr F     self._object = self._object.get()
2024-12-10T09:27:30.577402092+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py", line 31, in get
2024-12-10T09:27:30.577403476+08:00 stderr F     future_result = self.future.result(timeout=2)
2024-12-10T09:27:30.577406878+08:00 stderr F   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
2024-12-10T09:27:30.577408463+08:00 stderr F     return self.__get_result()
2024-12-10T09:27:30.577409921+08:00 stderr F   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2024-12-10T09:27:30.577411298+08:00 stderr F     raise self._exception
2024-12-10T09:27:30.577412594+08:00 stderr F   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-12-10T09:27:30.577413945+08:00 stderr F     result = self.fn(*self.args, **self.kwargs)
2024-12-10T09:27:30.577415661+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/global_context.py", line 203, in _recv
2024-12-10T09:27:30.577417009+08:00 stderr F     data = self._proxy.recv(src_party, seq_id)
2024-12-10T09:27:30.577418298+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/proxy/brpc_link/brpc_link.py", line 180, in recv
2024-12-10T09:27:30.57741969+08:00 stderr F     _recv_data()
2024-12-10T09:27:30.577421122+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/proxy/brpc_link/brpc_link.py", line 162, in _recv_data
2024-12-10T09:27:30.577422477+08:00 stderr F     msg = secure_pickle.loads(
2024-12-10T09:27:30.577423838+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/utils/secure_pickle.py", line 221, in loads
2024-12-10T09:27:30.577427164+08:00 stderr F     return load(
2024-12-10T09:27:30.577428513+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/utils/secure_pickle.py", line 198, in load
2024-12-10T09:27:30.577429909+08:00 stderr F     ).load()
2024-12-10T09:27:30.577431316+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/error_system/sf_exception.py", line 333, in __init__
2024-12-10T09:27:30.577433008+08:00 stderr F     assert False, (
2024-12-10T09:27:30.577434859+08:00 stderr F AssertionError: Derived SFException should be initialized with a NAMELESS 'reason' string parameter, or NAMED error_code(optional), description, reason, explanation parameters
2024-12-10T09:27:30.577457395+08:00 stderr F 2024-12-10 01:27:30.570 INFO driver.py:548 [h800-p2p] -- shutdown is called, barrier_on_shutdown False, on_error True
2024-12-10T09:27:30.577481833+08:00 stderr F 2024-12-10 01:27:30.570 INFO api.py:214 [h800-p2p] -- Shutdowning intendedly, wait_for_sending True
2024-12-10T09:27:30.577484143+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:214 [h800-p2p] -- Try stop context, wait_for_sending True, on_error True
2024-12-10T09:27:30.577485949+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:218 [h800-p2p] -- task_executor stoped
2024-12-10T09:27:30.577487579+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:220 [h800-p2p] -- recv_executor stoped
2024-12-10T09:27:30.577489063+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:224 [h800-p2p] -- send_executor stoped
2024-12-10T09:27:30.577499771+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:237 [h800-p2p] -- Context stoped
2024-12-10T09:27:30.635512066+08:00 stderr F 2024-12-10 01:27:30.635 INFO api.py:222 [h800-p2p] -- Shutdowned
2024-12-10T09:27:30.635529611+08:00 stderr F 2024-12-10 01:27:30.635 CRITICAL api.py:225 [h800-p2p] -- Exit now due to the previous error.

**Comment by damo894127201** [comment]
> > kusica容器内，kubectl get domaindata h800-p2p-user-behavior-dataset-table -n h800-p2p -oyaml kubectl get domaindata dcu-p2p-user-behavior-dataset-table -n dcu-p2p -oyaml ,提供一下
> 
> 空值问题解决了，是定义domaindata时，数据列的属性类型应该用str，实际用了string，但有新问题，如下
> 
> 2024-12-10T09:27:26.011831543+08:00 stderr F 2024-12-10 01:27:26.011 INFO brpc_link.py:101 [h800-p2p] -- brpc options: {'proxy_max_restarts': 3, 'timeout_in_ms': 300000, 'recv_timeout_ms': 604800000, 'connect_retry_times': 3600, 'connect_retry_interval_ms': 1000, 'brpc_channel_protocol': 'http', 'brpc_channel_connection_type': 'pooled'} 2024-12-10T09:27:26.037471881+08:00 stderr F I1210 01:27:26.037432 7 external/com_github_brpc_brpc/src/brpc/server.cpp:1181] Server[yacl::link::transport::internal::ReceiverServiceImpl] is serving on port=20154. 2024-12-10T09:27:26.037475227+08:00 stderr F W1210 01:27:26.037449 7 external/com_github_brpc_brpc/src/brpc/server.cpp:1187] Builtin services are disabled according to ServerOptions.has_builtin_services 2024-12-10T09:27:30.499948187+08:00 stderr F 2024-12-10 01:27:30.499 INFO brpc_link.py:127 [h800-p2p] -- Succeeded to listen on 0.0.0.0:20154. 2024-12-10T09:27:30.570672867+08:00 stderr F 2024-12-10 01:27:30.569 ERROR component.py:1208 [h800-p2p] -- eval failed 2024-12-10T09:27:30.577363843+08:00 stderr F Traceback (most recent call last): 2024-12-10T09:27:30.577369768+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/component/component.py", line 1205, in eval 2024-12-10T09:27:30.577371974+08:00 stderr F ret = self.__eval_callback(ctx=ctx, **kwargs) 2024-12-10T09:27:30.577373757+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/component/preprocessing/data_prep/psi.py", line 525, in two_party_balanced_psi_eval_fn 2024-12-10T09:27:30.577375383+08:00 stderr F input_path = get_input_path(ctx, [receiver_info, sender_info], task_id) 2024-12-10T09:27:30.577377027+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/component/preprocessing/data_prep/psi.py", line 415, in get_input_path 2024-12-10T09:27:30.577378619+08:00 stderr F wait( 2024-12-10T09:27:30.577380458+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/device/driver.py", line 212, in wait 2024-12-10T09:27:30.577381936+08:00 stderr F reveal([o.device(lambda o: None)(o) for o in objs]) 2024-12-10T09:27:30.57738329+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/device/driver.py", line 161, in reveal 2024-12-10T09:27:30.577392292+08:00 stderr F all_object = sfd.get(all_object_refs) 2024-12-10T09:27:30.577393695+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/primitive.py", line 160, in get 2024-12-10T09:27:30.577395212+08:00 stderr F return sf_fed.get(object_refs) 2024-12-10T09:27:30.577396496+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/api.py", line 307, in get 2024-12-10T09:27:30.577397936+08:00 stderr F flattened_args[i] = copy.deepcopy(flattened_args[i].get_object()) 2024-12-10T09:27:30.577399171+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py", line 117, in get_object 2024-12-10T09:27:30.577400591+08:00 stderr F self._object = self._object.get() 2024-12-10T09:27:30.577402092+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py", line 31, in get 2024-12-10T09:27:30.577403476+08:00 stderr F future_result = self.future.result(timeout=2) 2024-12-10T09:27:30.577406878+08:00 stderr F File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result 2024-12-10T09:27:30.577408463+08:00 stderr F return self.__get_result() 2024-12-10T09:27:30.577409921+08:00 stderr F File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result 2024-12-10T09:27:30.577411298+08:00 stderr F raise self._exception 2024-12-10T09:27:30.577412594+08:00 stderr F File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run 2024-12-10T09:27:30.577413945+08:00 stderr F result = self.fn(*self.args, **self.kwargs) 2024-12-10T09:27:30.577415661+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/global_context.py", line 203, in _recv 2024-12-10T09:27:30.577417009+08:00 stderr F data = self._proxy.recv(src_party, seq_id) 2024-12-10T09:27:30.577418298+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/proxy/brpc_link/brpc_link.py", line 180, in recv 2024-12-10T09:27:30.57741969+08:00 stderr F _recv_data() 2024-12-10T09:27:30.577421122+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/proxy/brpc_link/brpc_link.py", line 162, in _recv_data 2024-12-10T09:27:30.577422477+08:00 stderr F msg = secure_pickle.loads( 2024-12-10T09:27:30.577423838+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/utils/secure_pickle.py", line 221, in loads 2024-12-10T09:27:30.577427164+08:00 stderr F return load( 2024-12-10T09:27:30.577428513+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/utils/secure_pickle.py", line 198, in load 2024-12-10T09:27:30.577429909+08:00 stderr F ).load() 2024-12-10T09:27:30.577431316+08:00 stderr F File "/usr/local/lib/python3.10/site-packages/secretflow/error_system/sf_exception.py", line 333, in **init** 2024-12-10T09:27:30.577433008+08:00 stderr F assert False, ( 2024-12-10T09:27:30.577434859+08:00 stderr F AssertionError: Derived SFException should be initialized with a NAMELESS 'reason' string parameter, or NAMED error_code(optional), description, reason, explanation parameters 2024-12-10T09:27:30.577457395+08:00 stderr F 2024-12-10 01:27:30.570 INFO driver.py:548 [h800-p2p] -- shutdown is called, barrier_on_shutdown False, on_error True 2024-12-10T09:27:30.577481833+08:00 stderr F 2024-12-10 01:27:30.570 INFO api.py:214 [h800-p2p] -- Shutdowning intendedly, wait_for_sending True 2024-12-10T09:27:30.577484143+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:214 [h800-p2p] -- Try stop context, wait_for_sending True, on_error True 2024-12-10T09:27:30.577485949+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:218 [h800-p2p] -- task_executor stoped 2024-12-10T09:27:30.577487579+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:220 [h800-p2p] -- recv_executor stoped 2024-12-10T09:27:30.577489063+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:224 [h800-p2p] -- send_executor stoped 2024-12-10T09:27:30.577499771+08:00 stderr F 2024-12-10 01:27:30.570 INFO global_context.py:237 [h800-p2p] -- Context stoped 2024-12-10T09:27:30.635512066+08:00 stderr F 2024-12-10 01:27:30.635 INFO api.py:222 [h800-p2p] -- Shutdowned 2024-12-10T09:27:30.635529611+08:00 stderr F 2024-12-10 01:27:30.635 CRITICAL api.py:225 [h800-p2p] -- Exit now due to the previous error.

---------------------------------------------------------------------------------------------
已经解决了，一是domaindata的数据列字符串类型应为str，却写成了string；二是，两边的相同列的数据属性不一致，中间创建domaindata和授权时，没有保持同步
