### ISSUE TITLE
Enforce fail at external/psi/psi/legacy/bucket_psi.cc:234] . 220 vs 221.logstic error, reader.read_cnt=221, actual_count=220

### ISSUE THREAD

**Issue by damo894127201** [secretflow/secretflow#1621]
### Issue Type

Build/Installation

### Installation Source

Binary

### Secretflow Version

secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.10.0b1

### Operating System and Distribution

centos7

### Python Version

3.10

### Issue Description

```shell
基于Kuscia单独部署的点对点计算节点，在做隐私求交时报如下错误：

2024-12-11T08:23:03.17323449+08:00 stderr F [193.703]       perfetto.cc:47470 Tracing session 1 ended, total sessions:0
2024-12-11T08:23:03.174490128+08:00 stderr F 2024-12-11 00:23:03.173 ERROR call_holder.py:95 [h800-p2p] -- TASK:[SPURuntime::psi, -ID- 15] throw exception
2024-12-11T08:23:03.174493003+08:00 stderr F Traceback (most recent call last):
2024-12-11T08:23:03.174494738+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/call_holder.py", line 91, in _task
2024-12-11T08:23:03.174496434+08:00 stderr F     ret = self._task_impl(*resolved)
2024-12-11T08:23:03.174497843+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/actor.py", line 147, in _execute_impl
2024-12-11T08:23:03.174500081+08:00 stderr F     ret = func(*args, **kwargs)
2024-12-11T08:23:03.174501458+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py", line 1388, in psi
2024-12-11T08:23:03.174502868+08:00 stderr F     report = spu.psi.psi(config, self.link)
2024-12-11T08:23:03.174504301+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/spu/psi.py", line 118, in psi
2024-12-11T08:23:03.174505775+08:00 stderr F     report_str = libpsi.libs.psi(
2024-12-11T08:23:03.174507403+08:00 stderr F RuntimeError: what: 
2024-12-11T08:23:03.174511109+08:00 stderr F 	[Enforce fail at external/psi/psi/legacy/bucket_psi.cc:234] . 220 vs 221.logstic error, reader.read_cnt=221, actual_count=220, input_path=/tmp/sf_secretflow-task-20241211082147-single-psi_h800-p2p/33c4b74f-7688-4b5a-86f9-515c477d8440/user_behavior_dataset.csv.deal_null.csv, target_count=221, output_difference=false, please be sure the `indices` is sorted
```

### Reproduction Code

```shell
同样的脚本，昨天可以执行成功，今天报了错(中间又部署了一个secretpad all in one p2p节点)
```

**Comment by lanyy9527** [comment]
已在[gitee](https://gitee.com/secretflow/secretflow/issues/IBAITG)中回复，请关注

**Comment by lanyy9527** [comment]
如果您没有其他问题，这边就结束工单了哈。
