### ISSUE TITLE
隐语1.10.0b0版本中psi_csv函数执行错误

### ISSUE THREAD

**Issue by sMiaoPaSi** [secretflow/secretflow#1663]
### Issue Type

Usability

### Installation Source

Source

### Secretflow Version

1.10.0b0

### Operating System and Distribution

docker image 1.10.0b0

### Python Version

3.10.13

### Issue Description

```shell
在执行psi_csv函数时，参数设置  KKRT_PSI_2PC运行正常
换为  RR22_PSI_2PC 执行结果报错，报错结果如下
[root@d3cf4f53d7da ~]# python test.py 
I1230 08:53:05.260270 135358435340416 driver.py:456] Try init sf in SIMULATION mode
2024-12-30 08:53:05,261	INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 192.168.0.7:9001...
2024-12-30 08:53:05,305	INFO worker.py:1724 -- Connected to Ray cluster.
Traceback (most recent call last):
  File "/root/test.py", line 80, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/root/test.py", line 63, in main
    reports = spu.psi_csv(
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py", line 1874, in psi_csv
    return dispatch(
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/kernels/spu.py", line 321, in psi_csv
    return sfd.get(res)
  File "/usr/local/lib/python3.10/site-packages/secretflow/distributed/primitive.py", line 164, in get
    return ray.get(object_refs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::SPURuntime.psi_csv() (pid=545, ip=192.168.0.8, actor_id=91cab43805730f5b355a400204000000, repr=SPURuntime(device_id=None, party=bob))
  File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py", line 813, in psi_csv
    psi_type=psi.PsiType.Value(protocol),
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/internal/enum_type_wrapper.py", line 59, in Value
    raise ValueError('Enum {} has no value defined for name {!r}'.format(
ValueError: Enum PsiType has no value defined for name 'RR22_PSI_2PC'
```

### Reproduction Code

```shell
import sys
import time
import logging

from absl import app
import spu
import secretflow as sf

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# SPU settings
cluster_def = {
    'nodes': [
        # <<< !!! >>> replace <192.168.0.1:12945> to alice node's local ip & free port
        {'party': 'alice', 'address': '192.168.0.7:12945', 'listen_address': '0.0.0.0:12945'},
        # <<< !!! >>> replace <192.168.0.2:12946> to bob node's local ip & free port
        {'party': 'bob', 'address': '192.168.0.8:12946', 'listen_address': '0.0.0.0:12946'},
        # <<< !!! >>> if you need 3pc test, please add node here, for example, add carol as rank 2
        # {'party': 'carol', 'address': '127.0.0.1:12347'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}



def main(_):

    # sf init
    # <<< !!! >>> replace <192.168.0.1:9394> to your ray head
    sf.init(['alice','bob'], address='192.168.0.7:9001')
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')
    # carol = sf.PYU('carol')

    # <<< !!! >>> replace path to real parties local file path.
    input_path = {
        alice: 'alice.csv',
        bob: 'bob.csv',
        # if run with `ECDH_PSI_3PC`, add carol
        # carol: '/data/psi_3.csv',
    }
    output_path = {
        alice: '/root/alice_psi_output.csv',
        bob: '/root/bob_psi_output.csv',
        # if run with `ECDH_PSI_3PC`, add carol
        # carol: '/data/psi_output.csv',
    }
    select_keys = {
        alice: ['hashvalue'],
        bob: ['hashvalue'],
        # if run with `ECDH_PSI_3PC`, add carol
        # carol: ['id'],
    }
    spu = sf.SPU(cluster_def)

    # prepare data
    start = time.time()

    reports = spu.psi_csv(
        key=select_keys,
        input_path=input_path,
        output_path=output_path,
        receiver='alice',  # if `broadcast_result=False`, only receiver can get output file.
        protocol='RR22_PSI_2PC',	# psi protocol
        precheck_input=False,  # will cost ext time if set True
        sort=False,  # will cost ext time if set True
        broadcast_result=True,  # will cost ext time if set True
    )
    print(f"psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")

    sf.shutdown()


if __name__ == '__main__':
    app.run(main)
```

**Comment by lanyy9527** [comment]
RR22协议需要使用psi v2，参考：https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.11.0b1/source/secretflow#secretflow.SPU.psi
