### ISSUE TITLE
配置环境遇到关于zlib的问题

### ISSUE THREAD

**Issue by JSnobody** [secretflow/secretflow#20]
执行步骤：
```
- git clone https://github.com/secretflow/secretflow.git
- conda create -n secretflow python=3.8
- conda activate secretflow
- cd secretflow/
- pip install -r dev-requirements.txt -r requirements.txt
```

然后遇到关于zlib的问题：
### zlib.error: Error -3 while decompressing data: invalid block type

请问你们有遇到过吗？如何解决的？
非常感谢！

**Comment by wuxibin89** [comment]
是在`pip install`过程中遇到问题吗？麻烦把完整的错误信息贴一下

**Comment by JSnobody** [comment]
@wuxibin89 是的。
`ERROR: Exception:
Traceback (most recent call last):
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/xxxx/miniconda3/envs/secretflowlib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 390, in run
    installed = install_given_reqs(
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 758, in install
    install_wheel(
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/site-packages/pip/_internal/operations/install/wheel.py", line 794, in install_wheel
    _install_wheel(
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/site-packages/pip/_internal/operations/install/wheel.py", line 637, in _install_wheel
    file.save()
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/site-packages/pip/_internal/operations/install/wheel.py", line 406, in save
    shutil.copyfileobj(f, dest)
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/zipfile.py", line 940, in read
    data = self._read1(n)
  File "/xxxx/miniconda3/envs/secretflow/lib/python3.8/zipfile.py", line 1016, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid block type`

**Comment by wuxibin89** [comment]
似乎是网络问题导致的，重试一下，或者换一个国内源试试

**Comment by wuxibin89** [comment]
抱歉，这个应该是我们的python wheel包有问题导致的，稍后我们验证修复一下

**Comment by JSnobody** [comment]
@wuxibin89 好的，麻烦你们啦！

**Comment by anakinxc** [comment]
@JSnobody 试一下 secretflow==0.6.13b1，pip 包已经修复了

**Comment by JSnobody** [comment]
我下载secretflow源代码的install，那我重新下载最新的secretflow代码是吧？

**Comment by anakinxc** [comment]
> 我之前是下载secretflow源代码install的，那我重新下载最新的secretflow代码是吧？

嗯，是的

**Comment by JSnobody** [comment]
@wuxibin89 @anakinxc 你们好，刚才我验证了一下，问题已经解决！非常给力，感谢帮助！
