### ISSUE TITLE
secretflow 上如何像jit定义的方法一样使用class

### ISSUE THREAD

**Issue by Stratosphere-Tong** [secretflow/secretflow#231]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

Linux centos 3.10.0

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
在使用spu封装一个类的内置函数fit后，尝试使用sf.reveal()函数解密计算结果，产生如 AttributeError: 'str' object has no attribute '_origin_msg' 字样的报错，请问是什么原因导致的报错？应该如何解决？完整部分报错如下


2022-12-13 13:56:41,157 ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=173196, ip=192.168.1.42, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f0d7a2587c0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/home/jiahaozhao/.conda/envs/secretflow/lib/python3.8/site-packages/ray/exceptions.py", line 38, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
  File "/home/jiahaozhao/.conda/envs/secretflow/lib/python3.8/site-packages/jax/_src/errors.py", line 150, in __init__
    "Abstract tracer value encountered where concrete value is expected: "
AttributeError: 'str' object has no attribute '_origin_msg'
```

另外，如果我想封装一个python类的内置函数进行安全计算，如何才能更优雅的实现？
```


### Reproduction code to reproduce the issue.

```shell
w, b = device(obj.fit, 
                    num_returns_policy=sf.device.SPUCompilerNumReturnsPolicy.FROM_USER,
                    user_specified_num_returns=2,)(X_train, y_train)
 print(w, b)
 print(sf.reveal(w))
 obj.set_param(sf.reveal(w), sf.reveal(b))
```

**Comment by ian-huu** [comment]
似乎是 jax 编译出错了，尝试着直接用 jax.jit 编译你的 fit 函数并找出其中的问题：https://jax.readthedocs.io/en/latest/errors.html#

**Comment by Stratosphere-Tong** [comment]
谢谢，使用最新版本的secretflow已经可以看到原始的error msg了！
但是现在遇到了一个新的问题，在jit的编译过程中，我们可以使用如下的代码来注册类，定义好类的静态变量和动态变量，这样我们就可以在jit中使用自定义的对象了！
```python
class CustomClass:
  def __init__(self, x: jnp.ndarray, mul: bool):
    self.x = x
    self.mul = mul

  @jit
  def calc(self, y):
    if self.mul:
      return self.x * y
    return y

  def _tree_flatten(self):
    children = (self.x,)  # arrays / dynamic values
    aux_data = {'mul': self.mul}  # static values
    return (children, aux_data)

  @classmethod
  def _tree_unflatten(cls, aux_data, children):
    return cls(*children, **aux_data)

from jax import tree_util
tree_util.register_pytree_node(CustomClass,
                               CustomClass._tree_flatten,
                               CustomClass._tree_unflatten)
```
该示例可以在jax教程中 [how to use jit with methods](https://jax.readthedocs.io/en/latest/faq.html#strategy-3-making-customclass-a-pytree) 中看到，但是似乎在spu上这样操作仍然不能使用class，请问在secretflow上是否存在对应的方法来实现类似上面的操作呢？

**Comment by 6fj** [comment]
hi @Stratosphere-Tong 

请先尝试将class嵌入到你需要jit的函数内，感谢。
