### ISSUE TITLE
图像分类中重写加载data_loader,将数据格式转为FedNdarray后数据维度不对，只能重写load函数吗？有没有更为简单的方法来处理目标检测所需要的数据集？官方可以提供一个或者看看下面这个怎么解决吗

### ISSUE THREAD

**Issue by Shine-Thomas** [secretflow/secretflow#235]
### Issue Type

Others

### Source

source

### Secretflow Version

latest

### OS Platform and Distribution

Linux Ubuntun20.04  

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
/home/wppcc/miniconda3/envs/sf-benchmark/bin/python3 /home/wppcc/code/sf-benchmark/demo4_federal_clf_pic/demo_fed_torch_fashion.py 
2022-12-20 22:08:02.274383: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-20 22:08:02.306678: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-12-20 22:08:02.938229: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-20 22:08:02.938308: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-12-20 22:08:02.938316: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Files already downloaded and verified
Files already downloaded and verified
 78%|███████▊  | 490/625 [00:04<00:01, 100.36it/s]2022-12-20 22:08:20,224	ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::PYUFedAvgW.set_weights() (pid=2012102, ip=192.168.60.161, repr=<secretflow.ml.nn.fl.backend.torch.strategy.fed_avg_w.PYUFedAvgW object at 0x7f16b78cd100>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_run() (pid=2011317, ip=192.168.60.161)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_Masker.mask() (pid=2011972, ip=192.168.60.161, repr=<secretflow.security.aggregation.secure_aggregator._Masker object at 0x7ef3b0787700>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::PYUFedAvgW.get_weights() (pid=2012102, ip=192.168.60.161, repr=<secretflow.ml.nn.fl.backend.torch.strategy.fed_avg_w.PYUFedAvgW object at 0x7f16b78cd100>)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/proxy.py", line 72, in wrapper
    return method(*args, **kwargs)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/fl_base.py", line 151, in get_weights
    return self.model.get_weights(return_numpy=True)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Net' object has no attribute 'get_weights'
2022-12-20 22:08:20,235	ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::PYUFedAvgW.set_weights() (pid=2012103, ip=192.168.60.161, repr=<secretflow.ml.nn.fl.backend.torch.strategy.fed_avg_w.PYUFedAvgW object at 0x7fc7c1c86160>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_run() (pid=2011317, ip=192.168.60.161)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_Masker.mask() (pid=2011972, ip=192.168.60.161, repr=<secretflow.security.aggregation.secure_aggregator._Masker object at 0x7ef3b0787700>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::PYUFedAvgW.get_weights() (pid=2012102, ip=192.168.60.161, repr=<secretflow.ml.nn.fl.backend.torch.strategy.fed_avg_w.PYUFedAvgW object at 0x7f16b78cd100>)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/proxy.py", line 72, in wrapper
    return method(*args, **kwargs)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/fl_base.py", line 151, in get_weights
    return self.model.get_weights(return_numpy=True)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Net' object has no attribute 'get_weights'
100%|██████████| 625/625 [00:20<00:00, 93.71it/s]2022-12-20 22:09:07.386080: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-20 22:09:07.386171: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-12-20 22:09:07.386223: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-12-20 22:09:07.386276: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2022-12-20 22:09:07.386330: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2022-12-20 22:09:07.386381: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-12-20 22:09:07.386433: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2022-12-20 22:09:07.386485: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-12-20 22:09:07.386497: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "/home/wppcc/code/sf-benchmark/demo4_federal_clf_pic/demo_fed_torch_fashion.py", line 173, in <module>
    history = fl_model.fit(
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 418, in fit
    global_eval, local_eval = self.evaluate(
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 589, in evaluate
    local_metrics = reveal(metric_objs)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/driver.py", line 143, in reveal
    all_object = ray.get(all_object_refs)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/worker.py", line 1843, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::PYUFedAvgW.evaluate() (pid=2012102, ip=192.168.60.161, repr=<secretflow.ml.nn.fl.backend.torch.strategy.fed_avg_w.PYUFedAvgW object at 0x7f16b78cd100>)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/proxy.py", line 72, in wrapper
    return method(*args, **kwargs)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/fl_base.py", line 230, in evaluate
    y_pred = self.model(x)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wppcc/code/sf-benchmark/demo4_federal_clf_pic/demo_fed_torch_fashion.py", line 67, in forward
    x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/wppcc/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [6, 3, 5, 5], but got 5-dimensional input of size [32, 1, 32, 32, 3] instead
100%|██████████| 625/625 [00:55<00:00, 11.24it/s]

Process finished with exit code 1
```

### Reproduction code to reproduce the issue.

```shell
# -*- coding: utf-8 -*-
# @Time : 2022/12/5 16:32 
# @Author : YeMeng 
# @File : demo1.py 
# @contact: 876720687@qq.com
# @contact: 1274712878@qq.com

# TODO： needs high performance server.
# success in server.

import secretflow as sf
from secretflow.ml.nn.fl.backend.torch.utils import BaseModule, TorchModel
from secretflow.ml.nn.fl.utils import metric_wrapper, optim_wrapper
from secretflow.ml.nn import FLModel
from torchmetrics import Accuracy, Precision
from secretflow.security.aggregation import SecureAggregator
from secretflow.utils.simulation.datasets import load_mnist
from torch import nn, optim
from torch.nn import functional as F
from secretflow.utils.simulation.data.ndarray import create_ndarray
import numpy as np
import torchvision.transforms as transforms
# from torch_geometric.loader import DataLoader
from torchvision.datasets import CIFAR10
from typing import Dict, List, Tuple, Union
from secretflow.data.horizontal import HDataFrame
from secretflow.data.ndarray import FedNdarray, PartitionWay
from secretflow.data.vertical import VDataFrame
from secretflow.device.device.pyu import PYU
from secretflow.security.aggregation import Aggregator
from secretflow.security.compare import Comparator
from secretflow.utils.hash import sha256sum
from secretflow.utils.simulation.data.dataframe import create_df, create_vdf
from secretflow.utils.simulation.data.ndarray import create_ndarray
import warnings
warnings.filterwarnings('ignore')

# In case you have a running secretflow runtime already.
sf.shutdown()
sf.init(['alice', 'bob', 'charlie'], num_cpus=8, log_to_driver=False)
alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')


# class ConvNet(BaseModule):
#     """Small ConvNet for MNIST."""
#     def __init__(self):
#         super(ConvNet, self).__init__()
#         self.conv1 = nn.Conv2d(1, 3, kernel_size=3)
#         self.fc_in_dim = 192
#         self.fc = nn.Linear(self.fc_in_dim, 10)
#
#     def forward(self, x):
#         x = F.relu(F.max_pool2d(self.conv1(x), 3))
#         x = x.view(-1, self.fc_in_dim)
#         x = self.fc(x)
#         return F.softmax(x, dim=1)


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()  # nn. Module. init (self)
        self.conv1 = nn.Conv2d(3, 6, kernel_size=5)
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5)
        self.fcl = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(x.size()[0], -1)
        x = F.relu(self.fcl(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# class Batch_Net(nn.Module):
#     """
#     在上面的Activation_Net的基础上，增加了一个加快收敛速度的方法——批标准化
#     """
#     def __init__(self, in_dim, n_hidden_1, n_hidden_2, out_dim):
#         super(Batch_Net, self).__init__()
#         self.layer1 = nn.Sequential(nn.Linear(in_dim, n_hidden_1), nn.BatchNorm1d(n_hidden_1), nn.ReLU(True))
#         self.layer2 = nn.Sequential(nn.Linear(n_hidden_1, n_hidden_2), nn.BatchNorm1d(n_hidden_2), nn.ReLU(True))
#         self.layer3 = nn.Sequential(nn.Linear(n_hidden_2, out_dim))
#
#     def forward(self, x):
#         x = self.layer1(x)
#         x = self.layer2(x)
#         x = self.layer3(x)
#         return x


def load_fashion_mnist(
    parts: Union[List[PYU], Dict[PYU, Union[float, Tuple]]],
    # normalized_x: bool = True,
    # categorical_y: bool = False,
    is_torch: bool = False,
) -> Tuple[Tuple[FedNdarray, FedNdarray], Tuple[FedNdarray, FedNdarray]]:

    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
    ])

    # 训练集
    trainset = CIFAR10(
        root='../data',
        train=True,
        download=True,
        transform=transform
    )

    # 测试集
    testset = CIFAR10(
        root='../data',
        train=False,
        download=True,
        transform=transform
    )

    x_train, y_train = trainset.data, np.array(trainset.targets)
    x_test, y_test = testset.data, np.array(testset.targets)

    return (
        (
            create_ndarray(x_train, parts=parts, axis=0, is_torch=is_torch),
            create_ndarray(y_train, parts=parts, axis=0),
        ),
        (
            create_ndarray(x_test, parts=parts, axis=0, is_torch=is_torch),
            create_ndarray(y_test, parts=parts, axis=0),
        ),
    )

# (train_data, train_label), (test_data, test_label) = load_mnist(
#     parts={alice: 0.4, bob: 0.6},
#     normalized_x=True,
#     categorical_y=True,
#     is_torch=True,
# )

(train_data, train_label), (test_data, test_label) = load_fashion_mnist(
    parts={alice: 0.4, bob: 0.6},
    # normalized_x=True,
    # categorical_y=True,
    is_torch=True,
)


model_def = TorchModel(
    model_fn=Net,
    loss_fn=nn.CrossEntropyLoss,
    optim_fn=optim_wrapper(optim.Adam, lr=1e-2),
    metrics=[
        metric_wrapper(Accuracy, num_classes=10, average='micro'),
        metric_wrapper(Precision, num_classes=10, average='micro'),
    ],
)

device_list = [alice, bob]
server = charlie
aggregator = SecureAggregator(server,[alice,bob])

# spcify params
fl_model = FLModel(
    server=server,
    device_list=device_list,
    model=model_def,
    aggregator=aggregator,
    strategy='fed_avg_w',  # fl strategy
    backend="torch",  # backend support ['tensorflow', 'torch']
)

history = fl_model.fit(
            x=train_data,
            y=train_label,
            validation_data=(test_data, test_label),
            epochs=20,
            batch_size=32,
            aggregate_freq=1,
        )



# # Draw accuracy values for training & validation
# plt.plot(history.global_history['accuracy'])
# plt.plot(history.global_history['val_accuracy'])
# plt.title('FLModel accuracy')
# plt.ylabel('Accuracy')
# plt.xlabel('Epoch')
# plt.legend(['Train', 'Valid'], loc='upper left')
# plt.show()

期待能够得到解决方法，也可以用这个代码直接修改实现哈！！！
```

**Comment by zhangxingmeng** [comment]
能share一下单机版本明文的torch代码吗？基于这个代码改造会更方便一些

**Comment by Shine-Thomas** [comment]
> 
这个基本官方的torch简单改造的，只写了这个，没有其他了

**Comment by Shine-Thomas** [comment]
1 上述代码是目标分类，采用CIFAR10数据集重写load，遇到的维度问题，torch代码我又写了一下，如下：你看看可以可以参考
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# author： Leo
# datetime： 2022/12/20 19:43
import torch as t
import torchvision as tv
import torchvision.transforms as transforms
# from torch_geometric.loader import DataLoader
from torchvision.datasets import CIFAR10
from torchvision.transforms import ToPILImage

show = ToPILImage()  # 可以把Tensor转换为Image,方便可视化
import torch.nn as nn
import torch.nn.functional as F
from torch import optim
import matplotlib.pyplot as plt
import numpy as np

# import ssl
# ssl._create_default_https_context = ssl._create_unverified_context

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
])

# 训练集
trainset = CIFAR10(
    root='./data',
    train=True,
    download=True,
    transform=transform
)
trainloader = t.utils.data.DataLoader(
    trainset,
    batch_size=4,
    shuffle=True,
    num_workers=0
)
# 测试集
testset = CIFAR10(
    root='./data',
    train=False,
    download=True,
    transform=transform
)
testloader = t.utils.data.DataLoader(
    testset,
    batch_size=4,
    shuffle=False,
    num_workers=0
)

classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')
# datasets对象是一个数据集,可以按下标访问,返回形如(data,labe)的数据
(data, label) = trainset[100]
data.size()  # 验证某一张图片的维度
print(classes[label])
show((data + 1) / 2).resize((100, 100))
# Dataloader是一个可迭代的对象,它将 datasets返回的每一条数据拼接成一个 batch,并提供
# 多线程加速优化和数据打乱等操作。当程序将 datasets中的所有数据遍历完一遍之后,即对 Dataloader完成了一次迭代
dataiter = iter(trainloader)
images, labels = dataiter.next()  # 返回4张图片及标签
print("-----------------")
print(''.join('%11s' % classes[labels[j]] for j in range(4)))
show(tv.utils.make_grid((images + 1) / 2)).resize((400, 100))


def imshow(img):
    img = img / 2 + 0.5
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))


dataiter = iter(trainloader)
images, labels = dataiter.next()
print(images.size())
imshow(tv.utils.make_grid(images))
plt.show()


# 定义神经网络
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()  # nn. Module. init (self)
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fcl = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(x.size()[0], -1)
        x = F.relu(self.fcl(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()
print(net)

# 定义损失函数和优化函数
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

# 训练模型
import time

start_time = time.time()
for epoch in range(2):
    running_loss = 0.0
    # img, label = data
    # #img.size(0)表示每个batch图片数量
    # img = img.view(img.size(0), -1)
    # #img.view():与reshape类似，用来转换size大小,-1表示会自适应的调整剩余的维
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        if i % 2000 == 1999:
            print('[%d,%5d]loss:%.3f' % (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')
end_time = time.time()
print("Training duration:", end_time - start_time)
dataiter = iter(testloader)
images, labels = dataiter.next()
print('True label:', ''.join('%08s' % classes[labels[j]] for j in range(4)))
show(tv.utils.make_grid(images / 2 - 0.5)).resize((400, 100))
outputs = net(images)
_, predicted = t.max(outputs.data, 1)
print('Predicted label:', ''.join('%06s' % classes[predicted[j]] for j in range(4)))

correct = 0
total = 0
with t.no_grad():
    for data in testloader:
        images, labels = data
        outputs = net(images)
        _, predicted = t.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum()
print('Accuracy in testset of 10000 images:%d %%' % (100 * correct / total))

**Comment by Shine-Thomas** [comment]
> 能share一下单机版本明文的torch代码吗？基于这个代码改造会更方便一些

下面这个就是，不知道经过集成隐语后这个问题能否得到解决？？

**Comment by zhangxingmeng** [comment]
我们会在很快的后续版本提供对local dataloader的支持，可以直接把单机可以跑通的dataloader给进去。
希望可以满足你的需求
祝好！

**Comment by zhangxingmeng** [comment]
import numpy as np

data_list,label_list = [],[]
for i, data in enumerate(testloader, 0):
        inputs, labels = data
        for datum in inputs:
            data_list.append(datum.numpy())
        for label in labels:
            label_list.append(label.numpy())

np_data = np.array(data_list)
np_label = np.array(label_list)
np.save("cifar.npy",np_data)

转成fedndarray可以这样转
