### ISSUE TITLE
代码在jit上能跑，在spu上能跑，但是使用sf.reveal()后会报错

### ISSUE THREAD

**Issue by Maxime-Tong** [secretflow/secretflow#268]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.7.11b3

### OS Platform and Distribution

Linux centos 3.10.0

### Python version

3.8.13

### What happend and What you expected to happen.

我使用jit提供的control flow中的lax.cond、lax.while等函数，实现了一份可以在jit上正常运行的代码，使用spu后，同样可以输出结果：`<secretflow.device.device.spu.SPUObject object at 0x7f6118381790>`
但是想要使用sf.reveal()查看明文结果时就会报出如下错误：
```shell
Traceback (most recent call last):
  File "svm_jax.py", line 240, in <module>
    w, b = sf.reveal(w), sf.reveal(b)
  File "/home/jiahaozhao/.conda/envs/secretflow/lib/python3.8/site-packages/secretflow/device/driver.py", line 143, in reveal
    all_object = ray.get(all_object_refs)
  File "/home/jiahaozhao/.conda/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/jiahaozhao/.conda/envs/secretflow/lib/python3.8/site-packages/ray/worker.py", line 1843, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::SPURuntime.run() (pid=183897, ip=192.168.1.42, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f758a09d310>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
```
请问这个报错是什么意思？按照报错信息，有哪些输入参数是可以被计算的？

### Reproduction code to reproduce the issue.

```python
X, labels = loadDataSet('testSet.txt')
sf.shutdown()

sf.init(['alice', 'bob'], num_cpus=8, log_to_driver=True)

alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
device = spu

X_train, y_train = alice(split_test)(X, labels, part_id=1), bob(split_test)(X, labels, part_id=2)
X_train, y_train = X_train.to(device), y_train.to(device)
w, b = device(fit, static_argnames=['arg0', 'arg1'],
                num_returns_policy=sf.device.SPUCompilerNumReturnsPolicy.FROM_USER,
                user_specified_num_returns=2,
                )(X_train, y_train, arg0, arg1)
print(w, b)

# 下面这行代码会报错！！！
w, b = sf.reveal(w), sf.reveal(b)
print(w, b)
```

**Comment by Chrisdehe** [comment]
你好，Maxime-Tong！
您的secretflow版本太低，请先升级到[最新版本0.7.18b0](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/installation.html)

**Comment by Maxime-Tong** [comment]
谢谢，已经更新到最新版本0.7.18b0了，但是仍然会报错，且报错结果和之前基本相同：
```shell
Traceback (most recent call last):
  File "svm_jax.py", line 240, in <module>
    w, b = sf.reveal(w), sf.reveal(b)
  File "/home/jiahaozhao/.conda/envs/secretflow/lib/python3.8/site-packages/secretflow/device/driver.py", line 149, in reveal
    all_object = sfd.get(all_object_refs)
  File "/home/jiahaozhao/.conda/envs/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 49, in get
    return ray.get(object_refs)
  File "/home/jiahaozhao/.conda/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/jiahaozhao/.conda/envs/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::SPURuntime.run() (pid=218348, ip=192.168.1.42, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f3bb6dd8370>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
```

**Comment by rivertalk** [comment]
你好，可以提供一下 `fit` 函数的源码么

**Comment by Maxime-Tong** [comment]
谢谢，我们已经解决了这个问题了
