### ISSUE TITLE
cond控制流似乎不能正常使用

### ISSUE THREAD

**Issue by NDBTjay** [secretflow/secretflow#280]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
写了一个小demo测试一下cond能否在SPU上使用，cond_test()函数的作用类似于relu，大于0的保持不变，小于0的变为0。在jit上能运行，但到了SPU上就报错。可以帮忙看一下什么原因吗？

loc(fused["xla_computation(spu_test)/jit(main)/jit(f)/cond[linear=(False, False)]", "jit_test.py":25:0]): error: failed to legalize operation 'mhlo.case'
Traceback (most recent call last):
  File "jit_test.py", line 58, in <module>
    data = spu_test(data1, data2)
  File "/home/ndbtjay/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/util/distributed.py", line 663, in __call__
    executable, args_flat, out_tree = self._compile_jax_func(
  File "/home/ndbtjay/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/util/distributed.py", line 730, in _compile_jax_func
    executable, output = spu_fe.compile(
  File "/home/ndbtjay/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/util/frontend.py", line 87, in compile
    mlir = spuapi.compile(xla, input_vis)
  File "/home/ndbtjay/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/api.py", line 146, in compile
    return _spu_compilation(xla, MessageToJson(spu_pb2.XlaMeta(inputs=vis)))
  File "/home/ndbtjay/anaconda3/envs/secretflow/lib/python3.8/site-packages/cachetools/__init__.py", line 641, in wrapper
    v = func(*args, **kwargs)
  File "/home/ndbtjay/anaconda3/envs/secretflow/lib/python3.8/site-packages/spu/binding/api.py", line 131, in _spu_compilation
    return _lib.compile(xla, json_meta, "")
RuntimeError: what: 
        [spu/compiler/front_end/fe.cc:50] Run front end pipeline failed
stacktrace: 
#0 spu::compiler::compile()+0x7f9f5a4eeaa4
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f9f5a4c9ee6
#2 pybind11::cpp_function::dispatcher()+0x7f9f5a4d0552
#3 cfunction_call_varargs+0x55ad948e300e
```

### Reproduction code to reproduce the issue.

```shell
import argparse
import json
import jax
from jax import random, jit
import jax.numpy as jnp
import spu.binding.util.distributed as ppd

parser = argparse.ArgumentParser(description='distributed driver.')
parser.add_argument("-c", "--config", default="/home/ndbtjay/Desktop/PPC/SecretFlow/spu/examples/python/conf/3pc.json")
args = parser.parse_args()

with open(args.config, 'r') as file:
    conf = json.load(file)

ppd.init(conf["nodes"], conf["devices"])

def true_func(data, idx):
    return data

def false_func(data, idx):
    data = data.at[idx].set(0)
    return data

def f(data, idx):
    return jax.lax.cond(data[idx]>0, true_func, false_func, data, idx)

def cond_test(data):
    idx = 0
    for num in data:
        data = jax.jit(f)(data, idx)
        idx += 1
    return data

@ppd.device("SPU")
def spu_test(data1, data2):
    data = jnp.concatenate((data1, data2), axis=0) # 横向联邦
    data = cond_test(data)
    return data

def get_data(data):
    return data

if __name__=="__main__":
    # run on cpu
    data = [1, 2, 3, -3, -2, -1, 4, 5, 6]
    data = jnp.asarray(data)
    data = cond_test(data)
    print(data)
    
    # run on spu
    data = [1, 2, 3, -3, -2, -1, 4, 5, 6]
    data = jnp.asarray(data)
    n_points = len(data)
    data1 = data[: (n_points//2)]
    data2 = data[(n_points//2) :]
    data1 = ppd.device("P1")(get_data)(data1)
    data2 = ppd.device("P2")(get_data)(data2)
    data = spu_test(data1, data2)
    data = ppd.get(data)
    print(data)
```

**Comment by rivertalk** [comment]
Hi @NDBTjay 新年快乐

看上去是Jax 翻译出来的指令 `mhlo.case` SPU还没有支持
error: failed to legalize operation 'mhlo.case'

做编译器同学目前还在休假，等他上班了继续追踪这个问题

**Comment by NDBTjay** [comment]
@rivertalk 好的，谢谢
