### ISSUE TITLE
生产模式下求交报错brpc server failed start

### ISSUE THREAD

**Issue by hlysf** [secretflow/secretflow#296]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow: 0.7.18b0

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
生产模式下在两台机器上启动docker，容器内分别启动两个主节点ray。在两个容器中同时运行同样的代码，除了self_party和sf.init的address不同，报错brpc server failed start。。。Fail to listen 10.228.21.25:9548

log：
(secretflow) bash-4.4# python3 secretflow_03.py 
2023-02-07 02:12:03,876 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.228.21.25:9446...
2023-02-07 02:12:03,886 INFO worker.py:1538 -- Connected to Ray cluster.
Traceback (most recent call last):
  File "secretflow_03.py", line 52, in <module>
    spu.psi_csv('ID', input_path, output_path, 'alice', protocol="KKRT_PSI_2PC")
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1225, in psi_csv
    return dispatch(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 263, in psi_csv
    return sfd.get(res)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 49, in get
    return ray.get(object_refs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=3468, ip=10.228.21.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f0e02e63c40>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what: 
        [external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
stacktrace: 
#0 yacl::link::FactoryBrpc::CreateContext()+0x7f0e1404c0c1
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f0e12e95510
#2 pybind11::cpp_function::dispatcher()+0x7f0e12e7fc5b
#3 PyCFunction_Call+0x4dfd82
(SPURuntime pid=3468) 2023-02-07 02:12:07.573 [error] [server.cpp:BRPC:969] Fail to listen 10.228.21.26:9549
(SPURuntime pid=3468) 2023-02-07 02:12:07,605   ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=3468, ip=10.228.21.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f0e02e63c40>)
(SPURuntime pid=3468)   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=3468)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=3468) RuntimeError: what: 
(SPURuntime pid=3468)   [external/yacl/yacl/link/transport/channel_brpc.cc:126] brpc server failed start
(SPURuntime pid=3468) stacktrace: 
(SPURuntime pid=3468) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f0e1404c0c1
(SPURuntime pid=3468) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f0e12e95510
(SPURuntime pid=3468) #2 pybind11::cpp_function::dispatcher()+0x7f0e12e7fc5b
(SPURuntime pid=3468) #3 PyCFunction_Call+0x4dfd82
```

### Reproduction code to reproduce the issue.

```shell
运行的代码内容：
import spu
import secretflow as sf

sf.shutdown()
alice, bob = sf.PYU('alice'), sf.PYU('bob')
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.228.21.25:9448',
            'listen_addr': '0.0.0.0:9448'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.228.21.26:9449',
            'listen_addr': '0.0.0.0:9449'
        },
    },
    'self_party': alice #bob
}

cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            # Use the address and port of alice instead.
            # Please choose a unused port.
            'address': '10.228.21.25:9548',
        },
        {
            'party': 'bob',
            'id': '1',
            # Use the ip and port of bob instead.
            # Please choose a unused port.
            'address': '10.228.21.26:9549',
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}


# sf.init(parties=['alice', 'bob'], address='10.228.21.26:9446', cluster_config=cluster_config)
sf.init(parties=['alice', 'bob'], address='10.228.21.25:9446', cluster_config=cluster_config)
spu = sf.SPU(cluster_def=cluster_def)
input_path = {alice: '/root/psi/id_1500000.csv', bob: '/root/psi/id_1500000.csv'}
output_path = {alice: './alice_psi.csv', bob: './bob_psi.csv'}
spu.psi_csv('ID', input_path, output_path, 'alice', protocol="KKRT_PSI_2PC")
```

**Comment by zhouaihui** [comment]
> sf.init(parties=['alice', 'bob'], address='10.228.21.25:9446', cluster_config=cluster_config)

参见 [部署文档]()
1. 如果你想用仿真模式，则不需要填cluster_config
`sf.init(parties=['alice', 'bob'], address='10.228.21.25:9446')`

2. 如果你想用多ray集群模式（生产模式），则不要填parties参数。填了parties表示仿真模式。
 `sf.init(address='10.228.21.25:9446', cluster_config=cluster_config)`

**Comment by hlysf** [comment]
> > sf.init(parties=['alice', 'bob'], address='10.228.21.25:9446', cluster_config=cluster_config)
> 
> 参见 [部署文档](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html)
> 
> 1. 如果你想用仿真模式，则不需要填cluster_config
>    `sf.init(parties=['alice', 'bob'], address='10.228.21.25:9446')`
> 2. 如果你想用多ray集群模式（生产模式），则不要填parties参数。填了parties表示仿真模式。
>    `sf.init(address='10.228.21.25:9446', cluster_config=cluster_config)`
> 
> 两种模式不要混用。

使用生产模式，去掉parties报错
![image](https://user-images.githubusercontent.com/66900073/217132585-75ddfdb1-030b-42bc-aa2e-bb8f941be0a0.png)

**Comment by zhouaihui** [comment]
`'self_party': alice` > `'self_party': 'alice'`缺少引号，这里应该填写字符串。bob同理。
参见https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#start-secretflow-on-the-node-of-alice

**Comment by hlysf** [comment]
> `'self_party': alice` > `'self_party': 'alice'`缺少引号，这里应该填写字符串。bob同理。 参见https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#start-secretflow-on-the-node-of-alice

运行如下图就是完成了吗？需要手动退出，结果分别储存在双方output
![image](https://user-images.githubusercontent.com/66900073/217165113-8e8053ca-2e7e-49b2-a808-bf9193cb810c.png)
