### ISSUE TITLE
SPU示例：NameError: name 'alice' is not defined

### ISSUE THREAD

**Issue by onelyfly** [secretflow/secretflow#298]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

0.718

### OS Platform and Distribution

centos7

### Python version

Python 3.8 

### What happend and What you expected to happen.

```shell
问题：
>>> input_path = {alice: '/root/data/h_alice.csv', bob: '/root/data/h_bob.csv'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'alice' is not defined
>>> output_path = {alice: '/root/data/h_alice_psi.csv', bob: '/root/data/h_bob_psi.csv'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'alice' is not defined
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf 
from secretflow.device.device.spu import spu
sf.shutdown()
sf.init(address="10.0.152.10:7001")  

alice, bob = sf.PYU('alice'), sf.PYU('bob')

# Alice Bob Carol在三个IP上，但是端口一致
# link_desc是None，没办法，文档里就只说了有哪些参数，又没有example
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': 'localhost:0',
            'address': '10.0.152.10:7002',
            'listen_address': '0.0.0.0:7002'
        },
        {
            'party': 'bob',
            'id': 'localhost:1',
            'address': '10.0.152.11:7002',
            'listen_address': '0.0.0.0:7002'
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL
    }
}
spu_3pc = sf.SPU(cluster_def=cluster_def)

=============
执行
input_path = {alice: '/root/data/h_alice.csv', bob: '/root/data/h_bob.csv'}
output_path = {alice: '/root/data/h_alice_psi.csv', bob: '/root/data/h_bob_psi.csv'}
报错

数据集都有：
(secretflow) bash-4.4# ls
config  h_alice.csv  h_bob.csv
```

**Comment by miluoalbert** [comment]
Hi @onelyfly 
`alice` 和 `bob` 声明在
```py
alice, bob = sf.PYU('alice'), sf.PYU('bob')
```

所以，
```py
input_path = {alice: '/root/data/h_alice.csv', bob: '/root/data/h_bob.csv'}
output_path = {alice: '/root/data/h_alice_psi.csv', bob: '/root/data/h_bob_psi.csv'}
```
需要在上面脚本中使用
