### ISSUE TITLE
建立两个容器，进行PSI隐私求交时卡住无反应

### ISSUE THREAD

**Issue by shifengbj** [secretflow/secretflow#307]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow/secretflow-anolis8:0.7.11b2

### OS Platform and Distribution

Ubuntu18

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
建立了两个DOCKER容器，一个是ALICE,一个是BOB， 在进行PSI求交时，通讯卡住无反应。 
DOCKER通过宿主模式，配置代码如下： 

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# SPU settings
cluster_def = {
'nodes': [
# <<< !!! >>> replace <192.168.0.1:12945> to alice node's local ip & free port
        {'party': 'alice', 'id': 'alice', 'address': '10.1.120.48:12945', 'listen_address': '0.0.0.0:12945'},
# <<< !!! >>> replace <192.168.0.2:12946> to bob node's local ip & free port
        {'party': 'bob', 'id': 'bob', 'address': '10.1.120.48:12946', 'listen_address': '0.0.0.0:12946'},
# <<< !!! >>> if you need 3pc test, please add node here, for example, add carol as rank 2
# {'party': 'carol', 'id': 'local:2', 'address': '127.0.0.1:12347'},
    ],
'runtime_config': {
'protocol': spu.spu_pb2.SEMI2K,
'field': spu.spu_pb2.FM128,
    },
}

def init():
    sf.init(address='10.1.120.48:5666')
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')
    spu = sf.SPU(cluster_def)
    return alice,bob,spu


进行两方容器PSI请交代码如下： 
def to_psi(A_path, B_path, psi_key, alice, bob, spu):
    alice_path = A_path
    bob_path = B_path

    #vertical dataframe
    psi_key = {alice: 'uid', bob: 'uid'}
    vdf = v_read_csv(
        {alice: alice_path, bob: bob_path},
        spu=spu,
        keys=psi_key,
        drop_keys=psi_key,
        psi_protocl="KKRT_PSI_2PC",
    )
    #print(vdf.columns)
    return vdf


调用如下：
if __name__ == "__main__":

    print('[0] to init sf server')
    alice,bob,spu = init()

    # data process module
    # [1] read data from csv into dataframe.
    df = to_df('./data/full_csv',';')
    print('[1] read data from csv into dataframe.')
    print(df)

    # data psi module
    # [2] psi data from PART A & PART B
    print('[2] calulate PSI data from PART A & PART B')
    #psi_data = read_csv(psi_temp)
    psi_data = to_psi('./data/alice/alice_csv', './data/bob/bob_csv','uid', alice, bob, spu)
    print(psi_data.columns) 


ALICE 数据大致如下： 
age,job,marital,education,default,balance,housing,loan,uid
59,retired,married,primary,no,1425,yes,no,23737
22,blue-collar,single,secondary,no,682,no,no,40184
56,technician,married,secondary,no,3931,no,no,32083
36,blue-collar,married,unknown,no,444,no,no,43247
34,admin.,single,secondary,no,598,yes,no,32605
30,technician,single,tertiary,no,236,yes,no,3834
52,admin.,divorced,secondary,no,2717,no,no,25072
45,admin.,married,secondary,no,400,yes,yes,12311
33,technician,divorced,secondary,no,295,no,no,21647
42,admin.,divorced,secondary,no,687,yes,yes,5492
52,blue-collar,single,primary,no,0,no,no,14536
39,admin.,single,secondary,no,2749,yes,no,35643
39,services,single,secondary,no,-244,yes,no,1397
76,retired,married,tertiary,no,2991,no,no,42710
35,management,single,tertiary,no,1496,yes,no,22481
44,management,married,tertiary,no,3762,no,no,23507
59,retired,married,tertiary,no,148,yes,yes,35957
58,management,divorced,tertiary,no,26831,no,no,31040
45,blue-collar,divorced,primary,no,8,no,yes,12649
44,blue-collar,married,secondary,no,1081,yes,no,4689

BOB 数据大致如下： 
contact,day,month,duration,campaign,pdays,previous,poutcome,y,uid
cellular,24,jul,132,1,-1,0,unknown,no,16755
telephone,11,nov,513,1,91,1,success,yes,42228
cellular,25,oct,226,2,490,1,failure,yes,45107
unknown,16,jun,265,3,-1,0,unknown,no,10549
cellular,23,jul,157,1,-1,0,unknown,no,16347
cellular,2,feb,251,1,242,2,failure,no,28992
unknown,13,may,459,1,-1,0,unknown,no,2504
telephone,11,dec,173,1,-1,0,unknown,no,27725
unknown,6,may,524,2,-1,0,unknown,no,580
unknown,19,may,351,1,-1,0,unknown,no,4149
unknown,20,jun,26,17,-1,0,unknown,no,11829
telephone,2,jun,23,1,-1,0,unknown,no,39844
cellular,11,aug,342,3,-1,0,unknown,no,20396
cellular,14,may,311,1,-1,0,unknown,no,37870
cellular,21,nov,45,2,-1,0,unknown,no,27399
cellular,15,jul,101,2,-1,0,unknown,no,14526
unknown,29,may,332,2,-1,0,unknown,no,7301


执行显示如下： 
            4
4      33,unknown,single,unknown,no,1,no,no,unknown,5...            5
...                                                  ...          ...
45206  51,technician,married,tertiary,no,825,no,no,ce...        45207
45207  71,retired,divorced,primary,no,1729,no,no,cell...        45208
45208  72,retired,married,secondary,no,5715,no,no,cel...        45209
45209  57,blue-collar,married,secondary,no,668,no,no,...        45210
45210  37,entrepreneur,married,secondary,no,2971,no,n...        45211

[45211 rows x 2 columns]
[2] calulate PSI data from PART A & PART B

此后无响应。

烦请帮忙协助处理解决
```

### Reproduction code to reproduce the issue.

```shell
建立了两个DOCKER容器，一个是ALICE,一个是BOB， 在进行PSI求交时，通讯卡住无反应。 
DOCKER通过宿主模式，配置代码如下： 

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# SPU settings
cluster_def = {
'nodes': [
# <<< !!! >>> replace <192.168.0.1:12945> to alice node's local ip & free port
        {'party': 'alice', 'id': 'alice', 'address': '10.1.120.48:12945', 'listen_address': '0.0.0.0:12945'},
# <<< !!! >>> replace <192.168.0.2:12946> to bob node's local ip & free port
        {'party': 'bob', 'id': 'bob', 'address': '10.1.120.48:12946', 'listen_address': '0.0.0.0:12946'},
# <<< !!! >>> if you need 3pc test, please add node here, for example, add carol as rank 2
# {'party': 'carol', 'id': 'local:2', 'address': '127.0.0.1:12347'},
    ],
'runtime_config': {
'protocol': spu.spu_pb2.SEMI2K,
'field': spu.spu_pb2.FM128,
    },
}

def init():
    sf.init(address='10.1.120.48:5666')
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')
    spu = sf.SPU(cluster_def)
    return alice,bob,spu


进行两方容器PSI请交代码如下： 
def to_psi(A_path, B_path, psi_key, alice, bob, spu):
    alice_path = A_path
    bob_path = B_path

    #vertical dataframe
    psi_key = {alice: 'uid', bob: 'uid'}
    vdf = v_read_csv(
        {alice: alice_path, bob: bob_path},
        spu=spu,
        keys=psi_key,
        drop_keys=psi_key,
        psi_protocl="KKRT_PSI_2PC",
    )
    #print(vdf.columns)
    return vdf


调用如下：
if __name__ == "__main__":

    print('[0] to init sf server')
    alice,bob,spu = init()

    # data process module
    # [1] read data from csv into dataframe.
    df = to_df('./data/full_csv',';')
    print('[1] read data from csv into dataframe.')
    print(df)

    # data psi module
    # [2] psi data from PART A & PART B
    print('[2] calulate PSI data from PART A & PART B')
    #psi_data = read_csv(psi_temp)
    psi_data = to_psi('./data/alice/alice_csv', './data/bob/bob_csv','uid', alice, bob, spu)
    print(psi_data.columns) 


ALICE 数据大致如下： 
age,job,marital,education,default,balance,housing,loan,uid
59,retired,married,primary,no,1425,yes,no,23737
22,blue-collar,single,secondary,no,682,no,no,40184
56,technician,married,secondary,no,3931,no,no,32083
36,blue-collar,married,unknown,no,444,no,no,43247
34,admin.,single,secondary,no,598,yes,no,32605
30,technician,single,tertiary,no,236,yes,no,3834
52,admin.,divorced,secondary,no,2717,no,no,25072
45,admin.,married,secondary,no,400,yes,yes,12311
33,technician,divorced,secondary,no,295,no,no,21647
42,admin.,divorced,secondary,no,687,yes,yes,5492
52,blue-collar,single,primary,no,0,no,no,14536
39,admin.,single,secondary,no,2749,yes,no,35643
39,services,single,secondary,no,-244,yes,no,1397
76,retired,married,tertiary,no,2991,no,no,42710
35,management,single,tertiary,no,1496,yes,no,22481
44,management,married,tertiary,no,3762,no,no,23507
59,retired,married,tertiary,no,148,yes,yes,35957
58,management,divorced,tertiary,no,26831,no,no,31040
45,blue-collar,divorced,primary,no,8,no,yes,12649
44,blue-collar,married,secondary,no,1081,yes,no,4689

BOB 数据大致如下： 
contact,day,month,duration,campaign,pdays,previous,poutcome,y,uid
cellular,24,jul,132,1,-1,0,unknown,no,16755
telephone,11,nov,513,1,91,1,success,yes,42228
cellular,25,oct,226,2,490,1,failure,yes,45107
unknown,16,jun,265,3,-1,0,unknown,no,10549
cellular,23,jul,157,1,-1,0,unknown,no,16347
cellular,2,feb,251,1,242,2,failure,no,28992
unknown,13,may,459,1,-1,0,unknown,no,2504
telephone,11,dec,173,1,-1,0,unknown,no,27725
unknown,6,may,524,2,-1,0,unknown,no,580
unknown,19,may,351,1,-1,0,unknown,no,4149
unknown,20,jun,26,17,-1,0,unknown,no,11829
telephone,2,jun,23,1,-1,0,unknown,no,39844
cellular,11,aug,342,3,-1,0,unknown,no,20396
cellular,14,may,311,1,-1,0,unknown,no,37870
cellular,21,nov,45,2,-1,0,unknown,no,27399
cellular,15,jul,101,2,-1,0,unknown,no,14526
unknown,29,may,332,2,-1,0,unknown,no,7301


执行显示如下： 
            4
4      33,unknown,single,unknown,no,1,no,no,unknown,5...            5
...                                                  ...          ...
45206  51,technician,married,tertiary,no,825,no,no,ce...        45207
45207  71,retired,divorced,primary,no,1729,no,no,cell...        45208
45208  72,retired,married,secondary,no,5715,no,no,cel...        45209
45209  57,blue-collar,married,secondary,no,668,no,no,...        45210
45210  37,entrepreneur,married,secondary,no,2971,no,n...        45211

[45211 rows x 2 columns]
[2] calulate PSI data from PART A & PART B

此后无响应。

烦请帮忙协助处理解决
```

**Comment by anakinxc** [comment]
@shifengbj 可以提供一下日志吗，谢谢

**Comment by shifengbj** [comment]
一直无响应，强制CTRL+C中断后日志如下：  （但是通过SPU.PSI_CSV方法可以进行容器间求交，并返回VDF，具体代码在日志后粘贴）

强制退出日志：
[45211 rows x 2 columns]
[2] calulate PSI data from PART A & PART B


^CTraceback (most recent call last):
  File "main_test.py", line 62, in <module>
    psi_data = to_psi('./data/alice/alice_csv', './data/bob/bob_csv','uid', alice, bob, spu)
  File "/root/psi.py", line 36, in to_psi
    vdf = v_read_csv(
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/data/vertical/io.py", line 125, in read_csv
    columns_set = set(partition.columns)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/driver.py", line 123, in wrapper
    return reveal(func_or_object(*arg, **kwargs))
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/driver.py", line 143, in reveal
    all_object = ray.get(all_object_refs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/worker.py", line 1837, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/worker.py", line 364, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 1200, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 169, in ray._raylet.check_status



这里换成SPU.PSI_CSV方法可以，但是返回的是CSV输出，我们期望用上面的方法直接得到VDF，以便下一步进行数据分析，数据准备及切割，训练模型（纵向联邦学习）

# prepare data
    start = time.time()

    reports = spu.psi_csv(
        key=select_keys,
        input_path=input_path,
        output_path=output_path,
        receiver=target,  # if `broadcast_result=False`, only receiver can get output file.
        protocol='KKRT_PSI_2PC',  # psi protocol
        precheck_input=False,  # will cost ext time if set True
        sort=True,  # will cost ext time if set True
        broadcast_result=True,  # will cost ext time if set True
    )
    logging.info(f"cost time: {time.time() - start}")
    #print(sf.reveal(reports))
    sf.shutdown()
    return reports

**Comment by zhouaihui** [comment]
hi, @shifengbj , 这行需要修正一下：
```
sf.init(parties=['alice', 'bob'], address='10.1.120.48:5666')
```
仿真模式需要添加parties参数，参见[secretflow.init](https://www.secretflow.org.cn/docs/secretflow/zh_CN/source/secretflow.html#secretflow.init)

**Comment by shifengbj** [comment]
我用的是两个容器的通讯，ALICE和BOB起了两个不同的容器，容器间是宿主模式，通讯应该没问题。
RAY集群启动如下：

在第一个容器里启动
start  --head --node-ip-address="10.1.120.48" --port=“6555” --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats
在第二个容器里启动
ray start  --address='10.1.120.48:5666' --resources='{"bob": 8}' --disable-usage-stats

初始化配置如下： 
parties = {
    'parties': {
        'alice': {
            # The address for other parties.
            'address': '10.1.120.48:12945',
            # (Optional) the listen address, the `address` will
            # be used if not prodived.
            'listen_addr': '0.0.0.0:12945'
        },
        'bob': {
            # The address for other parties.
            'address': '10.1.120.48:12946',
            # (Optional) the listen address, the `address` will
            # be used if not prodived.
            'listen_address': '0.0.0.0:12946'
        },
    },
    'self_party': 'alice'
}

def init():
    #address='10.1.120.48:5666'
    sf.init(address='10.1.120.48:56666')
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')
    spu = sf.SPU(cluster_def)
    return alice,bob,spu

如果加入parties=['alice','bob']会提示不需要ADDRESS参数。

现在的问题是我想模拟生产环境，我看最新版本INIT里启动有个CLUSTER_CONFIG参数，是不是把PARTIES设置进去就行了，我现在的版本提升没有CLUSTER_CONFIG参数。

**Comment by zhouaihui** [comment]
建议先升级secretflow到0.7.18b2，这个版本和目前的文档是匹配的。

**Comment by shifengbj** [comment]
可以了，可能还是之前版本的问题，多谢。 ：）  @zhouaihui  @anakinxc
