### ISSUE TITLE
使用SPU-demo时数据读取出现问题

### ISSUE THREAD

**Issue by Rui-learning** [secretflow/secretflow#328]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.18b3

### OS Platform and Distribution

ubuntu20.04

### Python version

3.8

### What happend and What you expected to happen.

```shell
在使用SPU实例时出现如下问题：
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1977, in array
    dtype = dtypes._lattice_result_type(*leaves)[0] if leaves else dtypes.float_
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/dtypes.py", line 469, in _lattice_result_type
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/dtypes.py", line 469, in <genexpr>
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/dtypes.py", line 312, in _dtype_and_weaktype
    return dtype(value), any(value is typ for typ in _weak_types) or is_weakly_typed(value)
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/dtypes.py", line 462, in dtype
    dt = np.result_type(x)
  File "<__array_function__ internals>", line 180, in result_type
TypeError: Cannot interpret '<secretflow.device.device.spu.SPUObject object at 0x7fdb78774460>' as a data type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/SecretFlow/createPYU-SPU-HEU.py", line 48, in <module>
    jnp.array([alice_arr_spu, bob_arr_spu]), axis=1
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1982, in array
    dtype = dtypes._lattice_result_type(*leaves)[0]
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/dtypes.py", line 469, in _lattice_result_type
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/dtypes.py", line 469, in <genexpr>
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/dtypes.py", line 312, in _dtype_and_weaktype
    return dtype(value), any(value is typ for typ in _weak_types) or is_weakly_typed(value)
  File "/home/ubuntu/anaconda3/envs/secretFlow/lib/python3.8/site-packages/jax/_src/dtypes.py", line 464, in dtype
    raise TypeError(f"Value '{x}' with dtype {dt} is not a valid JAX array "
TypeError: Value '<secretflow.device.device.spu.SPUObject object at 0x7fdb78774460>' with dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.
(_run pid=539069) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=539069) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=539069) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=539069) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=539069) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=539069) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(_run pid=539073) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=539073) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=539073) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=539073) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=539073) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=539073) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(_run pid=539068) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=539068) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=539068) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=539068) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=539068) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=539068) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

以下时我的代码

import secretflow as sf
import pandas as pd
import spu
import jax.numpy as jnp
import numpy as np

sf.init(['alice', 'bob', 'carol'], address='local')

def load_data(file):
    return pd.read_csv(file).values

# 创建PYU实例
alice_pyu = sf.PYU('alice')
bob_pyu = sf.PYU('bob')
carol_pyu = sf.PYU('carol')

alice_arr:sf.PYUObject = alice_pyu(load_data)('alice.csv')
bob_arr:sf.PYUObject = bob_pyu(load_data)('bob.csv')
carol_arr:sf.PYUObject = carol_pyu(load_data)('carol.csv')

# 创建一次个基于ABY3协议的SPU实例
cluster_def = {
    'nodes':[
        {'party':'alice', 'id':'local:0', 'address':'127.0.0.1:10001'},
        {'party':'bob', 'id':'local:1', 'address':'127.0.0.1:10002'},
        {'party':'carol', 'id':'local:2', 'address':'127.0.0.1:10003'},
    ],
    'runtime_config':{'protocol':spu.spu_pb2.ABY3,
                      'field':spu.spu_pb2.FM64}
}

spu_device = sf.SPU(cluster_def=cluster_def)

alice_arr_spu:sf.SPUObject = alice_arr.to(spu_device)
bob_arr_spu:sf.SPUObject = bob_arr.to(spu_device)
carol_arr_spu:sf.SPUObject = carol_arr.to(spu_device)

 # jax.numpy.average(a, axis=None, ...)
avg:sf.SPUObject = spu_device(jnp.average)(
    jnp.array([alice_arr_spu, bob_arr_spu]), axis=0
)
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf
import pandas as pd
import spu
import jax.numpy as jnp
import numpy as np

sf.init(['alice', 'bob', 'carol'], address='local')

def load_data(file):
    return pd.read_csv(file).values

# 创建PYU实例
alice_pyu = sf.PYU('alice')
bob_pyu = sf.PYU('bob')
carol_pyu = sf.PYU('carol')

alice_arr:sf.PYUObject = alice_pyu(load_data)('alice.csv')
bob_arr:sf.PYUObject = bob_pyu(load_data)('bob.csv')
carol_arr:sf.PYUObject = carol_pyu(load_data)('carol.csv')

# 创建一次个基于ABY3协议的SPU实例
cluster_def = {
    'nodes':[
        {'party':'alice', 'id':'local:0', 'address':'127.0.0.1:10001'},
        {'party':'bob', 'id':'local:1', 'address':'127.0.0.1:10002'},
        {'party':'carol', 'id':'local:2', 'address':'127.0.0.1:10003'},
    ],
    'runtime_config':{'protocol':spu.spu_pb2.ABY3,
                      'field':spu.spu_pb2.FM64}
}

spu_device = sf.SPU(cluster_def=cluster_def)

alice_arr_spu:sf.SPUObject = alice_arr.to(spu_device)
bob_arr_spu:sf.SPUObject = bob_arr.to(spu_device)
carol_arr_spu:sf.SPUObject = carol_arr.to(spu_device)

 # jax.numpy.average(a, axis=None, ...)
avg:sf.SPUObject = spu_device(jnp.average)(
    jnp.array([alice_arr_spu, bob_arr_spu]), axis=0
)

```
```

**Comment by 6fj** [comment]
Hi @Rui-learning 

错误来自于[jax.numpy.array](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.array.html#jax.numpy.array)。请确保以下程序可以执行：
```
import pandas as pd
import jax.numpy as jnp

x = pd.read_csv(file).values
y = jnp.array([x, x]
```
如果上述代码不可以执行，请尝试预先处理csv。（你可以在pyu device中执行预处理操作）
请注意numpy.array可以执行不代表jnp.array也可以，jnp.array只是在默认前者的接口。

**Comment by anakinxc** [comment]
Hi @Rui-learning:

问题出现在这里

``` python
avg:sf.SPUObject = spu_device(jnp.average)(
    jnp.array([alice_arr_spu, bob_arr_spu]), axis=0
)
```

alice_arr_spu 和 bob_arr_spu 是连个 secret array，jax 并不知道怎么 concat

你可以改成 

``` python
def foo(x, y):
    return jnp.average([x,y])
```
