### ISSUE TITLE
使用pytorch线性模型进行训练报错

### ISSUE THREAD

**Issue by xiaoran33** [secretflow/secretflow#354]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.7.18b3

### OS Platform and Distribution

centos7

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
仿真模式下双节点加载两方数据使用pytorch线性模型进行训练报错，报错信息如下：
2023-03-07 10:08:19.952222: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-07 10:08:20.033965: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-07 10:08:21.337543: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-07 10:08:21.337707: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-03-07 10:08:21.337733: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-07 10:08:23,520 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 192.168.207.195:6379...
2023-03-07 10:08:23,534 INFO worker.py:1538 -- Connected to Ray cluster.
(154, 5)
(_run pid=32585, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=32585, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=32585, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=32585, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=32585, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=32585, ip=192.168.207.196) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(_run pid=2055) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=2055) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=2055) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=2055) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=2055) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=2055) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(_run pid=32706, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=32706, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=32706, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=32706, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=32706, ip=192.168.207.196) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=32706, ip=192.168.207.196) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(SPURuntime pid=2053) 2023-03-07 10:08:32.101 [info] [beaver_cheetah.cc:LazyExpandSEALContexts:299] BeaverCheetah::Mul uses 4 modulus (36 bit each) for 64 bit ring
(_run pid=2185) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=2185) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=2185) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=2185) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=2185) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=2185) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(SPURuntime pid=32584, ip=192.168.207.196) 2023-03-07 10:08:32.446 [info] [beaver_cheetah.cc:LazyExpandSEALContexts:299] BeaverCheetah::Mul uses 4 modulus (36 bit each) for 64 bit ring
(SPURuntime pid=2053) 2023-03-07 10:08:32.210 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 7
(SPURuntime pid=32584, ip=192.168.207.196) 2023-03-07 10:08:32.553 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 7
INFO:root:Neither train_size nor test_size is empty, Here use train_size for split
INFO:root:Neither train_size nor test_size is empty, Here use train_size for split
iris_data:(154, 4)
iris_label:(154, 3)
train_iris_data:(122, 4)
test_iris_data:(32, 4)
train_iris_label:(122, 3)
test_iris_label:(32, 3)
INFO:root:Create proxy actor <class 'secretflow.ml.nn.fl.backend.torch.strategy.fed_prox.PYUFedProx'> with party promoter.
INFO:root:Create proxy actor <class 'secretflow.ml.nn.fl.backend.torch.strategy.fed_prox.PYUFedProx'> with party provider.
INFO:root:FL Train Params: {'self': <secretflow.ml.nn.fl.fl_model.FLModel object at 0x7fbbb06c08b0>, 'x': HDataFrame(partitions={promoter_: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7fbbb06b0d90>), provider_: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7fbbb06e5100>)}, aggregator=<secretflow.security.aggregation.spu_aggregator.SPUAggregator object at 0x7fbbb07048e0>, comparator=None), 'y': HDataFrame(partitions={promoter_: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7fbbb06e5ee0>), provider_: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7fbbb0678220>)}, aggregator=<secretflow.security.aggregation.spu_aggregator.SPUAggregator object at 0x7fbbb07048e0>, comparator=None), 'batch_size': 32, 'batch_sampling_rate': None, 'epochs': 100, 'verbose': 1, 'callbacks': None, 'validation_data': (HDataFrame(partitions={promoter_: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7fbbb06b0d60>), provider_: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7fbbb06e58b0>)}, aggregator=<secretflow.security.aggregation.spu_aggregator.SPUAggregator object at 0x7fbbb07048e0>, comparator=None), HDataFrame(partitions={promoter_: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7fbbb06e5e80>), provider_: Partition(data=<secretflow.device.device.pyu.PYUObject object at 0x7fbbb0678400>)}, aggregator=<secretflow.security.aggregation.spu_aggregator.SPUAggregator object at 0x7fbbb07048e0>, comparator=None)), 'shuffle': False, 'class_weight': None, 'sample_weight': None, 'validation_freq': 1, 'aggregate_freq': 1, 'label_decoder': None, 'max_batch_size': 20000, 'prefetch_buffer_size': None, 'sampler_method': 'batch', 'random_seed': 95642, 'dp_spent_step_freq': None, 'audit_log_dir': None}
(pid=436, ip=192.168.207.196) 2023-03-07 10:08:40.531198: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=436, ip=192.168.207.196) 2023-03-07 10:08:40.600717: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=2365) 2023-03-07 10:08:40.518905: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=2365) 2023-03-07 10:08:40.589951: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=436, ip=192.168.207.196) 2023-03-07 10:08:41.782499: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
(pid=436, ip=192.168.207.196) 2023-03-07 10:08:41.782686: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
(pid=436, ip=192.168.207.196) 2023-03-07 10:08:41.782712: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(pid=2365) 2023-03-07 10:08:41.788597: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
(pid=2365) 2023-03-07 10:08:41.788781: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
(pid=2365) 2023-03-07 10:08:41.788809: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
  0%|                                                                                                                                       | 0/2 [00:00<?, ?it/s](PYUFedProx pid=2365) /root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/utils.py:51: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:189.)
(PYUFedProx pid=2365)   weights_dict[k] = torch.Tensor(v)
(PYUFedProx pid=436, ip=192.168.207.196) /root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/ml/nn/fl/backend/torch/utils.py:51: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:189.)
(PYUFedProx pid=436, ip=192.168.207.196)   weights_dict[k] = torch.Tensor(v)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:19<00:00, 15.85it/s]2023-03-07 10:10:44,442 ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=32584, ip=192.168.207.196, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f6151bea4f0>)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 342, in run
    self.runtime.run(executable)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/spu/binding/api.py", line 46, in run
    return self._vm.Run(executable.SerializeToString())
RuntimeError: what: 
        [Enforce fail at spu/mpc/beaver/cheetah/modswitch_helper.cc:490] src.stride() == 1. 
stacktrace: 
#0 spu::mpc::BeaverCheetah::MulImpl::EncodeArray()::{lambda()#1}::operator()()+0x7f6162a95bcd
#1 spu::mpc::BeaverCheetah::MulImpl::EncodeArray()+0x7f6162a95f99
#2 spu::mpc::BeaverCheetah::MulImpl::EncodeArray()+0x7f6162a9630a
#3 spu::mpc::BeaverCheetah::MulImpl::MulAShr()+0x7f6162aa8011
#4 spu::mpc::BeaverCheetah::MulAShr()+0x7f6162aa9057
#5 spu::mpc::BinaryKernel::evaluate()+0x7f616296e2c5
#6 spu::mpc::Object::call<>()+0x7f6162c14549
#7 spu::mpc::(anonymous namespace)::block_par_binary()+0x7f6162c1e1d3
#8 spu::mpc::(anonymous namespace)::ABProtMulSS::proc()+0x7f6162c1ee60
#9 spu::mpc::BinaryKernel::evaluate()+0x7f616296e2c5
#10 spu::mpc::Object::call<>()+0x7f6162c14549
#11 spu::mpc::mul_ss()+0x7f6162c43264
#12 spu::kernel::hal::_mul_ss()+0x7f616292cb53
#13 spu::kernel::hal::_mul()+0x7f6162923d3a
#14 spu::kernel::hal::detail::div_goldschmidt()+0x7f6162901fe4
#15 spu::kernel::hal::f_div()+0x7f61629058a6
Traceback (most recent call last):
  File "iris_myself_test_fl_non_iid_fedprox_18b1_mplnet.py", line 97, in <module>
    history = fl_model.fit(
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/ml/nn/fl/fl_model.py", line 391, in fit
    model_params.to(device) if model_params is not None else None
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/device/device/base.py", line 100, in to
    return dispatch(
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 40, in to
    return device(reveal)(
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 127, in wrapper
    sfd.remote(self._run)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 82, in _remote
    args, kwargs = _resolve_args(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 72, in _resolve_args
    actual_vals = ray.get(list(refs.values()))
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.outfeed_share() (pid=32584, ip=192.168.207.196, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f6151bea4f0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SPURuntime.run() (pid=32584, ip=192.168.207.196, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f6151bea4f0>)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 342, in run
    self.runtime.run(executable)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/spu/binding/api.py", line 46, in run
    return self._vm.Run(executable.SerializeToString())
RuntimeError: what: 
        [Enforce fail at spu/mpc/beaver/cheetah/modswitch_helper.cc:490] src.stride() == 1. 
stacktrace: 
#0 spu::mpc::BeaverCheetah::MulImpl::EncodeArray()::{lambda()#1}::operator()()+0x7f6162a95bcd
#1 spu::mpc::BeaverCheetah::MulImpl::EncodeArray()+0x7f6162a95f99
#2 spu::mpc::BeaverCheetah::MulImpl::EncodeArray()+0x7f6162a9630a
#3 spu::mpc::BeaverCheetah::MulImpl::MulAShr()+0x7f6162aa8011
#4 spu::mpc::BeaverCheetah::MulAShr()+0x7f6162aa9057
#5 spu::mpc::BinaryKernel::evaluate()+0x7f616296e2c5
#6 spu::mpc::Object::call<>()+0x7f6162c14549
#7 spu::mpc::(anonymous namespace)::block_par_binary()+0x7f6162c1e1d3
#8 spu::mpc::(anonymous namespace)::ABProtMulSS::proc()+0x7f6162c1ee60
#9 spu::mpc::BinaryKernel::evaluate()+0x7f616296e2c5
#10 spu::mpc::Object::call<>()+0x7f6162c14549
#11 spu::mpc::mul_ss()+0x7f6162c43264
#12 spu::kernel::hal::_mul_ss()+0x7f616292cb53
#13 spu::kernel::hal::_mul()+0x7f6162923d3a
#14 spu::kernel::hal::detail::div_goldschmidt()+0x7f6162901fe4
#15 spu::kernel::hal::f_div()+0x7f61629058a6
Exception ignored in: <function SPUObject.__del__ at 0x7fbc731a6a60>
Traceback (most recent call last):
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 152, in __del__
    actor.del_share.remote(self.shares_name[i])
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/actor.py", line 138, in remote
    return self._remote(args, kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 425, in _start_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/actor.py", line 184, in _remote
    return invocation(args, kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/actor.py", line 171, in invocation
    return actor._actor_method_call(
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/actor.py", line 1172, in _actor_method_call
    object_refs = worker.core_worker.submit_actor_task(
AttributeError: 'Worker' object has no attribute 'core_worker'
Exception ignored in: <function SPUObject.__del__ at 0x7fbc731a6a60>
Traceback (most recent call last):
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 152, in __del__
    actor.del_share.remote(self.shares_name[i])
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/actor.py", line 138, in remote
    return self._remote(args, kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 425, in _start_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/actor.py", line 184, in _remote
    return invocation(args, kwargs)
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/actor.py", line 171, in invocation
    return actor._actor_method_call(
  File "/root/miniconda3/envs/secretflow-3.8/lib/python3.8/site-packages/ray/actor.py", line 1172, in _actor_method_call
    object_refs = worker.core_worker.submit_actor_task(
AttributeError: 'Worker' object has no attribute 'core_worker'
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [02:02<00:00, 61.03s/it]
```

**Comment by fionser** [comment]
Hi，
The older CHEETAH implementation is not supporting strided input. Please upgrade to the latest version  of libspu.

**Comment by xiaoran33** [comment]
> Hi， The older CHEETAH implementation is not supporting strided input. For example [here](https://github.com/secretflow/spu/blob/6b6618f953eecd36d36376a3ae2115af5719413b/spu/mpc/beaver/cheetah/modswitch_helper.cc#L490)
> 
> Please upgrade to the latest version of libspu.

semi2k是支持的吧？

**Comment by anakinxc** [comment]
> > Hi， The older CHEETAH implementation is not supporting strided input. For example [here](https://github.com/secretflow/spu/blob/6b6618f953eecd36d36376a3ae2115af5719413b/spu/mpc/beaver/cheetah/modswitch_helper.cc#L490)
> > Please upgrade to the latest version of libspu.
> 
> semi2k是支持的吧？ 你的意思是单独升级spu到最新版本的话cheetah协议就支持了吗？

semi2k 应该是没问题的
升级 spu 的话你需要从源码编译一个最新的 spu

**Comment by xiaoran33** [comment]
源码编译最新的spu的话，cheetah协议就是支持的吗？

**Comment by anakinxc** [comment]
> 源码编译最新的spu的话，cheetah协议就是支持的吗？

是的

**Comment by Chrisdehe** [comment]
resolved
Close
