### ISSUE TITLE
ray集群部署后，运行程序出错

### ISSUE THREAD

**Issue by Rui-learning** [secretflow/secretflow#377]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.7.18b3

### OS Platform and Distribution

centos7

### Python version

3.8

### What happend and What you expected to happen.

```shell
在四台服务器中使用docker部署，模拟两方计算，分别启动ray集群，命令如下：
alice：
服务器1：
ray start --head --node-ip-address="10.33.3.148" --port="8848" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats
服务器2：
ray start --address="10.33.3.148:8848"  --disable-usage-stats

bob：
服务器3：
ray start --head --node-ip-address="10.33.3.150" --port="8848" --resources='{"bob": 16}' --include-dashboard=False --disable-usage-stats
服务器4：
ray start --address="10.33.3.150:8848"  --disable-usage-stats

初始化：
服务器1中运行如下：

import secretflow as sf

parties = {
  'alice': {
    'address': '10.33.3.148:8858'
  },
  'bob': {
    'address': '10.33.3.150:8858'
  }
}
cluster_config ={
  'parties': parties,
  'self_party': 'alice'
}

sf.init(address='10.33.3.148:8848', cluster_config=cluster_config)
```

服务器3中运行
```
import secretflow as sf

parties = {
  'alice': {
    'address': '10.33.3.148:8858'
  },
  'bob': {
    'address': '10.33.3.150:8858'
  }
}
cluster_config ={
  'parties': parties,
  'self_party': 'bob'
}

sf.init(address='10.33.3.150:8848', cluster_config=cluster_config)
```

之后在初始化SPU设备进行计算时，出现如下报错：
创建SPU实例......
2023-03-20 20:05:40,286 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.33.3.150:8848...
2023-03-20 20:05:40,314 INFO worker.py:1538 -- Connected to Ray cluster.
创建PYU实例......
各方读取数据......
(scheduler +13s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(scheduler +13s) Error: No available node types can fulfill resource request {'alice': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +49s) Error: No available node types can fulfill resource request {'alice': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
```


### Reproduction code to reproduce the issue.

```shell
运行的源代码如下：

import time
import secretflow as sf
import pandas as pd
import spu
import jax.numpy as jnp
import numpy as np

def load_data(file):
    return pd.read_csv(file).values


print("创建SPU实例......")
# 创建一次个基于SEMI2K协议的SPU实例
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.33.3.148:8868'},
        {
            'party': 'bob',
            'id': '1',
            'address': '10.33.3.150:8868'},
    ],
    'runtime_config': {'protocol': spu.spu_pb2.SEMI2K,
                      'field': spu.spu_pb2.FM64}
}

spu_device = sf.SPU(cluster_def=cluster_def)

print('创建PYU实例......')
# 创建PYU实例
alice_pyu = sf.PYU('alice')
bob_pyu = sf.PYU('bob')

start = time.time()

print("各方读取数据......")
alice_arr:sf.PYUObject = alice_pyu(load_data)('/root/sf/alice.csv')
bob_arr:sf.PYUObject = bob_pyu(load_data)('/root/sf/bob.csv')

alice_arr_spu:sf.SPUObject = alice_arr.to(spu_device)
bob_arr_spu:sf.SPUObject = bob_arr.to(spu_device)

def jnpAvg(x, y):
    return jnp.average(jnp.concatenate([x, y]), axis=0)

def concat(x,  y):
    return jnp.concatenate([x, y])


print('拼接展示：')
b:sf.SPUObject = spu_device(concat)(alice_arr_spu, bob_arr_spu)
concat_result = sf.reveal(b)


print("开始计算平均值......")
 # jax.numpy.average(a, axis=None, ...)
avg:sf.SPUObject = spu_device(jnpAvg)(alice_arr_spu, bob_arr_spu)
print('alice_arr_spu:', sf.reveal(alice_arr_spu))
print('bob_arr_spu', sf.reveal(bob_arr_spu))


a = sf.reveal(avg)
print('result = ', sf.reveal(a))
print('result.len = ', len(a))
print('SPU use time = ', time.time() - start, 's')

```
```

**Comment by miluoalbert** [comment]
可以在两台head机器上使用`ray status`查看一下目前的集群状态吗？

**Comment by Rui-learning** [comment]
服务器1：
(secretflow) bash-4.4# ray status
======== Autoscaler status: 2023-03-20 21:12:17.392025 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_7c7625a8671d6250d7b6445af0e469cdd0f61b643c0f0b5bf6dc8519
 1 node_cc52240f815ec98116a04b20cd0224215924aaca98763e162b376287
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 1.0/16.0 CPU
 1.0/16.0 alice
 0.00/19.061 GiB memory
 0.00/8.794 GiB object_store_memory

Demands:
 {'CPU': 1.0, 'bob': 1.0}: 10+ pending tasks/actors

服务器3：
(secretflow) bash-4.4# ray status
======== Autoscaler status: 2023-03-20 21:18:32.671204 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_7ab4f8240d6e476d299719a76ef76ef1d3c5026712000daa0816220f
 1 node_ee82fc2f3e852cb78e4c3e3e9c9d71a6fc5b4dfb8ec6c2987483b8c9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 1.0/8.0 CPU
 1.0/16.0 bob
 0.00/8.932 GiB memory
 0.00/4.466 GiB object_store_memory

Demands:
 {'CPU': 1.0, 'alice': 1.0}: 10+ pending tasks/actors

**Comment by Rui-learning** [comment]
服务器1：
```
(secretflow) bash-4.4# ray status
======== Autoscaler status: 2023-03-20 21:12:17.392025 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_7c7625a8671d6250d7b6445af0e469cdd0f61b643c0f0b5bf6dc8519
 1 node_cc52240f815ec98116a04b20cd0224215924aaca98763e162b376287
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 1.0/16.0 CPU
 1.0/16.0 alice
 0.00/19.061 GiB memory
 0.00/8.794 GiB object_store_memory

Demands:
 {'CPU': 1.0, 'bob': 1.0}: 10+ pending tasks/actors
```
服务器3
```
(secretflow) bash-4.4# ray status
======== Autoscaler status: 2023-03-20 21:18:32.671204 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_7ab4f8240d6e476d299719a76ef76ef1d3c5026712000daa0816220f
 1 node_ee82fc2f3e852cb78e4c3e3e9c9d71a6fc5b4dfb8ec6c2987483b8c9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 1.0/8.0 CPU
 1.0/16.0 bob
 0.00/8.932 GiB memory
 0.00/4.466 GiB object_store_memory

Demands:
 {'CPU': 1.0, 'alice': 1.0}: 10+ pending tasks/actors
```

**Comment by miluoalbert** [comment]
@Rui-learning 
日志里可以看到你在alice侧请求的是bob的资源，应该是两边代码执行反了，请检查下。

**Comment by miluoalbert** [comment]
Hi, @Rui-learning 
通过上述日志看问题应该是在bob这边：
```
Fail to listen 10.33.3.150:8868
```
需要确认下10.33.3.150的8868是否被占用，如果有占用端口的残余进程可以`kill`一下

**Comment by Rui-learning** [comment]
端口并没有占用，我换了其他的端口也一九无法成功执行。
我又进行了一次尝试，将服务器149和服务器151上的ray集群停止，目前运行“ray status”的结果如下：
服务器148：
```
(secretflow) bash-4.4# ray status
======== Autoscaler status: 2023-03-21 15:04:46.440381 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_7c7625a8671d6250d7b6445af0e469cdd0f61b643c0f0b5bf6dc8519
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 1.0/16.0 CPU
 1.0/16.0 alice
 0.00/19.061 GiB memory
 0.00/8.794 GiB object_store_memory

Demands:
 {'CPU': 1.0, 'bob': 1.0}: 12+ pending tasks/actors
```
服务器150：
```
(secretflow) bash-4.4#                   ray status
======== Autoscaler status: 2023-03-21 15:09:07.016903 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_ee82fc2f3e852cb78e4c3e3e9c9d71a6fc5b4dfb8ec6c2987483b8c9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 2.0/8.0 CPU
 1.0/16.0 bob
 0.00/8.932 GiB memory
 0.00/4.466 GiB object_store_memory

Demands:
 {'CPU': 1.0, 'alice': 1.0}: 12+ pending tasks/actors
```

服务器148程序如下：
```
import time

import secretflow as sf
import pandas as pd
import spu
import jax.numpy as jnp
import numpy as np

# print("初始化参与方......")
# # sf.init(['alice', 'bob', 'carol'], address='local')
# sf.init(['alice', 'bob', 'carol'], address='10.33.3.148:9999')

parties = {
  'alice': {
    'address': '10.33.3.148:8858'
  },
  'bob': {
    'address': '10.33.3.150:8858'
  }
}
cluster_config ={
  'parties': parties,
  'self_party': 'alice'
}

sf.init(address='10.33.3.148:8848', cluster_config=cluster_config)

def load_data(file):
    return pd.read_csv(file).values


print("创建SPU实例......")
# 创建一次个基于ABY3协议的SPU实例
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.33.3.148:8888'},
        {
            'party': 'bob',
            'id': '1',
            'address': '10.33.3.150:9999'},
    ],
    'runtime_config': {'protocol': spu.spu_pb2.SEMI2K,
                      'field': spu.spu_pb2.FM64}
}

spu_device = sf.SPU(cluster_def=cluster_def)

print('创建PYU实例......')
# 创建PYU实例
alice_pyu = sf.PYU('alice')
bob_pyu = sf.PYU('bob')

start = time.time()

print("各方读取数据......")
alice_arr:sf.PYUObject = alice_pyu(load_data)('/root/sf/alice.csv')
bob_arr:sf.PYUObject = bob_pyu(load_data)('/root/sf/bob.csv')
print("各方读取数据......完成")

alice_arr_spu:sf.SPUObject = alice_arr.to(spu_device)
bob_arr_spu:sf.SPUObject = bob_arr.to(spu_device)


def jnpAvg(x, y):
    return jnp.average(jnp.concatenate([x, y]), axis=0)

def concat(x,  y):
    return jnp.concatenate([x, y])


print('开始拼接：')
b:sf.SPUObject = spu_device(concat)(alice_arr_spu, bob_arr_spu)


print("开始计算平均值......")
 # jax.numpy.average(a, axis=None, ...)
avg:sf.SPUObject = spu_device(jnpAvg)(alice_arr_spu, bob_arr_spu)
print('alice_arr_spu:', sf.reveal(alice_arr_spu))
print('bob_arr_spu', sf.reveal(bob_arr_spu))

a = sf.reveal(avg)
print('result = ', sf.reveal(a))
print('result.len = ', len(a))
print('SPU use time = ', time.time() - start, 's')
```
服务器150程序如下：
```
import time

import secretflow as sf
import pandas as pd
import spu
import jax.numpy as jnp
import numpy as np

# print("初始化参与方......")
# # sf.init(['alice', 'bob', 'carol'], address='local')
# sf.init(['alice', 'bob', 'carol'], address='10.33.3.148:9999')

parties = {
  'alice': {
    'address': '10.33.3.148:8858'
  },
  'bob': {
    'address': '10.33.3.150:8858'
  }
}
cluster_config ={
  'parties': parties,
  'self_party': 'bob'
}

sf.init(address='10.33.3.150:8848', cluster_config=cluster_config)

def load_data(file):
    return pd.read_csv(file).values


print("创建SPU实例......")
# 创建一次个基于ABY3协议的SPU实例
cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.33.3.148:9988'},
        {
            'party': 'bob',
            'id': '1',
            'address': '10.33.3.150:9988'},
    ],
    'runtime_config': {'protocol': spu.spu_pb2.SEMI2K,
                      'field': spu.spu_pb2.FM64}
}

spu_device = sf.SPU(cluster_def=cluster_def)

print('创建PYU实例......')
# 创建PYU实例
alice_pyu = sf.PYU('alice')
bob_pyu = sf.PYU('bob')

start = time.time()

print("各方读取数据......")
alice_arr:sf.PYUObject = alice_pyu(load_data)('/root/sf/alice.csv')
bob_arr:sf.PYUObject = bob_pyu(load_data)('/root/sf/bob.csv')
print("各方读取数据......完成")

alice_arr_spu:sf.SPUObject = alice_arr.to(spu_device)
bob_arr_spu:sf.SPUObject = bob_arr.to(spu_device)


def jnpAvg(x, y):
    return jnp.average(jnp.concatenate([x, y]), axis=0)

def concat(x,  y):
    return jnp.concatenate([x, y])


print('开始拼接：')
b:sf.SPUObject = spu_device(concat)(alice_arr_spu, bob_arr_spu)


print("开始计算平均值......")
 # jax.numpy.average(a, axis=None, ...)
avg:sf.SPUObject = spu_device(jnpAvg)(alice_arr_spu, bob_arr_spu)
print('alice_arr_spu:', sf.reveal(alice_arr_spu))
print('bob_arr_spu', sf.reveal(bob_arr_spu))

a = sf.reveal(avg)
print('result = ', sf.reveal(a))
print('result.len = ', len(a))
print('SPU use time = ', time.time() - start, 's')
```

-------------------日志信息-----------------
服务器148：
```
(secretflow) bash-4.4# python3 createPYU-SPU-HEU.py 
INFO:root:Run secretflow in production mode.
2023-03-21 15:41:46,632 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.33.3.148:8848...
2023-03-21 15:41:46,653 INFO worker.py:1538 -- Connected to Ray cluster.
2023-03-21 15:41:48 INFO barriers.py:331 [alice] --  RecverProxy was successfully created.
(RecverProxyActor pid=43737) INFO:fed.barriers:Successfully start Grpc service without credentials.
2023-03-21 15:41:49 INFO barriers.py:368 [alice] --  SendProxy was successfully created.
创建SPU实例......
创建PYU实例......
各方读取数据......
各方读取数据......完成
2023-03-21 15:41:50 INFO cleanup.py:84 [alice] --  Start check sending thread.
2023-03-21 15:41:50 INFO cleanup.py:90 [alice] --  Start check sending monitor thread.
开始拼接：
开始计算平均值......
(scheduler +11s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(scheduler +11s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.
(_run pid=43817) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=43817) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=43817) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=43817) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=43817) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=43817) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "createPYU-SPU-HEU.py", line 81, in <module>
    print('alice_arr_spu:', sf.reveal(alice_arr_spu))
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/driver.py", line 153, in reveal
    all_object = sfd.get(all_object_refs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 47, in get
    return fed.get(object_refs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/fed/api.py", line 394, in get
    values = ray.get(ray_refs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=43816, ip=10.33.3.148, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f570b141520>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what: 
        [external/yacl/yacl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=1
stacktrace: 
#0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f571b161519
#1 pybind11::cpp_function::dispatcher()+0x7f571b14bc5b
#2 PyCFunction_Call+0x4dfd82
2023-03-21 15:42:04 INFO cleanup.py:102 [alice] --  Notify check sending thread to exit.
(SPURuntime pid=43816) 2023-03-21 15:42:04,546  ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=43816, ip=10.33.3.148, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f570b141520>)
(SPURuntime pid=43816)   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=43816)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=43816) RuntimeError: what: 
(SPURuntime pid=43816)  [external/yacl/yacl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=1
(SPURuntime pid=43816) stacktrace: 
(SPURuntime pid=43816) #0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f571b161519
(SPURuntime pid=43816) #1 pybind11::cpp_function::dispatcher()+0x7f571b14bc5b
(SPURuntime pid=43816) #2 PyCFunction_Call+0x4dfd82
(scheduler +46s) Error: No available node types can fulfill resource request {'bob': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +1m21s) Error: No available node types can fulfill resource request {'bob': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +1m56s) Error: No available node types can fulfill resource request {'bob': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +2m31s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.

```

服务器150：
```
(secretflow) bash-4.4# python3 createPYU-SPU-HEU.py  
INFO:root:Run secretflow in production mode.
2023-03-21 15:41:59,332 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.33.3.150:8848...
2023-03-21 15:41:59,370 INFO worker.py:1538 -- Connected to Ray cluster.
2023-03-21 15:42:01 INFO barriers.py:331 [bob] --  RecverProxy was successfully created.
(RecverProxyActor pid=40099) INFO:fed.barriers:Successfully start Grpc service without credentials.
2023-03-21 15:42:04 INFO barriers.py:368 [bob] --  SendProxy was successfully created.
创建SPU实例......
创建PYU实例......
各方读取数据......
各方读取数据......完成
2023-03-21 15:42:04 INFO cleanup.py:84 [bob] --  Start check sending thread.
2023-03-21 15:42:04 INFO cleanup.py:90 [bob] --  Start check sending monitor thread.
拼接展示：
开始计算平均值......
(_run pid=40183) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
(_run pid=40183) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=40183) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(_run pid=40183) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(_run pid=40183) INFO:jax._src.lib.xla_bridge:Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(_run pid=40183) WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(scheduler +18s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(scheduler +18s) Error: No available node types can fulfill resource request {'alice': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(SPURuntime pid=40182) 2023-03-21 15:42:40,685  ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=40182, ip=10.33.3.150, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fce4b204520>)
(SPURuntime pid=40182)   File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
(SPURuntime pid=40182)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=40182) RuntimeError: what: 
(SPURuntime pid=40182)  [external/yacl/yacl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=0
(SPURuntime pid=40182) stacktrace: 
(SPURuntime pid=40182) #0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fce5b213519
(SPURuntime pid=40182) #1 pybind11::cpp_function::dispatcher()+0x7fce5b1fdc5b
(SPURuntime pid=40182) #2 PyCFunction_Call+0x4dfd82
2023-03-21 15:42:40 WARNING cleanup.py:59 [bob] --  Failed to send ObjectRef(2d7eabecf2886b9afae377374f826dddca091b3a1b00000001000000) with error: ray::SendProxyActor.send() (pid=40144, ip=10.33.3.150, repr=<fed.barriers.SendProxyActor object at 0x7fa3a41241f0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=40182, ip=10.33.3.150, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fce4b204520>)
  File "/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 278, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what: 
        [external/yacl/yacl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=0
stacktrace: 
#0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fce5b213519
#1 pybind11::cpp_function::dispatcher()+0x7fce5b1fdc5b
#2 PyCFunction_Call+0x4dfd82
2023-03-21 15:42:40 WARNING cleanup.py:61 [bob] --  Signal self to exit.
2023-03-21 15:42:40 INFO cleanup.py:65 [bob] --  Check sending thread was exited.
*** SIGTERM received at time=1679413360 on cpu 2 ***
PC: @     0x7fd05c52552d  (unknown)  syscall
    @     0x7fd05cf8fc20  2093708240  (unknown)
    @     0x7fd0312bdae7        240  ray::gcs::GlobalStateAccessor::AddWorkerInfo()
    @     0x7fd031214ae1        112  __pyx_pw_3ray_7_raylet_19GlobalStateAccessor_27add_worker_info()
    @           0x4e4f3d  (unknown)  method_vectorcall_O
    @     0x7fd031214a50  (unknown)  (unknown)
[2023-03-21 15:42:40,793 E 40023 40023] logging.cc:361: *** SIGTERM received at time=1679413360 on cpu 2 ***
[2023-03-21 15:42:40,793 E 40023 40023] logging.cc:361: PC: @     0x7fd05c52552d  (unknown)  syscall
[2023-03-21 15:42:40,794 E 40023 40023] logging.cc:361:     @     0x7fd05cf8fc20  2093708240  (unknown)
[2023-03-21 15:42:40,794 E 40023 40023] logging.cc:361:     @     0x7fd0312bdae7        240  ray::gcs::GlobalStateAccessor::AddWorkerInfo()
[2023-03-21 15:42:40,794 E 40023 40023] logging.cc:361:     @     0x7fd031214ae1        112  __pyx_pw_3ray_7_raylet_19GlobalStateAccessor_27add_worker_info()
[2023-03-21 15:42:40,794 E 40023 40023] logging.cc:361:     @           0x4e4f3d  (unknown)  method_vectorcall_O
[2023-03-21 15:42:40,803 E 40023 40023] logging.cc:361:     @     0x7fd031214a50  (unknown)  (unknown)
2023-03-21 15:42:40 INFO cleanup.py:102 [bob] --  Notify check sending thread to exit.
```

麻烦帮忙看看有什么问题，谢谢

**Comment by zhouaihui** [comment]
目前每个ray集群仅支持单节点，可以每个机构只用一台机器试试。

**Comment by Rui-learning** [comment]
使用一台机器已经调试成功，对于仅支持单节点存在以下几个问题：
1.单节点是指每个机构的集群中只能存在一个主节点的机器，不可以添加其他子节点么？还是说可以添加子节点，但是每次任务只能使用一台物理机作为计算节点完成计算？
2.是否支持程序和数据分别存储在不同的物理机中，通过ray集群将两台物理机联通后作为一个机构的集群来完成MPC计算任务？

**Comment by Chrisdehe** [comment]
单节点的问题您可以参考下这条 @[issue](https://github.com/secretflow/secretflow/issues/266)
希望可以帮助到您！

**Comment by Rui-learning** [comment]
好的明白了，还有个问题，就是：如果使用HEU，就可以在单个机构的ray集群中部署多个节点了，对么？

**Comment by miluoalbert** [comment]
@Rui-learning 现在是由于目前版本使用ray的方式导致只能单节点，使用HEU也还是会有这个限制

**Comment by likeIronic** [comment]
在一台服务器上进行单机仿真，也出现了同样的问题

**Comment by ian-huu** [comment]
请更新到最新版本，0.7.18b3 版本有一个调度的 bug 可能造成这个问题

**Comment by likeIronic** [comment]
> 请更新到最新版本，0.7.18b3 版本有一个调度的 bug 可能造成这个问题

在一台ubuntu 18.04 server进行单机仿真的时候，使用的secretflow 0。7.18不b3，也出现了同样的问题。请问你解决了嘛

**Comment by likeIronic** [comment]
> 请更新到最新版本，0.7.18b3 版本仿真模式有一个调度的 bug 可能造成问题

在一台ubuntu 18.04 server进行单机仿真的时候，使用的secretflow 0.7.18b3，也出现了同样的问题
