### ISSUE TITLE
使用spu运行jnp的函数demo报错

### ISSUE THREAD

**Issue by xiaoran33** [secretflow/secretflow#389]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.7.7b1

### OS Platform and Distribution

centos7

### Python version

3.8.13

### Reproduction code to reproduce the issue.

```shell
报错如下：
2023-03-27 14:02:06.513271: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
<secretflow.device.device.spu.SPUObject object at 0x7f744061d790>
(_run pid=8228) 2023-03-27 14:02:13.922217: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(_run pid=8225) 2023-03-27 14:02:13.938810: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=8498) 2023-03-27 14:02:14.829576: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=8497) 2023-03-27 14:02:14.768723: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(_run pid=8225) 2023-03-27 14:02:16,527,527 WARNING [xla_bridge.py:backends:265] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(_run pid=8228) 2023-03-27 14:02:16,494,494 WARNING [xla_bridge.py:backends:265] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(SPURuntime pid=8498) I0327 14:02:17.392686  8498 external/com_github_brpc_brpc/src/brpc/server.cpp:1066] Server[yasl::link::internal::ReceiverServiceImpl] is serving on port=45354.
(SPURuntime pid=8498) I0327 14:02:17.392877  8498 external/com_github_brpc_brpc/src/brpc/server.cpp:1069] Check out http://localhost.localdomain:45354 in web browser.
(SPURuntime pid=8497) I0327 14:02:17.330066  8497 external/com_github_brpc_brpc/src/brpc/server.cpp:1066] Server[yasl::link::internal::ReceiverServiceImpl] is serving on port=36058.
(SPURuntime pid=8497) I0327 14:02:17.330197  8497 external/com_github_brpc_brpc/src/brpc/server.cpp:1069] Check out http://localhost.localdomain:36058 in web browser.
(SPURuntime pid=8497) I0327 14:02:17.431322  8705 external/com_github_brpc_brpc/src/brpc/socket.cpp:2202] Checking Socket{id=0 addr=127.0.0.1:45354} (0x561bfb7c1b40)
(SPURuntime pid=8497) I0327 14:02:17.431571  8708 external/com_github_brpc_brpc/src/brpc/socket.cpp:2262] Revived Socket{id=0 addr=127.0.0.1:45354} (0x561bfb7c1b40) (Connectable)
(SPURuntime pid=8497) [2023-03-27 14:02:22.047] [info] [beaver_cheetah.cc:298] BeaverCheetah::Mul uses 4 modulus (36 bit each) for 64 bit ring
(SPURuntime pid=8498) [2023-03-27 14:02:22.047] [info] [beaver_cheetah.cc:298] BeaverCheetah::Mul uses 4 modulus (36 bit each) for 64 bit ring
(SPURuntime pid=8497) [2023-03-27 14:02:22.203] [info] [thread_pool.cc:30] Create a fixed thread pool with size 7
(SPURuntime pid=8498) [2023-03-27 14:02:22.200] [info] [thread_pool.cc:30] Create a fixed thread pool with size 7
Traceback (most recent call last):
  File "test-arr-secure-statistics.py", line 47, in <module>
    print(sf.reveal(single_output))
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/secretflow/device/driver.py", line 142, in reveal
    all_object = ray.get(all_object_refs)
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/ray/worker.py", line 1843, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.run() (pid=8497, ip=192.168.207.195, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f59943e8c40>)
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 260, in run
    self.runtime.run(executable)
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/spu/binding/api.py", line 45, in run
    return self._vm.Run(executable.SerializeToString())
RuntimeError: what: 
        [Enforce fail at spu/hal/constants.cc:72] v.storage_type().isa<mpc::Pub2kTy>(). got semi2k.BShr<FM64,1>
stacktrace: 
#0 spu::hal::test::dump_public_as<>()+0x7f5a0c2d52ad
#1 spu::device::getConditionValue()+0x7f5a0c2d6b98
#2 spu::device::pphlo::kernel::Sort<>()::{lambda()#1}::operator()()::{lambda()#2}::operator()()+0x7f5a0c2a5ec5
#3 std::__insertion_sort<>()+0x7f5a0c2a6216
#4 std::__stable_sort_adaptive<>()+0x7f5a0c2a6fca
#5 spu::device::pphlo::RegionExecutor::execute()+0x7f5a0c2a8423
#6 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c299100
#7 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c299526
#8 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c2997d6
#9 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c299a86
#10 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c299d36
#11 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c299fe6
#12 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c29a296
#13 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c29a546
#14 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c29a796
#15 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f5a0c29aa46
2023-03-27 14:02:22,683 ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=8498, ip=192.168.207.195, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f8b58f7ac40>)
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 260, in run
    self.runtime.run(executable)
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/spu/binding/api.py", line 45, in run
    return self._vm.Run(executable.SerializeToString())
RuntimeError: what: 
        [Enforce fail at spu/hal/constants.cc:72] v.storage_type().isa<mpc::Pub2kTy>(). got semi2k.BShr<FM64,1>
stacktrace: 
#0 spu::hal::test::dump_public_as<>()+0x7f8bc90b42ad
#1 spu::device::getConditionValue()+0x7f8bc90b5b98
#2 spu::device::pphlo::kernel::Sort<>()::{lambda()#1}::operator()()::{lambda()#2}::operator()()+0x7f8bc9084ec5
#3 std::__insertion_sort<>()+0x7f8bc9085216
#4 std::__stable_sort_adaptive<>()+0x7f8bc9085fca
#5 spu::device::pphlo::RegionExecutor::execute()+0x7f8bc9087423
#6 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc9078100
#7 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc9078526
#8 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc90787d6
#9 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc9078a86
#10 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc9078d36
#11 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc9078fe6
#12 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc9079296
#13 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc9079546
#14 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc9079796
#15 spu::device::pphlo::RegionExecutor::dispatchOp<>()+0x7f8bc9079a46

请教一下这个是报错怎么解决呢？
```

**Comment by anakinxc** [comment]
[duplicated issue](https://github.com/secretflow/spu/issues/31) already fixed in SPU recent releases, will be resolved with next SecretFlow release.

**Comment by xiaoran33** [comment]
可以告知具体在哪个版本吗？

**Comment by anakinxc** [comment]
> 可以告知具体在哪个版本吗？

现在只是在 SPU 的 pre-release 里，如果你想 build from source 的话可以用 spu 的 head，但是整合到 SecretFlow 可能会有兼容性问题

建议等下一个 SecretFlow 更新

**Comment by anakinxc** [comment]
Fixed via #395
