### ISSUE TITLE
error occur when running the demo on different dataset 

### ISSUE THREAD

**Issue by adan1324** [secretflow/secretflow#39]
### Issue Type

Bug

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
But I used my own dataset which is much larger to run the demo，the following error occurred. 

2022-07-14 09:14:38,001	WARNING worker.py:1416 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff86b5b6b3ddbc49317ecc0c5801000000 Worker ID: 5e383a84459651f44846404f76675b3a8dd9e9ac626ff4e286e39455 Node ID: e0f67ccadcf8945daacf7665de1242222467fc5e633957d4a381300d Worker IP address: 172.17.0.2 Worker port: 41807 Worker PID: 10310
Traceback (most recent call last):
  File "jax_fk.py", line 178, in <module>
    params = sf.reveal(params_spu)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/driver.py", line 158, in reveal
    value_obj = ray.get(value_ref)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/worker.py", line 1845, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: SPURuntime
	actor_id: 86b5b6b3ddbc49317ecc0c5801000000
	pid: 10310
	namespace: 3b837c97-994a-4894-bdbc-f3e070b54a9e
	ip: 172.17.0.2
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR_EXIT
(SPURuntime pid=10311) I0714 09:14:38.084491 10471 external/com_github_brpc_brpc/src/brpc/socket.cpp:2202] Checking Socket{id=0 addr=127.0.0.1:36067} (0x563ea08fe600)

The url of demo is https://secretflow.readthedocs.io/en/latest/tutorial/nn_with_spu.html.
The dataset's info :
x1 is : [[0.00291545 0.1        0.         ... 0.         0.41176471 0.7852172 ]
 [0.00291545 0.1        0.         ... 0.         0.41176471 0.7852172 ]
 [0.00291545 0.1        0.00980392 ... 0.         0.41176471 1.        ]
 ...
 [0.         0.         0.         ... 0.         0.41176471 0.7852172 ]
 [0.         0.         0.         ... 0.         0.41176471 0.5       ]
 [0.0058309  0.1        0.01960784 ... 0.         0.41176471 0.7852172 ]]
x1 type : <class 'numpy.ndarray'>
x1 dtype : float64
x1 shape : (106501, 400)
```

### Reproduction code to reproduce the issue.

```shell
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import time
from jax.example_libraries import stax
from jax.example_libraries.stax import (
    Dense,
    Relu,
    Softplus,
    Dropout,
    Sigmoid,
)

import jax
import jax.numpy as jnp
from jax.example_libraries import optimizers, stax


def load_fk_dataset(party_id) -> (np.ndarray, np.ndarray):
    if party_id == 1:
        data = pd.read_csv("./data/train_fk_cu.csv")
        features = data.drop(["example_id"], axis=1)
        return features.to_numpy(), None
    else:
        data = pd.read_csv("./data/train_fk_jd.csv")
        labels = data["label"]
        features = data.drop(["label", "example_id"], axis=1)
        return features.to_numpy(), labels.to_numpy()
    
    
def load_train_dataset(party_id=None) -> (np.ndarray, np.ndarray):
    features, label = load_breast_cancer(return_X_y=True)
    scaler = StandardScaler()
    features = scaler.fit_transform(features)
    X_train, _, y_train, _ = train_test_split(
        features, label, test_size=0.8, random_state=42
    )

    if party_id:
        if party_id == 1:
            return X_train[:, 15:], _
        else:
            return X_train[:, :15], y_train
    else:
        return X_train, y_train

def load_test_dataset():
    features, label = load_breast_cancer(return_X_y=True)
    scaler = StandardScaler()
    features = scaler.fit_transform(features)
    _, X_test, _, y_test = train_test_split(
        features, label, test_size=0.8, random_state=42
    )
    return X_test, y_test


def MLP():
    nn_init, nn_apply = stax.serial(
        Dense(128*2),
        Relu,
        Dense(710),
        Relu,
        Dense(400),
        Relu,
        Dense(100),
        Softplus,
        Dense(50),
        Softplus,
        Dense(1),
        Sigmoid, 
    )

    return nn_init, nn_apply


KEY = jax.random.PRNGKey(0)
INPUT_SHAPE = (-1,731)

def init_state(learning_rate):
    init_fun, _ = MLP()
    _, params_init = init_fun(KEY, INPUT_SHAPE)
    opt_init, _, _ = optimizers.sgd(learning_rate)
    opt_state = opt_init(params_init)
    return opt_state

def train(
    train_x1,
    train_x2,
    train_y,
    opt_state,
    learning_rate,
    epochs,
    batch_size,
):
    train_x = jnp.concatenate([train_x1, train_x2], axis=1)

    _, predict_fun = MLP()
    _, opt_update, get_params = optimizers.sgd(learning_rate)

    def update_model(state, imgs, labels, i):
        def mse(y, pred):
            return jnp.mean(jnp.multiply(y - pred, y - pred) / 2.0)

        def loss_func(params):
            y = predict_fun(params, imgs)
            return mse(y, labels), y

        grad_fn = jax.value_and_grad(loss_func, has_aux=True)
        (loss, y), grads = grad_fn(get_params(state))
        return opt_update(i, grads, state)
    import time
    for i in range(1, epochs + 1):
        begin =time.time()
        imgs_batchs = jnp.array_split(train_x, len(train_x) / batch_size, axis=0)
        labels_batchs = jnp.array_split(train_y, len(train_y) / batch_size, axis=0)

        for batch_idx, (batch_images, batch_labels) in enumerate(
            zip(imgs_batchs, labels_batchs)
        ):
            opt_state = update_model(opt_state, batch_images, batch_labels, i)
        end = time.time()
        print("epoch-{} cost time:{} s".format(i, end - begin))
    return get_params(opt_state)
from sklearn.metrics import roc_auc_score


def validate_model(params, X_test, y_test):
    _, predict_fun = MLP()
    y_pred = predict_fun(params, X_test)
    return roc_auc_score(y_test, y_pred)

if __name__ == "__main__":
    import jax

    # Load the data
    x1, _ = load_fk_dataset(party_id=1)
    print("x1 is :", x1)
    print("x1 type :", type(x1))
    print("x1 dtype :", x1.dtype)
    print("x1 shape :", x1.shape)
    x2, y = load_fk_dataset(party_id=2)


    # Hyperparameter
    batch_size = 100
    epochs = 10
    learning_rate = 0.1


    # Load the data
    import secretflow as sf

    # In case you have a running secretflow runtime already.
    sf.shutdown()

    sf.init(['alice', 'bob'], num_cpus=16, log_to_driver=True)

    alice, bob = sf.PYU('alice'), sf.PYU('bob')
    spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

    x1, _ = alice(load_fk_dataset)(party_id=1)
    x2, y = bob(load_fk_dataset)(party_id=2)


    device = spu
    x1_, x2_, y_ = x1.to(device), x2.to(device), y.to(device)
    init_params_ = sf.to(spu, lambda: init_state(learning_rate))
    begin = time.time()
    params_spu = spu(train, static_argnames=['learning_rate', 'epochs', 'batch_size'])(
        x1_, x2_, y_,init_params_, learning_rate=learning_rate, epochs=epochs, batch_size=batch_size
    )

    params = sf.reveal(params_spu)
    print("train cost time:",time.time() - begin)
    # print(params)
    X_test, y_test = load_test_dataset()
    auc = validate_model(params, X_test, y_test)
    print(f'auc={auc}')
```

**Comment by 6fj** [comment]
Could you please provide hardware specifications, e.g cpu info and memory size?

**Comment by adan1324** [comment]
The demo run inside the container ,cpu is 6C, Memory is 8G

**Comment by adan1324** [comment]
> Could you please provide hardware specifications, e.g cpu info and memory size?

The demo run inside the container ,cpu is 6C, Memory is 8G

**Comment by 6fj** [comment]
Hi @adan1324,

Since you have provided a much larger dataset according to your description, 6c8g may not be suitable for your application. And according to https://secretflow.readthedocs.io/en/latest/getting_started/install.html#environment, 8c16g is the minimum requirements.

Could you please switch to another machine with larger memory?

Thanks.

**Comment by adan1324** [comment]
I think you are right , it is the lack of resources that causes the error to occur, but after I use the 8C16G machine, there will still be a similar problem, so I would like to consult the relationship between data and memory, currently my data is 1.2G (600M+600M)

**Comment by rivertalk** [comment]
Hi @adan1324 

Thanks for the detailed information!

In general, the memory used by the SPU will be much higher than that of the CPU.  The main reason is that the SPU will calculate on encrypted data, and the cipher-text itself occupies more memory. When encountering nonlinear functions, the peak memory consumption will be more obvious.

For now, could you please test with a smaller dataset. We will do some memory optimizations in the future, perhaps to support larger datasets.

**Comment by adan1324** [comment]
> Hi @adan1324
> 
> Thanks for the detailed information!
> 
> In general, the memory used by the SPU will be much higher than that of the CPU. The main reason is that the SPU will calculate on encrypted data, and the cipher-text itself occupies more memory. When encountering nonlinear functions, the peak memory consumption will be more obvious.
> 
> For now, could you please test with a smaller dataset. We will do some memory optimizations in the future, perhaps to support larger datasets.

Thanks for your answer, I am trying to test with a smaller dataset on the SPU. I have a question, the model built with jax runs on the SPU, the SPU is using the ABY3 protocol by default?  I will be very grateful for your answer.

**Comment by 6fj** [comment]
The default protocol depends on number of parties:
1. If SPU device is 2PC, SEMI2K will be used.
2. If SPU device is 3PC, ABY3 will be used.

**Comment by adan1324** [comment]
In the demo [Neural Network with SPU](https://secretflow.readthedocs.io/en/latest/tutorial/nn_with_spu.html), Alice and Bob own the data, In this case, whether there are three calculate participants: Alice/Bob/SPU,like this [image](https://spu.readthedocs.io/en/beta/_images/outsourcing.svg)

**Comment by 6fj** [comment]
Hi @adan1324 ,

**Comment by 6fj** [comment]
Hi @adan1324 ,

When you init a SPU device like:
```
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
```
You have to provide a list of nodes to constitute a SPU device for MPC computation, i.e. **['alice', 'bob']**, we use this list to indicate **parties** of a SPU device.

In the demo, SPU device is 2PC.

**Comment by adan1324** [comment]
Thank you very much for your help

**Comment by 6fj** [comment]
You are welcome, have a nice day!
