### ISSUE TITLE
集群环境垂直数据合并问题

### ISSUE THREAD

**Issue by nainai123** [secretflow/secretflow#416]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.0b1

### OS Platform and Distribution

linux

### Python version

3.8

### What happend and What you expected to happen.

```shell
集群模式下合并数据集 发生了错误，我的疑问是我在第二台机器读取数据集后为什么无法进行合并

Traceback (most recent call last):
  File "test.py", line 44, in <module>
    vdf  = h_read_csv({np1: x1, np2: x2})
  File "/usr/local/lib/python3.8/site-packages/secretflow/data/horizontal/io.py", line 53, in read_csv
    dtypes = part.dtypes
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/driver.py", line 130, in wrapper
    return reveal(func_or_object(*arg, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/secretflow/data/base.py", line 270, in dtypes
    return self.data.device(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 127, in wrapper
    sfd.remote(self._run)
  File "/usr/local/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 82, in _remote
    args, kwargs = _resolve_args(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 72, in _resolve_args
    actual_vals = ray.get(list(refs.values()))
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::_run() (pid=10940, ip=192.168.0.254)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 163, in _run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/data/io/util.py", line 59, in read_csv_wrapper
    return pd.read_csv(open(filepath), **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/site-packages/pandas/io/common.py", line 704, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/site-packages/pandas/io/common.py", line 1163, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
```

### Reproduction code to reproduce the issue.

```shell
import sys
import time
import logging

from absl import app
import spu
import secretflow as sf
import pandas as pd
from secretflow.data.horizontal import read_csv as h_read_csv
from secretflow.security.aggregation import SecureAggregator
from secretflow.security.compare import SPUComparator

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# SPU settings
cluster_def = {
    'nodes': [
        {'party': 'np1', 'id': 'np1', 'address': '192.168.0.111:12945', 'listen_address': '0.0.0.0:12945'},
        {'party': 'np2', 'id': 'np2', 'address': '192.168.0.111:12946', 'listen_address': '0.0.0.0:12946'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}

def get_data(path):
    data = pd.read_csv(path,encoding='utf-8')
    return data



sf.init(['np1', 'np2'], address='192.168.0.111:9001')
np1 = sf.PYU('np1')
np2 = sf.PYU('np2')
spu = sf.SPU(cluster_def)

x1= np1(get_data)(path='/root/data/train1.csv')
x2= np2(get_data)(path='/root/data/train2.csv')

spu = sf.SPU(sf.utils.testing.cluster_def(parties=['np1', 'np2']))
comp = SPUComparator(spu)
vdf  = h_read_csv({np1: x1, np2: x2})

print(vdf.columns)
vdf_part = vdf[['HCO3-', 'ae_copd']]
print(vdf_part.mean(numeric_only=True))
```

**Comment by nainai123** [comment]
还有一个问题就是   是否所有的机器学习数据都要归一化？

**Comment by rivertalk** [comment]
![image](https://user-images.githubusercontent.com/103552262/230550184-78090ecb-9cbe-45b4-a4d2-5fccb326a6f1.png)
看上去你在 `get_data`里面已经 read_csv了，应该不需要重复`h_read_csv`

**Comment by rivertalk** [comment]
> 问题就是 是否所有的机器学习数据都要归

我理解不需要，还是算法case by case的，不过MPC算法一般建议先做数据归一化，原因是MPC底层原语对数字范围比较敏感

**Comment by nainai123** [comment]
> > 问题就是 是否所有的机器学习数据都要归
> 
> 我理解不需要，还是算法case by case的，不过MPC算法一般建议先做数据归一化，原因是MPC底层原语对数字范围比较敏感

谢谢   明白了

**Comment by nainai123** [comment]
> ![image](https://user-images.githubusercontent.com/103552262/230550184-78090ecb-9cbe-45b4-a4d2-5fccb326a6f1.png) 看上去你在 `get_data`里面已经 read_csv了，应该不需要重复`h_read_csv`

我已经找到了具体原因    谢谢你的回复    我在看看对应的API文档
