### ISSUE TITLE
secretflow.data.vertical.VDataFrame.drop 出现意外报错

### ISSUE THREAD

**Issue by Mingbo-Lee** [secretflow/secretflow#423]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.8.0b1

### OS Platform and Distribution

Linux Ubuntu 20.04.5 LTS

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
secretflow.data.vertical.VDataFrame.drop删除指定列数据报错
```

### Reproduction code to reproduce the issue.

```shell
step 1:
从 https://www.kaggle.com/datasets/erdemtaha/cancer-data 处下载数据，得到Cancer_Data_a.csv
step 2:
对数据进行预处理，完成数据的划分


```
预处理代码如下

# data preprocess
import pandas as pd
cancer_data_path = './Cancer_Data.csv'
cancer_data = pd.read_csv(cancer_data_path)
# get columns
columns_name = cancer_data.columns
# split columns of data
print(len(columns_name))
party_a_columns_names = columns_name[:int(len(columns_name)/2)]
party_b_columns_names = columns_name[int(len(columns_name)/2):]
print(party_a_columns_names)
print(len(party_a_columns_names))
print(party_b_columns_names)
print(len(party_b_columns_names))
#split date
party_a_data = cancer_data[party_a_columns_names]
party_b_data = cancer_data[party_b_columns_names]
print(party_a_data.shape)
print(party_b_data.shape)
# save to csv
party_a_data.to_csv('./Cancer_Data_a.csv', index=False)
party_b_data.to_csv('./Cancer_Data_b.csv', index=False)
```
step 3:
对数据分别进行pandas和secretflow的drop操作
代码如下
```python
import pandas as pd
import secretflow as sf
sf.shutdown()
sf.init(['alice', 'bob'], address='local')
alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
import os
from secretflow.data.vertical import read_csv
v_alice_path = './Cancer_Data_a.csv'
v_bob_path = './Cancer_Data_b.csv'
v_df = read_csv({alice: v_alice_path, bob: v_bob_path})

pd_aclice_df = pd.read_csv('./Cancer_Data_a.csv')
print("before delete 'diagnosis' in pd_aclice_df.columns:",'diagnosis' in pd_aclice_df.columns)
# drop 'diagnosis' in pandas
pd_aclice_data = pd_aclice_df.drop('diagnosis',axis=1)
print("after delete 'diagnosis' in pd_aclice_df.columns:",'diagnosis' in pd_aclice_df.columns)
print("after delete 'diagnosis' in pd_aclice_data.columns:",'diagnosis' in pd_aclice_data.columns)
print("'diagnosis' in v_df.columns:",'diagnosis' in v_df.columns)
# drop 'diagnosis' in secretflow
data = v_df.drop('diagnosis',axis=1)
```
获得输出和报错，内容如下：
```bash
/opt/anaconda3/envs/limingbo_sf/bin/python /home/limingbo/sf/src/cancer_data_split.py 
INFO:root:Run secretflow in simulation mode.
2023-04-09 16:48:52,146	INFO worker.py:1538 -- Started a local Ray instance.
(pid=159524) 
(pid=159528) 
before delete 'diagnosis' in pd_aclice_df.columns: True
after delete 'diagnosis' in pd_aclice_df.columns: True
after delete 'diagnosis' in pd_aclice_data.columns: False
'diagnosis' in v_df.columns: True
(SPURuntime pid=162323) 2023-04-09 16:48:57.550 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=127.0.0.1:42083} (0x0x552bb00): Connection refused [R1][E112]Not connected to 127.0.0.1:42083 yet, server_id=0 [R2][E112]Not connected to 127.0.0.1:42083 yet, server_id=0 [R3][E112]Not connected to 127.0.0.1:42083 yet, server_id=0
2023-04-09 16:48:59,420	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_run() (pid=159943, ip=10.24.93.13)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 163, in _run
    return fn(*args, **kwargs)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['diagnosis'] not in index"
Traceback (most recent call last):
  File "/home/limingbo/sf/src/cancer_data_split.py", line 38, in <module>
    data = v_df.drop('diagnosis',axis=1)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/data/vertical/dataframe.py", line 502, in drop
    return self.__part_apply(
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/data/vertical/dataframe.py", line 111, in __part_apply
    {
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/data/vertical/dataframe.py", line 112, in <dictcomp>
    pyu: fn(part, *args, **kwargs)[part.columns]
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/data/base.py", line 443, in __getitem__
    return self.__partition_wrapper(pd.DataFrame.__getitem__, item_list)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/data/base.py", line 72, in __partition_wrapper
    return Partition(self.data.device(fn)(self.data, *args, **kwargs))
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 127, in wrapper
    sfd.remote(self._run)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 82, in _remote
    args, kwargs = _resolve_args(*args, **kwargs)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 72, in _resolve_args
    actual_vals = ray.get(list(refs.values()))
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): ray::_run() (pid=159578, ip=10.24.93.13)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 163, in _run
    return fn(*args, **kwargs)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/secretflow/data/base.py", line 329, in _drop
    return df.drop(**kwargs)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/pandas/core/frame.py", line 5399, in drop
    return super().drop(
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/pandas/core/generic.py", line 4505, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/pandas/core/generic.py", line 4546, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6934, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['diagnosis'] not found in axis"

进程已结束,退出代码1

```
```
```

**Comment by zhouaihui** [comment]
正确用法是v_df.drop(columns='diagnosis')。drop的第一个参数默认是label，而 diagnosis 是列，使用columns应该更合理。

**Comment by Mingbo-Lee** [comment]
非常感谢！ @zhouaihui 但是此处应该封装成与pandas的dataframe 操作逻辑完全相同：
>This dataframe is design to provide a federated pandas dataframe and just same as using pandas. 

ref: https://www.secretflow.org.cn/docs/secretflow/zh_CN/source/secretflow.data.vertical.html#secretflow.data.vertical.VDataFrame.drop
可以使得大家的学习成本更低
我也被这句话给误导了而没有仔细看文档了

**Comment by zhouaihui** [comment]
感谢这个建议。
因为这个是直接针对column操作，使用`columns=`应该是更直观的用法， 虽然`index=, axis=1`等价于columns，但是这种用法挺奇怪的，SecretFlow没有支持这种写法。

**Comment by Mingbo-Lee** [comment]
好的
