### ISSUE TITLE
导入secretflow.ml.boost.sgb_v报错 

### ISSUE THREAD

**Issue by Mingbo-Lee** [secretflow/secretflow#428]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.8.0b1

### OS Platform and Distribution

Linux Ubuntu 20.04.5 LTS

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
隐语最近发布了隐语纵向联邦 SecureBoost Benchmark白皮书：https://mp.weixin.qq.com/s/PzINyHrNf4ENk63WUCmUlA，我想尝试这个算法，但是我在最新的0.8.0b1版本中进行调用，出现报错。
我想问一下：目前是算法还没有包含在0.8.0b1版本中，需要自行基于最新的源代码构建安装包或者等到后期发布新的版本才能尝试吗？
```

### Reproduction code to reproduce the issue.

```shell
from secretflow.ml.boost.sgb_v import Sgb

报错

Traceback (most recent call last):
  File "/opt/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1b181f82f320>", line 1, in <module>
    from secretflow.ml.boost.sgb_v import Sgb
```
```

**Comment by anakinxc** [comment]
sgb 在 >= 0.8.1b0 的版本里，麻烦更新一下

**Comment by Mingbo-Lee** [comment]
好的，非常感谢！ @anakinxc
