### ISSUE TITLE
能不能离线安装？

### ISSUE THREAD

**Issue by cookiejoo** [secretflow/secretflow#454]
### Issue Type

Others

### Source

source

### Secretflow Version

0.8

### OS Platform and Distribution

Linux

### Python version

3.10

### What happend and What you expected to happen.

```shell
我用源码安装提示报错无法连接外部的url，我看setup.py有趣调用github的地址，由于内网机器不给外网权限，这个怎么解决？
```

### Reproduction code to reproduce the issue.

```shell
WARNING: The wheel package is not available.
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Location '--extra-index-url https://download.pytorch.org/whl/cpu' is ignored: it is either a non-existing path or lacks a specific scheme.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/protobuf-distutils/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/protobuf-distutils/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/protobuf-distutils/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/protobuf-distutils/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/protobuf-distutils/
ERROR: Could not find a version that satisfies the requirement protobuf_distutils (from versions: none)
ERROR: No matching distribution found for protobuf_distutils
```

**Comment by cookiejoo** [comment]
> hi，@cookiejoo 离线我建议您使用docker来解决 通过其他机器下载好docker镜像，使用docker save命令导出为一个tar.gz文件后scp到离线的机器中，使用docker load进行镜像导入。

我申请了权限，现在安装也报错
pip install -U secretflow --trusted-host mirrors.aliyun.com
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Collecting secretflow
  Using cached http://mirrors.aliyun.com/pypi/packages/3c/d6/90e65201b1dbcf357de5ce233117da0cde9ed1612c0a5e05148de84467cd/secretflow-0.7.7b0.tar.gz (163 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/usr/local/python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-h8e3xelq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-h8e3xelq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-h8e3xelq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-h8e3xelq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 100, in <module>
        File "<string>", line 17, in read_requirements
      FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Chrisdehe** [comment]
辛苦贴下你的gcc跟cmake版本

**Comment by anakinxc** [comment]
Hi @cookiejoo 

请问您是需要 build from source 吗

**Comment by cookiejoo** [comment]
我用build from source也不行，用pip install -U secretflow也不行。现在换Docker方式安装看看

**Comment by anakinxc** [comment]
Hi @cookiejoo 

如果要一次性安全的话可能下载[这个](https://hub.docker.com/r/secretflow/secretflow-anolis8)镜像是最方便的

**Comment by zhouaihui** [comment]
建议检查下是否满足[安装要求](https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/installation.html#environment)
