### ISSUE TITLE
集群模式下，隐私求交发生数据读取错误

### ISSUE THREAD

**Issue by Yaru6210** [secretflow/secretflow#459]
### Issue Type

Bug

### Source

binary

### Secretflow Version

最新版

### OS Platform and Distribution

anolis

### Python version

3.8

### What happend and What you expected to happen.

```shell
执行隐私求交任务，csv读取报错
---------------------------------------------------------------------------
RayTaskError(RuntimeError)                Traceback (most recent call last)
Cell In[93], line 3
      1 input_path = {alice: './FraudCall_alice/data/train_a_processed.csv', bob: './FraudCall_bob/data/train_b_processed.csv'}
      2 output_path = {alice: './FraudCall_alice/data/psi_train_A.csv', bob: './FraudCall_bob/data/psi_train_B.csv'}
----> 3 spu.psi_csv('row_num', input_path, output_path, 'alice')

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py:1426, in SPU.psi_csv(self, key, input_path, output_path, receiver, protocol, precheck_input, sort, broadcast_result, bucket_size, curve_type, preprocess_path, ecdh_secret_key_path, dppsi_bob_sub_sampling, dppsi_epsilon)
   1381 def psi_csv(
   1382     self,
   1383     key: Union[str, List[str], Dict[Device, List[str]]],
   (...)
   1396     dppsi_epsilon=3,
   1397 ):
   1398     """Private set intersection with csv file.
   1399 
   1400     Args:
   (...)
   1423         List[Dict]: PSI reports output by SPU with order reserved.
   1424     """
-> 1426     return dispatch(
   1427         'psi_csv',
   1428         self,
   1429         key,
   1430         input_path,
   1431         output_path,
   1432         receiver,
   1433         protocol,
   1434         precheck_input,
   1435         sort,
   1436         broadcast_result,
   1437         bucket_size,
   1438         curve_type,
   1439         preprocess_path,
   1440         ecdh_secret_key_path,
   1441         dppsi_bob_sub_sampling,
   1442         dppsi_epsilon,
   1443     )

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/register.py:111, in dispatch(name, self, *args, **kwargs)
    101 def dispatch(name: str, self, *args, **kwargs):
    102     """Dispatch device kernel.
    103 
    104     Args:
   (...)
    109         Kernel execution result.
    110     """
--> 111     return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/register.py:80, in Registrar.dispatch(self, device_type, name, *args, **kwargs)
     78 if name not in self._ops[device_type]:
     79     raise KeyError(f'device: {device_type}, op: {name} not registered')
---> 80 return self._ops[device_type][name](*args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/kernels/spu.py:300, in psi_csv(device, key, input_path, output_path, receiver, protocol, precheck_input, sort, broadcast_result, bucket_size, curve_type, preprocess_path, ecdh_secret_key_path, dppsi_bob_sub_sampling, dppsi_epsilon)
    280         res.append(
    281             actor.psi_csv.remote(
    282                 k,
   (...)
    296             )
    297         )
    299 # wait for all tasks done
--> 300 return sfd.get(res)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py:75, in get(object_refs)
     73     return fed.get(object_refs)
     74 else:
---> 75     return ray.get(object_refs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
   2307     worker.core_worker.dump_object_store_memory_usage()
   2308 if isinstance(value, RayTaskError):
-> 2309     raise value.as_instanceof_cause()
   2310 else:
   2311     raise value

RayTaskError(RuntimeError): ray::SPURuntime.psi_csv() (pid=1823293, ip=172.25.143.241, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe01e016c70>)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 697, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/spu/psi.py", line 48, in bucket_psi
    report_str = libspu.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
	[external/yacl/yacl/io/rw/csv_reader.cc:398] Input CSV file format error: Line#9609 fields size '6' != header's size '106'
stacktrace: 
#0 spu::psi::CsvChecker::CsvChecker()+0x7fe02a29ff58
#1 std::__future_base::_Task_setter<>::operator()()+0x7fe02a26f360
#2 std::__future_base::_State_baseV2::_M_do_set()+0x7fe02989c6ee
#3 __pthread_once_slow+0x7fe9b980fe57
(SPURuntime pid=946121) 2023-04-20 14:24:58.893 [info] [bucket_psi.cc:Run:115] End sanity check for input file: ./FraudCall_alice/data/train_a_processed.csv, size=39143
2023-04-20 14:27:04,224	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.psi_csv() (pid=946121, ip=172.25.143.242, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f4499cf2c40>)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 697, in psi_csv
    report = psi.bucket_psi(self.link, config, ic_mode)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/spu/psi.py", line 48, in bucket_psi
    report_str = libspu.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
	[external/yacl/yacl/link/transport/channel.cc:117] Get data timeout, key=root:4:ALLGATHER
stacktrace: 
#0 yacl::link::Context::RecvInternal()+0x7f44a60e2c17
#1 yacl::link::AllGatherImpl<>()+0x7f44a60dd9d5
#2 yacl::link::AllGather()+0x7f44a60ddd83
#3 spu::psi::BucketPsi::Run()+0x7f44a5f2be99
#4 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f44a4e4a608
#5 pybind11::cpp_function::dispatcher()+0x7f44a4e257d6
#6 PyCFunction_Call+0x4f5652
```

### Reproduction code to reproduce the issue.

```shell
input_path = {alice: './FraudCall_alice/data/train_a_processed.csv', bob: './FraudCall_bob/data/train_b_processed.csv'}
output_path = {alice: './FraudCall_alice/data/psi_train_A.csv', bob: './FraudCall_bob/data/psi_train_B.csv'}
spu.psi_csv('row_num', input_path, output_path, 'alice')
```

**Comment by zhanglei486** [comment]
![image](https://user-images.githubusercontent.com/47308800/233286851-95bd1ef0-2d01-4412-8eae-3095cf814c72.png)
根据报错信息，建议检查Line#9609行的数据是否和csv头部的列名数量匹配

**Comment by Yaru6210** [comment]
已检查过，数据集无缺失值，9609行的数据和csv头部的列名数量一致，均为101列

**Comment by Chrisdehe** [comment]
如果数据不隐私的情况下，辛苦将数据都上传下，我们帮您再检查一次。

**Comment by Yaru6210** [comment]
[datasets.zip](https://github.com/secretflow/secretflow/files/11283458/datasets.zip)

**Comment by zhanglei486** [comment]
用上面数据和提供的调用代码，调用psi_csv能正常运行
建议把input_path和output_path换成绝对路径试一下，可能是相对路径读取的文件并不是期望的文件

**Comment by zhanglei486** [comment]
2023-04-20 07:47:05,189	WARNING services.py:1732 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-04-20 07:47:05,341	INFO worker.py:1538 -- Started a local Ray instance.
(SPURuntime pid=52632) 2023-04-20 07:47:09.991 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=127.0.0.1:17269} (0x0x3c91100): Connection refused [R1][E112]Not connected to 127.0.0.1:17269 yet, server_id=0 [R2][E112]Not connected to 127.0.0.1:17269 yet, server_id=0 [R3][E112]Not connected to 127.0.0.1:17269 yet, server_id=0
(SPURuntime pid=52635) 2023-04-20 07:47:10.999 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
(SPURuntime pid=52635) 2023-04-20 07:47:10.999 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: /home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939/train_b_processed.csv, precheck_switch:true
(SPURuntime pid=52632) 2023-04-20 07:47:10.999 [info] [bucket_psi.cc:Init:228] bucket size set to 1048576
(SPURuntime pid=52632) 2023-04-20 07:47:10.999 [info] [bucket_psi.cc:Run:97] Begin sanity check for input file: /home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939/train_a_processed.csv, precheck_switch:true
(SPURuntime pid=52635) 2023-04-20 07:47:11.132 [info] [csv_checker.cc:CsvChecker:121] Executing duplicated scripts: LC_ALL=C sort --buffer-size=1G --temporary-directory=/home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939 --stable selected-keys.1681976830999892926 | LC_ALL=C uniq -d > duplicate-keys.1681976830999892926
(SPURuntime pid=52632) 2023-04-20 07:47:11.125 [info] [csv_checker.cc:CsvChecker:121] Executing duplicated scripts: LC_ALL=C sort --buffer-size=1G --temporary-directory=/home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939 --stable selected-keys.1681976831000123648 | LC_ALL=C uniq -d > duplicate-keys.1681976831000123648
(SPURuntime pid=52635) 2023-04-20 07:47:11.521 [info] [bucket_psi.cc:Run:115] End sanity check for input file: /home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939/train_b_processed.csv, size=39143
(SPURuntime pid=52635) 2023-04-20 07:47:11.521 [info] [bucket_psi.cc:Run:133] Skip doing psi, because dataset has been aligned!
(SPURuntime pid=52635) 2023-04-20 07:47:11.522 [info] [bucket_psi.cc:Run:178] Begin post filtering, indices.size=39143, should_sort=true
(SPURuntime pid=52632) 2023-04-20 07:47:11.521 [info] [bucket_psi.cc:Run:115] End sanity check for input file: /home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939/train_a_processed.csv, size=39143
(SPURuntime pid=52632) 2023-04-20 07:47:11.521 [info] [bucket_psi.cc:Run:133] Skip doing psi, because dataset has been aligned!
(SPURuntime pid=52632) 2023-04-20 07:47:11.522 [info] [bucket_psi.cc:Run:178] Begin post filtering, indices.size=39143, should_sort=true
(SPURuntime pid=52635) 2023-04-20 07:47:11.571 [info] [utils.cc:MultiKeySort:88] Executing sort scripts: tail -n +2 /home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939/tmp-sort-in-1681976831523383461 | LC_ALL=C sort --buffer-size=3G --parallel=8 --temporary-directory=./ --stable --field-separator=, --key=103,103 >>/home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939/tmp-sort-out-1681976831523383461
(SPURuntime pid=52632) 2023-04-20 07:47:11.566 [info] [utils.cc:MultiKeySort:88] Executing sort scripts: tail -n +2 /home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939/tmp-sort-in-1681976831523496198 | LC_ALL=C sort --buffer-size=3G --parallel=8 --temporary-directory=./ --stable --field-separator=, --key=100,100 >>/home/admin/dev/psi/#U65b0#U5efa#U6587#U4ef6#U5939/tmp-sort-out-1681976831523496198
psi reports: [{'party': 'alice', 'original_count': 39143, 'intersection_count': 39143}, {'party': 'bob', 'original_count': 39143, 'intersection_count': 39143}]
I0420 07:47:11.789387 140693325252416 psi2.py:85] cost time: 3.850637197494507

**Comment by Yaru6210** [comment]
改为了绝对路径，依然报错
![image](https://user-images.githubusercontent.com/89012199/233311061-de64effb-4dda-4ac5-9a6c-a02f2b371b74.png)
![image](https://user-images.githubusercontent.com/89012199/233311206-bb67f115-2c85-410c-a961-2b1fd2063344.png)

**Comment by zhanglei486** [comment]
看报错是bob端的数据检查报错，重点检查一下bob端的数据
检查一下文件的sha256sum 是否和发给我们的一样

**Comment by Yaru6210** [comment]
已解决 重新上传了一下 感谢解答！！！
