### ISSUE TITLE
train_test_split  函数使用报错

### ISSUE THREAD

**Issue by nainai123** [secretflow/secretflow#462]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.0b1

### OS Platform and Distribution

linux

### Python version

3.8

### What happend and What you expected to happen.

```shell
在使用read_csv去读取两方数据后 对数据使用  train_test_split 数据分割 后报错
```

### Reproduction code to reproduce the issue.

```shell
import sys
import time
import logging

import spu
import secretflow as sf
from secretflow.device.driver import wait, reveal
from secretflow.data import FedNdarray, PartitionWay
from secretflow.ml.linear.ss_sgd import SSRegression
import pandas as pd

# SPU settings
cluster_def = {
    'nodes': [
        {'party': 'np1', 'id': 'np1', 'address': '127.0.0.1:12945'},
        {'party': 'np2', 'id': 'np2', 'address': '127.0.0.1:12946'},
        {'party': 'np3', 'id': 'np3', 'address': '127.0.0.1:12947'},
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}

sf.shutdown()
sf.init(['np1', 'np2', 'np3'], address="local", ignore_reinit_error=True,log_to_driver=True)

np1 = sf.PYU('np1')
np2 = sf.PYU('np2')
np3 = sf.PYU('np3')
spud = sf.SPU(cluster_def)
from secretflow.data.horizontal import read_csv as h_read_csv
from secretflow.security.aggregation import SecureAggregator
from secretflow.security.compare import SPUComparator

aggr = SecureAggregator(device=np3, participants=[np1, np2, np3])
comp = SPUComparator(spud)
hdf = h_read_csv({np1: '/root/data/train1.csv',
                  np2: '/root/data/train2.csv'},
                  aggregator=aggr,
                  comparator=comp)

from sklearn.model_selection import train_test_split
x_train,x_test =  train_test_split(hdf, test_size=0.2, random_state=42)

报错信息：
2023-04-21 01:44:43,699	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_run() (pid=573, ip=192.168.0.254)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 163, in _run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6130, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index([(329, 173, 272, 497, 182, 268, 352, 117, 393, 332, 456, 468, 356, 86, 438, 75, 452, 15, 210, 180, 397, 19, 505, 340, 56, 278, 446, 515, 154, 25, 265, 42, 312, 412, 457, 284, 126, 334, 31, 113, 255, 218, 416, 57, 396, 24, 17, 192, 66, 286, 422, 94, 311, 368, 23, 271, 299, 373, 5, 116, 45, 185, 16, 479, 367, 3, 234, 384, 60, 110, 409, 420, 29, 274, 302, 26, 7, 181, 467, 108, 37, 157, 483, 118, 114, 266, 175, 421, 349, 144, 380, 391, 211, 321, 496, 485, 141, 376, 67, 408, ...)], dtype='object')] are in the [columns]"
2023-04-21 01:44:43,704	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_run() (pid=566, ip=192.168.0.254)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 163, in _run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6130, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index([(329, 173, 272, 497, 182, 268, 352, 117, 393, 332, 456, 468, 356, 86, 438, 75, 452, 15, 210, 180, 397, 19, 505, 340, 56, 278, 446, 515, 154, 25, 265, 42, 312, 412, 457, 284, 126, 334, 31, 113, 255, 218, 416, 57, 396, 24, 17, 192, 66, 286, 422, 94, 311, 368, 23, 271, 299, 373, 5, 116, 45, 185, 16, 479, 367, 3, 234, 384, 60, 110, 409, 420, 29, 274, 302, 26, 7, 181, 467, 108, 37, 157, 483, 118, 114, 266, 175, 421, 349, 144, 380, 391, 211, 321, 496, 485, 141, 376, 67, 408, ...)], dtype='object')] are in the [columns]"
2023-04-21 01:44:44,700	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_run() (pid=573, ip=192.168.0.254)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 163, in _run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6130, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index([(304, 501, 441, 153, 503, 131, 204, 512, 325, 247, 507, 353, 289, 84, 10, 324, 78, 30, 184, 195, 222, 209, 281, 208, 124, 250, 76, 382, 342, 323, 244, 331, 140, 9, 72, 400, 489, 225, 73, 177, 403, 68, 155, 55, 405, 298, 77, 469, 317, 477, 90, 238, 487, 63, 504, 70, 2, 287, 341, 137, 249, 194, 172, 82, 454, 318, 33, 426, 227, 0, 11, 237, 22, 104, 296, 101, 79, 429, 431, 18, 176, 231, 508, 132, 39, 465, 46, 357, 277, 362, 93, 447, 203, 451, 148, 220, 69, 253, 398, 167, ...)], dtype='object')] are in the [columns]"
2023-04-21 01:44:44,705	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_run() (pid=568, ip=192.168.0.254)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 163, in _run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6130, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index([(304, 501, 441, 153, 503, 131, 204, 512, 325, 247, 507, 353, 289, 84, 10, 324, 78, 30, 184, 195, 222, 209, 281, 208, 124, 250, 76, 382, 342, 323, 244, 331, 140, 9, 72, 400, 489, 225, 73, 177, 403, 68, 155, 55, 405, 298, 77, 469, 317, 477, 90, 238, 487, 63, 504, 70, 2, 287, 341, 137, 249, 194, 172, 82, 454, 318, 33, 426, 227, 0, 11, 237, 22, 104, 296, 101, 79, 429, 431, 18, 176, 231, 508, 132, 39, 465, 46, 357, 277, 362, 93, 447, 203, 451, 148, 220, 69, 253, 398, 167, ...)], dtype='object')] are in the [columns]"
```

**Comment by magic-hya** [comment]
h_read_csv读取出来的不是一个单纯的数据，直接用sklearn的api应该处理不了的，要用sf的内部api

**Comment by zhangxingmeng** [comment]
![image](https://user-images.githubusercontent.com/103552200/233533037-b49555be-0065-4449-ae27-37e147df852f.png)
因为我们这边是HDataFrame所以没有办法用sklearn的train_test_split
请使用`from secretflow.data.split import train_test_split`

**Comment by zhangxingmeng** [comment]
![image](https://user-images.githubusercontent.com/103552200/233555234-7e918337-ee04-4546-8bf1-fcd18334b3d8.png)
这两个要对应起来使用，这个点是和明文一样的。2分类和多分类的metric不能混用

**Comment by nainai123** [comment]
> 
hdf.columns
Index(['肺结核', 'mMRC评分', '吸入药物种类', '气促-症状', '舒张前FEV1/FVC%', '舒张后FVC',
       '舒张后FEV1/FVC%', 'FVC舒张后/预计', 'FEV 1舒张后/预计', 'HCO3-', 'ae_copd'],
      dtype='object')

SFXgboost 模型当columns为以上名称时训练报错：
报错信息如下：

RayTaskError(ValueError)                  Traceback (most recent call last)
Cell In[31], line 1
----> 1 bst.train(x_train, x_test, params=params, num_boost_round=6)

File /usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/homo_booster.py:190, in SFXgboost.train(self, train_hdf, valid_hdf, params, num_boost_round, obj, feval, maximize, early_stopping_rounds, evals_result, verbose_eval, xgb_model, callbacks)
    170         mock_df = worker.gen_mock_data(
    171             data_num=100,
    172             columns=columns,
    173             label_name=params["label_key"],
    174             num_class=num_class,
    175         )
    176         self.fed_bst[worker.device] = worker.homo_train(
    177             train_hdf=mock_df,
    178             valid_hdf=mock_df,
   (...)
    188             callbacks=callbacks,
    189         )
--> 190 reveal(self.fed_bst)

File /usr/local/lib/python3.8/site-packages/secretflow/device/driver.py:153, in reveal(func_or_object, heu_encoder)
    150         all_object_refs.extend(x.device.outfeed_shares(x.shares_name))
    152 cur_idx = 0
--> 153 all_object = sfd.get(all_object_refs)
    155 new_flatten_val = []
    156 for x in flatten_val:

File /usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py:49, in get(object_refs)
     47     return fed.get(object_refs)
     48 else:
---> 49     return ray.get(object_refs)

File /usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File /usr/local/lib/python3.8/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
   2307     worker.core_worker.dump_object_store_memory_usage()
   2308 if isinstance(value, RayTaskError):
-> 2309     raise value.as_instanceof_cause()
   2310 else:
   2311     raise value

RayTaskError(ValueError): ray::HomoBooster.homo_train() (pid=10925, ip=192.168.0.254, repr=<secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster object at 0x7efaf75a00d0>)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/homo_booster_worker.py", line 145, in homo_train
    self.bst = train(
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 224, in train
    bst = _train_internal(
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 155, in _train_internal
    if callbacks.after_iteration(bst, i, dtrain, evals):
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/callback.py", line 76, in after_iteration
    score = model.eval_set(evals, epoch, self.metric)
  File "/usr/local/lib/python3.8/site-packages/xgboost/core.py", line 1739, in eval_set
    self._validate_features(d[0])
  File "/usr/local/lib/python3.8/site-packages/xgboost/core.py", line 2485, in _validate_features
    raise ValueError(msg.format(self.feature_names, data.feature_names))
ValueError: feature_names mismatch: ['\\u80ba\\u7ed3\\u6838', 'mMRC\\u8bc4\\u5206', '\\u5438\\u5165\\u836f\\u7269\\u79cd\\u7c7b', '\\u6c14\\u4fc3-\\u75c7\\u72b6', '\\u8212\\u5f20\\u524dFEV1/FVC%', '\\u8212\\u5f20\\u540eFVC', '\\u8212\\u5f20\\u540eFEV1/FVC%', 'FVC\\u8212\\u5f20\\u540e/\\u9884\\u8ba1', 'FEV 1\\u8212\\u5f20\\u540e/\\u9884\\u8ba1', 'HCO3-'] ['肺结核', 'mMRC评分', '吸入药物种类', '气促-症状', '舒张前FEV1/FVC%', '舒张后FVC', '舒张后FEV1/FVC%', 'FVC舒张后/预计', 'FEV 1舒张后/预计', 'HCO3-']
expected mMRC\u8bc4\u5206, \u5438\u5165\u836f\u7269\u79cd\u7c7b, \u6c14\u4fc3-\u75c7\u72b6, \u8212\u5f20\u540eFEV1/FVC%, \u8212\u5f20\u540eFVC, \u8212\u5f20\u524dFEV1/FVC%, FEV 1\u8212\u5f20\u540e/\u9884\u8ba1, \u80ba\u7ed3\u6838, FVC\u8212\u5f20\u540e/\u9884\u8ba1 in input data
training data did not have the following fields: 舒张后FVC, 肺结核, mMRC评分, FVC舒张后/预计, 吸入药物种类, FEV 1舒张后/预计, 气促-症状, 舒张前FEV1/FVC%, 舒张后FEV1/FVC%

2023-04-21 07:00:12,789	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::HomoBooster.homo_train() (pid=10926, ip=192.168.0.254, repr=<secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster object at 0x7fd072beb190>)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/homo_booster_worker.py", line 145, in homo_train
    self.bst = train(
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 224, in train
    bst = _train_internal(
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 155, in _train_internal
    if callbacks.after_iteration(bst, i, dtrain, evals):
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/callback.py", line 76, in after_iteration
    score = model.eval_set(evals, epoch, self.metric)
  File "/usr/local/lib/python3.8/site-packages/xgboost/core.py", line 1739, in eval_set
    self._validate_features(d[0])
  File "/usr/local/lib/python3.8/site-packages/xgboost/core.py", line 2485, in _validate_features
    raise ValueError(msg.format(self.feature_names, data.feature_names))
ValueError: feature_names mismatch: ['\\u80ba\\u7ed3\\u6838', 'mMRC\\u8bc4\\u5206', '\\u5438\\u5165\\u836f\\u7269\\u79cd\\u7c7b', '\\u6c14\\u4fc3-\\u75c7\\u72b6', '\\u8212\\u5f20\\u524dFEV1/FVC%', '\\u8212\\u5f20\\u540eFVC', '\\u8212\\u5f20\\u540eFEV1/FVC%', 'FVC\\u8212\\u5f20\\u540e/\\u9884\\u8ba1', 'FEV 1\\u8212\\u5f20\\u540e/\\u9884\\u8ba1', 'HCO3-'] ['肺结核', 'mMRC评分', '吸入药物种类', '气促-症状', '舒张前FEV1/FVC%', '舒张后FVC', '舒张后FEV1/FVC%', 'FVC舒张后/预计', 'FEV 1舒张后/预计', 'HCO3-']
expected \u8212\u5f20\u540eFEV1/FVC%, mMRC\u8bc4\u5206, \u8212\u5f20\u540eFVC, \u5438\u5165\u836f\u7269\u79cd\u7c7b, FEV 1\u8212\u5f20\u540e/\u9884\u8ba1, \u80ba\u7ed3\u6838, \u8212\u5f20\u524dFEV1/FVC%, \u6c14\u4fc3-\u75c7\u72b6, FVC\u8212\u5f20\u540e/\u9884\u8ba1 in input data
training data did not have the following fields: 舒张前FEV1/FVC%, 气促-症状, FEV 1舒张后/预计, 肺结核, 吸入药物种类, 舒张后FEV1/FVC%, 舒张后FVC, mMRC评分, FVC舒张后/预计

**Comment by zhangxingmeng** [comment]
看起来是编码问题导致的不匹配，可以尝试统一使用utf-8
或者简单起见把columns改成英文。
祝好

**Comment by nainai123** [comment]
> 看起来是编码问题导致的不匹配，可以尝试统一使用utf-8 或者简单起见把columns改成英文。 祝好

我验证了  如果我把columns改成英文训练是没问题的      经过我的测试   我在保证文件的编码是utf-8的前提下  列名为
['肺结核', 'mMRC评分', '吸入药物种类', '气促-症状', '舒张前FEV1/FVC%', '舒张后FVC','舒张后FEV1/FVC%', 'FVC舒张后/预计', 'FEV 1舒张后/预计', 'HCO3-', 'ae_copd']的情况下建模失败报错跟上面提到的一样

**Comment by zhangxingmeng** [comment]
Hi
中文header的问题已修复，后续的更新将会带上来。
这个问题是xgboost的load函数在读json时会将中文转成ascii，导致和df的header不匹配，导致报错。
修复后您可以尝试使用中文header来进行训练
祝好！
