### ISSUE TITLE
已经提供tls需要的三个文件，两周前的版本运行正确，今天更新后无法运行

### ISSUE THREAD

**Issue by hnjiakai** [secretflow/secretflow#465]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.1b1

### OS Platform and Distribution

centos

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
Traceback (most recent call last):
  File "run-sf-with-sec.py", line 87, in <module>
    sf.init(address=self_addr + ':' + ray_port, cluster_config=cluster_config, tls_config=tls_config)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py", line 407, in init
    _parse_tls_config(tls_config)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/driver.py", line 526, in _parse_tls_config
    raise InvalidArgumentError(
secretflow.utils.errors.InvalidArgumentError: You should provide cert, key and ca_cert at the same time.
```

### Reproduction code to reproduce the issue.

```shell
tls_config = {
    "ca_cert": other_party + "_certs/ca.crt", 
    "cert": self_party + "_certs/server.crt",
    "key": self_party + "_certs/server.key",
}
```

**Comment by Chrisdehe** [comment]
hi，@hnjiakai
请按照以下写法运行
 tls_config = {
     'alice' : {
        "ca_cert": other_party + "_certs/ca.crt", 
        "cert": self_party + "_certs/server.crt",
        "key": self_party + "_certs/server.key",
     }
}

**Comment by hnjiakai** [comment]
@Chrisdehe  好的，这种用法文档入口地址方便给下吗，我在https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#production中看见的还是旧的格式

**Comment by Chrisdehe** [comment]
当中327行起：
https://github.com/secretflow/secretflow/blob/main/secretflow/device/driver.py/
祝好！

**Comment by zhouaihui** [comment]
hi, @hnjiakai, 这里有一个bug，临时修复的话，你可以把下面这行代码先注释掉。
https://github.com/secretflow/secretflow/blob/main/secretflow/device/driver.py/#L407

附：如何找到driver.py
执行`pip show secretflow`，可以得到secretflow安装的地址，类似`xxx/lib/python3.8/site-packages`，那么文件的位置就是 `xxx/lib/python3.8/site-packages/secretflow/device/driver.py`

**Comment by zhouaihui** [comment]
上述代码注释掉后，配置方式还是老的方式。

**Comment by hnjiakai** [comment]
> 上述代码注释掉后，配置方式还是老的方式。

@zhouaihui   根据指导，已经用旧配置成功启动。另外，请问下，spu里的tls_opts可以使用了吧 : )

**Comment by hnjiakai** [comment]
请问下生产模式下（通讯网路如图）
https://gw.alipayobjects.com/render/p/yuyan/180020010001209636/docs/secretflow/zh_CN/_images/rayfed_comm_ch.png
在做spi计算时，alice与bob之间的proxy端口、spu端口，分别都做哪些工作？

**Comment by Niclouge** [comment]
tls_config = {
  'alice' : {
    "ca_cert": other_party + "_certs/ca.crt",
    "cert": self_party + "_certs/server.crt",
    "key": self_party + "_certs/server.key",
  }
}
其中的other_party 和self_party 指的是什么？‘alice’和'bob'么？还是有特殊代指？直接输入'alice'和'bob‘就变成了路径了

**Comment by Niclouge** [comment]
> 
其中的other_party 和self_party 指的是什么？‘alice’和'bob'么？还是有特殊代指？直接输入'alice'和'bob‘就变成了路径了

**Comment by Niclouge** [comment]
> hi，@hnjiakai 请按照以下写法运行 tls_config = { 'alice' : { "ca_cert": other_party + "_certs/ca.crt", "cert": self_party + "_certs/server.crt", "key": self_party + "_certs/server.key", } }
其中的other_party 和self_party 指的是什么？‘alice’和'bob'么？还是有特殊代指？直接输入'alice'和'bob‘就变成了路径了

**Comment by Niclouge** [comment]
> hi，@hnjiakai 请按照以下写法运行 tls_config = { 'alice' : { "ca_cert": other_party + "_certs/ca.crt", "cert": self_party + "_certs/server.crt", "key": self_party + "_certs/server.key", } }



其中的other_party 和self_party 指的是什么？‘alice’和'bob'么？还是有特殊代指？直接输入'alice'和'bob‘就变成了路径了

**Comment by zhouaihui** [comment]
> https://gw.alipayobjects.com/render/p/yuyan/180020010001209636/docs/secretflow/zh_CN/_images/rayfed_comm_ch.png

只做PSI计算的话，主要是SPU端口负责进行PSI协议的通信，proxy在这种情况下没有通信。

**Comment by zhouaihui** [comment]
> > hi，@hnjiakai 请按照以下写法运行 tls_config = { 'alice' : { "ca_cert": other_party + "_certs/ca.crt", "cert": self_party + "_certs/server.crt", "key": self_party + "_certs/server.key", } }
> 
> 其中的other_party 和self_party 指的是什么？‘alice’和'bob'么？还是有特殊代指？直接输入'alice'和'bob‘就变成了路径了 @Chrisdehe

请参考上面我的回复。

**Comment by hnjiakai** [comment]
@zhouaihui  已经成功修正了sf.init里的tls配置导致的错误，但是spu = sf.SPU里面的tls配置，出现连新的错误提示。请问下我该如何改正?

配置如下

`python
def spu_tls_opts(domain='alice'):
    return {
        'server_ssl_opts': {
            'certificate_path': domain + '_certs/server.crt',
            'private_key_path': domain + '_certs/server.key',
            # The options used for verify peer's client certificate
            'ca_file_path': domain + '_certs/ca.crt',
            # Maximum depth of the certificate chain for verification
            'verify_depth': 1
        },
        'client_ssl_opts': {
            'certificate_path': domain + '_certs/client.crt',
            'private_key_path': domain + '_certs/client.key',
            # The options used for verify peer's server certificate
            'ca_file_path': domain + '_certs/ca.crt',
            # Maximum depth of the certificate chain for verification
            'verify_depth': 1
        }
    }


spu_cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': alice_addr + ':' + spu_port,
            'listen_addr': '0.0.0.0:' + spu_port,
            'tls_opts': spu_tls_opts('alice')
        },
        {
            'party': 'bob',
            'id': '1',
            'address': bob_addr + ':' + spu_port,
            'listen_addr': '0.0.0.0:' + spu_port,
            'tls_opts': spu_tls_opts('bob')
        },
    ],
    'runtime_config': {
        # 'protocol': spu.spu_pb2.SEMI2K, #调试用
        'protocol': spu.spu_pb2.CHEETAH,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

# spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
spu_link_desc = {
    'connect_retry_interval_ms': 2000,
    'recv_timeout_ms': 120000,
    'http_timeout_ms': 120000
}

spu = sf.SPU(cluster_def=spu_cluster_def, link_desc=spu_link_desc)
`

错误如下
`shell  
{'parties': {'alice': {'address': 'alice:9001', 'listen_addr': '0.0.0.0:9001'}, 'bob': {'address': 'bob:9001', 'listen_addr': '0.0.0.0:9001'}}, 'self_party': 'bob'}
2023-04-27 17:33:07,383 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: bob:9000...
[2023-04-27 17:33:07,397 I 44690 44690] global_state_accessor.cc:357: This node has an IP address of 172.16.108.40, while we can not find the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
2023-04-27 17:33:07,400 INFO worker.py:1538 -- Connected to Ray cluster.
2023-04-27 17:33:07 INFO api.py:202 [bob] --  Started rayfed with {'CLUSTER_ADDRESSES': {'alice': {'address': 'alice:9001', 'listen_addr': '0.0.0.0:9001'}, 'bob': {'address': 'bob:9001', 'listen_addr': '0.0.0.0:9001'}}, 'CURRENT_PARTY_NAME': 'bob', 'TLS_CONFIG': {'ca_cert': 'alice_certs/ca.crt', 'cert': 'bob_certs/server.crt', 'key': 'bob_certs/server.key'}, 'CROSS_SILO_SERIALIZING_ALLOWED_LIST': None, 'CROSS_SILO_MESSAGES_MAX_SIZE_IN_BYTES': None, 'CROSS_SILO_TIMEOUT_IN_SECONDS': 3600}
2023-04-27 17:33:08 INFO barriers.py:353 [bob] --  RecverProxy was successfully created.
(RecverProxyActor pid=44743) 2023-04-27 17:33:08 INFO barriers.py:114 [bob] --  Successfully start Grpc service with credentials.
2023-04-27 17:33:08 INFO barriers.py:388 [bob] --  SendProxy was successfully created.
2023-04-27 17:33:08 INFO barriers.py:463 [bob] --  Try ping ['alice'] at 0 attemp, up to 3600 attemps.
2023-04-27 17:33:08 INFO barriers.py:444 [bob] --  Succeeded to ping alice on alice:9001, the result: OK.
2023-04-27 17:33:08 INFO cleanup.py:85 [bob] --  Start check sending thread.
2023-04-27 17:33:08 INFO cleanup.py:91 [bob] --  Start check sending monitor thread.
(SPURuntime pid=44822) 2023-04-27 17:33:10.442 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
(SPURuntime pid=44822) 2023-04-27 17:33:10.457 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error
(SPURuntime pid=44822) 2023-04-27 17:33:10.460 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=1016, message=[E1016]Fail to connect Socket{id=0 addr=172.16.108.41:9002} (0x0x35a6e40): SSL related operation failed
(SPURuntime pid=44822) 2023-04-27 17:33:10.548 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
(SPURuntime pid=44822) 2023-04-27 17:33:12.460 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R1][E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R2][E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R3][E112]Not connected to 172.16.108.41:9002 yet, server_id=0
(SPURuntime pid=44822) 2023-04-27 17:33:13.460 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error
(SPURuntime pid=44822) 2023-04-27 17:33:13.554 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
(SPURuntime pid=44822) 2023-04-27 17:33:14.461 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R1][E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R2][E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R3][E112]Not connected to 172.16.108.41:9002 yet, server_id=0
`

**Comment by oeqqwq** [comment]
> @zhouaihui 已经成功修正了sf.init里的tls配置导致的错误，但是spu = sf.SPU里面的tls配置，出现连新的错误提示。请问下我该如何改正?
> 
> 配置如下
> 
> def spu_tls_opts(domain='alice'): return { 'server_ssl_opts': { 'certificate_path': domain + '_certs/server.crt', 'private_key_path': domain + '_certs/server.key', 'ca_file_path': domain + '_certs/ca.crt', 'verify_depth': 1 }, 'client_ssl_opts': { 'certificate_path': domain + '_certs/client.crt', 'private_key_path': domain + '_certs/client.key', 'ca_file_path': domain + '_certs/ca.crt', 'verify_depth': 1 } }
> 
> spu_cluster_def = { 'nodes': [ { 'party': 'alice', 'id': '0', 'address': alice_addr + ':' + spu_port, 'listen_addr': '0.0.0.0:' + spu_port, 'tls_opts': spu_tls_opts('alice') }, { 'party': 'bob', 'id': '1', 'address': bob_addr + ':' + spu_port, 'listen_addr': '0.0.0.0:' + spu_port, 'tls_opts': spu_tls_opts('bob') }, ], 'runtime_config': { 'protocol': spu.spu_pb2.CHEETAH, 'field': spu.spu_pb2.FM128, 'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL, } }
> 
> spu_link_desc = { 'connect_retry_interval_ms': 2000, 'recv_timeout_ms': 120000, 'http_timeout_ms': 120000 }
> 
> spu = sf.SPU(cluster_def=spu_cluster_def, link_desc=spu_link_desc)
> 
> 错误如下
> 
> {'parties': {'alice': {'address': 'alice:9001', 'listen_addr': '0.0.0.0:9001'}, 'bob': {'address': 'bob:9001', 'listen_addr': '0.0.0.0:9001'}}, 'self_party': 'bob'} 2023-04-27 17:33:07,383 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: bob:9000... [2023-04-27 17:33:07,397 I 44690 44690] global_state_accessor.cc:357: This node has an IP address of 172.16.108.40, while we can not find the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container. 2023-04-27 17:33:07,400 INFO worker.py:1538 -- Connected to Ray cluster. 2023-04-27 17:33:07 INFO api.py:202 [bob] -- Started rayfed with {'CLUSTER_ADDRESSES': {'alice': {'address': 'alice:9001', 'listen_addr': '0.0.0.0:9001'}, 'bob': {'address': 'bob:9001', 'listen_addr': '0.0.0.0:9001'}}, 'CURRENT_PARTY_NAME': 'bob', 'TLS_CONFIG': {'ca_cert': 'alice_certs/ca.crt', 'cert': 'bob_certs/server.crt', 'key': 'bob_certs/server.key'}, 'CROSS_SILO_SERIALIZING_ALLOWED_LIST': None, 'CROSS_SILO_MESSAGES_MAX_SIZE_IN_BYTES': None, 'CROSS_SILO_TIMEOUT_IN_SECONDS': 3600} 2023-04-27 17:33:08 INFO barriers.py:353 [bob] -- RecverProxy was successfully created. (RecverProxyActor pid=44743) 2023-04-27 17:33:08 INFO barriers.py:114 [bob] -- Successfully start Grpc service with credentials. 2023-04-27 17:33:08 INFO barriers.py:388 [bob] -- SendProxy was successfully created. 2023-04-27 17:33:08 INFO barriers.py:463 [bob] -- Try ping ['alice'] at 0 attemp, up to 3600 attemps. 2023-04-27 17:33:08 INFO barriers.py:444 [bob] -- Succeeded to ping alice on alice:9001, the result: OK. 2023-04-27 17:33:08 INFO cleanup.py:85 [bob] -- Start check sending thread. 2023-04-27 17:33:08 INFO cleanup.py:91 [bob] -- Start check sending monitor thread. (SPURuntime pid=44822) 2023-04-27 17:33:10.442 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding (SPURuntime pid=44822) 2023-04-27 17:33:10.457 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error (SPURuntime pid=44822) 2023-04-27 17:33:10.460 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=1016, message=[E1016]Fail to connect Socket{id=0 addr=172.16.108.41:9002} (0x0x35a6e40): SSL related operation failed (SPURuntime pid=44822) 2023-04-27 17:33:10.548 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding (SPURuntime pid=44822) 2023-04-27 17:33:12.460 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R1][E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R2][E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R3][E112]Not connected to 172.16.108.41:9002 yet, server_id=0 (SPURuntime pid=44822) 2023-04-27 17:33:13.460 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error (SPURuntime pid=44822) 2023-04-27 17:33:13.554 [error] [socket.cpp:BRPC:1926] Fail to SSL_do_handshake: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding (SPURuntime pid=44822) 2023-04-27 17:33:14.461 [error] [context.cc:operator():132] connect to rank=0 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R1][E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R2][E112]Not connected to 172.16.108.41:9002 yet, server_id=0 [R3][E112]Not connected to 172.16.108.41:9002 yet, server_id=0

`Fail to SSL_do_handshake: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding`
这个错误通常是由于客户端或服务器端SSL证书或密钥出现问题而导致的，可以进行如下检查：

1、检查设置的证书和对应的密钥是否匹配

2、确认各方的SSL证书是能够被其他方的CA证书验证，举例如下：
alice's server ca --verify-->  bob's client certificate
alice's client ca  --verify-->  bob's server certificate
bob's server ca  --verify-->  alice's client certificate
bob's client ca   --verify-->  alice's server certificate
