### ISSUE TITLE
源码方式编译Secretflow

### ISSUE THREAD

**Issue by wjwJack** [secretflow/secretflow#470]
### Issue Type

Bug

### Source

binary

### Secretflow Version

git最新版

### OS Platform and Distribution

cent OS 7.9

### Python version

3.8

### Bazel version

5.4.1

### What happend and What you expected to happen.

```shell
(secretflow) [root@bogon secretflow]# python setup.py bdist_wheel
Requirements:  ['# Avoid thead pool fork issue, see https://github.com/grpc/grpc/issues/31772', 'grpcio<=1.49.1', 'jax', 'jaxlib', 'multiprocess', 'networkx==2.8.8', 'numpy==1.23.5', '# TODO: onnx and tensorflow have dependency conflicts, waiting for upstream to resolve', '# onnx==1.13.1', 'pandas==1.5.3', '# For security reason.', 'protobuf==3.19.6', 'pyarrow==11.0.0', 's3fs==2022.1.0', 'scikit-learn==1.1.3', 'secretflow-rayfed==0.1.1a3', 'sparse>=0.14.0', 'spu==0.3.2b12', 'sf-heu==0.4.2b0', 'tensorflow-macos==2.11.0; platform_machine == "arm64" and platform_system == "Darwin"', 'tensorflow==2.10.1; platform_machine != "arm64"', 'tf2onnx>=1.13.0', 'tqdm', 'validator.py==1.3.0', 'xgboost==1.5.2', '# For security reason.', 'wheel>=0.38.1', 'torch==2.0.0', 'torchmetrics==0.11.4', 'torchvision==0.15.1', 'torchaudio==2.0.1']
Dependency:  ['--extra-index-url https://download.pytorch.org/whl/cpu']
/root/miniconda3/envs/secretflow/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running bdist_wheel
running build
running build_py
running build_ext
bazel build //secretflow_lib/binding:_lib.so --symlink_prefix=build/temp.linux-x86_64-cpython-38/bazel- --compilation_mode=opt
DEBUG: Rule 'yacl' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1680751531 +0800"
DEBUG: Repository yacl instantiated at:
  /root/source/secretflow/WORKSPACE:5:15: in <toplevel>
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Repository local_config_cc instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:519:13: in <toplevel>
  /root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/cc_configure.bzl:184:16: in cc_configure
Repository rule cc_autoconf defined at:
  /root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/cc_configure.bzl:145:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/cc_configure.bzl", line 127, column 33, in cc_autoconf_impl
                configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 345, column 17, in configure_unix_toolchain
                cc = find_cc(repository_ctx, overriden_tools)
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 23, in find_cc
                cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 306, column 32, in _find_generic
                auto_configure_fail(msg)
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable
ERROR: /DEFAULT.WORKSPACE.SUFFIX:519:13: fetching cc_autoconf rule //external:local_config_cc: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/cc_configure.bzl", line 127, column 33, in cc_autoconf_impl
                configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 345, column 17, in configure_unix_toolchain
                cc = find_cc(repository_ctx, overriden_tools)
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 23, in find_cc
                cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 306, column 32, in _find_generic
                auto_configure_fail(msg)
        File "/root/.cache/bazel/_bazel_root/05cc63e07212433159ac849dee593535/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable
ERROR: /root/source/secretflow/secretflow_lib/binding/BUILD.bazel:13:17: //secretflow_lib/binding:_lib.so depends on @local_config_cc//:cc-compiler-k8 in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': 
Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable
ERROR: Analysis of target '//secretflow_lib/binding:_lib.so' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.209s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @local_config_python; fetching
error: command '/usr/local/bin/bazel' failed with exit code 1
(secretflow) [root@bogon secretflow]#
```

### Reproduction code to reproduce the issue.

```shell
通过源码方式安装secretflow，先后执行了以下命令
git clone https://github.com/secretflow/secretflow.git
cd secretflow

中途安装了conda和bazel

conda create -n secretflow python=3.8
conda activate secretflow

执行python setup.py bdist_wheel  该命令时报错
```

**Comment by Chrisdehe** [comment]
Hi，@wjwJack 
请问你的gcc跟cmake版本是多少呢？

**Comment by anakinxc** [comment]
Hi @wjwJack 

源码编译的依赖可以参考[这里](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux)

**Comment by wjwJack** [comment]
> Hi，@wjwJack 请问你的gcc跟cmake版本是多少呢？

不知道要安装这些，如果把命令统一放到安装方式3里就好了
![图片](https://user-images.githubusercontent.com/8414952/234435592-8fee298e-0bd9-4eb9-a2b0-e92bf4d7cb3c.png)

**Comment by wjwJack** [comment]
> Hi @wjwJack
> 
> 源码编译的依赖可以参考[这里](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux)



> Hi @wjwJack
> 
> 源码编译的依赖可以参考[这里](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux)

好的，我再看看

**Comment by wjwJack** [comment]
> Hi @wjwJack
> 
> 源码编译的依赖可以参考[这里](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux)

好的，我再看看
