### ISSUE TITLE
采用secretflow.data.vertical.read_csv时报错

### ISSUE THREAD

**Issue by Niclouge** [secretflow/secretflow#500]
### Issue Type

Bug

### Source

source

### Secretflow Version

secretflow 0.8.1b1

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
实际生产环境下，采用纵向联邦数据集读取时，出现了一个类似列名重复的错误，错误如下所示：
Traceback (most recent call last):
  File "alice.py", line 203, in <module>
    xgb_model.train()
  File "alice.py", line 99, in train
    vertical_data, label_name, heu, = self.set_data()
  File "alice.py", line 86, in set_data
    vertical_dataframe = read_csv({
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/data/vertical/io.py", line 162, in read_csv
    assert col not in unique_cols, f'col {col} duplicate in multiple devices'
AssertionError: col Unnamed: 0 duplicate in multiple devices

这两份数据集是将load_breast_cancer数据集拆分，对于alice数据集，获取前15个特征+标签y，对于bob数据集，获取后15个特征，因此不存在列名重复的情况。

alice 的列名如下：
mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error,texture error,perimeter error,area error,smoothness error,y

bob 的列名如下：
compactness error,concavity error,concave points error,symmetry error,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
```

### Reproduction code to reproduce the issue.

```shell
产生数据集的代码：
ds = load_breast_cancer()
x, y = ds['data'], ds['target']
feature = ds.feature_names
data_1 = pd.DataFrame(x[:, :15], columns=feature[:15])
data_2 = pd.DataFrame(y, columns=["y"])
data_3 = pd.concat([data_1, data_2], axis=1)
data_3.to_csv("alice.csv")
data_4 = pd.DataFrame(x[:, 15:], columns=feature[15:])
data_4.to_csv("bob.csv")


读取数据集的代码
from secretflow.data.vertical import read_csv
alice = sf.PYU('party_1')  # create party 1 pyu
bob = sf.PYU('party_2')  # create party 2 pyu
vertical_dataframe = read_csv({
            alice: "/home/sunthinker/PycharmProjects/pythonProject/alice.csv",
            bob: "/home/wu/bob_foder/bob.csv"
        })
```

**Comment by miluoalbert** [comment]
根据日志，应该是名为`Unnamed`的index重复了，可能是数据加载过程中自动识别的dtypes有一些问题，可以通过使用pandas在某一侧加载文件后，`print(df.dtypes.index)`验证一下

**Comment by miluoalbert** [comment]
use `pd.to_csv(..., index=False)`  to not write out an unnamed index column in the first place

Ref: https://stackoverflow.com/questions/36519086/how-to-get-rid-of-unnamed-0-column-in-a-pandas-dataframe-read-in-from-csv-fil

**Comment by Niclouge** [comment]
> 


非常感谢，已经解决问题了！
