### ISSUE TITLE
teeu 找不到Enclave.pem

### ISSUE THREAD

**Issue by 472002463** [secretflow/secretflow#513]
我根据teeu仿真模式部署
运行
```shell
occlum build --sgx-mode sim
```
找不到
![企业微信截图_16836024681361](https://user-images.githubusercontent.com/33944862/236985891-fdcdd3f7-3541-496d-bbfd-99c29b1eab88.png)

```shell
Error: invalid signing key path: /opt/occlum/etc/template/Enclave.pem
```
镜像里面没有，这是要我自己生成吗？我记得occlum镜像本身就有这个，咋teeu这里就没了

**Comment by zhouaihui** [comment]
可以加一下参数使用自己生成的签名密钥， `--sign-key private_key.pem`

**Comment by zhouaihui** [comment]
使用occlum默认密钥是不安全的，所以我们去除了这个默认密钥。
你也可以自己生成一个密钥放在相同的位置。生成方式文档里有描述

**Comment by 472002463** [comment]
> --sign-key private_key.pem

好的，非常感谢，不过这个文档描述有点问题，我本来想在仿真模式下运行，密钥生成这个在非仿真模式下面才看到，建议加个描述引用

**Comment by zhouaihui** [comment]
感谢提醒，我们会改进文档

**Comment by 472002463** [comment]
![image](https://user-images.githubusercontent.com/33944862/237024697-ff3877b2-49bf-4685-b832-c70ee43248f0.png)
请问下 这个`teeu` 是哪个包下的
```python
import secretflow.device.device.teeu as teu

teeu = teu('carol', mr_enclave='')
```

我在验证那个上手指南，仿真模式，出现了以下错误。
区别的代码只有这个引入包的代码。
![image](https://user-images.githubusercontent.com/33944862/237028897-44fbf9c5-9ffd-4d9f-a692-2d5738ebd383.png)

**Comment by zheyang0825** [comment]
可以这样引入，稍后会修复文档错误
```
from secretflow.device import TEEU

teeu = TEEU('carol', mr_enclave='')
```

**Comment by 472002463** [comment]
@zheyang0825 
代码没问题了，但是运行时候报错
我使用三台服务器进行测试
alice：172.16.40.168  8G
bob: 172.16.40.250   16G
carol: 172.16.40.252   TEE设备（40G内存）
出现以下错误
其中我只看出了
`Worker exits with an exit code None. The worker may have exceeded K8s pod memory limits.`
这个错误，可是我并没有限制pod的内存，且我明确carol内存完全足够

```
INFO:root:Authority manager config is {'host': '172.16.40.250', 'mr_enclave': ''}
2023-05-10 02:31:54,043 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.16.40.168:10000...
2023-05-10 02:31:54,049 INFO worker.py:1538 -- Connected to Ray cluster.
2023-05-10 02:31:54 INFO api.py:202 [alice] --  Started rayfed with {'CLUSTER_ADDRESSES': {'alice': {'address': '172.16.40.168:10001', 'listen_address': '0.0.0.0:10001'}, 'bob': {'address': '172.16.40.250:10001', 'listen_address': '0.0.0.0:10001'}, 'carol': {'address': '172.16.40.252:10001', 'listen_address': '0.0.0.0:10001'}}, 'CURRENT_PARTY_NAME': 'alice', 'TLS_CONFIG': {}, 'CROSS_SILO_SERIALIZING_ALLOWED_LIST': None, 'CROSS_SILO_MESSAGES_MAX_SIZE_IN_BYTES': None, 'CROSS_SILO_TIMEOUT_IN_SECONDS': 3600}
2023-05-10 02:31:54 INFO barriers.py:353 [alice] --  RecverProxy was successfully created.
(RecverProxyActor pid=354) 2023-05-10 02:31:54 INFO barriers.py:114 [alice] --  Successfully start Grpc service without credentials.
2023-05-10 02:31:55 INFO barriers.py:388 [alice] --  SendProxy was successfully created.
2023-05-10 02:31:55 INFO barriers.py:463 [alice] --  Try ping ['bob', 'carol'] at 0 attemp, up to 3600 attemps.
2023-05-10 02:31:55 INFO barriers.py:444 [alice] --  Succeeded to ping bob on 172.16.40.250:10001, the result: OK.
2023-05-10 02:31:55 INFO barriers.py:444 [alice] --  Succeeded to ping carol on 172.16.40.252:10001, the result: OK.
2023-05-10 02:31:55 INFO cleanup.py:85 [alice] --  Start check sending thread.
2023-05-10 02:31:55 INFO cleanup.py:91 [alice] --  Start check sending monitor thread.
2023-05-10 02:31:57,721 WARNING worker.py:1851 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 154, in _run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/kernels/pyu.py", line 157, in create_auth
    data_uuid, data_key = auth_frame.create_auth(
  File "/usr/local/lib/python3.8/site-packages/sdc/auth_frame.py", line 217, in create_auth
    self.register_public_key(owner_id, public_key_pem)
  File "/usr/local/lib/python3.8/site-packages/sdc/auth_frame.py", line 109, in register_public_key
    response = self.stub.RegisterInsPubKey(request)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2023-05-10T02:31:57.718729857+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-05-10T02:31:57.718726248+00:00"}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 589, in ray._raylet.store_task_errors
  File "python/ray/_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
  File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 515, in serialize
    return self._serialize_to_msgpack(value)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 470, in _serialize_to_msgpack
    value = value.to_bytes()
  File "/usr/local/lib/python3.8/site-packages/ray/exceptions.py", line 32, in to_bytes
    serialized_exception=pickle.dumps(self),
  File "/usr/local/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.RLock' object
An unexpected internal error occurred while the worker was executing a task.
2023-05-10 02:31:57,723 WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 31c6bf39ca3d8fb2846ad8b98104cc9724dad9cc01000000 Worker ID: 6f328e73020be423029cb0e4a909326a958b3cf5fcbcace5dce72819 Node ID: 1474f6c7f1d69fec112ded49695403411254082dc3801f68c2b803cf Worker IP address: 172.16.40.168 Worker port: 10006 Worker PID: 439 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned.
(_run pid=439) 2023-05-10 02:31:57,721  ERROR worker.py:763 -- Worker exits with an exit code None. The worker may have exceeded K8s pod memory limits.
(_run pid=439)  Traceback (most recent call last):
(_run pid=439)   File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 154, in _run
(_run pid=439)     return fn(*args, **kwargs)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/kernels/pyu.py", line 157, in create_auth
(_run pid=439)     data_uuid, data_key = auth_frame.create_auth(
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/sdc/auth_frame.py", line 217, in create_auth
(_run pid=439)     self.register_public_key(owner_id, public_key_pem)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/sdc/auth_frame.py", line 109, in register_public_key
(_run pid=439)     response = self.stub.RegisterInsPubKey(request)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
(_run pid=439)     return _end_unary_response_blocking(state, call, False, None)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
(_run pid=439)     raise _InactiveRpcError(state)
(_run pid=439) grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
(_run pid=439)  status = StatusCode.UNAVAILABLE
(_run pid=439)  details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
(_run pid=439)  debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2023-05-10T02:31:57.718729857+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-05-10T02:31:57.718726248+00:00"}]}"
(_run pid=439) >
(_run pid=439) 
(_run pid=439) During handling of the above exception, another exception occurred:
(_run pid=439) 
(_run pid=439) Traceback (most recent call last):
(_run pid=439)   File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
(_run pid=439)   File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
(_run pid=439)   File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 589, in ray._raylet.store_task_errors
(_run pid=439)   File "python/ray/_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 515, in serialize
(_run pid=439)     return self._serialize_to_msgpack(value)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 470, in _serialize_to_msgpack
(_run pid=439)     value = value.to_bytes()
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/exceptions.py", line 32, in to_bytes
(_run pid=439)     serialized_exception=pickle.dumps(self),
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
(_run pid=439)     cp.dump(obj)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
(_run pid=439)     return Pickler.dump(self, obj)
(_run pid=439) TypeError: cannot pickle '_thread.RLock' object
(_run pid=439) An unexpected internal error occurred while the worker was executing a task.
(_run pid=439) Traceback (most recent call last):
(_run pid=439)   File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 154, in _run
(_run pid=439)     return fn(*args, **kwargs)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/kernels/pyu.py", line 157, in create_auth
(_run pid=439)     data_uuid, data_key = auth_frame.create_auth(
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/sdc/auth_frame.py", line 217, in create_auth
(_run pid=439)     self.register_public_key(owner_id, public_key_pem)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/sdc/auth_frame.py", line 109, in register_public_key
(_run pid=439)     response = self.stub.RegisterInsPubKey(request)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
(_run pid=439)     return _end_unary_response_blocking(state, call, False, None)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
(_run pid=439)     raise _InactiveRpcError(state)
(_run pid=439) grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
(_run pid=439)  status = StatusCode.UNAVAILABLE
(_run pid=439)  details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
(_run pid=439)  debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2023-05-10T02:31:57.718729857+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-05-10T02:31:57.718726248+00:00"}]}"
(_run pid=439) >
(_run pid=439) 
(_run pid=439) During handling of the above exception, another exception occurred:
(_run pid=439) 
(_run pid=439) Traceback (most recent call last):
(_run pid=439)   File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
(_run pid=439)   File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
(_run pid=439)   File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
(_run pid=439)   File "python/ray/_raylet.pyx", line 589, in ray._raylet.store_task_errors
(_run pid=439)   File "python/ray/_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 515, in serialize
(_run pid=439)     return self._serialize_to_msgpack(value)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/_private/serialization.py", line 470, in _serialize_to_msgpack
(_run pid=439)     value = value.to_bytes()
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/exceptions.py", line 32, in to_bytes
(_run pid=439)     serialized_exception=pickle.dumps(self),
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
(_run pid=439)     cp.dump(obj)
(_run pid=439)   File "/usr/local/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
(_run pid=439)     return Pickler.dump(self, obj)
(_run pid=439) TypeError: cannot pickle '_thread.RLock' object
(_run pid=439) 
(_run pid=439) During handling of the above exception, another exception occurred:
(_run pid=439) 
(_run pid=439) Traceback (most recent call last):
(_run pid=439)   File "python/ray/_raylet.pyx", line 1176, in ray._raylet.task_execution_handler
(_run pid=439) SystemExit
```

**Comment by zhouaihui** [comment]
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2023-05-10T02:31:57.718729857+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-05-10T02:31:57.718726248+00:00"}]}"
>
```
连接不上AuthManager，可以检查下你的authmanager配置。

**Comment by 472002463** [comment]
>连接不上AuthManager，可以检查下你的authmanager配置。

这个在仿真模式下需要执行下面这个命令吗，
```
cd occlum_release
occlum run /bin/auth-manager --config_path /host/config.yaml
```
首先，occlum_release没找到这个目录
其次，我在运行这个容器后，我看里面服务就启动了
![image](https://github.com/secretflow/secretflow/assets/33944862/98ca0a42-2fab-40a9-a330-897a27f3008b)

**Comment by 472002463** [comment]
> 连接不上AuthManager，可以检查下你的authmanager配置。

不好意思，我看错了。这是occlum的日志

我现在正常启动authmanager了

请问下这个host是IP+端口吗，
```
auth_manager_config = {
    'host': '172.16.40.250',
    'mr_enclave': ''
}
```

**Comment by zhouaihui** [comment]
是的。

**Comment by 472002463** [comment]
请问下这个是什么问题,
bob代码片段跟alice都是一样的，除了配置不一样
```python
INFO:root:Authority manager config is {'host': '172.16.40.250:8835', 'mr_enclave': ''}
2023-05-10 03:27:32,429 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.16.40.168:10000...
2023-05-10 03:27:32,435 INFO worker.py:1538 -- Connected to Ray cluster.
2023-05-10 03:27:32 INFO api.py:202 [alice] --  Started rayfed with {'CLUSTER_ADDRESSES': {'alice': {'address': '172.16.40.168:10001', 'listen_address': '0.0.0.0:10001'}, 'bob': {'address': '172.16.40.250:10001', 'listen_address': '0.0.0.0:10001'}, 'carol': {'address': '172.16.40.252:10001', 'listen_address': '0.0.0.0:10001'}}, 'CURRENT_PARTY_NAME': 'alice', 'TLS_CONFIG': {}, 'CROSS_SILO_SERIALIZING_ALLOWED_LIST': None, 'CROSS_SILO_MESSAGES_MAX_SIZE_IN_BYTES': None, 'CROSS_SILO_TIMEOUT_IN_SECONDS': 3600}
2023-05-10 03:27:33 INFO barriers.py:353 [alice] --  RecverProxy was successfully created.
(RecverProxyActor pid=2040) 2023-05-10 03:27:33 INFO barriers.py:114 [alice] --  Successfully start Grpc service without credentials.
2023-05-10 03:27:33 INFO barriers.py:388 [alice] --  SendProxy was successfully created.
2023-05-10 03:27:33 INFO barriers.py:463 [alice] --  Try ping ['bob', 'carol'] at 0 attemp, up to 3600 attemps.
2023-05-10 03:27:33 INFO barriers.py:444 [alice] --  Succeeded to ping bob on 172.16.40.250:10001, the result: OK.
2023-05-10 03:27:33 INFO barriers.py:444 [alice] --  Succeeded to ping carol on 172.16.40.252:10001, the result: OK.
2023-05-10 03:27:33 INFO cleanup.py:85 [alice] --  Start check sending thread.
2023-05-10 03:27:33 INFO cleanup.py:91 [alice] --  Start check sending monitor thread.
2023-05-10 03:27:36 WARNING cleanup.py:62 [alice] --  Signal self to exit.
*** SIGTERM received at time=1683689256 on cpu 0 ***
2023-05-10 03:27:36 INFO cleanup.py:66 [alice] --  Check sending thread was exited.
PC: @     0x7ffab6c0e79a  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7ffab6c12ce0  (unknown)  (unknown)
[2023-05-10 03:27:36,503 E 1989 1989] logging.cc:361: *** SIGTERM received at time=1683689256 on cpu 0 ***
[2023-05-10 03:27:36,503 E 1989 1989] logging.cc:361: PC: @     0x7ffab6c0e79a  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2023-05-10 03:27:36,503 E 1989 1989] logging.cc:361:     @     0x7ffab6c12ce0  (unknown)  (unknown)
(SendProxyActor pid=2080) 2023-05-10 03:27:36 ERROR barriers.py:240 [alice] --  Failed to send data to seq_id 7 of bob from {upstream_seq_id}, error: <AioRpcError of RPC that terminated with:
(SendProxyActor pid=2080)       status = StatusCode.UNIMPLEMENTED
(SendProxyActor pid=2080)       details = "Method not found!"
(SendProxyActor pid=2080)       debug_error_string = "UNKNOWN:Error received from peer ipv4:172.16.40.250:10001 {grpc_message:"Method not found!", grpc_status:12, created_time:"2023-05-10T03:27:36.499253665+00:00"}"
(SendProxyActor pid=2080) >
2023-05-10 03:27:37 INFO cleanup.py:103 [alice] --  Notify check sending thread to exit.
```

**Comment by 472002463** [comment]
我在仔细看了下文档
在仿真模式中
alice的代码address不应该是alice自己的主节点IP吗，为啥是连接到bob的address啊
```python
# Connect to Bob's ray
sf.init(
    address='192.168.0.20:10000',  
    cluster_config=cluster_config,
    party_key_pair=party_key_pair,
    auth_manager_config=auth_manager_config,
    tee_simulation=True,
)
```

**Comment by zhouaihui** [comment]
感谢指出，这里应该连接alice的ray。我们会尽快修复文档。
