### ISSUE TITLE
PIR label length  大于 128 报错

### ISSUE THREAD

**Issue by prunu** [secretflow/secretflow#519]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

centos7

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
Traceback (most recent call last):
  File "alice_pir.py", line 46, in <module>
    spu.pir_query(server='bob',config=query_config)
  File "/opt/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1802, in pir_query
    return dispatch(
  File "/opt/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/opt/secretflow/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/opt/secretflow/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 527, in pir_query
    return sfd.get(res)
  File "/opt/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 73, in get
    return fed.get(object_refs)
  File "/opt/secretflow/lib/python3.8/site-packages/fed/api.py", line 411, in get
    values = ray.get(ray_refs)
  File "/opt/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::SPURuntime.pir_query() (pid=20172, ip=172.20.60.250, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fb69d2fa100>)
  File "/opt/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1179, in pir_query
    report = pir.pir_client(self.link, config)
  File "/opt/secretflow/lib/python3.8/site-packages/spu/pir.py", line 48, in pir_client
    report_str = libspu.libs.pir_client(link, config.SerializeToString())
RuntimeError: what: 
	[Enforce fail at libspu/psi/utils/utils.cc:179] (proto.ParseFromArray(data.data(), data.size())). 
stacktrace: 
#0 spu::psi::LabelPsiReceiver::ProcessQueryResult()+0x7fb6a93b1144
#1 std::_Function_handler<>::_M_invoke()+0x7fb6a93b1773
#2 std::_Function_handler<>::_M_invoke()+0x7fb6a906d02b
#3 yacl::internal::_parallel_run()+0x7fb6a968ee51
#4 yacl::parallel_for()+0x7fb6a9077af7
#5 spu::psi::LabelPsiReceiver::RequestQuery()+0x7fb6a93b56fb
#6 spu::pir::LabeledPirClient()+0x7fb6a939f39e
#7 spu::pir::PirClient()+0x7fb6a93a0754
#8 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fb6a84141ef
#9 pybind11::cpp_function::dispatcher()+0x7fb6a83ee5c6
#10 PyCFunction_Call+0x4f5652
2023-05-10 05:16:10 INFO cleanup.py:103 [alice] --  Notify check sending thread to exit.
2023-05-10 05:16:10 WARNING cleanup.py:59 [alice] --  Failed to send ObjectRef(0b679d9d91808d3fe57d77ad29b5c06c4b7a2c783400000001000000) with error: ray::SendProxyActor.send() (pid=20129, ip=172.20.60.250, repr=<fed.barriers.SendProxyActor object at 0x7f4550118d00>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SPURuntime.pir_query() (pid=20172, ip=172.20.60.250, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fb69d2fa100>)
  File "/opt/secretflow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1179, in pir_query
    report = pir.pir_client(self.link, config)
  File "/opt/secretflow/lib/python3.8/site-packages/spu/pir.py", line 48, in pir_client
    report_str = libspu.libs.pir_client(link, config.SerializeToString())
RuntimeError: what: 
	[Enforce fail at libspu/psi/utils/utils.cc:179] (proto.ParseFromArray(data.data(), data.size())). 
stacktrace: 
#0 spu::psi::LabelPsiReceiver::ProcessQueryResult()+0x7fb6a93b1144
#1 std::_Function_handler<>::_M_invoke()+0x7fb6a93b1773
#2 std::_Function_handler<>::_M_invoke()+0x7fb6a906d02b
#3 yacl::internal::_parallel_run()+0x7fb6a968ee51
#4 yacl::parallel_for()+0x7fb6a9077af7
#5 spu::psi::LabelPsiReceiver::RequestQuery()+0x7fb6a93b56fb
#6 spu::pir::LabeledPirClient()+0x7fb6a939f39e
#7 spu::pir::PirClient()+0x7fb6a93a0754
#8 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fb6a84141ef
#9 pybind11::cpp_function::dispatcher()+0x7fb6a83ee5c6
#10 PyCFunction_Call+0x4f5652
2023-05-10 05:16:10 WARNING cleanup.py:62 [alice] --  Signal self to exit.
2023-05-10 05:16:10 INFO cleanup.py:66 [alice] --  Check sending thread was exited.
*** SIGTERM received at time=1683710170 on cpu 1 ***
PC: @     0x7f583bef1b3b  (unknown)  do_futex_wait.constprop.1
    @     0x7f583bef3630  (unknown)  (unknown)
    @ ... and at least 1 more frames
[2023-05-10 05:16:10,838 E 20037 20037] logging.cc:361: *** SIGTERM received at time=1683710170 on cpu 1 ***
[2023-05-10 05:16:10,838 E 20037 20037] logging.cc:361: PC: @     0x7f583bef1b3b  (unknown)  do_futex_wait.constprop.1
[2023-05-10 05:16:10,838 E 20037 20037] logging.cc:361:     @     0x7f583bef3630  (unknown)  (unknown)
[2023-05-10 05:16:10,838 E 20037 20037] logging.cc:361:     @ ... and at least 1 more frames
```

### Reproduction code to reproduce the issue.

```shell
spu.pir_setup(server='bob', input_path='.data/bob.csv', key_columns=['a'], label_columns=['b','c'],oprf_key_path='.data/oprf_key.bin', setup_path='.data/setup_path', num_per_query=1, label_max_len=256)
```

**Comment by zhanglei486** [comment]
为了便于定位问题，请上传一下出错的完整代码和数据

**Comment by zhanglei486** [comment]
我错了测试验证，padding部分的代码bug，超过128字节会报错，内部已修复，预计今天修复的代码会同步到github，可以自己打包spu的whl库测试验证，spu pip上的更新目前还不清楚什么时候会发版

**Comment by prunu** [comment]
修复版本的PIR返回数据长度会有限制么？最长能到多少？

**Comment by zhanglei486** [comment]
> 修复版本的PIR返回数据长度会有限制么？最长能到多少？

长度限制主要在apsi的实现，大概是1024字节

**Comment by prunu** [comment]
> 我做了测试验证，padding部分的代码bug，超过128字节会报错，内部已修复，预计今天修复的代码会同步到github，可以自己打包spu的whl库测试验证，spu pip上的更新目前还不清楚什么时候会发版

从master打包测试，报错：
ImportError: /opt/python3.8/site-packages/spu/libspu.so: undefined symbol: PyFrame_GetCode

**Comment by anakinxc** [comment]
> > 我做了测试验证，padding部分的代码bug，超过128字节会报错，内部已修复，预计今天修复的代码会同步到github，可以自己打包spu的whl库测试验证，spu pip上的更新目前还不清楚什么时候会发版
> 
> 从master打包测试，报错： ImportError: /opt/python3.8/site-packages/spu/libspu.so: undefined symbol: PyFrame_GetCode

麻烦确保打包环境的 python 版本是 3.8

**Comment by prunu** [comment]
用docker镜像，里面已经是python3.11  
registry.hub.docker.com/secretflow/release-ci:latest

**Comment by anakinxc** [comment]
> 用docker镜像，里面已经是python3.11
> registry.hub.docker.com/secretflow/release-ci:latest

release-ci 需要自己创建一个新的 python3.8 的 conda env

```sh
conda create --name build python=3.8

conda activate build
```

**Comment by anakinxc** [comment]
> 另外问下，怎么解决编译完的二进制在Centos7上运行问题（Centos glibc版本低于docker环境）

release-ci 是基于 centos7 的 glibc 版本不应该低于 centos7

请问您的 glibc 版本是多少？
