### ISSUE TITLE
pytorch 使用sf.reveal获取模型参数时报错

### ISSUE THREAD

**Issue by 962209699** [secretflow/secretflow#52]
### Issue Type

Others

### Source

source

### Secretflow Version

0.6.13b1

### OS Platform and Distribution

Rocky Linux release 8.5

### Python version

3.8.12

### What happend and What you expected to happen.

```shell
(_run pid=1977253) 2022-07-20 11:11:55.857356: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(_run pid=1977254) 2022-07-20 11:11:56.079320: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=1977495) 2022-07-20 11:11:56.253085: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(_run pid=1977250) 2022-07-20 11:11:56.365197: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=1977496) 2022-07-20 11:11:56.503680: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(_run pid=1977253) 2022-07-20 11:11:56,939,939 WARNING [xla_bridge.py:backends:265] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(_run pid=1977254) 2022-07-20 11:11:57,120,120 WARNING [xla_bridge.py:backends:265] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(SPURuntime pid=1977495) I0720 11:11:57.312257 1977495 external/com_github_brpc_brpc/src/brpc/server.cpp:1065] Server[yasl::link::internal::ReceiverServiceImpl] is serving on port=46567.
(SPURuntime pid=1977495) I0720 11:11:57.312313 1977495 external/com_github_brpc_brpc/src/brpc/server.cpp:1068] Check out http://localhost.localdomain:46567 in web browser.
(_run pid=1977250) 2022-07-20 11:11:57,401,401 WARNING [xla_bridge.py:backends:265] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(SPURuntime pid=1977495) I0720 11:11:57.413011 1977723 external/com_github_brpc_brpc/src/brpc/socket.cpp:2202] Checking Socket{id=0 addr=127.0.0.1:58775} (0x65ef180)
(SPURuntime pid=1977496) I0720 11:11:57.516299 1977496 external/com_github_brpc_brpc/src/brpc/server.cpp:1065] Server[yasl::link::internal::ReceiverServiceImpl] is serving on port=58775.
(SPURuntime pid=1977496) I0720 11:11:57.516340 1977496 external/com_github_brpc_brpc/src/brpc/server.cpp:1068] Check out http://localhost.localdomain:58775 in web browser.
(SPURuntime pid=1977495) I0720 11:12:00.413251 1977722 external/com_github_brpc_brpc/src/brpc/socket.cpp:2262] Revived Socket{id=0 addr=127.0.0.1:58775} (0x65ef180) (Connectable)
2022-07-20 11:12:01,757	ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=1977495, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fc1af31ea00>)
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

ray::SPURuntime.run() (pid=1977495, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fc1af31ea00>)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/ray/workers/default_worker.py", line 238, in <module>
    ray.worker.global_worker.main_loop()
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 196, in run
    cfn, output = jax.xla_computation(fn, return_shape=True)(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/api.py", line 807, in computation_maker
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_dynamic(jaxtree_fun, avals)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1779, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1816, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/tmp/ipykernel_1290442/1368379063.py", line 2, in abc
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/core.py", line 528, in __len__
    return self.aval._len(self)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/core.py", line 1335, in _len
    raise TypeError("len() of unsized object") from err  # same as numpy error
jax._src.traceback_util.UnfilteredStackTrace: TypeError: len() of unsized object

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ray::SPURuntime.run() (pid=1977495, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fc1af31ea00>)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 196, in run
    cfn, output = jax.xla_computation(fn, return_shape=True)(*args, **kwargs)
  File "/tmp/ipykernel_1290442/1368379063.py", line 2, in abc
TypeError: len() of unsized object
---------------------------------------------------------------------------
RayTaskError(TypeError)                   Traceback (most recent call last)
Input In [273], in <cell line: 2>()
      1 w = device(abc)(x1_,x2_,y_)
----> 2 model_w = sf.reveal(w)
      3 model_w

File ~/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/secretflow/device/driver.py:158, in reveal(func_or_object)
    155             value_ref.append(value.device.sk_keeper.decrypt.remote(value.data))
    156         value_idx.append(i)
--> 158 value_obj = ray.get(value_ref)
    159 idx = 0
    160 for i in value_idx:

File ~/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/ray/worker.py:1843, in get(object_refs, timeout)
   1841     worker.core_worker.dump_object_store_memory_usage()
   1842 if isinstance(value, RayTaskError):
-> 1843     raise value.as_instanceof_cause()
   1844 else:
   1845     raise value

RayTaskError(TypeError): ray::SPURuntime.run() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

ray::SPURuntime.run() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/ray/workers/default_worker.py", line 238, in <module>
    ray.worker.global_worker.main_loop()
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 196, in run
    cfn, output = jax.xla_computation(fn, return_shape=True)(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/api.py", line 807, in computation_maker
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_dynamic(jaxtree_fun, avals)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1779, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1816, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/tmp/ipykernel_1290442/1368379063.py", line 2, in abc
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/core.py", line 528, in __len__
    return self.aval._len(self)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/core.py", line 1335, in _len
    raise TypeError("len() of unsized object") from err  # same as numpy error
jax._src.traceback_util.UnfilteredStackTrace: TypeError: len() of unsized object

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ray::SPURuntime.run() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 196, in run
    cfn, output = jax.xla_computation(fn, return_shape=True)(*args, **kwargs)
  File "/tmp/ipykernel_1290442/1368379063.py", line 2, in abc
TypeError: len() of unsized object

(SPURuntime pid=1977495) WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(SPURuntime pid=1977496) WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2022-07-20 11:12:06,945	ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.get_var() (pid=1977495, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fc1af31ea00>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SPURuntime.run() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

ray::SPURuntime.run() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/ray/workers/default_worker.py", line 238, in <module>
    ray.worker.global_worker.main_loop()
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 196, in run
    cfn, output = jax.xla_computation(fn, return_shape=True)(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/api.py", line 807, in computation_maker
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_dynamic(jaxtree_fun, avals)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1779, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1816, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/tmp/ipykernel_1290442/1368379063.py", line 2, in abc
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/core.py", line 528, in __len__
    return self.aval._len(self)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/core.py", line 1335, in _len
    raise TypeError("len() of unsized object") from err  # same as numpy error
jax._src.traceback_util.UnfilteredStackTrace: TypeError: len() of unsized object

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ray::SPURuntime.run() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 196, in run
    cfn, output = jax.xla_computation(fn, return_shape=True)(*args, **kwargs)
  File "/tmp/ipykernel_1290442/1368379063.py", line 2, in abc
TypeError: len() of unsized object
2022-07-20 11:12:06,946	ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.get_var() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SPURuntime.run() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

ray::SPURuntime.run() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/ray/workers/default_worker.py", line 238, in <module>
    ray.worker.global_worker.main_loop()
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 196, in run
    cfn, output = jax.xla_computation(fn, return_shape=True)(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/api.py", line 807, in computation_maker
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_dynamic(jaxtree_fun, avals)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1779, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1816, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/tmp/ipykernel_1290442/1368379063.py", line 2, in abc
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/core.py", line 528, in __len__
    return self.aval._len(self)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/jax/core.py", line 1335, in _len
    raise TypeError("len() of unsized object") from err  # same as numpy error
jax._src.traceback_util.UnfilteredStackTrace: TypeError: len() of unsized object

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ray::SPURuntime.run() (pid=1977496, ip=10.180.216.25, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fe6544a6a00>)
  File "/root/.pyenv/versions/3.8.12/envs/secret_flow/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 196, in run
    cfn, output = jax.xla_computation(fn, return_shape=True)(*args, **kwargs)
  File "/tmp/ipykernel_1290442/1368379063.py", line 2, in abc
TypeError: len() of unsized object
```

### Reproduction code to reproduce the issue.

```shell
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


def load_train_dataset(party_id=None) -> (np.ndarray, np.ndarray):
    features, label = load_breast_cancer(return_X_y=True)
    scaler = StandardScaler()
    features = scaler.fit_transform(features)
    X_train, _, y_train, _ = train_test_split(
        features, label, test_size=0.8, random_state=42
    )

    if party_id:
        if party_id == 1:
            return X_train[:, 15:], _
        else:
            return X_train[:, :15], y_train
    else:
        return X_train, y_train


def load_test_dataset():
    features, label = load_breast_cancer(return_X_y=True)
    scaler = StandardScaler()
    features = scaler.fit_transform(features)
    _, X_test, _, y_test = train_test_split(
        features, label, test_size=0.8, random_state=42
    )
    return X_test, y_test

import secretflow as sf

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob'], num_cpus=8, log_to_driver=True)

alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

x1, _ = alice(load_train_dataset)(party_id=1)
x2, y = bob(load_train_dataset)(party_id=2)

device = spu
x1_, x2_, y_ = (
    x1.to(device),
    x2.to(device),
    y.to(device),
)
x1_, x2_, y_

from torch import nn
import numpy
class Lr(nn.Module):
    def __init__(self):
        super(Lr, self).__init__()  #继承父类init的参数
        self.linear = nn.Linear(30, 1) 
 
    def forward(self, x1, x2):
        x = numpy.concatenate([x1, x2], axis=1)
        out = self.linear(torch.tensor(x))
        return out

def abc(x1, x2, y):
    x1 = torch.tensor(x1,dtype=torch.float64)
    x2 = torch.tensor(x2,dtype=torch.float64)
    y = torch.tensor(y,dtype=torch.float64)
    model = Lr() 
    criterion = nn.MSELoss() 
    optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
    for i in range(100):
        model = model.double()
        y_predict = model(x1, x2) 
        loss = criterion(torch.tensor(np.expand_dims(y,axis=1),dtype=torch.float64),y_predict) 
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    return dict(model.state_dict())['linear.weight'].numpy()

w = device(abc)(x1_,x2_,y_)
model_w = sf.reveal(w)
model_w
```

**Comment by wuxibin89** [comment]
SPU目前只支持[JAX](https://jax.readthedocs.io/en/latest/)前端，暂不支持TensorFlow, PyTorch

**Comment by 962209699** [comment]
好的，大概什么时候可以支持呢

**Comment by rivertalk** [comment]
Hi @962209699 

密态设备工作原理是通过隐语编译器翻译前端语言（tf, Pytorch, JAX)，所以整体工作量比较大

目前
- Tensorflow 2.0 (中可以支持 tf.function 部分）在开发中
- PyTorch 有计划支持，但是没有具体的时间点

一个workaround是使用 numpy 转化的中间表达，在进入SPU前将数据从PyTorch 转成numpy，在SPU 设备中使用 JAX 开发。

祝您生活愉快～
