### ISSUE TITLE
SSRegression.fit()和Xgb.fit()报错

### ISSUE THREAD

**Issue by Sally-Er** [secretflow/secretflow#523]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.2b1

### OS Platform and Distribution

Linux ubuntu 16.04

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
Exception ignored in: <function SPUObject.__del__ at 0x7f111241e820>
Traceback (most recent call last):
  File "/root/miniconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 170, in __del__
    actor.del_share.remote(self.shares_name[i])
  File "/root/miniconda3/envs/sf/lib/python3.8/site-packages/fed/_private/fed_actor.py", line 108, in remote
    return self._fed_call_holder.internal_remote(*args, **kwargs)
  File "/root/miniconda3/envs/sf/lib/python3.8/site-packages/fed/_private/fed_call_holder.py", line 68, in internal_remote
    ray_obj_ref = self._submit_ray_task_func(resolved_args, resolved_kwargs)
  File "/root/miniconda3/envs/sf/lib/python3.8/site-packages/fed/_private/fed_actor.py", line 116, in _execute_impl
    return self._fed_actor_handle._execute_remote_method(
  File "/root/miniconda3/envs/sf/lib/python3.8/site-packages/fed/_private/fed_actor.py", line 79, in _execute_remote_method
    ray_object_ref = self._actor_handle._actor_method_call(
  File "/root/miniconda3/envs/sf/lib/python3.8/site-packages/ray/actor.py", line 1172, in _actor_method_call
    object_refs = worker.core_worker.submit_actor_task(
AttributeError: 'Worker' object has no attribute 'core_worker'
```

### Reproduction code to reproduce the issue.

```shell
def lr(ray_master, ray_config, spu_config, input_data_path):
    sf.shutdown()
    sf.init(address=ray_master, cluster_config=ray_config)
    sf_spu = sf.SPU(cluster_def=spu_config)
    alice, bob = sf.PYU('alice'), sf.PYU('bob')

    vdf = v_read_csv({alice: input_data_path[0],
                      bob: input_data_path[1]},
                     spu=sf_spu,
                     keys='id',
                     drop_keys='id')

    random_state = 1234
    train_vdf, test_vdf = train_test_split(vdf, train_size=0.8, random_state=random_state)

    train_x = train_vdf.drop(columns=['y'])
    train_y = train_vdf['y']

    test_x = test_vdf.drop(columns=['y'])
    test_y = test_vdf['y']
    """

    lr_model = SSRegression(sf_spu)
    lr_model.fit(
        x=train_x,
        y=train_y,
        epochs=3,
        learning_rate=0.1,
        batch_size=1024,
        sig_type='t1',
        reg_type='logistic',
        penalty='l2',
        l2_norm=0.5,
    )

    lr_y_hat = lr_model.predict(x=test_x, batch_size=1024, to_pyu=bob)



if __name__ == '__main__':

    cluster_nodes_config = {
        'nodes': [
            {
                'party': 'alice',
                'id': '0',
                # Use the ip and port of alice instead.
                # Please choose an unused port.
                'address': '192.168.5.52:9802',
                'listen_addr': '0.0.0.0:9802'
            },
            {
                'party': 'bob',
                'id': '1',
                # Use the ip and port of bob instead.
                # Please choose an unused port.
                'address': '192.168.5.53:9802',
                'listen_addr': '0.0.0.0:9802'
            },
        ],
        'runtime_config': {
            'protocol': spu.spu_pb2.SEMI2K,
            'field': spu.spu_pb2.FM128,
            'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
        }
    }
    alice_ray_master_address = "192.168.5.52:9800"

    alice_ray_cluster_config = {
        'parties': {
            'alice': {
                # replace with alice's real address.
                'address': '192.168.5.52:9801',
                'listen_addr': '0.0.0.0:9801'
            },
            'bob': {
                'address': '192.168.5.53:9801',
                'listen_addr': '0.0.0.0:9801'
            },
        },
        'self_party': 'alice'
    }

    bob_ray_master_address = "192.168.5.53:9800"
    bob_ray_cluster_config = {
        'parties': {
            'bob': {
                'address': '192.168.5.53:9801',
                'listen_addr': '0.0.0.0:9801'
            },
            'alice': {
                # replace with alice's real address.
                'address': '192.168.5.52:9801',
                'listen_addr': '0.0.0.0:9801'
            }
        },
        'self_party': 'bob'
    }

    input_data = ['/data/test_data/alice_data.csv',
                  '/data/test_data/bob_data.csv']

    test_lr(alice_ray_master_address,
             alice_ray_cluster_config,
             cluster_nodes_config,
             input_data)
```

**Comment by anakinxc** [comment]
麻烦提供一下 ray 和 rayfed 的版本信息，谢谢

**Comment by Sally-Er** [comment]
根绝 文档安装的配置的虚拟环境
conda create -n sf python=3.8
conda activate sf
pip install -U secretflow
其中 ray和rayfed 
secretflow-ray               2.2.0
secretflow-rayfed            0.1.1a3
