### ISSUE TITLE
多机构部署集群仿真，Ray连接不稳定

### ISSUE THREAD

**Issue by Mingbo-Lee** [secretflow/secretflow#527]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.8.2b1

### OS Platform and Distribution

dockeruh secretflow/secretflow

### Python version

3.8.15

### Bazel version

/

### GCC/Compiler version

/

### What happend and What you expected to happen.

```shell
使用两台服务器进行多机构部署集群仿真，Ray连接不稳定；
机器A的日志：
[root@a602-2288H-V5 ~]# ray start --head --node-ip-address="10.24.93.13" --port="9060" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats
Usage stats collection is disabled.

Local node IP: 10.24.93.13
2023-05-11 07:51:32,991 WARNING services.py:1732 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='10.24.93.13:9060'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _node_ip_address='10.24.93.13')
  
  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')
  
  To see the status of the cluster, use
    ray status
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
[root@a602-2288H-V5 ~]# ray status
======== Autoscaler status: 2023-05-11 07:51:47.633602 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_1b34a3ab1d1cd2252c0cd811a820909963ab4c9aaf03447b2636419c
 1 node_049a5db52545ac22d70e8914bc0d925d05807e955f16fcf18b5ceee0
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/40.0 CPU
 0.0/2.0 GPU
 0.0/16.0 alice
 0.00/168.624 GiB memory
 0.00/9.313 GiB object_store_memory

Demands:
 (no resource demands)
[root@a602-2288H-V5 ~]# ray status
======== Autoscaler status: 2023-05-11 07:52:52.763184 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_1b34a3ab1d1cd2252c0cd811a820909963ab4c9aaf03447b2636419c
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/40.0 CPU
 0.0/2.0 GPU
 0.0/16.0 alice
 0.00/168.624 GiB memory
 0.00/9.313 GiB object_store_memory

Demands:
 (no resource demands)



机器B的日志：
[root@mc2 PSI]# ray start --address="10.24.93.13:9060" --resources='{"bob": 16}' --disable-usage-stats
Local node IP: 10.24.93.12
2023-05-11 07:51:42,784 WARNING services.py:1732 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
[2023-05-11 07:51:42,809 I 4402 4402] global_state_accessor.cc:357: This node has an IP address of 10.24.93.12, while we can not find the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.

--------------------
Ray runtime started.
--------------------

To terminate the Ray runtime, run
  ray stop
[root@mc2 PSI]# ray status
======== Autoscaler status: 2023-05-11 07:51:57.652872 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_1b34a3ab1d1cd2252c0cd811a820909963ab4c9aaf03447b2636419c
 1 node_049a5db52545ac22d70e8914bc0d925d05807e955f16fcf18b5ceee0
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/40.0 CPU
 0.0/2.0 GPU
 0.0/16.0 alice
 0.00/168.624 GiB memory
 0.00/9.313 GiB object_store_memory

Demands:
 (no resource demands)
[root@mc2 PSI]# ray status
======== Autoscaler status: 2023-05-11 07:53:42.861544 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_1b34a3ab1d1cd2252c0cd811a820909963ab4c9aaf03447b2636419c
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/40.0 CPU
 0.0/2.0 GPU
 0.0/16.0 alice
 0.00/168.624 GiB memory
 0.00/9.313 GiB object_store_memory

Demands:
 (no resource demands)

通过两次 ray  status 可以看到ray集群的节点少了一个;

此时执行PSI操作代码报错：

2023-05-11 07:59:40,487 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 10.24.93.13:9060...
2023-05-11 07:59:40,495 INFO worker.py:1538 -- Connected to Ray cluster.
(SPURuntime pid=802) 2023-05-11 07:59:42.559 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=113, message=[E113]Fail to connect Socket{id=0 addr=10.24.93.12:9160} (0x0x4b89740): No route to host
(scheduler +3s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(scheduler +3s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.
(SPURuntime pid=802) 2023-05-11 07:59:43.559 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R1][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R2][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R3][E112]Not connected to 10.24.93.12:9160 yet, server_id=0
(SPURuntime pid=802) 2023-05-11 07:59:44.560 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R1][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R2][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R3][E112]Not connected to 10.24.93.12:9160 yet, server_id=0
(SPURuntime pid=802) 2023-05-11 07:59:45.560 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R1][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R2][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R3][E112]Not connected to 10.24.93.12:9160 yet, server_id=0
(SPURuntime pid=802) 2023-05-11 07:59:46.560 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R1][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R2][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R3][E112]Not connected to 10.24.93.12:9160 yet, server_id=0
(SPURuntime pid=802) 2023-05-11 07:59:47.561 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R1][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R2][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R3][E112]Not connected to 10.24.93.12:9160 yet, server_id=0
(SPURuntime pid=802) 2023-05-11 07:59:48.561 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R1][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R2][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R3][E112]Not connected to 10.24.93.12:9160 yet, server_id=0
(SPURuntime pid=802) 2023-05-11 07:59:49.561 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R1][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R2][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R3][E112]Not connected to 10.24.93.12:9160 yet, server_id=0
(SPURuntime pid=802) 2023-05-11 07:59:50.562 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R1][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R2][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R3][E112]Not connected to 10.24.93.12:9160 yet, server_id=0
Traceback (most recent call last):
  File "psi.py", line 55, in <module>
    report = spu.psi_csv('id', input_path, output_path, 'alice') 
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1622, in psi_csv
    return dispatch(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 300, in psi_csv
    return sfd.get(res)
  File "/usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 75, in get
    return ray.get(object_refs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=802, ip=10.24.93.13, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f43a96b78e0>)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 306, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what: 
        [external/yacl/yacl/link/context.cc:165] connect to mesh failed, failed to setup connection to rank=1
stacktrace: 
#0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f43b47ce3ed
#1 pybind11::cpp_function::dispatcher()+0x7f43b47b55c6
#2 PyCFunction_Call+0x4e0212
(SPURuntime pid=802) 2023-05-11 07:59:51,566    ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=802, ip=10.24.93.13, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f43a96b78e0>)
(SPURuntime pid=802)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 306, in __init__
(SPURuntime pid=802)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=802) RuntimeError: what: 
(SPURuntime pid=802)    [external/yacl/yacl/link/context.cc:165] connect to mesh failed, failed to setup connection to rank=1
(SPURuntime pid=802) stacktrace: 
(SPURuntime pid=802) #0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f43b47ce3ed
(SPURuntime pid=802) #1 pybind11::cpp_function::dispatcher()+0x7f43b47b55c6
(SPURuntime pid=802) #2 PyCFunction_Call+0x4e0212
(SPURuntime pid=802) 2023-05-11 07:59:51.562 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R1][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R2][E112]Not connected to 10.24.93.12:9160 yet, server_id=0 [R3][E112]Not connected to 10.24.93.12:9160 yet, server_id=0

psi.py 代码：
import spu
import secretflow as sf
import logging

sf.shutdown()
alice, bob = sf.PYU('alice'), sf.PYU('bob')
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.24.93.13:9060',
            'listen_addr': '0.0.0.0:9060'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.24.93.12:9060',
            'listen_addr': '0.0.0.0:9060'
        },
    },
    'self_party': 'alice' #bob
}

cluster_def = {
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            # Use the address and port of alice instead.
            # Please choose a unused port.
            'address': '10.24.93.13:9160',
        },
        {
            'party': 'bob',
            'id': '1',
            # Use the ip and port of bob instead.
            # Please choose a unused port.
            'address': '10.24.93.12:9160',
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}
link_desc = {
    'recv_timeout_ms': 3600000,
}

sf.init(parties=['alice', 'bob'], address='10.24.93.13:9060')
# sf.init(address='192.168.65.3:9327', cluster_config=cluster_config)
spu = sf.SPU(cluster_def=cluster_def, link_desc=link_desc)
input_path = {alice: '/home/A/contest/PSI/A_PSI_DATA.csv', bob: '/home/B/contest/PSI/B_PSI_DATA.csv'}
output_path = {alice: '/home/A/contest/PSI/A_PSI_result.csv', bob: '/home/B/contest/PSI/B_PSI_result.csv'}
report = spu.psi_csv('id', input_path, output_path, 'alice') 
logging.info(f"psi report:{report}")
```

### Reproduction code to reproduce the issue.

```shell
A:
ray start --head --node-ip-address="10.24.93.13" --port="9060" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats
B:
ray start --address="10.24.93.13:9060" --resources='{"bob": 16}' --disable-usage-stats
A：
python psi.py
```

**Comment by anakinxc** [comment]
Hi @Mingbo-Lee 

检查一下 SPU 的端口是不是都正常

**Comment by Mingbo-Lee** [comment]
Hi,@anakinxc,端口检测情况如下：
机器A：10.24.93.13
机器B：10.24.93.12
机器A连接机器B的端口：
```
[root@a602-2288H-V5 ~]# telnet 10.24.93.12 9060
Trying 10.24.93.12...
telnet: connect to address 10.24.93.12: No route to host
[root@a602-2288H-V5 ~]# telnet 10.24.93.12 9160
Trying 10.24.93.12...
telnet: connect to address 10.24.93.12: No route to host
```
机器B连接机器A的端口
```
[root@mc2 ~]# telnet 10.24.93.13 9060
Trying 10.24.93.13...
Connected to 10.24.93.13.
Escape character is '^]'.
?�?� ?
Connection closed by foreign host.
[root@mc2 ~]# telnet 10.24.93.13 9160
Trying 10.24.93.13...
telnet: connect to address 10.24.93.13: Connection refused
```


但是我觉得Ray集群只有一个节点可用，或许才导致了连接的问题

**Comment by anakinxc** [comment]
现在不是 ray 连不上，是 spu 直接的通信连不上

**Comment by Mingbo-Lee** [comment]
哦哦，好的，那可以怎么解决呢？

**Comment by anakinxc** [comment]
看看 spu 的 9160 端口都有没有被占用

**Comment by Mingbo-Lee** [comment]
容器内：
- 机器A：
```
[root@a602-2288H-V5 ~]# lsof -i:9160
[root@a602-2288H-V5 ~]# 
```
- 机器B：
```
[root@mc2 ~]# lsof -i:9160
[root@mc2 ~]# 
```
宿主机：
- 机器A：
```
(base) ➜  ~ lsof -i:9160                                                                                                
(base) ➜  ~ 
```
- 机器B：
```
➜  ~ lsof -i:9160  
➜  ~ 
```

**Comment by anakinxc** [comment]
试一下两个 spu 给不一样的端口呢

**Comment by anakinxc** [comment]
顺便问一下，你 docker 是怎么起的？

**Comment by Mingbo-Lee** [comment]
docker --name=sf_a   --net=host -it  secretflow/secretflow-anolis8:latest

**Comment by Mingbo-Lee** [comment]
网络确实是用host 模式：
容器A：
```
(base) ➜  ~ docker inspect sf_a | grep Networks -A 5
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "ad03208db348b54f6b6dfd8c8b18967827bf853ba254ccdf0cad8e5aaceb8de4",
```

容器B：
```
➜  ~ docker inspect sf_b | grep Networks -A 5 
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "815c23bdbd5c21a58bef3adce2dc27f3189a7cb40f9616490d82de0be1c6d401",
```

**Comment by Mingbo-Lee** [comment]
> 好的，我试试

等一下，这种跨计算机的bridge模式，隐语不是强烈不推荐吗？
要不要考虑最朴素的方式，直接使用容器暴露端口？ @anakinxc

**Comment by anakinxc** [comment]
> > 好的，我试试
> 
> 等一下，这种跨计算机的bridge模式，隐语不是强烈不推荐吗？ 要不要考虑最朴素的方式，直接使用容器暴露端口？ @anakinxc

等一下，现在是跨机器的生产模式还是仿真模式？
我一直以为是单机多容器的仿真

**Comment by Mingbo-Lee** [comment]
看一下标题？多机构部署集群会使用单机多容器的仿真？[捂脸哭]
一直都在说：机器A， 机器B，[捂脸哭]

**Comment by anakinxc** [comment]
> 看一下标题？多机构部署集群会使用单机多容器的仿真？[捂脸哭] 一直都在说：机器A， 机器B，[捂脸哭]

那试一下直接暴露端口吧

**Comment by Mingbo-Lee** [comment]
直接暴露端口，运行情况如下：
启动容器：
- 机器A：
```
docker run  --name=sf_port_a  -p  20010:20010 -p 20011:20011  -it secretflow/secretflow-anolis8:latest
```
- 机器B：
```
docker run  --name=sf_port_b  -p  20010:20010 -p 20011:20011  -it secretflow/secretflow-anolis8:latest
```
运行过后使用docker ps 查看端口暴露情况:
- 机器A：
```
(base) ➜  ~ docker ps
CONTAINER ID   IMAGE                                   COMMAND                   CREATED          STATUS          PORTS                                                                                                                             NAMES
0e01eb5e2590   secretflow/secretflow-anolis8:latest    "/bin/bash"               13 minutes ago   Up 13 minutes   0.0.0.0:20010-20011->20010-20011/tcp, :::20010-20011->20010-20011/tcp                                                             sf_port_a
```
- 机器B：
```
➜  temp docker ps                   
CONTAINER ID   IMAGE                                         COMMAND                   CREATED          STATUS          PORTS                                                                   NAMES
f599d621956c   secretflow/secretflow-anolis8:latest          "/bin/bash"               12 minutes ago   Up 12 minutes   0.0.0.0:20010-20011->20010-20011/tcp, :::20010-20011->20010-20011/tcp   sf_port_b
```
Ray集群启动：
- 机器A：
```
ray start --head --node-ip-address="10.24.93.13" --port="20010" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats
```
- 机器B：
```
ray start --address="10.24.93.13:20010" --resources='{"bob": 16}' --disable-usage-stats
```
使用``ray status``检查Ray集群状态：
- 机器A：
```
[root@0e01eb5e2590 PSI]# ray start --head --node-ip-address="10.24.93.13" --port="20010" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats
Usage stats collection is disabled.

Local node IP: 10.24.93.13
2023-05-12 03:09:19,027 WARNING services.py:1732 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='10.24.93.13:20010'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _node_ip_address='10.24.93.13')
  
  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')
  
  To see the status of the cluster, use
    ray status
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
[root@0e01eb5e2590 PSI]# ray status
======== Autoscaler status: 2023-05-12 03:09:58.845047 ========
Node status
---------------------------------------------------------------
Healthy:

Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:

Demands:
 (no resource demands)
[root@0e01eb5e2590 PSI]# ray status
No cluster status.
[root@0e01eb5e2590 PSI]# 

```
- 机器B：
```
[root@f599d621956c PSI]# ray start --address="10.24.93.13:20010" --resources='{"bob": 16}' --disable-usage-stats
Local node IP: 172.17.0.2
2023-05-12 03:09:40,119 WARNING services.py:1732 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
[2023-05-12 03:09:40,154 W 17 17] global_state_accessor.cc:390: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?

--------------------
Ray runtime started.
--------------------

To terminate the Ray runtime, run
  ray stop
[root@f599d621956c PSI]# ray status
======== Autoscaler status: 2023-05-12 03:09:43.813282 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_75862948391ec16f780d7b799073091ced3f45c0ba9aba3ee5e3841e
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:

Demands:
 (no resource demands)
[root@f599d621956c PSI]# ray status
No cluster status.
[root@f599d621956c PSI]# 

```

**Comment by ian-huu** [comment]
仿真模式下只映射两个端口是不够的，ray 集群本身需要很多额外的端口，因此建议直接使用 host 模式（暴露所有端口）：https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#deploy-secretflow-in-a-docker-container-with-simulation-mode

**Comment by Mingbo-Lee** [comment]
hi, @ian-huu  host模式已经出现断联了，完整的issue已经包含此部分的讨论，正是host模式失败了，才尝试暴露端口的模式。

**Comment by ian-huu** [comment]
> hi, @ian-huu host模式已经出现断联了，完整的issue已经包含此部分的讨论，正是host模式失败了，才尝试暴露端口的模式。

看了一下上下文，首先仍然建议用 host 模式；
确认一下：
1. host 模式下 ray 集群启动以后 100% 出现其中一个 node 退出的情况吗
2. 查看一下两个节点上的 ray 日志，看看有没有什么报错，日志在 /tmp/ray/session_*/logs 目录

**Comment by Mingbo-Lee** [comment]
> 

1.由上面的运行日志可以看到，ray集群启动以后100%会出现node退出的情况；
2.节点的ray日志：
- 机器A：
```
[root@a602-2288H-V5 logs]# pwd 
/tmp/ray/session_latest/logs
[root@a602-2288H-V5 logs]# ls
dashboard.log
dashboard_agent.log
debug_state.txt
debug_state_gcs.txt
events
gcs_server.err
gcs_server.out
log_monitor.log
monitor.err
monitor.log
monitor.out
old
python-core-driver-01000000ffffffffffffffffffffffffffffffffffffffffffffffff_1851.log
python-core-driver-02000000ffffffffffffffffffffffffffffffffffffffffffffffff_2138.log
python-core-driver-03000000ffffffffffffffffffffffffffffffffffffffffffffffff_2383.log
python-core-worker-08825a602f77e4692dae40ad19da3b90dc21fad18e14e36ab7228d90_2254.log
python-core-worker-79efeb800f99a77cdd846cb513a46ad4abc95a8cd754fc208726abb6_1967.log
python-core-worker-d49223fe5b79b488a59cbec666d2512e196d1466e5dee33f192babbc_2499.log
ray_client_server.err
ray_client_server.out
raylet.err
raylet.out
worker-08825a602f77e4692dae40ad19da3b90dc21fad18e14e36ab7228d90-02000000-2254.err
worker-08825a602f77e4692dae40ad19da3b90dc21fad18e14e36ab7228d90-02000000-2254.out
worker-79efeb800f99a77cdd846cb513a46ad4abc95a8cd754fc208726abb6-01000000-1967.err
worker-79efeb800f99a77cdd846cb513a46ad4abc95a8cd754fc208726abb6-01000000-1967.out
worker-d49223fe5b79b488a59cbec666d2512e196d1466e5dee33f192babbc-03000000-2499.err
worker-d49223fe5b79b488a59cbec666d2512e196d1466e5dee33f192babbc-03000000-2499.out
[root@a602-2288H-V5 logs]# 
```
- 节点B：
```
[root@mc2 logs]# pwd
/tmp/ray/session_latest/logs
[root@mc2 logs]# ls
dashboard_agent.log  debug_state.txt  log_monitor.log  old  raylet.err  raylet.out
[root@mc2 logs]# 
```
你需要看哪些日志？ @ian-huu

**Comment by ian-huu** [comment]
不清楚是哪个部分出的问题可能所有日志都需要看一下，也可以设置一下环境变量 `RAY_LOG_TO_STDERR=1` 让日志打到屏幕上看起来简单一些：  https://docs.ray.io/en/latest/ray-observability/ray-logging.html#redirecting-ray-logs-to-stderr

**Comment by Mingbo-Lee** [comment]
我对ray不熟悉，因为我另外一个同学使用虚拟机和服务器连接也出现了类似的问题，我觉得这可能是bug，建议你们试着复现一下。

**Comment by ian-huu** [comment]
可以打包一下日志发上来吗，我们先分析一下你这边现场的日志

**Comment by Mingbo-Lee** [comment]
好的，我已经让王得和帮忙把日志转发给你。 @ian-huu

**Comment by Mingbo-Lee** [comment]
机器A和机器B能互相ping通，机器A的防火墙关闭，机器B的防火墙打开：
- 机器A：
```
(base) ➜  ~ sudo ufw status                   
状态：不活动
(base) ➜  ~ ping 10.24.93.12               
PING 10.24.93.12 (10.24.93.12) 56(84) bytes of data.
64 字节，来自 10.24.93.12: icmp_seq=1 ttl=64 时间=0.167 毫秒
64 字节，来自 10.24.93.12: icmp_seq=2 ttl=64 时间=0.122 毫秒
64 字节，来自 10.24.93.12: icmp_seq=3 ttl=64 时间=0.120 毫秒
^C
--- 10.24.93.12 ping 统计 ---
已发送 3 个包， 已接收 3 个包, 0% 包丢失, 耗时 2031 毫秒
rtt min/avg/max/mdev = 0.120/0.136/0.167/0.021 ms
```
- 机器B：
```
➜  ~ ping 10.24.93.13               
PING 10.24.93.13 (10.24.93.13) 56(84) bytes of data.
64 bytes from 10.24.93.13: icmp_seq=1 ttl=64 time=0.176 ms
64 bytes from 10.24.93.13: icmp_seq=2 ttl=64 time=0.120 ms
64 bytes from 10.24.93.13: icmp_seq=3 ttl=64 time=0.109 ms
^C
--- 10.24.93.13 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2028ms
rtt min/avg/max/mdev = 0.109/0.135/0.176/0.029 ms
➜  ~ sudo systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-05-10 17:01:54 CST; 2 days ago
       Docs: man:firewalld(1)
   Main PID: 1769 (firewalld)
      Tasks: 3 (limit: 309068)
     Memory: 45.9M
        CPU: 3.563s
     CGroup: /system.slice/firewalld.service
             └─1769 /usr/bin/python3 /usr/sbin/firewalld --nofork --nopid
```

出于安全原因，我们不能关闭机器B的防火墙，难道Ray集群的部署，一定需要关闭防火墙吗？可以通过暴露端口来实现通信吗？
如果完全暴露端口才能实现多机多容器部署，这样不是也存在安全隐患吗？

**Comment by ian-huu** [comment]
开发环境建议关闭防火墙，如果有安全性要求，需要对防火墙做正确的配置，保证应用层双向通信正常，保证 telnet 的效果是 “Connection refused” 而不是 “No route to host”

**Comment by Mingbo-Lee** [comment]
好的，我试试，非常感谢

**Comment by Mingbo-Lee** [comment]
我觉得目前的host模式+主机关闭防火墙的方式存在比较大的安全隐患，
一方面：
>映射两个端口是不够的，ray 集群本身需要很多额外的端口，因此建议直接使用 host 模式（暴露所有端口）：

另一方面：
>开发环境建议关闭防火墙，如果有安全性要求，需要对防火墙做正确的配置，保证应用层双向通信正常，保证 telnet 的效果是 “Connection refused” 而不是 “No route to host”
我试过，仅开放两个端口是不够的，Ray集群确实连接不上，能否：
1. 给出Ray集群连接所需要的最小端口，使得直接暴露端口的方式可行？
2. 我相信出于安全原因，绝大部分服务器都不允许关闭防火墙，既然，
>如果有安全性要求，需要对防火墙做正确的配置，保证应用层双向通信正常，保证 telnet 的效果是 “Connection refused” 而不是 “No route to host”

这样的配置应该怎样去做，隐语能否提供完整的文档支持呢？

**Comment by zhouaihui** [comment]
1. 防火墙是否可以设置ip白名单，这样配置会简单很多。
2. 我们是非常不推荐端口模式，因为Ray本身使用到的端口就很多，而且可能还处于增删中，如果遇到问题不太直观能排查到。可以参考 https://github.com/secretflow/secretflow/issues/50#issuecomment-1188949496

**Comment by Mingbo-Lee** [comment]
@zhouaihui ，非常感谢，白名单的方案可行。我已经添加文档支持：https://github.com/secretflow/secretflow/pull/556

**Comment by liyunhan** [comment]
我遇到过类似的，应该是防火墙问题，两个节点之间只开放6379会自动退出子节点，感觉就是ray有很多隐藏端口导致的。然后我就ufw allow from <node:ip> ，把节点间的ip都加入防火墙白名单，然后就正常了。（docker是直接network_mode:"host"了）
