### ISSUE TITLE
SGB提示"list index out of range"

### ISSUE THREAD

**Issue by hanweidong** [secretflow/secretflow#528]
### Issue Type

Others

### Source

binary

### Secretflow Version

v0.8.2b1

### OS Platform and Distribution

CentOS Linux release 7.7.1908 (Core)

### Python version

3.8

### What happend and What you expected to happen.

```shell
你好，我用纵向SGB尝试训练模型，但是提示“list index out of range”，详细错误描述如下：

2023-05-11 16:56:00 INFO proxy.py:180 [bob] --  Create proxy actor <class 'secretflow.ml.boost.sgb_v.core.split_tree_trainer.split_tree_trainer.SplitTreeTrainer'> with party alice.
2023-05-11 16:56:00 INFO proxy.py:180 [bob] --  Create proxy actor <class 'secretflow.ml.boost.sgb_v.core.split_tree_trainer.split_tree_trainer.SplitTreeTrainer'> with party bob.
2023-05-11 16:56:00 INFO proxy.py:180 [bob] --  Create proxy actor <class 'secretflow.ml.boost.sgb_v.core.label_holder.label_holder.LabelHolder'> with party alice.
2023-05-11 16:56:00 INFO sgb.py:258 [bob] --  global_setup time 0.08386124577373266s
2023-05-11 16:56:03 WARNING cleanup.py:59 [bob] --  Failed to send ObjectRef(a6d6d59239756144d85dff8700d23bc50bfb8c5b0100000001000000) with error: ray::SendProxyActor.send() (pid=945, ip=10.3.70.140, repr=<fed.barriers.SendProxyActor object at 0x7f78da951100>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_run() (pid=2538, ip=10.3.70.140)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_run() (pid=2538, ip=10.3.70.140)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SplitTreeTrainer.global_setup() (pid=3294, ip=10.3.70.140, repr=<secretflow.ml.boost.sgb_v.core.split_tree_trainer.split_tree_trainer.SplitTreeTrainer object at 0x7efe92eebf10>)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/core/split_tree_trainer/split_tree_trainer.py", line 47, in global_setup
    self.splitter.build_maps(x, buckets)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/core/split_tree_trainer/splitter.py", line 43, in build_maps
    self.order_map_context.build_maps(x, buckets)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/core/split_tree_trainer/order_map_context.py", line 112, in build_maps
    bins, split_point = self._qcut(x[:, f])
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/core/split_tree_trainer/order_map_context.py", line 66, in _qcut
    elif split_points[-1] != sorted_x[-1]:
IndexError: list index out of range
2023-05-11 16:56:03 WARNING cleanup.py:62 [bob] --  Signal self to exit.
2023-05-11 16:56:03 INFO cleanup.py:66 [bob] --  Check sending thread was exited.
*** SIGTERM received at time=1683795363 on cpu 14 ***
PC: @     0x7f0782189da2  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7f078218d5f0  (unknown)  (unknown)
    @ ... and at least 16 more frames
[2023-05-11 16:56:03,575 E 28102 28102] logging.cc:361: *** SIGTERM received at time=1683795363 on cpu 14 ***
[2023-05-11 16:56:03,575 E 28102 28102] logging.cc:361: PC: @     0x7f0782189da2  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2023-05-11 16:56:03,575 E 28102 28102] logging.cc:361:     @     0x7f078218d5f0  (unknown)  (unknown)
[2023-05-11 16:56:03,575 E 28102 28102] logging.cc:361:     @ ... and at least 15 more frames
---------------------------------------------------------------------------
RayTaskError(IndexError)                  Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[9], line 10
      1 # model = xgb.train(params, train_data, train_label)
      2 # logging.info(f"main train time: {time.time() - start}")
      3 
   (...)
      7 # logging.info(f"main predict time: {time.time() - start}")
      8 # logging.info(f"main auc: {roc_auc_score(y, yhat)}")
---> 10 model = xgb.train(params, data, label)
     11 logging.info(f"main train time: {time.time() - start}")

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/sgb.py:264, in Sgb.train(self, params, dtrain, label, audit_paths)
    263 cur_tree_num = len(model.trees)
--> 264 self._tree_setup(cur_tree_num)
    266 tree = self._train_tree(cur_tree_num)

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/sgb.py:189, in Sgb._tree_setup(self, tree_num)
    188 wait([self.train_label_holder.get_gh(), *self.encrypted_gh.values()])
--> 189 self._sub_sampling()

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/sgb.py:501, in Sgb._sub_sampling(self)
    491     self.order_map_sub = FedNdarray(
    492         partitions={
    493             pyu: pyu(lambda x, y: x[y, :])(
   (...)
    499         partition_way=PartitionWay.VERTICAL,
    500     )
--> 501 self.order_map_sub_shapes = self.order_map_sub.partition_shape()

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/driver.py:129, in reveal.<locals>.wrapper(*arg, **kwargs)
    127 @wraps(func_or_object)
    128 def wrapper(*arg, **kwargs):
--> 129     return reveal(func_or_object(*arg, **kwargs))

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/driver.py:155, in reveal(func_or_object, heu_encoder)
    154 cur_idx = 0
--> 155 all_object = sfd.get(all_object_refs)
    157 new_flatten_val = []

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/distributed/primitive.py:73, in get(object_refs)
     72 if production_mode():
---> 73     return fed.get(object_refs)
     74 else:

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/fed/api.py:411, in get(fed_objects)
    409         ray_refs.append(received_ray_object_ref)
--> 411 values = ray.get(ray_refs)
    412 if is_individual_id:

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
   2308 if isinstance(value, RayTaskError):
-> 2309     raise value.as_instanceof_cause()
   2310 else:

RayTaskError(IndexError): ray::_run() (pid=2538, ip=10.3.70.140)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_run() (pid=2538, ip=10.3.70.140)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::SplitTreeTrainer.global_setup() (pid=3294, ip=10.3.70.140, repr=<secretflow.ml.boost.sgb_v.core.split_tree_trainer.split_tree_trainer.SplitTreeTrainer object at 0x7efe92eebf10>)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/core/split_tree_trainer/split_tree_trainer.py", line 47, in global_setup
    self.splitter.build_maps(x, buckets)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/core/split_tree_trainer/splitter.py", line 43, in build_maps
    self.order_map_context.build_maps(x, buckets)
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/core/split_tree_trainer/order_map_context.py", line 112, in build_maps
    bins, split_point = self._qcut(x[:, f])
  File "/usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/secretflow/ml/boost/sgb_v/core/split_tree_trainer/order_map_context.py", line 66, in _qcut
    elif split_points[-1] != sorted_x[-1]:
IndexError: list index out of range

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:2057, in InteractiveShell.showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2055         stb = value._render_traceback_()
   2056     else:
-> 2057         stb = self.InteractiveTB.structured_traceback(
   2058             etype, value, tb, tb_offset=tb_offset
   2059         )
   2061 except Exception:
   2062     print(
   2063         "Unexpected exception formatting exception. Falling back to standard exception"
   2064     )

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/IPython/core/ultratb.py:1118, in AutoFormattedTB.structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1116 else:
   1117     self.tb = tb
-> 1118 return FormattedTB.structured_traceback(
   1119     self, etype, value, tb, tb_offset, number_of_lines_of_context)

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/IPython/core/ultratb.py:1012, in FormattedTB.structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1009 mode = self.mode
   1010 if mode in self.verbose_modes:
   1011     # Verbose modes need a full traceback
-> 1012     return VerboseTB.structured_traceback(
   1013         self, etype, value, tb, tb_offset, number_of_lines_of_context
   1014     )
   1015 elif mode == 'Minimal':
   1016     return ListTB.get_exception_only(self, etype, value)

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/IPython/core/ultratb.py:865, in VerboseTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
    856 def structured_traceback(
    857     self,
    858     etype: type,
   (...)
    862     number_of_lines_of_context: int = 5,
    863 ):
    864     """Return a nice text document describing the traceback."""
--> 865     formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
    866                                                            tb_offset)
    868     colors = self.Colors  # just a shorthand + quicker name lookup
    869     colorsnormal = colors.Normal  # used a lot

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/IPython/core/ultratb.py:799, in VerboseTB.format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
    796 assert isinstance(tb_offset, int)
    797 head = self.prepare_header(etype, self.long_header)
    798 records = (
--> 799     self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
    800 )
    802 frames = []
    803 skipped = 0

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/IPython/core/ultratb.py:854, in VerboseTB.get_records(self, etb, number_of_lines_of_context, tb_offset)
    848     formatter = None
    849 options = stack_data.Options(
    850     before=before,
    851     after=after,
    852     pygments_formatter=formatter,
    853 )
--> 854 return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/stack_data/core.py:597, in FrameInfo.stack_data(cls, frame_or_tb, options, collapse_repeated_frames)
    594     frame, lineno = frame_and_lineno(x)
    595     return frame.f_code, lineno
--> 597 yield from collapse_repeated(
    598     stack,
    599     mapper=mapper,
    600     collapser=RepeatedFrames,
    601     key=_frame_key,
    602 )

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/stack_data/utils.py:83, in collapse_repeated(lst, collapser, mapper, key)
     81 original_group, highlighted_group = zip(*group)
     82 if is_highlighted:
---> 83     yield from map(mapper, original_group)
     84 else:
     85     keyed_group, _ = zip(*highlighted_group)

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/stack_data/core.py:587, in FrameInfo.stack_data.<locals>.mapper(f)
    586 def mapper(f):
--> 587     return cls(f, options)

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/stack_data/core.py:551, in FrameInfo.__init__(self, frame_or_tb, options)
    546 def __init__(
    547         self,
    548         frame_or_tb: Union[FrameType, TracebackType],
    549         options: Optional[Options] = None,
    550 ):
--> 551     self.executing = Source.executing(frame_or_tb)
    552     frame, self.lineno = frame_and_lineno(frame_or_tb)
    553     self.frame = frame

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/executing/executing.py:359, in Source.executing(cls, frame_or_tb)
    357 if not args:
    358     node = stmts = decorator = None
--> 359     source = cls.for_frame(frame)
    360     tree = source.tree
    361     if tree:

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/executing/executing.py:277, in Source.for_frame(cls, frame, use_cache)
    271 @classmethod
    272 def for_frame(cls, frame, use_cache=True):
    273     # type: (types.FrameType, bool) -> "Source"
    274     """
    275     Returns the `Source` object corresponding to the file the frame is executing in.
    276     """
--> 277     return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/executing/executing.py:296, in Source.for_filename(cls, filename, module_globals, use_cache)
    294 # Save the current linecache entry, then ensure the cache is up to date.
    295 entry = linecache.cache.get(filename) # type: ignore[attr-defined]
--> 296 linecache.checkcache(filename)
    297 lines = get_lines()
    298 if entry is not None and not lines:
    299     # There was an entry, checkcache removed it, and nothing replaced it.
    300     # This means the file wasn't simply changed (because the `lines` wouldn't be empty)
    301     # but rather the file was found not to exist, probably because `filename` was fake.
    302     # Restore the original entry so that we still have something.

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/linecache.py:74, in checkcache(filename)
     72     continue   # no-op for files loaded via a __loader__
     73 try:
---> 74     stat = os.stat(fullname)
     75 except OSError:
     76     cache.pop(filename, None)

File /usr/lib/fedai/miniconda/envs/hik_kernel_env/lib/python3.8/site-packages/ray/_private/worker.py:1640, in sigterm_handler(signum, frame)
   1639 def sigterm_handler(signum, frame):
-> 1640     sys.exit(signum)

SystemExit: 15
```
```


### Reproduction code to reproduce the issue.

```shell
我的模型参数设置如下：

from secretflow.ml.boost.sgb_v import Sgb
# xgb = Xgb(spu)
xgb = Sgb(heu_x)

start = time.time()

params = {
    # <<< !!! >>> change args to your test settings.
    # for more detail, see Xgb.train.__doc__
    "num_boost_round": 20,
    "max_depth": 5,
    "learning_rate": 0.3,
    "sketch_eps": 0.05,
    "objective": "logistic",
    "reg_lambda": 1,
    "subsample": 0.75,
    "colsample_by_tree": 1,
    "base_score": 0.58,
}
```
```

**Comment by da-niao-dan** [comment]
你好，
的确不应该发生这样的事情，还请提供一下完整的代码，特别是x和y和所属，维度，等信息。

**Comment by hanweidong** [comment]
> 你好， 的确不应该发生这样的事情，还请提供一下完整的代码，特别是x和y和所属，维度，等信息。

你好 ，我的数据情况如下：
1、x方（有标签）：39143*166
2、y方（无标签）：39143*83

完整代码如下：
```
import sys
import time
import logging

from secretflow.ml.boost.ss_xgb_v import Xgb
from secretflow.device.driver import wait, reveal
from secretflow.data import FedNdarray, PartitionWay

from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score


# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
import spu
import secretflow as sf
sf.shutdown()
cluster_config ={
    'parties': {
        'alice': {
            # replace with alice's real address.
            'address': '10.3.70.138:9923',
            'listen_addr': '0.0.0.0:9923'
        },
        'bob': {
            # replace with bob's real address.
            'address': '10.3.70.140:9924',
            'listen_addr': '0.0.0.0:9924'
        },
    },
    'self_party': 'bob'
}


# Use ray head adress please.
sf.init(address='10.3.70.140:9914', 
        cluster_config=cluster_config
)

spu_config={
    'nodes': [
        {
            'party': 'alice',
            'id': '0',
            'address': '10.3.70.138:9933',
            'listen_addr': '0.0.0.0:9933'
        },
        {
            'party': 'bob',
            'id': '1',
            'address': '10.3.70.140:9934',
            'listen_addr': '0.0.0.0:9934'
        },
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
        'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
    }
}

link_desc = {
    'connect_retry_times': 60,
    'recv_timeout_ms': 60 * 60 * 1000,
}

spu = sf.SPU(cluster_def=spu_config,link_desc=link_desc)

# spu = sf.SPU(cluster_def=cluster_def)


alice, bob = sf.PYU('alice'), sf.PYU('bob')
# HEU settings
heu_config = {
    "sk_keeper": {"party": "alice"},
    "evaluators": [{"party": "bob"}],
    "mode": "PHEU",  # 这里修改同态加密相关配置
    "he_parameters": {
        "schema": "ou",
        "key_pair": {
            "generate": {
                "bit_size": 2048,
            },
        },
    },
    "encoding": {
        "cleartext_type": "DT_I32",
        "encoder": "IntegerEncoder",
        "encoder_args": {"scale": 1},
    },
}
import copy

heu_x = sf.HEU(heu_config, spu_config["runtime_config"]["field"])
heu_config = copy.deepcopy(heu_config)
sk_keeper = heu_config["sk_keeper"]
evaluator = heu_config["evaluators"][0]
heu_config["sk_keeper"] = evaluator
heu_config["evaluators"][0] = sk_keeper
heu_y = sf.HEU(heu_config, spu_config["runtime_config"]["field"])
# 最初处理的数据集
from secretflow.data.vertical import read_csv as v_read_csv

vdf = v_read_csv({alice:'/home/hwd/competition/code/competition/test/data/alice_train.csv', bob:'/home/hwd/competition/code/competition/test/data/bob_train.csv'})
vdf
data = vdf.drop(columns="label").values
label = vdf[['label']].values
data, label
y = reveal(label.partitions[alice])
from secretflow.ml.boost.sgb_v import Sgb
# xgb = Xgb(spu)
xgb = Sgb(heu_x)

start = time.time()

params = {
    # <<< !!! >>> change args to your test settings.
    # for more detail, see Xgb.train.__doc__
    "num_boost_round": 20,
    "max_depth": 5,
    "learning_rate": 0.3,
    "sketch_eps": 0.05,
    "objective": "logistic",
    "reg_lambda": 1,
    "subsample": 0.75,
    "colsample_by_tree": 1,
    "base_score": 0.58,
}
model = xgb.train(params, data, label)
logging.info(f"main train time: {time.time() - start}")

start = time.time()
spu_yhat = model.predict(data)
yhat = reveal(spu_yhat)
logging.info(f"main predict time: {time.time() - start}")
logging.info(f"main auc: {roc_auc_score(y, yhat)}")
```

**Comment by da-niao-dan** [comment]
经过一些排查，我们发现当特征列的数据有大量NaN值的时候，qcut可能会失败。值得注意的是，这个出现问题特征的确不适合分桶。

当前版本还需要用户处理好特征数据，后续版本中会给出对于含NaN值的警告和更明确的报错。

**Comment by da-niao-dan** [comment]
后续版本将会强制检查nan值，建议先处理了缺失值再训练，后续可能会更新这一个行为。暂时先关闭这个issue
