### ISSUE TITLE
如何在训练时提高cpu使用率？

### ISSUE THREAD

**Issue by dutyu** [secretflow/secretflow#608]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.8.2

### OS Platform and Distribution

Linux Centos 7

### Python version

3.8.13

### What happend and What you expected to happen.

使用生产模式通过docker部署3个节点，1个server, 2个trainer，docker启动没有限制资源，ray启动命令如下：
`ray start --head --port="${RAY_PORT}" --num-cpus="${CPU_NUM}" --include-dashboard=False --disable-usage-stats --block`

其中CPU_NUM=44，但是我们进行xgb横向联邦训练时发现对cpu使用率一直不高，top后基本上在100%左右，实际机器有44个核心，top信息如下：

![image](https://github.com/secretflow/secretflow/assets/5926365/818c4963-46d1-438d-a6cf-0cb6cac6e2ef)

训练的数据规模比较大1900维，上百万行。那么如何能在训练时尽可能的提高cpu使用率呢？

代码如下:
```python
data = read_csv({trainer_a: '/home/sf/jupyter/workplace/wangxiangyu/data/jt_a_app_subscore/part_a.csv', 
                 trainer_b: '/home/sf/jupyter/workplace/wangxiangyu/data/jt_a_app_subscore/part_b.csv'},
                aggregator=aggregator,
                comparator=comparator)
###参数
params = {
    'booster':'gbtree',
    'objective':'binary:logistic',
    'eval_metric':'auc',
    'learning_rate':0.1,
    'num_leaves':16,
    'max_depth':4,
    'min_child_weight':25,
    'subsample':0.8,
    'colsample_bytree':0.8,
    'alpha':1,
    'lambda':1,
    'gamma':0,
    'max_bin':128,
    'seed': 12,
    'eta': 0.3,
    'nthread': 45,
    # Special params in SFXgboost
    # Required
    'hess_key': 'hess',  # Required, Mark hess columns, optionally choosing a column name that is not in the demo set
    'grad_key': 'grad',  # Required，Mark grad columns, optionally choosing a column name that is not in the demo set
    'label_key': 'class',  # Required，ark label columns, optionally choosing a column name that is not in the demo set
}
num_round = 1000
bst = SFXgboost(server=server, clients=[trainer_a, trainer_b])
bst.train(data, data, params=params, num_boost_round=num_round, early_stopping_rounds=1000)
```

目前训练过程阻塞在`bst.train(data, data, params=params, num_boost_round=num_round, early_stopping_rounds=1000)`这一句，打印日志如下：
```log
2023-05-31 05:53:37 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party trainer_a.
2023-05-31 05:53:37 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party trainer_b.
2023-05-31 05:53:37 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party server.
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 WARNING xla_bridge.py:463 [trainer_b] --  No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
2023-05-31 05:58:21 WARNING xla_bridge.py:463 [trainer_b] --  No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2023-05-31 05:58:24 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party trainer_a.
2023-05-31 05:58:24 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party trainer_b.
(raylet) Spilled 10928 MiB, 1 objects, write throughput 516 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
2023-05-31 06:00:15 INFO homo_binning.py:153 [trainer_b] --  start recursive
(raylet) Spilled 10930 MiB, 2 objects, write throughput 516 MiB/s.
(raylet) Spilled 10931 MiB, 3 objects, write throughput 516 MiB/s.
```

更新：
我们发现跑了一段时间后，训练挂掉了，日志如下：
```log
2023-05-31 05:53:37 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party trainer_a.
2023-05-31 05:53:37 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party trainer_b.
2023-05-31 05:53:37 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party server.
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(RecverProxyActor pid=1403) 2023-05-31 05:58:21 WARNING xla_bridge.py:463 [trainer_b] --  No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
2023-05-31 05:58:21 INFO xla_bridge.py:455 [trainer_b] --  Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
2023-05-31 05:58:21 WARNING xla_bridge.py:463 [trainer_b] --  No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2023-05-31 05:58:24 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party trainer_a.
2023-05-31 05:58:24 INFO proxy.py:180 [trainer_b] --  Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party trainer_b.
(raylet) Spilled 10928 MiB, 1 objects, write throughput 516 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
2023-05-31 06:00:15 INFO homo_binning.py:153 [trainer_b] --  start recursive
(raylet) Spilled 10930 MiB, 2 objects, write throughput 516 MiB/s.
(raylet) Spilled 10931 MiB, 3 objects, write throughput 516 MiB/s.
(HomoBooster pid=1797) [06:38:00] WARNING: ../src/learner.cc:767: 
(HomoBooster pid=1797) Parameters: { "num_leaves" } are not used.
(HomoBooster pid=1797) 
(HomoBooster pid=1797) INFO:fed.cleanup:Start check sending thread.
(HomoBooster pid=1797) INFO:fed.cleanup:Start check sending monitor thread.
2023-05-31 06:38:02 WARNING cleanup.py:59 [trainer_b] --  Failed to send ObjectRef(15ada42b51bdd80fbaa4ef74c361b33723c5eda60100000001000000) with error: ray::SendProxyActor.send() (pid=1483, ip=10.220.161.208, repr=<fed.barriers.SendProxyActor object at 0x7fe2701aa7f0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::HomoBooster.homo_train() (pid=1797, ip=10.220.161.208, repr=<secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster object at 0x7f7fab3c9ca0>)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/homo_booster_worker.py", line 145, in homo_train
    self.bst = train(
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 207, in train
    bst = _train_internal(
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 135, in _train_internal
    bst.federate_update(params, dtrain, hdata, global_bin, iter_round=i, fobj=obj)
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/core.py", line 117, in federate_update
    train_data, _ = train_test_split(
TypeError: train_test_split() got an unexpected keyword argument 'ratio'
2023-05-31 06:38:02 WARNING cleanup.py:62 [trainer_b] --  Signal self to exit.
2023-05-31 06:38:02 INFO cleanup.py:66 [trainer_b] --  Check sending thread was exited.
*** SIGTERM received at time=1685515082 on cpu 44 ***
PC: @     0x7fa731039dc3  (unknown)  clone
    @     0x7fa732012ce0       3632  (unknown)
    @ ... and at least 1 more frames
[2023-05-31 06:38:02,049 E 1260 1397] logging.cc:361: *** SIGTERM received at time=1685515082 on cpu 44 ***
[2023-05-31 06:38:02,049 E 1260 1397] logging.cc:361: PC: @     0x7fa731039dc3  (unknown)  clone
[2023-05-31 06:38:02,049 E 1260 1397] logging.cc:361:     @     0x7fa732012ce0       3632  (unknown)
[2023-05-31 06:38:02,049 E 1260 1397] logging.cc:361:     @ ... and at least 1 more frames
---------------------------------------------------------------------------
RayTaskError(TypeError)                   Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[4], line 2
      1 bst = SFXgboost(server=server, clients=[trainer_a, trainer_b])
----> 2 bst.train(data, data, params=params, num_boost_round=num_round, early_stopping_rounds=1000)

File /usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/homo_booster.py:190, in SFXgboost.train(self, train_hdf, valid_hdf, params, num_boost_round, obj, feval, maximize, early_stopping_rounds, evals_result, verbose_eval, xgb_model, callbacks)
    176         self.fed_bst[worker.device] = worker.homo_train(
    177             train_hdf=mock_df,
    178             valid_hdf=mock_df,
   (...)
    188             callbacks=callbacks,
    189         )
--> 190 reveal(self.fed_bst)

File /usr/local/lib/python3.8/site-packages/secretflow/device/driver.py:155, in reveal(func_or_object, heu_encoder)
    154 cur_idx = 0
--> 155 all_object = sfd.get(all_object_refs)
    157 new_flatten_val = []

File /usr/local/lib/python3.8/site-packages/secretflow/distributed/primitive.py:73, in get(object_refs)
     72 if production_mode():
---> 73     return fed.get(object_refs)
     74 else:

File /usr/local/lib/python3.8/site-packages/fed/api.py:411, in get(fed_objects)
    409         ray_refs.append(received_ray_object_ref)
--> 411 values = ray.get(ray_refs)
    412 if is_individual_id:

File /usr/local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File /usr/local/lib/python3.8/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
   2308 if isinstance(value, RayTaskError):
-> 2309     raise value.as_instanceof_cause()
   2310 else:

RayTaskError(TypeError): ray::HomoBooster.homo_train() (pid=1797, ip=10.220.161.208, repr=<secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster object at 0x7f7fab3c9ca0>)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/homo_booster_worker.py", line 145, in homo_train
    self.bst = train(
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 207, in train
    bst = _train_internal(
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/training.py", line 135, in _train_internal
    bst.federate_update(params, dtrain, hdata, global_bin, iter_round=i, fobj=obj)
  File "/usr/local/lib/python3.8/site-packages/secretflow/ml/boost/homo_boost/boost_core/core.py", line 117, in federate_update
    train_data, _ = train_test_split(
TypeError: train_test_split() got an unexpected keyword argument 'ratio'

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

File /usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:2105, in InteractiveShell.showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2103         stb = value._render_traceback_()
   2104     else:
-> 2105         stb = self.InteractiveTB.structured_traceback(
   2106             etype, value, tb, tb_offset=tb_offset
   2107         )
   2109 except Exception:
   2110     print(
   2111         "Unexpected exception formatting exception. Falling back to standard exception"
   2112     )

File /usr/local/lib/python3.8/site-packages/IPython/core/ultratb.py:1396, in AutoFormattedTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1394 else:
   1395     self.tb = etb
-> 1396 return FormattedTB.structured_traceback(
   1397     self, etype, evalue, etb, tb_offset, number_of_lines_of_context
   1398 )

File /usr/local/lib/python3.8/site-packages/IPython/core/ultratb.py:1287, in FormattedTB.structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1284 mode = self.mode
   1285 if mode in self.verbose_modes:
   1286     # Verbose modes need a full traceback
-> 1287     return VerboseTB.structured_traceback(
   1288         self, etype, value, tb, tb_offset, number_of_lines_of_context
   1289     )
   1290 elif mode == 'Minimal':
   1291     return ListTB.get_exception_only(self, etype, value)

File /usr/local/lib/python3.8/site-packages/IPython/core/ultratb.py:1140, in VerboseTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1131 def structured_traceback(
   1132     self,
   1133     etype: type,
   (...)
   1137     number_of_lines_of_context: int = 5,
   1138 ):
   1139     """Return a nice text document describing the traceback."""
-> 1140     formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1141                                                            tb_offset)
   1143     colors = self.Colors  # just a shorthand + quicker name lookup
   1144     colorsnormal = colors.Normal  # used a lot

File /usr/local/lib/python3.8/site-packages/IPython/core/ultratb.py:1030, in VerboseTB.format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1027 assert isinstance(tb_offset, int)
   1028 head = self.prepare_header(str(etype), self.long_header)
   1029 records = (
-> 1030     self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
   1031 )
   1033 frames = []
   1034 skipped = 0

File /usr/local/lib/python3.8/site-packages/IPython/core/ultratb.py:1081, in VerboseTB.get_records(self, etb, number_of_lines_of_context, tb_offset)
   1079 before = context - after
   1080 if self.has_colors:
-> 1081     style = get_style_by_name("default")
   1082     style = stack_data.style_with_executing_node(style, self._tb_highlight)
   1083     formatter = Terminal256Formatter(style=style)

File /usr/local/lib/python3.8/site-packages/pygments/styles/__init__.py:89, in get_style_by_name(name)
     86     cls = name.title() + "Style"
     88 try:
---> 89     mod = __import__('pygments.styles.' + mod, None, None, [cls])
     90 except ImportError:
     91     raise ClassNotFound("Could not find style module %r" % mod +
     92                      (builtin and ", though it should be builtin") + ".")

File <frozen importlib._bootstrap>:991, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:975, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:671, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:839, in exec_module(self, module)

File <frozen importlib._bootstrap_external>:934, in get_code(self, fullname)

File <frozen importlib._bootstrap_external>:1033, in get_data(self, path)

File /usr/local/lib/python3.8/site-packages/ray/_private/worker.py:1640, in sigterm_handler(signum, frame)
   1639 def sigterm_handler(signum, frame):
-> 1640     sys.exit(signum)

SystemExit: 15
```

### Reproduction code to reproduce the issue.

```shell
不是bug，咨询下如何提高cpu使用率
```

**Comment by zhangxingmeng** [comment]
这个问题是指在使用行采样的时候会遇到吗？看起来是遗留的一个bug，我这边快速修复下

**Comment by dutyu** [comment]
> core

应该是用户指定了`subsample`参数时会触发

**Comment by dutyu** [comment]
> 这个问题是指在使用行采样的时候会遇到吗？看起来是遗留的一个bug，我这边快速修复下

看到你提交的pr了，多谢～
这边有个新的疑问，我这边更新了一下代码重新训练了下，代码如下：
```python
train_hdf = read_csv({trainer_a: '/home/sf/jupyter/workplace/wangxiangyu/data/jt_a_app_subscore/part_a.csv', 
                 trainer_b: '/home/sf/jupyter/workplace/wangxiangyu/data/jt_a_app_subscore/part_b.csv'},
                aggregator=aggregator,
                comparator=comparator)
valid_hdf = read_csv({trainer_a: '/home/sf/jupyter/workplace/wangxiangyu/data/jt_a_app_subscore/part_a_valid.csv', 
                 trainer_b: '/home/sf/jupyter/workplace/wangxiangyu/data/jt_a_app_subscore/part_b_valid.csv'},
                aggregator=aggregator,
                comparator=comparator)

params = {
    'booster':'gbtree',
    'objective':'binary:logistic',
    'eval_metric':'auc',
    'num_leaves':16,
    'max_depth':4,
    'min_child_weight':25,
    # 'subsample':0.8,
    'colsample_bytree':0.8,
    'alpha':1,
    'lambda':1,
    'gamma':0,
    'max_bin':128,
    'seed': 12,
    'eta': 0.1,
    'nthread': 45,
    # Special params in SFXgboost
    # Required
    'hess_key': 'hess',  # Required, Mark hess columns, optionally choosing a column name that is not in the demo set
    'grad_key': 'grad',  # Required，Mark grad columns, optionally choosing a column name that is not in the demo set
    'label_key': 'class',  # Required，ark label columns, optionally choosing a column name that is not in the demo set
}
num_round = 100

bst = SFXgboost(server=server, clients=[trainer_a, trainer_b])
bst.train(train_hdf, valid_hdf, params=params, num_boost_round=num_round, early_stopping_rounds=100)
```
目前已经跑了一个半小时，开始跑的时候的时候`ray::HomoBinnin`进程还能占用100%左右的cpu，但是目前发现基本上所有进程都不繁忙。

client端top信息如下：

```log
top - 10:44:26 up 575 days,  1:12,  0 users,  load average: 0.29, 0.24, 0.24
Tasks:  25 total,   1 running,  24 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.1 us,  0.2 sy,  0.1 ni, 99.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 128437.1 total,  71559.6 free,  15654.9 used,  41222.7 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  97054.3 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                           
10716 sf        20   0   56.1g 266504  83476 S   6.0   0.2   5:09.74 python                                                                                                                                                            
10940 sf        35  15   41.6g 157372  57728 S   1.7   0.1   1:23.63 ray::SendProxyA                                                                                                                                                   
11098 sf        35  15   41.0g  72136  23232 S   1.7   0.1   1:16.85 ray::IDLE                                                                                                                                                         
11099 sf        35  15   50.3g  17.4g   8.6g S   1.7  13.9   4:30.56 ray::IDLE                                                                                                                                                         
11100 sf        35  15   43.9g   4.7g   2.3g S   1.7   3.7   2:07.30 ray::IDLE                                                                                                                                                         
11324 sf        35  15   41.8g 214500  72828 S   1.7   0.2   1:23.34 ray::HomoBooste                                                                                                                                                   
11815 sf        35  15   42.2g   9.2g   8.6g S   1.7   7.3  25:15.25 ray::HomoBinnin                                                                                                                                                   
  461 sf        20   0 2524144  62000  19336 S   1.3   0.0   2:42.86 python                                                                                                                                                            
  714 sf        20   0 2376032  61156  19096 S   1.3   0.0   1:33.33 python                                                                                                                                                            
10860 sf        35  15   52.7g 137324  55348 S   1.3   0.1   1:29.08 ray::RecverProx                                                                                                                                                   
11018 sf        35  15   41.7g 212576  74276 S   1.3   0.2   1:24.70 ray::_Masker                                                                                                                                                      
  423 sf        20   0 2332260  29112   8168 S   0.7   0.0   1:14.68 gcs_server                                                                                                                                                        
  699 sf        20   0   78.2g  76844   9348 S   0.7   0.1   1:23.69 raylet                                                                                                                                                            
  359 sf        20   0 2722396  71724  21800 S   0.3   0.1   0:07.93 ray                                                                                                                                                               
  776 sf        20   0 2461144  73500  20168 S   0.3   0.1   0:19.19 python                                                                                                                                                            
    1 root      20   0   11908   1600   1336 S   0.0   0.0   0:00.03 bootstrap.sh                                                                                                                                                      
  358 root      20   0  101900   3344   2476 S   0.0   0.0   0:00.00 su                                                                                                                                                                
  359 sf        20   0 2722396  71724  21800 S   0.0   0.1   0:07.92 ray                                                                                                                                                               
  476 sf        20   0 2610664  72416  20000 S   0.0   0.1   0:08.27 python                                                                                                                                                            
  776 sf        20   0 2461144  73500  20168 S   0.0   0.1   0:19.18 python                                                                                                                                                            
 1261 sf        20   0   12484   2340   1796 S   0.0   0.0   0:00.07 bash                                                                                                                                                              
 4196 sf        20   0   12484   2292   1760 S   0.0   0.0   0:00.05 bash                                                                                                                                                              
10671 sf        20   0   12484   2328   1784 S   0.0   0.0   0:00.05 bash                                                                                                                                                              
11411 root      20   0   12040   2144   1612 S   0.0   0.0   0:00.04 bash                                                                                                                                                              
17008 root      20   0   49156   2144   1488 R   0.0   0.0   0:00.08 top 
```

client端训练程序日志如下：
```
2023-05-31 09:26:59 INFO proxy.py:180 [trainer_a] --  Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party trainer_a.
2023-05-31 09:26:59 INFO proxy.py:180 [trainer_a] --  Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party trainer_b.
2023-05-31 09:26:59 INFO proxy.py:180 [trainer_a] --  Create proxy actor <class 'secretflow.ml.boost.homo_boost.homo_booster_worker.HomoBooster'> with party server.
2023-05-31 09:30:00 INFO xla_bridge.py:455 [trainer_a] --  Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
2023-05-31 09:30:00 INFO xla_bridge.py:455 [trainer_a] --  Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
2023-05-31 09:30:00 INFO xla_bridge.py:455 [trainer_a] --  Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
2023-05-31 09:30:00 INFO xla_bridge.py:455 [trainer_a] --  Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
2023-05-31 09:30:00 WARNING xla_bridge.py:463 [trainer_a] --  No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
(RecverProxyActor pid=10860) 2023-05-31 09:30:00 INFO xla_bridge.py:455 [trainer_a] --  Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(RecverProxyActor pid=10860) 2023-05-31 09:30:00 INFO xla_bridge.py:455 [trainer_a] --  Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
(RecverProxyActor pid=10860) 2023-05-31 09:30:00 INFO xla_bridge.py:455 [trainer_a] --  Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
(RecverProxyActor pid=10860) 2023-05-31 09:30:00 INFO xla_bridge.py:455 [trainer_a] --  Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
(RecverProxyActor pid=10860) 2023-05-31 09:30:00 WARNING xla_bridge.py:463 [trainer_a] --  No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2023-05-31 09:30:02 INFO proxy.py:180 [trainer_a] --  Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party trainer_a.
2023-05-31 09:30:02 INFO proxy.py:180 [trainer_a] --  Create proxy actor <class 'secretflow.preprocessing.binning.homo_binning_base.HomoBinningBase'> with party trainer_b.
2023-05-31 09:31:36 INFO homo_binning.py:153 [trainer_a] --  start recursive
```

数据规模：1900+维，每个client有70行数据，client端使用docker启的，没有ray oom异常，看起来内存是够用的，就想咨询下这个现象是正常的么，因为这个验证任务比较紧急，想尽快确认下训练有无问题？

**Comment by zhangxingmeng** [comment]
不正常我这边30w数据也是很快就训完了
![image](https://github.com/secretflow/secretflow/assets/103552200/bab70916-8772-401b-a4ea-5727326e74a7)

cpu利用率也不会很低
