### ISSUE TITLE
运行官方手册第三方psi时报错

### ISSUE THREAD

**Issue by lvying0019** [secretflow/secretflow#66]
### Issue Type

Bug

### Source

source

### Secretflow Version

最新版

### OS Platform and Distribution

centos 7.6

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=89408, ip=172.16.160.4, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f6822262d60>)
  File "/mnt/hgfs/code/secretflow/secretflow/device/device/spu.py", line 125, in __init__
    self.link = link.create_brpc(desc, rank)
RuntimeError: what: 
	[external/yasl/yasl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=2
stacktrace: 
#0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f6874c28ed7
#1 pybind11::cpp_function::dispatcher()+0x7f6874c150cb
#2 PyCFunction_Call+0x43bdca
```

### Reproduction code to reproduce the issue.

```shell
运行说明书中三方psi的第10步
```

**Comment by 6fj** [comment]
Hi @lvying0019 ,

1. 可否将提供更完整的trace
2. 可以参考这个[回复](https://github.com/secretflow/secretflow/issues/30#issuecomment-1181263227)调整一下端口SPU内部的端口设置吗？并请确保设置的端口没有被占用。
3. 请问你目前的机器配置是如何的？隐语推荐的最低配置是8c16g。

**Comment by lvying0019** [comment]
> Hi @lvying0019 ,
> 
> 1. 可否将提供更完整的trace
> 2. 可以参考这个[回复](https://github.com/secretflow/secretflow/issues/30#issuecomment-1181263227)调整一下端口SPU内部的端口设置吗？并请确保设置的端口没有被占用。
> 3. 请问你目前的机器配置是如何的？隐语推荐的最低配置是8c16g。

错误信息如下：
```bash
RayActorError                             Traceback (most recent call last)
Input In [10], in <cell line: 3>()
      1 input_path = {alice: '.data/alice.csv', bob: '.data/bob.csv', carol: '.data/carol.csv'}
      2 output_path = {alice: '.data/alice_psi.csv', bob: '.data/bob_psi.csv', carol: '.data/carol_psi.csv'}
----> 3 spu_3pc.psi_csv(['uid', 'month'], input_path, output_path, protocol='ecdh')

File /mnt/hgfs/code/secretflow/secretflow/device/device/spu.py:484, in SPU.psi_csv(self, key, input_path, output_path, protocol, sort)
    464 def psi_csv(
    465     self,
    466     key: Union[str, Iterable[str]],
   (...)
    470     sort=True,
    471 ):
    472     """Private set intersection with csv file.
    473 
    474     Args:
   (...)
    482         List[Dict]: PSI reports output by SPU with order reserved.
    483     """
--> 484     return dispatch('psi_csv', self, key, input_path, output_path, protocol, sort)

File /mnt/hgfs/code/secretflow/secretflow/device/device/register.py:111, in dispatch(name, self, *args, **kwargs)
    101 def dispatch(name: str, self, *args, **kwargs):
    102     """Dispatch device kernel.
    103 
    104     Args:
   (...)
    109         Kernel execution result.
    110     """
--> 111     return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)

File /mnt/hgfs/code/secretflow/secretflow/device/device/register.py:80, in Registrar.dispatch(self, device_type, name, *args, **kwargs)
     78 if name not in self._ops[device_type]:
     79     raise KeyError(f'device: {device_type}, op: {name} not registered')
---> 80 return self._ops[device_type][name](*args, **kwargs)

File /mnt/hgfs/code/secretflow/secretflow/device/kernels/spu.py:177, in psi_csv(device, key, input_path, output_path, protocol, sort)
    174         res.append(actor.psi_csv.remote(key, ipath, opath, protocol, sort))
    176 # wait for all tasks done
--> 177 return ray.get(res)

File /usr/local/software/python/venv/secretflow-38/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File /usr/local/software/python/venv/secretflow-38/lib/python3.8/site-packages/ray/worker.py:1845, in get(object_refs, timeout)
   1843             raise value.as_instanceof_cause()
   1844         else:
-> 1845             raise value
   1847 if is_individual_id:
   1848     values = values[0]

RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=89408, ip=172.16.160.4, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f6822262d60>)
  File "/mnt/hgfs/code/secretflow/secretflow/device/device/spu.py", line 125, in __init__
    self.link = link.create_brpc(desc, rank)
RuntimeError: what: 
	[external/yasl/yasl/link/context.cc:140] connect to mesh failed, failed to setup connection to rank=2
stacktrace: 
#0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f6874c28ed7
#1 pybind11::cpp_function::dispatcher()+0x7f6874c150cb
#2 PyCFunction_Call+0x43bdca
```
我是在电脑里面装的虚拟机，配置可能没那么大。
电脑端口信息如下：
``` bash
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51559      ESTABLISHED
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51469      ESTABLISHED
tcp        0      0 localhost:48991         localhost:59222         ESTABLISHED
tcp        0      0 localhost:53558         localhost:44886         ESTABLISHED
tcp        0      0 localhost:57162         localhost:35324         ESTABLISHED
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51466      ESTABLISHED
tcp        0      0 localhost:57138         localhost:35324         ESTABLISHED
tcp        0      0 localhost:53558         localhost:44898         ESTABLISHED
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51467      ESTABLISHED
tcp        0      0 localhost:34910         localhost:57714         ESTABLISHED
tcp        0      0 localhost:36570         localhost:37496         ESTABLISHED
tcp        0      0 localhost:34936         localhost:57714         ESTABLISHED
tcp        0      0 localhost:59178         localhost:48991         ESTABLISHED
tcp        0      0 localhost:36582         localhost:37496         ESTABLISHED
tcp        0      0 localhost:48991         localhost:59234         ESTABLISHED
tcp        0      0 localhost:47104         localhost:50094         ESTABLISHED
tcp        0      0 localhost:44898         localhost:53558         ESTABLISHED
tcp        0      0 localhost.localdoma:ssh 172.16.160.1:54746      ESTABLISHED
tcp        0      0 localhost:50094         localhost:47096         ESTABLISHED
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51465      ESTABLISHED
tcp        0      0 localhost:59222         localhost:48991         ESTABLISHED
tcp        0      0 localhost:44874         localhost:53558         ESTABLISHED
tcp        0      0 localhost:48991         localhost:59178         ESTABLISHED
tcp        0      0 localhost:35324         localhost:57138         ESTABLISHED
tcp        0      0 localhost:49786         localhost:39900         ESTABLISHED
tcp        0      0 localhost:53558         localhost:44874         ESTABLISHED
tcp        0      0 localhost:53558         localhost:44836         ESTABLISHED
tcp        0      0 localhost:35324         localhost:57162         ESTABLISHED
tcp        0      0 localhost:57974         localhost:39623         ESTABLISHED
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51557      ESTABLISHED
tcp        0      0 localhost:50094         localhost:47104         ESTABLISHED
tcp        0      0 localhost.localdoma:ssh 172.16.160.1:65483      ESTABLISHED
tcp        0      0 localhost:59210         localhost:48991         ESTABLISHED
tcp        0      0 localhost:47128         localhost:50094         ESTABLISHED
tcp        0      0 localhost:57714         localhost:34910         ESTABLISHED
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51468      ESTABLISHED
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51558      ESTABLISHED
tcp        0      0 localhost:50094         localhost:47116         ESTABLISHED
tcp        0      0 localhost:47096         localhost:50094         ESTABLISHED
tcp        0      0 localhost:59234         localhost:48991         ESTABLISHED
tcp        0      0 localhost:39623         localhost:57974         ESTABLISHED
tcp        0      0 localhost:37496         localhost:36570         ESTABLISHED
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51464      ESTABLISHED
tcp        0      0 localhost:44886         localhost:53558         ESTABLISHED
tcp        0      0 localhost:36558         localhost:37496         ESTABLISHED
tcp        0      0 localhost:49786         localhost:39922         ESTABLISHED
tcp        0      0 localhost:47116         localhost:50094         ESTABLISHED
tcp        0      0 localhost:37496         localhost:36558         ESTABLISHED
tcp        0      0 localhost:48991         localhost:59210         ESTABLISHED
tcp        0      0 localhost:40488         localhost:42022         CLOSE_WAIT 
tcp        0      0 localhost:39922         localhost:49786         ESTABLISHED
tcp        0      0 localhost:39900         localhost:49786         ESTABLISHED
tcp        0      0 localhost:44836         localhost:53558         ESTABLISHED
tcp        0      0 localhost.loc:ddi-tcp-1 172.16.160.1:51556      ESTABLISHED
tcp        0      0 localhost:57714         localhost:34936         ESTABLISHED
tcp        0      0 localhost:50094         localhost:47128         ESTABLISHED
tcp        0      0 localhost:37496         localhost:36582         ESTABLISHED
tcp        0      0 localhost.localdoma:ssh 172.16.160.1:63078      ESTABLISHED
```

**Comment by 6fj** [comment]
> Hi @lvying0019 ,
> 
> 1. 可否将提供更完整的trace
> 2. 可以参考这个[回复](https://github.com/secretflow/secretflow/issues/30#issuecomment-1181263227)调整一下端口SPU内部的端口设置吗？并请确保设置的端口没有被占用。
> 3. 请问你目前的机器配置是如何的？隐语推荐的最低配置是8c16g。

请先follow第二条建议。
BTW，你现在的配置是怎么样的，其他example是否可以成功运行呢？

**Comment by 6fj** [comment]
Hi @lvying0019 ，

1. 可否试着将https://secretflow.readthedocs.io/en/latest/tutorial/PSI_On_SPU.html 第9步替换为

```
sf.shutdown()

sf.init(['alice', 'bob', 'carol'], num_cpus=8, log_to_driver=False)

alice, bob, carol = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol')
spu_3pc = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob', 'carol']))
```
确保3pc的spu可以创建成功。

2. 请确保你正在使用最新的代码来build from source。

感谢。

**Comment by lvying0019** [comment]
> Hi @lvying0019 ，
> 
> 1. 可否试着将https://secretflow.readthedocs.io/en/latest/tutorial/PSI_On_SPU.html 第9步替换为
> 
> ```
> sf.shutdown()
> 
> sf.init(['alice', 'bob', 'carol'], num_cpus=8, log_to_driver=False)
> 
> alice, bob, carol = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol')
> spu_3pc = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob', 'carol']))
> ```
> 
> 确保3pc的spu可以创建成功。
> 
> 2. 请确保你正在使用最新的代码来build from source。
> 
> 感谢。

感谢，已经已经可以正常运行了
