### ISSUE TITLE
PIP安装问题

### ISSUE THREAD

**Issue by BJTUpupil** [secretflow/secretflow#696]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

0.8.3b0

### OS Platform and Distribution

Windows 11 专业版

### Python version

3.8

### What happend and What you expected to happen.

```shell
pip install -U secretflow
```

### Reproduction code to reproduce the issue.

```shell
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting secretflow
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3c/d6/90e65201b1dbcf357de5ce233117da0cde9ed1612c0a5e05148de84467cd/secretflow-0.7.7b0.tar.gz (163 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\12035\AppData\Local\Temp\pip-install-8bbrymt4\secretflow_71c4c41574ed462592c169f827a8f751\setup.py", line 100, in <module>
          install_requires=read_requirements(),
        File "C:\Users\12035\AppData\Local\Temp\pip-install-8bbrymt4\secretflow_71c4c41574ed462592c169f827a8f751\setup.py", line 17, in read_requirements
          with open('./requirements.txt') as file:
      FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
问题的原因是secretflow不支持windows平台~

**Comment by BJTUpupil** [comment]
我瞎了，求管理员给删掉这个issue

**Comment by litterqi** [comment]
hello，我在wsl中安装也碰到了这个问题，请问你知道如何解决吗
