### ISSUE TITLE
SPU做500万和10亿数据集求交时发生问题

### ISSUE THREAD

**Issue by enidastronomical** [secretflow/secretflow#707]
我们在使用ecdh和kkrt做500万和10亿数据集求交时发生了如下问题，请问这个应该怎么解决呢？谢谢

[2023-07-05 03:16:30.157] [info] [bucket_psi.cc:211] bucket size set to 1048576
[2023-07-05 03:16:30.157] [info] [bucket_psi.cc:103] Begin sanity check for input file: /root/fastpsi/5m.csv, precheck_switch:true
[2023-07-05 03:16:32.231] [info] [csv_checker.cc:125] Executing duplicated scripts: LC_ALL=C sort --buffer-size=1G --temporary-directory=fastpsi_execute20230704135956 --stable selected-keys.1688519790158176827 | LC_ALL=C uniq -d > duplicate-keys.1688519790158176827
[2023-07-05 03:39:17.582] [info] [bucket_psi.cc:121] End sanity check for input file: /root/fastpsi/5m.csv, size=5000000
I0705 03:39:17.759143 13474 external/com_github_brpc_brpc/src/brpc/socket.cpp:2236] Checking Socket{id=0 addr=10.88.167.99:1212} (0x21a5b80)
I0705 03:39:20.760469 13470 external/com_github_brpc_brpc/src/brpc/socket.cpp:2296] Revived Socket{id=0 addr=10.88.167.99:1212} (0x21a5b80) (Connectable)

Traceback (most recent call last):
  File "/usr/local/bin/spu", line 65, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/usr/local/bin/spu", line 58, in main
    report = psi.bucket_psi(setup_link(FLAGS.rank), config, FLAGS.ic_mode)
  File "/usr/local/lib/python3.8/dist-packages/spu/binding/psi.py", line 48, in bucket_psi
    report_str = _lib.libs.bucket_psi(link, config.SerializeToString(), ic_mode)
RuntimeError: what: 
        [external/yacl/yacl/link/transport/channel.cc:83] Get data timeout, key=root:275:ALLGATHER
stacktrace: 
#0 yacl::link::Context::RecvInternal()+0x7ff502fee6e2
#1 yacl::link::AllGatherImpl<>()+0x7ff502fea415
#2 yacl::link::AllGather()+0x7ff502fea7c4
#3 spu::psi::BucketPsi::Run()+0x7ff502ea0b7a
#4 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7ff501e32708
#5 pybind11::cpp_function::dispatcher()+0x7ff501e11c5b
#6 PyCFunction_Call+0x5f2cc9

I0705 03:41:19.534473 13444 external/com_github_brpc_brpc/src/brpc/server.cpp:1130] Server[yacl::link::internal::ReceiverServiceImpl] is going to quit
2023-07-05 03:41:19 - spu execution failed for input file: /root/fastpsi/5m.csv, cost time: 1494 seconds, err logs: 
2023-07-05 03:41:19 - 
2023-07-05 03:41:19 - Retrying failed tasks (Attempt: 33)

**Comment by zhanglei486** [comment]
可以试一下把precheck=false

**Comment by enidastronomical** [comment]
> 可以试一下把precheck=false

请问precheck=false是怎么设置呢，是在指令里增加
“-precheck false”字段吗？

**Comment by Chrisdehe** [comment]
hi，@enidastronomical 
在reports方法中有一个 precheck_input（查重）的参数，请将它的值改为false。
