### ISSUE TITLE
Ray的安装或版本问题

### ISSUE THREAD

**Issue by Hisaft** [secretflow/secretflow#725]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

1.0.0b3

### OS Platform and Distribution

MacOS 13.2

### Python version

3.8.17

### What happend and What you expected to happen.

```shell
在安装完ray以后，python中执行“import secretflow as sf” 就会报错。有一个解决办法就是不安装ray，用secretflow安装包集成的部分ray的组件也可以完成模拟（像是运行“ray start“ 和 ”ray status“ 可以运行，但运行”ray --version“会提示未安装ray）。想和开发人员反馈一下，问一下能否支持安装ray或指定版本的ray？
```

### Reproduction code to reproduce the issue.

```shell
>>> import secretflow as sf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/__init__.py", line 16, in <module>
    from . import (
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/data/__init__.py", line 15, in <module>
    from . import horizontal, vertical
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/data/horizontal/__init__.py", line 15, in <module>
    from .dataframe import HDataFrame
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/data/horizontal/dataframe.py", line 21, in <module>
    from secretflow.data.base import DataFrameBase, Partition
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/data/base.py", line 24, in <module>
    from secretflow.device import PYUObject, reveal
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/device/__init__.py", line 15, in <module>
    from .device import *
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/device/device/__init__.py", line 16, in <module>
    from .heu import HEU
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/device/device/heu.py", line 28, in <module>
    import secretflow.distributed as sfd
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/distributed/__init__.py", line 16, in <module>
    from .primitive import get, kill, production_mode, remote, set_production, shutdown
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 20, in <module>
    import fed
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/fed/__init__.py", line 15, in <module>
    from fed.api import (get, init, kill, remote,
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/fed/api.py", line 23, in <module>
    import fed._private.compatible_utils as compatible_utils
  File "/Users/chenmingxu/miniconda3/envs/sftest/lib/python3.8/site-packages/fed/_private/compatible_utils.py", line 20, in <module>
    from ray._private.gcs_utils import GcsClient
ImportError: cannot import name 'GcsClient' from 'ray._private.gcs_utils'
```

**Comment by zhouaihui** [comment]
安装secretflow的时候默认会安装ray的secretflow版本，secretflow-ray，所以正常情况下你不需要再单独安装ray。

1. secretflow-ray和ray不能同时安装，会有冲突。
2. 如果确实需要安装自己的ray，请确保先卸载secretflow-ray干净，然后再安装ray，建议版本2.2。

**Comment by Hisaft** [comment]
好的，感谢回复
