### ISSUE TITLE
TEEU仿真模式

### ISSUE THREAD

**Issue by tongxinfen** [secretflow/secretflow#726]
### Issue Type

Bug

### Source

binary

### Secretflow Version

1.0.0b0 

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
按照https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/teeu#non-simulation-mode文档中部署authmanager，alice，bob和carol，并运行代码后，出现报错
```

### Reproduction code to reproduce the issue.

```shell
2023-07-12 07:25:58,454 WARNING worker.py:1851 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 154, in _run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/kernels/pyu.py", line 157, in create_auth
    data_uuid, data_key = auth_frame.create_auth(
  File "/usr/local/lib/python3.8/site-packages/sdc/auth_frame.py", line 217, in create_auth
    self.register_public_key(owner_id, public_key_pem)
  File "/usr/local/lib/python3.8/site-packages/sdc/auth_frame.py", line 109, in register_public_key
    response = self.stub.RegisterInsPubKey(request)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for host of AuthManager: C-ares status is not ARES_SUCCESS qtype=A name=host of AuthManager is_balancer=0: Could not contact DNS servers"
        debug_error_string = "UNKNOWN:DNS resolution failed for host of AuthManager: C-ares status is not ARES_SUCCESS qtype=A name=host of AuthManager is_balancer=0: Could not contact DNS servers {grpc_status:14, created_time:"2023-07-12T07:25:58.444639182+00:00"}"

其中authmanger和carol运行在同一台机器上，alice和bob运行在不同机器上，确保demo.py中各party方的ip地址是对的，三方能够通信，但是会有线程报错
```

**Comment by zhouaihui** [comment]
"Could not contact DNS servers"
 报错的意思是连接不上DNS服务，请确保你的DNS服务是可用的。
