### ISSUE TITLE
secretflow是否支撑GRPC路由模式？

### ISSUE THREAD

**Issue by Niclouge** [secretflow/secretflow#740]
### Issue Type

Others

### Source

source

### Secretflow Version

secretflow 0.8.2b1

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
secretflow是否支持GRPC路由模式？即A->GRPC路由1->GRPC路由2->B，然后B->GRPC路由2->GRPC路由1->A。
在生产环境中，为了保证安全性，服务器一般都在内网中，使得双方服务器都没有办法直连，于是我们考虑用GRPC路由的方式做一个转发，在尝试的过程中，发生了以下错误，

在最开始，出现了BRPC标准的问题，无法解析baidu_std的响应：
2023-07-20 14:28:30 INFO cleanup.py:85 [party_1] --  Start check sending thread.
2023-07-20 14:28:30 INFO cleanup.py:91 [party_1] --  Start check sending monitor thread.
(SPURuntime pid=4825) 2023-07-20 14:28:32.349 [error] [input_messenger.cpp:BRPC:109] Fail to parse response from 192.168.200.114:6679 by baidu_std at client-side
2023-07-20 14:28:32 WARNING cleanup.py:59 [party_1] --  Failed to send ObjectRef(0d12401e8fa9a714d8de2acc9ff89bdf76cae7fd0200000001000000) with error: ray::SendProxyActor.send() (pid=4789, ip=192.168.200.156, repr=<fed.barriers.SendProxyActor object at 0x7f5044389a60>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_run() (pid=4833, ip=192.168.200.156)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_run() (pid=4833, ip=192.168.200.156)

于是，通过对SPU的阅读，设置了link_desc={"brpc_channel_protocol": "h2:grpc"}，然后又出现了下述的错误
对于A方：
023-07-21 10:21:01 INFO cleanup.py:85 [party_1] --  Start check sending thread.
2023-07-21 10:21:01 INFO cleanup.py:91 [party_1] --  Start check sending monitor thread.
(SPURuntime pid=17182) 2023-07-21 10:21:11,779	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=17182, ip=192.168.200.156, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fed18883940>)
(SPURuntime pid=17182)   File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 306, in __init__
(SPURuntime pid=17182)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=17182) RuntimeError: what: 
(SPURuntime pid=17182) 	[external/yacl/yacl/link/context.cc:167] connect to mesh failed, failed to setup connection to rank=1
(SPURuntime pid=17182) stacktrace: 
(SPURuntime pid=17182) #0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fed233f3f0d
(SPURuntime pid=17182) #1 pybind11::cpp_function::dispatcher()+0x7fed233db6d6
(SPURuntime pid=17182) #2 PyCFunction_Call+0x559aa253c052

对于B方：
2023-07-21 10:21:12,745 WARNING worker.py:1851 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what: 
        [external/yacl/yacl/link/context.cc:167] connect to mesh failed, failed to setup connection to rank=0
stacktrace: 
#0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f3942b2b55d
#1 pybind11::cpp_function::dispatcher()+0x7f3942b16b5c
#2 PyCFunction_Call+0x4f5592



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/root/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
    return f"SPURuntime(device_id={self.id}, party={self.party})"
AttributeError: 'SPURuntime' object has no attribute 'id'
An unexpected internal error occurred while the worker was executing a task.
2023-07-21 10:21:12,746 WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff2b2c0e30a8ba40bfe14bacef07000000 Worker ID: 65c38eabb32f5531ee032e1d249a04b9e35e1402f92dd2bd0a48da0b Node ID: d535c4677951b5022d4d829032542e8cd32cd7d707454dadac7ae806 Worker IP address: 192.168.200.191 Worker port: 10028 Worker PID: 23262 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
```

### Reproduction code to reproduce the issue.

```shell
看了报错信息，集中在SPU这里，同样有Ray的错误，
在出现baidu_std的时候，修改了SPU的配置
spu_object = sf.SPU(cluster_def=spu_config, link_desc={"brpc_channel_protocol": "h2:grpc"})

其中，
spu_config = {
                'nodes': [
                    {
                        'party': 'party_1',
                        'address': '192.168.200.156:6679',                                                  
                        'listen_address': '192.168.200.156:6679'
                    },
                    {
                        'party': 'party_2',
                        'address': '192.168.200.191:6679',
                        'listen_address': '192.168.200.191:6679'
                    }
                ],
                'runtime_config': {
                    'protocol': spu.spu_pb2.SEMI2K,
                    'field': spu.spu_pb2.FM128
                },
            }
cluster_config = {
                'parties': {
                    'party_1': {
                        'address': '192.168.200.156:6678'
                    },
                    'party_2': {
                        'address': '192.168.200.191:6678’
                    }
                },
                'self_party': config['fedConfig']['selfParty']
            }

在这里，端口设置为6677、6678、6679

验证过程中的转发如下：
 192.168.200.156:6677 -> 192.168.200.114:6677 ->192.168.200.191:6677
 192.168.200.156:6678 -> 192.168.200.114:6678 ->192.168.200.191:6678
 192.168.200.156:6679 -> 192.168.200.114:6679 ->192.168.200.191:6679

192.168.200.191:6677 -> 192.168.200.114:16677 ->192.168.200.156:6677
192.168.200.191:6678 -> 192.168.200.114:16678 ->192.168.200.156:6678
192.168.200.191:6679 -> 192.168.200.114:16679 ->192.168.200.156:6679

这里暂时是验证通过一个GRPC路由完成转发，192.168.200.114做转发，请问这种情况下该如何该如何做？
```

**Comment by Niclouge** [comment]
接上面，考虑到是不是连接时间的问题，所以设置了连接重新连接时间，超时时间等，还是在创建任务的时候失败了
link_desc = {
            "connect_retry_times": 6000,
            "connect_retry_interval_ms": 6000,
            "recv_timeout_ms": 600000,
            "brpc_channel_protocol": "h2:grpc",
        }
spu_object = sf.SPU(cluster_def=spu_config, link_desc=link_desc)

023-07-21 13:53:53 INFO cleanup.py:85 [party_1] --  Start check sending thread.
2023-07-21 13:53:53 INFO cleanup.py:91 [party_1] --  Start check sending monitor thread.
(SPURuntime pid=22117) 2023-07-21 13:53:54,925	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=22117, ip=192.168.200.156, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f2d311858b0>)
(SPURuntime pid=22117)   File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 306, in __init__
(SPURuntime pid=22117)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=22117) RuntimeError: what: 
(SPURuntime pid=22117) 	[external/yacl/yacl/link/transport/channel_brpc.cc:373] send, peer failed message=dispatch error, key=connect_00, error=[external/yacl/yacl/link/transport/channel_brpc.cc:79] dispatch error, listener rank=0 not found
(SPURuntime pid=22117) stacktrace: 
(SPURuntime pid=22117) #0 yacl::link::ChannelBase::TestSend()+0x7f2d3cfe7faf
(SPURuntime pid=22117) #1 yacl::link::Context::ConnectToMesh()+0x7f2d3cfe35d3
(SPURuntime pid=22117) #2 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f2d3bd10f0d
(SPURuntime pid=22117) #3 pybind11::cpp_function::dispatcher()+0x7f2d3bcf86d6
(SPURuntime pid=22117) #4 PyCFunction_Call+0x557f1ace1052

**Comment by zhouaihui** [comment]
SecretFlow用的是标准grpc和brpc，这两套rpc框架都是支持中间路由的。SecretFlow自带的框架[kuscia](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans)已经支持通信路由和端口归一，可以考虑配合kuscia一起使用，也可以参考kuscia的具体实现 [kuscia-envoy](https://github.com/secretflow/kuscia-envoy)。

**Comment by Niclouge** [comment]
收到，谢谢

**Comment by awencai** [comment]
hello, 请问这个问题你怎么解决的。我也遇到了 ` 'SPURuntime' object has no attribute 'id'` 报错，辛苦讲一下解决思路和方法，感谢

**Comment by awencai** [comment]
> hello, 请问这个问题你怎么解决的。我也遇到了 ` 'SPURuntime' object has no attribute 'id'` 报错，辛苦讲一下解决思路和方法，感谢

已解决，spu 端口防火墙拦截导致 spu 未能成功启动。

**Comment by Niclouge** [comment]
> hello, 请问这个问题你怎么解决的。我也遇到了 ` 'SPURuntime' object has no attribute 'id'` 报错，辛苦讲一下解决思路和方法，感谢

这里其实是两方的SPU没有互通引起的，一方已经起了，成功连接然后发送成功，但是另外一方起了之后，没有成功连接，没有连接的一方会报这样的错误。
建议：
1、检查两方的机器是够能够正常连接，如果是通过GRPC路由的话，GRPC要双方都能连接上，可以ping一下；
2、检查双方的SPU配置是否编写正确。

**Comment by awencai** [comment]
> > hello, 请问这个问题你怎么解决的。我也遇到了 ` 'SPURuntime' object has no attribute 'id'` 报错，辛苦讲一下解决思路和方法，感谢
> 
> 这里其实是两方的SPU没有互通引起的，一方已经起了，成功连接然后发送成功，但是另外一方起了之后，没有成功连接，没有连接的一方会报这样的错误。在连接的时候会有一个ping的过程，但是还是要注意端口这一点，之前我是因为GRPC路由端口配置的有问题，无法转发消息，所以报错。 建议： 1、检查两方的机器是够能够正常连接，如果是通过GRPC路由的话，GRPC要双方都能连接上，可以ping一下； 2、检查双方的SPU配置是否编写正确。

THANKS :)
