### ISSUE TITLE
[问题] 关于集群模式仿真

### ISSUE THREAD

**Issue by ZhouZhaoJi** [secretflow/secretflow#782]
我的局域网有三台不同的机器，10.154.24.6，10.154.24.10和10.154.24.11。
我拉取了secretflow的镜像，并且在这三台机器上，各自运行一个secretflow的容器，通过下面的命令：
`docker run -it --name sf -p 7890:7890 -p 7891:7891 secretflow/secretflow-anolis8:1.0.0b3`

在10.154.24.6的容器中，我运行了
`ray start --head --node-ip-address="127.0.0.1" --port="7890" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats`
在10.154.24.10容器中，运行
`ray start --address="10.154.24.6:7890" --resources='{"bob": 16}' --disable-usage-stats`
运行上面命令时，报错`global_state_accessor.cc:390: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?`
在10.154.24.11容器中，运行
`ray start --address="10.154.24.6:7890" --resources='{"joe": 16}' --disable-usage-stats`

在10.154.24.6容器中运行python，输入下面的代码：
```
import spu
import secretflow as sf
sf.init(parties=['bob','joe'], address='10.154.24.6:7890')

cluster_def={
    'nodes': [
    	{
            'party': 'bob',
            'address': '10.154.24.10:7891',
            'listen_addr': '0.0.0.0:7891'
        },
        {
            'party': 'joe',
            'address': '10.154.24.11:7891',
            'listen_addr': '0.0.0.0:7891'
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.CHEETAH,
        'field': spu.spu_pb2.FM128,
    }
}
spu = sf.SPU(cluster_def=cluster_def)
```
报错：
(scheduler +1m10s) Error: No available node types can fulfill resource request {'joe': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +1m10s) Error: No available node types can fulfill resource request {'bob': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.

这是为什么？

**Comment by ZhouZhaoJi** [comment]
![image](https://github.com/secretflow/secretflow/assets/36101779/b859db21-c44a-4674-abda-dae5b493fab0)
节点并没有添加成功，感觉是网络没有搞对，但也不知道什么原因。

**Comment by Chrisdehe** [comment]
hi,@ZhouZhaoJi 

`sf.init(parties=['bob','joe'], address='10.154.24.6:7890')
`
>>>>>
`sf.init(parties=['alice','bob','joe'], address='10.154.24.6:7890')
`

**Comment by Chrisdehe** [comment]
请参考以下配置：
`import spu
import secretflow as sf
sf.init(parties=['alice','bob','joe'], address='10.154.24.6:7890')

cluster_def={
    'nodes': [
{
            'party': 'alice',
            'address': '10.154.24.06:7891',
            'listen_addr': '0.0.0.0:7891'
        },
    	{
            'party': 'bob',
            'address': '10.154.24.10:7891',
            'listen_addr': '0.0.0.0:7891'
        },
        {
            'party': 'joe',
            'address': '10.154.24.11:7891',
            'listen_addr': '0.0.0.0:7891'
        }
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.CHEETAH,
        'field': spu.spu_pb2.FM128,
    }
}
spu = sf.SPU(cluster_def=cluster_def)`

**Comment by ZhouZhaoJi** [comment]
```
2023-07-26 02:29:12,846     WARNING worker.py:1851 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what:
        [external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
stacktrace:
#0 yacl::link::FactoryBrpc::CreateContext()+0x7f84e03fc1d7
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f84df07b54f
#2 pybind11::cpp_function::dispatcher()+0x7f84df066b5c
#3 PyCFunction_Call+0x4e0212



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
    return f"SPURuntime(device_id={self.id}, party={self.party})"
AttributeError: 'SPURuntime' object has no attribute 'id'
An unexpected internal error occurred while the worker was executing a task.
2023-07-26 02:29:12,849 WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffcdf308e1e15db536e5f4bb9701000000 Worker ID: 2418d7789b1cdfd36df2402321b2c8990e3fe50950e4bf91887e30e2 Node ID: 7fe37180074afd0438bd55a362b40082f37a8b4c53507c4d6233d305 Worker IP address: 172.17.0.2 Worker port: 10003 Worker PID: 890 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what:
        [external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
stacktrace:
#0 yacl::link::FactoryBrpc::CreateContext()+0x7f84e03fc1d7
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f84df07b54f
#2 pybind11::cpp_function::dispatcher()+0x7f84df066b5c
#3 PyCFunction_Call+0x4e0212



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
    return f"SPURuntime(device_id={self.id}, party={self.party})"
AttributeError: 'SPURuntime' object has no attribute 'id'
An unexpected internal error occurred while the worker was executing a task.
(SPURuntime pid=890) 2023-07-26 02:29:12.819 [error] [server.cpp:BRPC:1011] Fail to listen 10.154.24.6:7891
(SPURuntime pid=890) 2023-07-26 02:29:12.842 [warning] [channel.h:~ChannelBase:116] ChannelBase destructor is called before WaitLinkTaskFinish, try stop send thread
(SPURuntime pid=890) 2023-07-26 02:29:12.842 [warning] [channel.h:~ChannelBase:116] ChannelBase destructor is called before WaitLinkTaskFinish, try stop send thread
(SPURuntime pid=890) 2023-07-26 02:29:12,844    ERROR worker.py:763 -- Worker exits with an exit code None.
(SPURuntime pid=890)  Traceback (most recent call last):
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
(SPURuntime pid=890)     return method(__ray_actor, *args, **kwargs)
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(SPURuntime pid=890)     return method(self, *_args, **_kwargs)
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
(SPURuntime pid=890)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=890) RuntimeError: what:
(SPURuntime pid=890)    [external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
(SPURuntime pid=890) stacktrace:
(SPURuntime pid=890) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f84e03fc1d7
(SPURuntime pid=890) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f84df07b54f
(SPURuntime pid=890) #2 pybind11::cpp_function::dispatcher()+0x7f84df066b5c
(SPURuntime pid=890) #3 PyCFunction_Call+0x4e0212
(SPURuntime pid=890)
(SPURuntime pid=890)
(SPURuntime pid=890)
(SPURuntime pid=890) During handling of the above exception, another exception occurred:
(SPURuntime pid=890)
(SPURuntime pid=890) Traceback (most recent call last):
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(SPURuntime pid=890)     return method(self, *_args, **_kwargs)
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
(SPURuntime pid=890)     return f"SPURuntime(device_id={self.id}, party={self.party})"
(SPURuntime pid=890) AttributeError: 'SPURuntime' object has no attribute 'id'
(SPURuntime pid=890) An unexpected internal error occurred while the worker was executing a task.
(SPURuntime pid=890) Traceback (most recent call last):
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
(SPURuntime pid=890)     return method(__ray_actor, *args, **kwargs)
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(SPURuntime pid=890)     return method(self, *_args, **_kwargs)
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
(SPURuntime pid=890)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=890) RuntimeError: what:
(SPURuntime pid=890)    [external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
(SPURuntime pid=890) stacktrace:
(SPURuntime pid=890) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f84e03fc1d7
(SPURuntime pid=890) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f84df07b54f
(SPURuntime pid=890) #2 pybind11::cpp_function::dispatcher()+0x7f84df066b5c
(SPURuntime pid=890) #3 PyCFunction_Call+0x4e0212
(SPURuntime pid=890)
(SPURuntime pid=890)
(SPURuntime pid=890)
(SPURuntime pid=890) During handling of the above exception, another exception occurred:
(SPURuntime pid=890)
(SPURuntime pid=890) Traceback (most recent call last):
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(SPURuntime pid=890)     return method(self, *_args, **_kwargs)
(SPURuntime pid=890)   File "/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
(SPURuntime pid=890)     return f"SPURuntime(device_id={self.id}, party={self.party})"
(SPURuntime pid=890) AttributeError: 'SPURuntime' object has no attribute 'id'
(SPURuntime pid=890)
(SPURuntime pid=890) During handling of the above exception, another exception occurred:
(SPURuntime pid=890)
(SPURuntime pid=890) Traceback (most recent call last):
(SPURuntime pid=890)   File "python/ray/_raylet.pyx", line 1176, in ray._raylet.task_execution_handler
(SPURuntime pid=890) SystemExit
(scheduler +1m23s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(scheduler +1m23s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'joe': 1.0}. Add suitable node types to this cluster to resolve this issue.
(scheduler +1m23s) Error: No available node types can fulfill resource request {'CPU': 1.0, 'bob': 1.0}. Add suitable node types to this cluster to resolve this issue.
```

**Comment by ZhouZhaoJi** [comment]
我尝试换一个端口，不确定是否能解决。

**Comment by ZhouZhaoJi** [comment]
我感觉是docker映射的问题。

**Comment by Chrisdehe** [comment]
ok，brpc启动失败，有三个需要同时注意的点：
1、容器的话在docker run的过程中配置下--net=host，它能够使docker和host共享所有网络端口；
2、端口号占用问题；
3、可以将'nodes'中的监听去掉，改为id。（例如alice：'id': '0'，bob为1，coral为2）
辛苦尝试一下
祝好

**Comment by ZhouZhaoJi** [comment]
解决了

**Comment by Chrisdehe** [comment]
hey，@ZhouZhaoJi 
请问是因为哪点而导致的这个错误呢？

**Comment by ZhouZhaoJi** [comment]
@Chrisdehe 
从
sf.init(parties=['bob','joe'], address='10.154.24.6:7890') 
改为
sf.init(parties=['alice','bob','joe'], address='10.154.24.6:7890') 
就可以了。
集群比如填入所有节点。
