### ISSUE TITLE
Ubuntu中运行import secretflow as sf时出现错误ImportError: cannot import name 'GcsClient' from 'ray._private.gcs_utils' (/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/gcs_utils.py)

### ISSUE THREAD

**Issue by gting1** [secretflow/secretflow#826]
import secretflow as sf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/__init__.py", line 16, in <module>
    from . import (
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/data/__init__.py", line 15, in <module>
    from . import horizontal, vertical
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/data/horizontal/__init__.py", line 15, in <module>
    from .dataframe import HDataFrame
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/data/horizontal/dataframe.py", line 21, in <module>
    from secretflow.data.base import DataFrameBase, Partition
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/data/base.py", line 24, in <module>
    from secretflow.device import PYUObject, reveal
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/__init__.py", line 15, in <module>
    from .device import *
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/__init__.py", line 16, in <module>
    from .heu import HEU
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/heu.py", line 28, in <module>
    import secretflow.distributed as sfd
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/__init__.py", line 16, in <module>
    from .primitive import get, kill, production_mode, remote, set_production, shutdown
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 20, in <module>
    import fed
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/fed/__init__.py", line 15, in <module>
    from fed.api import (get, init, kill, remote,
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/fed/api.py", line 23, in <module>
    import fed._private.compatible_utils as compatible_utils
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/fed/_private/compatible_utils.py", line 20, in <module>
    from ray._private.gcs_utils import GcsClient
ImportError: cannot import name 'GcsClient' from 'ray._private.gcs_utils' (/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/gcs_utils.py)

**Comment by zhouaihui** [comment]
看起来是你安装了非SecretFlow要求的ray版本
1. SecretFlow要求安装secretflow-ray （2.2.0）
2. 请不要同时安装官方ray，会产生冲突。如果有安装，请确保先卸载ray以及secretflow-ray，然后重新安装secretflow-ray

**Comment by gting1** [comment]
删除非官方ray后，是secretflow-ray  2.2.0 与secretflow-rayfed 0.1.1a4这两个版本，
运行后出现了新的错误如下：
import secretflow as sf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/__init__.py", line 16, in <module>
    from . import (
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/data/__init__.py", line 15, in <module>
    from . import horizontal, vertical
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/data/horizontal/__init__.py", line 15, in <module>
    from .dataframe import HDataFrame
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/data/horizontal/dataframe.py", line 21, in <module>
    from secretflow.data.base import DataFrameBase, Partition
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/data/base.py", line 24, in <module>
    from secretflow.device import PYUObject, reveal
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/__init__.py", line 15, in <module>
    from .device import *
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/__init__.py", line 16, in <module>
    from .heu import HEU
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/heu.py", line 28, in <module>
    import secretflow.distributed as sfd
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/__init__.py", line 16, in <module>
    from .primitive import get, kill, production_mode, remote, set_production, shutdown
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 20, in <module>
    import fed
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/fed/__init__.py", line 15, in <module>
    from fed.api import (get, init, kill, remote,
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/fed/api.py", line 23, in <module>
    import fed._private.compatible_utils as compatible_utils
  File "/home/gt/anaconda3/envs/sf/lib/python3.8/site-packages/fed/_private/compatible_utils.py", line 19, in <module>
    import ray.experimental.internal_kv as ray_internal_kv
ModuleNotFoundError: No module named 'ray.experimental'

**Comment by gting1** [comment]
是因为官方ray安装错误吗

**Comment by zhouaihui** [comment]
如果有安装，请确保先卸载ray以及secretflow-ray，然后重新安装secretflow-ray
----
是严格按照上述步骤操作的吗

**Comment by gting1** [comment]
开始只卸载了ray，之后都卸载了并重新安装，已解决，谢谢

**Comment by Niclouge** [comment]
@zhouaihui 
您好，为了搞清楚模块之间的关系，我分别对rayfed/secretflow源码部署，在部署secretflow的时候，注释掉了requirements.txt里面的secretflow-rayfed，然后git clone了rayfed(https://github.com/secretflow/rayfed)的源码，直接源码部署（python setup.py bdist_wheel && pip install dist/*.whl --force-reinstall），也出现了上述的问题。所以有一些疑问：
1、requirements.txt中的secretflow-rayfed和rayfed不是同一个工程么？在pypi中看secretflow-rayfed的homepage，跳转到了ray-project/rayfed，不是secretflow/rayfed；
2、如果想对rayfed做一些改造，两个工程分别源码部署的方式能否适用？

**Comment by zhouaihui** [comment]
使用分支 https://github.com/secretflow/rayfed/tree/secretflow-rayfed
打包文件使用 setup_secretflow.py

**Comment by Niclouge** [comment]
> 使用分支 https://github.com/secretflow/rayfed/tree/secretflow-rayfed 打包文件使用 setup_secretflow.py

好的，谢谢解答，之前一直都是切换了tag就直接打包，然后打包的setup.py。

**Comment by Niclouge** [comment]
> 使用分支 https://github.com/secretflow/rayfed/tree/secretflow-rayfed 打包文件使用 setup_secretflow.py

@zhouaihui 
我在使用secretflow-rayfed分支以及setup_secretflow.py打包之后，还是出现了问题，如下所示，该如何解决

2023-08-22 09:59:49,704	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::SPURuntime.run() (pid=485976, ip=10.0.2.15, repr=<secretflow.device.device.spu.SPURuntime object at 0x7f2a5bd79b20>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_spu_compile() (pid=485753, ip=10.0.2.15)
  File "/home/sunthinker/temp/secretflow/secretflow/device/device/spu.py", line 1226, in _spu_compile
    executable, output_tree = spu_fe.compile(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 112, in compile
    ir_text, output = _jax_compilation(fn, static_argnums, args, kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 41, in _jax_compilation
    cfn, output = jax.xla_computation(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/api.py", line 555, in computation_maker
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/interpreters/mlir.py", line 646, in lower_jaxpr_to_module
    raise ValueError(f"Unknown platform {platform}")
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Unknown platform interpreter

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ray::_spu_compile() (pid=485753, ip=10.0.2.15)
  File "/home/sunthinker/temp/secretflow/secretflow/device/device/spu.py", line 1226, in _spu_compile
    executable, output_tree = spu_fe.compile(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 112, in compile
    ir_text, output = _jax_compilation(fn, static_argnums, args, kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 41, in _jax_compilation
    cfn, output = jax.xla_computation(
ValueError: Unknown platform interpreter

During handling of the above exception, another exception occurred:

ray::_spu_compile() (pid=485753, ip=10.0.2.15)
  File "/home/sunthinker/temp/secretflow/secretflow/device/device/spu.py", line 1238, in _spu_compile
    raise ray.exceptions.WorkerCrashedError()
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
Traceback (most recent call last):
  File "/home/sunthinker/Project/Tidavaless_FL_Component/te.py", line 23, in <module>
    woe_rules = binning.binning(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/preprocessing/binning/vert_woe_binning.py", line 252, in binning
    bins_positive = self.secure_device(spu_work)(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/base.py", line 68, in to
    return dispatch(_name_of_to(device.device_type), self, device, *args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 44, in spu_to_pyu
    return pyu(reveal)(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/pyu.py", line 98, in wrapper
    sfd.remote(self._run)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/remote_function.py", line 226, in remote
    return func_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 108, in _remote
    args, kwargs = _resolve_args(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 98, in _resolve_args
    actual_vals = ray.get(list(refs.values()))
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::SPURuntime.run() (pid=485973, ip=10.0.2.15, repr=<secretflow.device.device.spu.SPURuntime object at 0x7fb3af050b20>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_spu_compile() (pid=485753, ip=10.0.2.15)
  File "/home/sunthinker/temp/secretflow/secretflow/device/device/spu.py", line 1226, in _spu_compile
    executable, output_tree = spu_fe.compile(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 112, in compile
    ir_text, output = _jax_compilation(fn, static_argnums, args, kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 41, in _jax_compilation
    cfn, output = jax.xla_computation(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/api.py", line 555, in computation_maker
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/jax/_src/interpreters/mlir.py", line 646, in lower_jaxpr_to_module
    raise ValueError(f"Unknown platform {platform}")
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Unknown platform interpreter

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ray::_spu_compile() (pid=485753, ip=10.0.2.15)
  File "/home/sunthinker/temp/secretflow/secretflow/device/device/spu.py", line 1226, in _spu_compile
    executable, output_tree = spu_fe.compile(
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 112, in compile
    ir_text, output = _jax_compilation(fn, static_argnums, args, kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py", line 41, in _jax_compilation
    cfn, output = jax.xla_computation(
ValueError: Unknown platform interpreter

During handling of the above exception, another exception occurred:

ray::_spu_compile() (pid=485753, ip=10.0.2.15)
  File "/home/sunthinker/temp/secretflow/secretflow/device/device/spu.py", line 1238, in _spu_compile
    raise ray.exceptions.WorkerCrashedError()
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
Exception ignored in: <function SPUObject.__del__ at 0x7faf85f3b310>
Traceback (most recent call last):
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 170, in __del__
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/actor.py", line 138, in remote
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 425, in _start_span
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/actor.py", line 184, in _remote
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/actor.py", line 171, in invocation
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/actor.py", line 1172, in _actor_method_call
AttributeError: 'Worker' object has no attribute 'core_worker'
Exception ignored in: <function SPUObject.__del__ at 0x7faf85f3b310>
Traceback (most recent call last):
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 170, in __del__
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/actor.py", line 138, in remote
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 425, in _start_span
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/actor.py", line 184, in _remote
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/actor.py", line 171, in invocation
  File "/home/sunthinker/anaconda3/envs/sf/lib/python3.8/site-packages/ray/actor.py", line 1172, in _actor_method_call
AttributeError: 'Worker' object has no attribute 'core_worker'

python的package如下所示：

![image](https://github.com/secretflow/secretflow/assets/44387768/76ff5416-3daf-414e-a271-9b2c1081fb79)

**Comment by zhouaihui** [comment]
按照requirements.txt里面的要求，重新安装一下jax和jaxlib

**Comment by Niclouge** [comment]
> 按照requirements.txt里面的要求，重新安装一下jax和jaxlib

按照rayfed中requirement.txt中的要求，jax和jaxlib版本大于等于0.3.0，还是出现了上面的报错
![image](https://github.com/secretflow/secretflow/assets/44387768/44e64d4e-bfd2-4ed1-85bb-cf114e8cad61)

**Comment by zhouaihui** [comment]
建议更新下代码，rayfed的requirements没有jax，secretflow的requirements对jax/jaxlib的要求是<=4.12

**Comment by Niclouge** [comment]
谢谢，已经可以正常运行了
