### ISSUE TITLE
根据secretflow官方teeu文档运行代码报错

### ISSUE THREAD

**Issue by linushio** [secretflow/secretflow#831]
部分报错如下：
2023-08-21 08:35:12,014 WARNING worker.py:1851 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "/usr/local/lib/python3.8/dist-packages/secretflow/device/device/pyu.py", line 154, in _run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/secretflow/device/kernels/pyu.py", line 157, in create_auth
    data_uuid, data_key = auth_frame.create_auth(
  File "/usr/local/lib/python3.8/dist-packages/sdc/auth_frame.py", line 217, in create_auth
    self.register_public_key(owner_id, public_key_pem)
  File "/usr/local/lib/python3.8/dist-packages/sdc/auth_frame.py", line 109, in register_public_key
    response = self.stub.RegisterInsPubKey(request)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2023-08-21T08:35:12.009811735+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {created_time:"2023-08-21T08:35:12.009800596+00:00", grpc_status:14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 589, in ray._raylet.store_task_errors
  File "python/ray/_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 515, in serialize
    return self._serialize_to_msgpack(value)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 470, in _serialize_to_msgpack
    value = value.to_bytes()
  File "/usr/local/lib/python3.8/dist-packages/ray/exceptions.py", line 32, in to_bytes
    serialized_exception=pickle.dumps(self),
  File "/usr/local/lib/python3.8/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.8/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.RLock' object
An unexpected internal error occurred while the worker was executing a task.
2023-08-21 08:35:12,016 WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 8fa7c299a4f9e9adf220af6b70258e80a133680305000000 Worker ID: c3175509a605ba3bcbf789372fb10b59e73b7d32b0c8c3e7c819334e Node ID: 3b470d834f6d1df8fb483daaeb25a3832d1938b9fce9e3ae487c74ec Worker IP address: 192.168.10.161 Worker port: 10031 Worker PID: 3874 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "/usr/local/lib/python3.8/dist-packages/secretflow/device/device/pyu.py", line 154, in _run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/secretflow/device/kernels/pyu.py", line 157, in create_auth
    data_uuid, data_key = auth_frame.create_auth(
  File "/usr/local/lib/python3.8/dist-packages/sdc/auth_frame.py", line 217, in create_auth
    self.register_public_key(owner_id, public_key_pem)
  File "/usr/local/lib/python3.8/dist-packages/sdc/auth_frame.py", line 109, in register_public_key
    response = self.stub.RegisterInsPubKey(request)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2023-08-21T08:35:12.009811735+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {created_time:"2023-08-21T08:35:12.009800596+00:00", grpc_status:14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 589, in ray._raylet.store_task_errors
  File "python/ray/_raylet.pyx", line 2447, in ray._raylet.CoreWorker.store_task_outputs
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 515, in serialize
    return self._serialize_to_msgpack(value)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 470, in _serialize_to_msgpack
    value = value.to_bytes()
  File "/usr/local/lib/python3.8/dist-packages/ray/exceptions.py", line 32, in to_bytes
    serialized_exception=pickle.dumps(self),
  File "/usr/local/lib/python3.8/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.8/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.RLock' object
An unexpected internal error occurred while the worker was executing a task

**Comment by zhouaihui** [comment]
"failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"

检查一下AuthManager的地址是否正确，以及是否服务正常。

**Comment by linushio** [comment]
> "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
> 
> 检查一下AuthManager的地址是否正确，以及是否服务正常。

[2023-08-21T14:29:26.322285447+08:00] [auth_manager] [INFO] remote endpoint localhost:8341
[2023-08-21T14:29:26.674876151+08:00] [auth_manager] [INFO] Server run at: 0.0.0.0:8835 mode simulation
您好，服务是正常的，authmanager配置是否需要填端口号？目前只填了ip

**Comment by linushio** [comment]
修改后已跑通，感谢
