### ISSUE TITLE
集群模式非仿真部署，psi任务报错， brpc server failed start 'SPURuntime' object has no attribute 'id'

### ISSUE THREAD

**Issue by itux2** [secretflow/secretflow#839]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.0.0b3

### OS Platform and Distribution

centos7

### Python version

3.8.17

### What happend and What you expected to happen.

```shell
按照官方部署文档进行部署，采用生产模式，部署两个节点，独立的ray集群

节点1
RAY_DISABLE_REMOTE_CODE=true \
ray start --head --node-ip-address="172.16.51.11" --port="9394" --resources='{"alice": 8}' --include-dashboard=False

节点2
RAY_DISABLE_REMOTE_CODE=true \
ray start --head --node-ip-address="172.16.51.12" --port="9394" --resources='{"bob": 8}' --include-dashboard=False

执行代码参考 psi_benchmark
https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/developer/benchmark/psi_benchmark

两方分别执行，报错信息如下：


2023-08-23 14:35:59,110	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.16.51.11:9394...
2023-08-23 14:35:59,127	INFO worker.py:1538 -- Connected to Ray cluster.
2023-08-23 14:35:59 INFO api.py:202 [alice] --  Started rayfed with {'CLUSTER_ADDRESSES': {'alice': {'address': '172.16.51.11:12945', 'listen_addr': '0.0.0.0:12945'}, 'bob': {'address': '172.16.51.12:12946', 'listen_addr': '0.0.0.0:12946'}}, 'CURRENT_PARTY_NAME': 'alice', 'TLS_CONFIG': {}, 'CROSS_SILO_SERIALIZING_ALLOWED_LIST': None, 'CROSS_SILO_MESSAGES_MAX_SIZE_IN_BYTES': None, 'CROSS_SILO_TIMEOUT_IN_SECONDS': 3600}
2023-08-23 14:36:00 INFO barriers.py:353 [alice] --  RecverProxy was successfully created.
(RecverProxyActor pid=31201) 2023-08-23 14:36:00 INFO barriers.py:114 [alice] --  Successfully start Grpc service without credentials.
2023-08-23 14:36:01 INFO barriers.py:388 [alice] --  SendProxy was successfully created.
2023-08-23 14:36:01 INFO barriers.py:463 [alice] --  Try ping ['bob'] at 0 attemp, up to 3600 attemps.
2023-08-23 14:36:01 INFO barriers.py:449 [alice] --  Failed to ping bob on 172.16.51.12:12946, this could be normal, the possible reason is bob has not yet started.
2023-08-23 14:36:03 INFO barriers.py:463 [alice] --  Try ping ['bob'] at 1 attemp, up to 3600 attemps.
2023-08-23 14:36:03 INFO barriers.py:444 [alice] --  Succeeded to ping bob on 172.16.51.12:12946, the result: OK.
2023-08-23 14:36:03 INFO cleanup.py:83 [alice] --  Start check sending thread.
2023-08-23 14:36:03 INFO cleanup.py:89 [alice] --  Start check sending monitor thread.
2023-08-23 14:36:05,185	WARNING worker.py:1851 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what:
	[external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
stacktrace:
#0 yacl::link::FactoryBrpc::CreateContext()+0x7f65991271d7
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f6597da654f
#2 pybind11::cpp_function::dispatcher()+0x7f6597d91b5c
#3 PyCFunction_Call+0x4f5592



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
    return f"SPURuntime(device_id={self.id}, party={self.party})"
AttributeError: 'SPURuntime' object has no attribute 'id'
An unexpected internal error occurred while the worker was executing a task.
2023-08-23 14:36:05,188	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff740e7540cecdf36b336fd72403000000 Worker ID: 6bc0c1067f8f1a097e6c1e88cd7f959744d46a85bf5897f624b05219 Node ID: 1123ecfdd965c67501ecb1d13a37fdf0946c912f2b0d7e7678449cbc Worker IP address: 172.16.51.11 Worker port: 10013 Worker PID: 31338 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what:
	[external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
stacktrace:
#0 yacl::link::FactoryBrpc::CreateContext()+0x7f65991271d7
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f6597da654f
#2 pybind11::cpp_function::dispatcher()+0x7f6597d91b5c
#3 PyCFunction_Call+0x4f5592



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
    return f"SPURuntime(device_id={self.id}, party={self.party})"
AttributeError: 'SPURuntime' object has no attribute 'id'
An unexpected internal error occurred while the worker was executing a task.
2023-08-23 14:36:05 WARNING cleanup.py:59 [alice] --  Failed to send ObjectRef(4984f7d6f9a761adb66e249384d887c905da13710300000001000000) with error: ray::SendProxyActor.send() (pid=31270, ip=172.16.51.11, repr=<fed.barriers.SendProxyActor object at 0x7f75c82a2400>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: SPURuntime
	actor_id: 740e7540cecdf36b336fd72403000000
	pid: 31338
	namespace: c5404f12-c7bb-4067-a748-200e60c720e1
	ip: 172.16.51.11
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
    self.link = spu_link.create_brpc(desc, rank)
RuntimeError: what:
	[external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
stacktrace:
#0 yacl::link::FactoryBrpc::CreateContext()+0x7f65991271d7
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f6597da654f
#2 pybind11::cpp_function::dispatcher()+0x7f6597d91b5c
#3 PyCFunction_Call+0x4f5592



During handling of the above exception, another exception occurred:

ray::SendProxyActor.send() (pid=31270, ip=172.16.51.11, repr=<fed.barriers.SendProxyActor object at 0x7f75c82a2400>)
  File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
    return f"SPURuntime(device_id={self.id}, party={self.party})"
AttributeError: 'SPURuntime' object has no attribute 'id'
An unexpected internal error occurred while the worker was executing a task.
2023-08-23 14:36:05 WARNING cleanup.py:62 [alice] --  Signal self to exit.
2023-08-23 14:36:05 INFO cleanup.py:66 [alice] --  Check sending thread was exited.
*** SIGTERM received at time=1692772565 on cpu 24 ***
PC: @     0x7fe7ca799de2  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7fe7ca79d630  (unknown)  (unknown)
    @ ... and at least 8 more frames
[2023-08-23 14:36:05,204 E 31101 31101] logging.cc:361: *** SIGTERM received at time=1692772565 on cpu 24 ***
[2023-08-23 14:36:05,204 E 31101 31101] logging.cc:361: PC: @     0x7fe7ca799de2  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2023-08-23 14:36:05,204 E 31101 31101] logging.cc:361:     @     0x7fe7ca79d630  (unknown)  (unknown)
[2023-08-23 14:36:05,204 E 31101 31101] logging.cc:361:     @ ... and at least 8 more frames
2023-08-23 14:36:05 INFO cleanup.py:101 [alice] --  Notify check sending thread to exit.
(SPURuntime pid=31338) 2023-08-23 14:36:05.156 [error] [server.cpp:BRPC:1011] Fail to listen 0.0.0.0:12945
(SPURuntime pid=31338) 2023-08-23 14:36:05.180 [warning] [channel.h:~ChannelBase:116] ChannelBase destructor is called before WaitLinkTaskFinish, try stop send thread
(SPURuntime pid=31338) 2023-08-23 14:36:05,183	ERROR worker.py:763 -- Worker exits with an exit code None.
(SPURuntime pid=31338)  Traceback (most recent call last):
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
(SPURuntime pid=31338)     return method(__ray_actor, *args, **kwargs)
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(SPURuntime pid=31338)     return method(self, *_args, **_kwargs)
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
(SPURuntime pid=31338)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=31338) RuntimeError: what:
(SPURuntime pid=31338) 	[external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
(SPURuntime pid=31338) stacktrace:
(SPURuntime pid=31338) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f65991271d7
(SPURuntime pid=31338) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f6597da654f
(SPURuntime pid=31338) #2 pybind11::cpp_function::dispatcher()+0x7f6597d91b5c
(SPURuntime pid=31338) #3 PyCFunction_Call+0x4f5592
(SPURuntime pid=31338)
(SPURuntime pid=31338)
(SPURuntime pid=31338)
(SPURuntime pid=31338) During handling of the above exception, another exception occurred:
(SPURuntime pid=31338)
(SPURuntime pid=31338) Traceback (most recent call last):
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(SPURuntime pid=31338)     return method(self, *_args, **_kwargs)
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
(SPURuntime pid=31338)     return f"SPURuntime(device_id={self.id}, party={self.party})"
(SPURuntime pid=31338) AttributeError: 'SPURuntime' object has no attribute 'id'
(SPURuntime pid=31338) An unexpected internal error occurred while the worker was executing a task.
(SPURuntime pid=31338) Traceback (most recent call last):
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
(SPURuntime pid=31338)     return method(__ray_actor, *args, **kwargs)
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(SPURuntime pid=31338)     return method(self, *_args, **_kwargs)
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 308, in __init__
(SPURuntime pid=31338)     self.link = spu_link.create_brpc(desc, rank)
(SPURuntime pid=31338) RuntimeError: what:
(SPURuntime pid=31338) 	[external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
(SPURuntime pid=31338) stacktrace:
(SPURuntime pid=31338) #0 yacl::link::FactoryBrpc::CreateContext()+0x7f65991271d7
(SPURuntime pid=31338) #1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f6597da654f
(SPURuntime pid=31338) #2 pybind11::cpp_function::dispatcher()+0x7f6597d91b5c
(SPURuntime pid=31338) #3 PyCFunction_Call+0x4f5592
(SPURuntime pid=31338)
(SPURuntime pid=31338)
(SPURuntime pid=31338)
(SPURuntime pid=31338) During handling of the above exception, another exception occurred:
(SPURuntime pid=31338)
(SPURuntime pid=31338) Traceback (most recent call last):
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
(SPURuntime pid=31338)     return method(self, *_args, **_kwargs)
(SPURuntime pid=31338)   File "/data/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 320, in __repr__
(SPURuntime pid=31338)     return f"SPURuntime(device_id={self.id}, party={self.party})"
(SPURuntime pid=31338) AttributeError: 'SPURuntime' object has no attribute 'id'
(SPURuntime pid=31338)
(SPURuntime pid=31338) During handling of the above exception, another exception occurred:
(SPURuntime pid=31338)
(SPURuntime pid=31338) Traceback (most recent call last):
(SPURuntime pid=31338)   File "python/ray/_raylet.pyx", line 1176, in ray._raylet.task_execution_handler
(SPURuntime pid=31338) SystemExit
```

### Reproduction code to reproduce the issue.

```shell
两方代码如下：

alice:

import sys
import time
import logging

from absl import app
import spu
import secretflow as sf

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# SPU settings
cluster_def = {
    'nodes': [
        {'party': 'alice', 'address': '172.16.51.11:12945', 'listen_address': '0.0.0.0:12945'},
        {'party': 'bob', 'address': '172.16.51.12:12946', 'listen_address': '0.0.0.0:12946'}
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}


def main(_):

    # sf init
    cluster_config={
        'parties': {
            'alice': {
                # replace with alice's real address.
                'address': '172.16.51.11:12945',
                'listen_addr': '0.0.0.0:12945'
            },
            'bob': {
                # replace with bob's real address.
                'address': '172.16.51.12:12946',
                'listen_addr': '0.0.0.0:12946'
            },
        },
        'self_party': 'alice'
    }
    sf.init( address='172.16.51.11:9394', cluster_config=cluster_config)
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')
# <<< !!! >>> replace path to real parties local file path.
    input_path = {
        alice: '/data/projects/sf-benchmark/psi_1.csv',
        bob: '/data/projects/sf-benchmark/psi_2.csv',
    }
    output_path = {
        alice: '/data/projects/sf-benchmark/psi_output.csv',
        bob: '/data/projects/sf-benchmark/psi_output.csv',
    }
    select_keys = {
        alice: ['id'],
        bob: ['id'],
    }
    spu = sf.SPU(cluster_def, id='11')

    # prepare data
    start = time.time()

    reports = spu.psi_csv(
        key=select_keys,
        input_path=input_path,
        output_path=output_path,
        receiver='alice',  # if `broadcast_result=False`, only receiver can get output file.
        protocol='KKRT_PSI_2PC',        # psi protocol
        precheck_input=False,  # will cost ext time if set True
        sort=False,  # will cost ext time if set True
        broadcast_result=False,  # will cost ext time if set True
    )
    print(f"psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")

    sf.shutdown()


if __name__ == '__main__':
    app.run(main)



bob方执行代码:

import sys
import time
import logging

from absl import app
import spu
import secretflow as sf

# init log
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# SPU settings
cluster_def = {
    'nodes': [
        {'party': 'alice', 'address': '172.16.51.11:12945', 'listen_address': '0.0.0.0:12945'},
        {'party': 'bob', 'address': '172.16.51.12:12946', 'listen_address': '0.0.0.0:12946'}
    ],
    'runtime_config': {
        'protocol': spu.spu_pb2.SEMI2K,
        'field': spu.spu_pb2.FM128,
    },
}


def main(_):

    cluster_config={
        'parties': {
            'alice': {
                # replace with alice's real address.
                'address': '172.16.51.11:12945',
                'listen_addr': '0.0.0.0:12945'
            },
            'bob': {
                # replace with bob's real address.
                'address': '172.16.51.12:12946',
                'listen_addr': '0.0.0.0:12946'
            },
        },
        'self_party': 'bob'
    }
    sf.init( address='172.16.51.12:9394', cluster_config=cluster_config)
    # sf init
    #sf.init(['alice','bob'], address='172.16.51.11:9394')
    alice = sf.PYU('alice')
    bob = sf.PYU('bob')

    # <<< !!! >>> replace path to real parties local file path.
    input_path = {
        alice: '/data/projects/sf-benchmark/psi_1.csv',
        bob: '/data/projects/sf-benchmark/psi_2.csv',
    }
    output_path = {
        alice: '/data/projects/sf-benchmark/psi_output.csv',
        bob: '/data/projects/sf-benchmark/psi_output.csv',
    }
    select_keys = {
        alice: ['id'],
        bob: ['id'],
    }
    spu = sf.SPU(cluster_def, id='12')

    # prepare data
    start = time.time()

    reports = spu.psi_csv(
        key=select_keys,
        input_path=input_path,
        output_path=output_path,
        receiver='alice',  # if `broadcast_result=False`, only receiver can get output file.
        protocol='KKRT_PSI_2PC',        # psi protocol
        precheck_input=False,  # will cost ext time if set True
        sort=False,  # will cost ext time if set True
        broadcast_result=False,  # will cost ext time if set True
    )
    print(f"psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")

    sf.shutdown()


if __name__ == '__main__':
    app.run(main)
```

**Comment by itux2** [comment]
根据报错信息，尝试在初始化spu时增加id 参数， 但报错依然存在

    spu = sf.SPU(cluster_def, id='12')

**Comment by Chrisdehe** [comment]
hi,@itux2
在这行中
`spu = sf.SPU(cluster_def, id='12')`
我们没有“id”的参数，请去掉后重新跑一次
——————————————————
另外，这是spu已有参数的支持，可以参考下
https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/source/secretflow#secretflow.PYU.__init__

**Comment by itux2** [comment]
@Chrisdehe  感谢回复， 问题已解决
原因是rayfed的通信端口和spu的brpc端口设置重复了， 需要设置不同的端口
用来初始化sf的cluster_config和用来初始化spu的cluster_def是两个不同的配置

**Comment by itux2** [comment]
已解决

**Comment by Chrisdehe** [comment]
OK
