### ISSUE TITLE
The examples in the TEEU Getting Started Guide require a minimum of 50 CPU cores to run

### ISSUE THREAD

**Issue by houxiangying** [secretflow/secretflow#860]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow/secretflow-teeu:latest

### OS Platform and Distribution

CentOS Linux release 7.9.2009 (Core)

### Python version

python3.8

### What happend and What you expected to happen.

```shell
I've noticed that the examples in the TEEU Getting Started Guide require a minimum of 50 CPU cores to run. I'm curious about why such a high core count is necessary. This high demand might pose challenges for many users, especially in resource-constrained environments. I'd like to inquire whether it's possible to optimize this requirement to reduce the demand on CPU cores.
```

### Reproduction code to reproduce the issue.

```shell
If the CPU count is below 50,starting the Carol node in Docker will result in the following error:
occlum_instance# occlum run /bin/python /root/demo.py
W0904 02:53:19.467437     2 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:434] Fail to open /proc/self/io: No such file or directory
W0904 02:53:19.511616    44 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:214] Fail to open /proc/self/statm: No such file or directory
W0904 02:53:19.511790    44 external/com_github_brpc_brpc/src/bvar/default_variables.cpp:281] Fail to open /proc/loadavg: No such file or directory
INFO:root:Authority manager config is {'host': '10.143.12.119:8835', 'mr_enclave': ''}
WARNING:ray.worker:File descriptor limit 1024 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
/opt/secretflow/lib/python3.8/site-packages/ray/thirdparty_files/psutil/_pslinux.py:513: RuntimeWarning: buffers, cached, shared, active, inactive memory stats couldn't be determined and were set to 0
  warnings.warn(msg, RuntimeWarning)
2023-09-04 02:53:30,015 INFO services.py:2039 -- object_store_memory is not verified when plasma_directory is set.
Traceback (most recent call last):
  File "/opt/secretflow/lib/python3.8/site-packages/ray/node.py", line 310, in __init__
    ray._private.services.wait_for_node(
  File "/opt/secretflow/lib/python3.8/site-packages/ray/_private/services.py", line 398, in wait_for_node
    raise TimeoutError("Timed out while waiting for node to startup.")
TimeoutError: Timed out while waiting for node to startup.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/demo.py", line 24, in <module>
    sf.init(
  File "/opt/secretflow/lib/python3.8/site-packages/secretflow/device/driver.py", line 480, in init
    fed.init(
  File "/opt/secretflow/lib/python3.8/site-packages/fed/api.py", line 164, in init
    compatible_utils.init_ray(address=address, **kwargs)
  File "/opt/secretflow/lib/python3.8/site-packages/fed/_private/compatible_utils.py", line 55, in init_ray
    ray.init(**kwargs)
  File "/opt/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/secretflow/lib/python3.8/site-packages/ray/worker.py", line 1041, in init
    _global_node = ray.node.Node(
  File "/opt/secretflow/lib/python3.8/site-packages/ray/node.py", line 317, in __init__
    raise Exception(
Exception: The current node has not been updated within 30 seconds, this could happen because of some of the Ray processes failed to startup.
```

**Comment by yuki252111** [comment]
Because ray needs a lot of memory, and occlum needs to allocate a sufficient amount of memory in advance and cannot be dynamically allocated, we will use VM to solve this situation later, so stay tuned

**Comment by houxiangying** [comment]
Ray需要大量内存，并且Occlum需要预先分配内存，而无法动态分配，因此计划在以后使用VM来解决这种情况。
Occlum 在TEE内部的内存分配和隔离机制，使得不同的应用程序或服务在TEE内部不会相互干扰。为了实现这种隔离，Occlum 要求在运行应用程序之前分配一定数量的内存。这个内存分配过程需要一定的计算资源，包括CPU时间。

**Comment by ligw1998** [comment]
I have encountered a similar problem. I guessed this is because the secretflowray is based one the ray version of 0.2.2. When initializing, it does not set the pre-defined number of cpus, but read the number of current machine instead. You can try passing a specified number of cpu cores (e.g. 32) in ray.init().
