### ISSUE TITLE
如果只运行PSI，PIR等安全计算协议，可以少装点依赖吗？

### ISSUE THREAD

**Issue by a7853z** [secretflow/secretflow#880]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

1.1.0.dev230825

### OS Platform and Distribution

CentOS 7

### Python version

3.8.17 

### Bazel version

5.4.1

### GCC/Compiler version

gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC) 

### What happend and What you expected to happen.

```shell
源码安装，由于只想运行下PSI，PIR等协议，希望少装点占用存储大的依赖，在requirements.txt中删掉了
tensorflow-macos
tensorflow
xgboost
torch
torchmetrics
torchvision
torchaudio

完成编译后运行PSI任务，出现如下报错：
An unexpected internal error occurred while the worker was executing a task.
2023-09-13 09:53:04,905	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffc2cadb80cb87e960ef0a6bec03000000 Worker ID: 474f11647f98cb04202d743f726c5cab7c248452eb650ddc21ce5992 Node ID: 6e6c84a2e2f0e6fa2e1b121744c9f7337aa556f0b103a35ceb2e527a Worker IP address: 10.0.50.64 Worker port: 10004 Worker PID: 125487 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name SPURuntime failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/root/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
AttributeError: Can't get attribute 'SPURuntime.outfeed_shares_chunk_count' on <module 'secretflow.device.device.spu' from '/root/miniconda3/envs/sf-benchmark/lib/python3.8/site-packages/secretflow/device/device/spu.p
```

### Reproduction code to reproduce the issue.

```shell
1.删除掉requirements.txt中的一些依赖(tensorflow,torch)
2.源码编译
3.运行psi-benchmark中的psi实例。
```

**Comment by zhouaihui** [comment]
可以安装lite版本 `pip install -U secretflow-lite`

**Comment by a7853z** [comment]
> 可以安装lite版本 `pip install -U secretflow-lite`

好的 我试试
