### ISSUE TITLE
SL模型下载预测问题

### ISSUE THREAD

**Issue by Niclouge** [secretflow/secretflow#929]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow 1.1.0.dev20230918

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.8.16

### What happend and What you expected to happen.

```shell
在应用SLModel的load_model()接口之后，用load的模型evalueate，出现了一个ValueError，看报错应该是在汇聚层的时候没有找到两方的base_model，请问该如何解决？或者是我的代码编写错误，具体报错如下所示：

2023-10-07 10:07:50.004430: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-10-07 10:07:50.487924: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-10-07 10:07:50.487969: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-10-07 10:07:50.487973: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-10-07 10:07:53,471	INFO worker.py:1538 -- Started a local Ray instance.
INFO:root:Create proxy actor <class 'secretflow.ml.nn.sl.backend.tensorflow.sl_base.PYUSLTFModel'> with party alice.
INFO:root:Create proxy actor <class 'secretflow.ml.nn.sl.backend.tensorflow.sl_base.PYUSLTFModel'> with party bob.
(SPURuntime pid=10657) 2023-10-07 10:07:56.279 [info] [default_brpc_retry_policy.cc:DoRetry:52] socket error, sleep=1000000us and retry
(SPURuntime pid=10657) 2023-10-07 10:07:57.279 [info] [default_brpc_retry_policy.cc:LogHttpDetail:29] cntl ErrorCode '112', http status code '200', response header '', error msg '[E111]Fail to connect Socket{id=0 addr=127.0.0.1:46115} (0x0x564a11dabb40): Connection refused [R1][E112]Not connected to 127.0.0.1:46115 yet, server_id=0'
(SPURuntime pid=10657) 2023-10-07 10:07:57.280 [info] [default_brpc_retry_policy.cc:DoRetry:75] aggressive retry, sleep=1000000us and retry
INFO:root:SL Train Params: {'x': VDataFrame(partitions={PYURuntime(alice): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7f26af2b98e0>, PYURuntime(bob): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7f26af2413a0>}, aligned=True), 'y': VDataFrame(partitions={PYURuntime(alice): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7f26af267280>}, aligned=True), 'batch_size': 128, 'epochs': 10, 'verbose': 1, 'callbacks': None, 'validation_data': (VDataFrame(partitions={PYURuntime(alice): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7f26af267a60>, PYURuntime(bob): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7f26af267ac0>}, aligned=True), VDataFrame(partitions={PYURuntime(alice): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7f26af272250>}, aligned=True)), 'shuffle': True, 'sample_weight': None, 'validation_freq': 1, 'dp_spent_step_freq': None, 'dataset_builder': None, 'audit_log_params': {}, 'random_seed': 27850, 'audit_log_dir': None, 'self': <secretflow.ml.nn.sl.sl_model.SLModel object at 0x7f26af2a81f0>}
(pid=10747) 2023-10-07 10:07:58.210993: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=10777) 2023-10-07 10:07:58.264063: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(SPURuntime pid=10657) 2023-10-07 10:07:58.280 [info] [default_brpc_retry_policy.cc:LogHttpDetail:29] cntl ErrorCode '112', http status code '200', response header '', error msg '[E111]Fail to connect Socket{id=0 addr=127.0.0.1:46115} (0x0x564a11dabb40): Connection refused [R1][E112]Not connected to 127.0.0.1:46115 yet, server_id=0 [R2][E112]Not connected to 127.0.0.1:46115 yet, server_id=0'
(SPURuntime pid=10657) 2023-10-07 10:07:58.280 [info] [default_brpc_retry_policy.cc:DoRetry:75] aggressive retry, sleep=1000000us and retry
(SPURuntime pid=10661) 2023-10-07 10:07:58.296 [info] [default_brpc_retry_policy.cc:DoRetry:69] not retry for reached rcp timeout, ErrorCode '1008', error msg '[E1008]Reached timeout=2000ms @127.0.0.1:44575'
(pid=10747) 2023-10-07 10:07:58.968929: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
(pid=10747) 2023-10-07 10:07:58.969005: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
(pid=10747) 2023-10-07 10:07:58.969011: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(pid=10777) 2023-10-07 10:07:59.006209: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
(pid=10777) 2023-10-07 10:07:59.006442: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
(pid=10777) 2023-10-07 10:07:59.006463: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(PYUSLTFModel pid=10747) 2023-10-07 10:08:00.916238: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
(PYUSLTFModel pid=10747) 2023-10-07 10:08:00.916279: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
(PYUSLTFModel pid=10777) 2023-10-07 10:08:00.916237: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
(PYUSLTFModel pid=10777) 2023-10-07 10:08:00.916281: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
(PYUSLTFModel pid=10777) Model: "sequential"
(PYUSLTFModel pid=10777) _________________________________________________________________
(PYUSLTFModel pid=10777)  Layer (type)                Output Shape              Param #   
(PYUSLTFModel pid=10777) =================================================================
(PYUSLTFModel pid=10777)  dense (Dense)               (None, 128)               384       
(PYUSLTFModel pid=10777)                                                                  
(PYUSLTFModel pid=10777) =================================================================
(PYUSLTFModel pid=10777) Total params: 384
(PYUSLTFModel pid=10777) Trainable params: 384
(PYUSLTFModel pid=10777) Non-trainable params: 0
(PYUSLTFModel pid=10777) _________________________________________________________________
(PYUSLTFModel pid=10747) Model: "sequential"
(PYUSLTFModel pid=10747) _________________________________________________________________
(PYUSLTFModel pid=10747)  Layer (type)                Output Shape              Param #   
(PYUSLTFModel pid=10747) =================================================================
(PYUSLTFModel pid=10747)  dense (Dense)               (None, 128)               384       
(PYUSLTFModel pid=10747)                                                                  
(PYUSLTFModel pid=10747) =================================================================
(PYUSLTFModel pid=10747) Total params: 384
(PYUSLTFModel pid=10747) Trainable params: 384
(PYUSLTFModel pid=10747) Non-trainable params: 0
(PYUSLTFModel pid=10747) _________________________________________________________________
(PYUSLTFModel pid=10747) Model: "model"
(PYUSLTFModel pid=10747) __________________________________________________________________________________________________
(PYUSLTFModel pid=10747)  Layer (type)                   Output Shape         Param #     Connected to                     
(PYUSLTFModel pid=10747) ==================================================================================================
(PYUSLTFModel pid=10747)  input_2 (InputLayer)           [(None, 128)]        0           []                               
(PYUSLTFModel pid=10747)                                                                                                   
(PYUSLTFModel pid=10747)  input_3 (InputLayer)           [(None, 128)]        0           []                               
(PYUSLTFModel pid=10747)                                                                                                   
(PYUSLTFModel pid=10747)  concatenate (Concatenate)      (None, 256)          0           ['input_2[0][0]',                
(PYUSLTFModel pid=10747)                                                                   'input_3[0][0]']                
(PYUSLTFModel pid=10747)                                                                                                   
(PYUSLTFModel pid=10747)  dense_1 (Dense)                (None, 64)           16448       ['concatenate[0][0]']            
(PYUSLTFModel pid=10747)                                                                                                   
(PYUSLTFModel pid=10747)  dense_2 (Dense)                (None, 3)            195         ['dense_1[0][0]']                
(PYUSLTFModel pid=10747)                                                                                                   
(PYUSLTFModel pid=10747) ==================================================================================================
(PYUSLTFModel pid=10747) Total params: 16,643
(PYUSLTFModel pid=10747) Trainable params: 16,643
(PYUSLTFModel pid=10747) Non-trainable params: 0
(PYUSLTFModel pid=10747) __________________________________________________________________________________________________
  0%|          | 0/1 [00:00<?, ?it/s]2023-10-07 10:08:01.918728: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-10-07 10:08:01.918751: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
(_run pid=10382) 2023-10-07 10:08:02.192527: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(_run pid=10382) 2023-10-07 10:08:02.999086: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
(_run pid=10382) 2023-10-07 10:08:02.999140: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
(_run pid=10382) 2023-10-07 10:08:02.999146: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(_run pid=10382) 2023-10-07 10:08:04.443526: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
(_run pid=10382) 2023-10-07 10:08:04.443562: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
100%|██████████| 1/1 [00:03<00:00,  3.47s/it, epoch: 1/10 -  train_loss:1.1273828744888306  train_accuracy:0.34166666865348816  val_loss:1.0957878828048706  val_accuracy:0.5666666626930237 ]
100%|██████████| 1/1 [00:00<00:00, 21.54it/s, epoch: 2/10 -  train_loss:1.0258997678756714  train_accuracy:0.6833333373069763  val_loss:1.0197452306747437  val_accuracy:0.4333333373069763 ]
100%|██████████| 1/1 [00:00<00:00, 20.06it/s, epoch: 3/10 -  train_loss:0.9795152544975281  train_accuracy:0.5166666507720947  val_loss:0.9662132859230042  val_accuracy:0.2666666805744171 ]
100%|██████████| 1/1 [00:00<00:00, 32.62it/s, epoch: 4/10 -  train_loss:0.9506603479385376  train_accuracy:0.3499999940395355  val_loss:0.9285690188407898  val_accuracy:0.2666666805744171 ]
100%|██████████| 1/1 [00:00<00:00, 23.38it/s, epoch: 5/10 -  train_loss:0.9256908297538757  train_accuracy:0.38333332538604736  val_loss:0.8989661931991577  val_accuracy:0.2666666805744171 ]
100%|██████████| 1/1 [00:00<00:00, 30.66it/s, epoch: 6/10 -  train_loss:0.8947981595993042  train_accuracy:0.44999998807907104  val_loss:0.8740193247795105  val_accuracy:0.4333333373069763 ]
100%|██████████| 1/1 [00:00<00:00, 27.47it/s, epoch: 7/10 -  train_loss:0.858871579170227  train_accuracy:0.6416666507720947  val_loss:0.8539456725120544  val_accuracy:0.5666666626930237 ]
100%|██████████| 1/1 [00:00<00:00, 27.11it/s, epoch: 8/10 -  train_loss:0.8232128024101257  train_accuracy:0.6916666626930237  val_loss:0.8384859561920166  val_accuracy:0.5666666626930237 ]
100%|██████████| 1/1 [00:00<00:00, 17.85it/s, epoch: 9/10 -  train_loss:0.7918679714202881  train_accuracy:0.6916666626930237  val_loss:0.8234193921089172  val_accuracy:0.5666666626930237 ]
100%|██████████| 1/1 [00:00<00:00, 19.58it/s, epoch: 10/10 -  train_loss:0.7642842531204224  train_accuracy:0.6916666626930237  val_loss:0.8062951564788818  val_accuracy:0.5666666626930237 ]
Evaluate Processing:: 100%|██████████| 1/1 [00:00<00:00, 99.43it/s, loss:0.8062951564788818 accuracy:0.5666666626930237] 
{'loss': 0.80629516, 'accuracy': 0.56666666}
save model
load model
INFO:root:Create proxy actor <class 'secretflow.ml.nn.sl.backend.tensorflow.sl_base.PYUSLTFModel'> with party alice.
(pid=11004) 2023-10-07 10:08:06.211196: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
(pid=11004) 2023-10-07 10:08:06.852072: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
(pid=11004) 2023-10-07 10:08:06.852142: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
(pid=11004) 2023-10-07 10:08:06.852152: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(PYUSLTFModel pid=11004) 2023-10-07 10:08:08.155616: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
(PYUSLTFModel pid=11004) 2023-10-07 10:08:08.155640: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
<secretflow.ml.nn.sl.sl_model.SLModel object at 0x7f26af13a100>
evaluate data
Evaluate Processing::   0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/sunthinker/Project/Tidavaless_FL_Component/algorithm/function_test/multiplelr.py", line 165, in <module>
    print(predict_model.evaluate(test_data, test_label))
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/driver.py", line 132, in wrapper
    return reveal(func_or_object(*arg, **kwargs))
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/ml/nn/sl/sl_model.py", line 644, in evaluate
    report_list = [f"{k}:{v}" for k, v in reveal(metrics).items()]
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/driver.py", line 162, in reveal
    all_object = sfd.get(all_object_refs)
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 75, in get
    return ray.get(object_refs)
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::PYUSLTFModel.evaluate() (pid=11004, ip=192.168.200.102, repr=<secretflow.ml.nn.sl.backend.tensorflow.sl_base.PYUSLTFModel object at 0x7f7ba1163670>)
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/device/proxy.py", line 79, in wrapper
    return method(*args, **kwargs)
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/ml/nn/sl/backend/tensorflow/sl_base.py", line 679, in evaluate
    metrics = self._evaluate_internal(
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_file0bg_05gh.py", line 10, in tf___evaluate_internal
    y_pred = ag__.converted_call(ag__.ld(self).model_fuse, (ag__.ld(hiddens),), dict(training=False, **ag__.ld(self).kwargs), fscope)
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/keras/engine/input_spec.py", line 216, in assert_input_compatibility
    raise ValueError(
ValueError: in user code:

    File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/secretflow/ml/nn/sl/backend/tensorflow/sl_base.py", line 626, in _evaluate_internal  *
        y_pred = self.model_fuse(hiddens, training=False, **self.kwargs)
    File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "/home/sunthinker/anaconda3/envs/secretflow/lib/python3.8/site-packages/keras/engine/input_spec.py", line 216, in assert_input_compatibility
        raise ValueError(

    ValueError: Layer "model" expects 2 input(s), but it received 0 input tensors. Inputs received: []
Evaluate Processing:: 100%|██████████| 1/1 [00:02<00:00,  2.91s/it]

Process finished with exit code 1
```

### Reproduction code to reproduce the issue.

```shell
import pandas as pd
import secretflow as sf
from secretflow.data.split import train_test_split
from secretflow.data.vertical import read_csv as v_read_csv
from secretflow.ml.nn import SLModel
from secretflow.security.privacy import DPStrategy, LabelDP
from secretflow.security.privacy.mechanism.tensorflow import GaussianEmbeddingDP
from sklearn.datasets import load_iris
from tensorflow import keras
from tensorflow.keras import layers

iris = load_iris()
X = iris.data
y = iris.target

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target
iris_df[["petal length (cm)", "petal width (cm)", "target"]].to_csv('iris_dataset_alice.csv', index=False)
iris_df[["sepal length (cm)", "sepal width (cm)"]].to_csv('iris_dataset_bob.csv', index=False)

sf.init(['alice', 'bob'], address='local')
alice, bob = sf.PYU('alice'), sf.PYU('bob')
spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))

data = v_read_csv({
    alice: "./iris_dataset_alice.csv",
    bob: "./iris_dataset_bob.csv"
})

label = data["target"]
data = data.drop(columns=["target"])

random_state = 1234
train_data, test_data = train_test_split(
    data, train_size=0.8, random_state=random_state
)
train_label, test_label = train_test_split(
    label, train_size=0.8, random_state=random_state
)


# 基础模型，包含两层
def create_base_model(input_dim, output_dim, name="base_model"):
    def create_model():
        model = keras.Sequential(
            [
                keras.Input(shape=input_dim),
                keras.layers.Dense(output_dim, activation='relu')
            ]
        )
        model.summary()
        model.compile(optimizer='adam',
                      loss='sparse_categorical_crossentropy',
                      metrics=['accuracy'])
        return model

    return create_model


# prepare model
hidden_size = 128

model_base_alice = create_base_model(2, hidden_size)
model_base_bob = create_base_model(2, hidden_size)


# 定义有label的一方，或者server端的模型——fuse_model
def create_fuse_model(input_dim, output_dim, party_numbers, name="fuze_model"):
    def create_model():
        # input
        input_layers = []
        for i in range(party_numbers):
            input_layers.append(
                keras.Input(input_dim)
            )
        merged_layer = layers.concatenate(input_layers)
        fuze_layer = layers.Dense(64, activation='relu')(merged_layer)
        output = layers.Dense(output_dim, activation='softmax')(fuze_layer)

        model = keras.Model(inputs=input_layers, outputs=output)
        model.summary()

        model.compile(
            loss='sparse_categorical_crossentropy',
            optimizer='adam',
            metrics=["accuracy"],
        )
        return model

    return create_model


data_label = sf.reveal(label.partitions[alice].data)
model_fuse = create_fuse_model(input_dim=hidden_size, party_numbers=2, output_dim=len(data_label["target"].unique()))

base_model_dict = {alice: model_base_alice, bob: model_base_bob}

sl_model = SLModel(
    base_model_dict=base_model_dict,
    device_y=alice,
    model_fuse=model_fuse
)

print(sf.reveal(test_data.partitions[alice].data), sf.reveal(
    test_label.partitions[alice].data
))

print(sf.reveal(train_data.partitions[bob].data))
print("****************************************************")
history = sl_model.fit(
    train_data,
    train_label,
    validation_data=(test_data, test_label),
    epochs=10,
    batch_size=train_batch_size,
    shuffle=True,
    verbose=1,
    validation_freq=1
)

print(sl_model.evaluate(test_data, test_label))


save_params = {
    "save_traces": True,
    "save_format": "h5"
}
print("save model")
sl_model.save_model(base_model_path="./base_model.h5",
                    fuse_model_path="./fuze_model.h5",
                    is_test=True,
                    save_traces=True,
                    save_format="h5")
print("load model")

predict_model = SLModel(device_y=alice)
predict_model.load_model(base_model_path="./base_model.h5",
                         fuse_model_path="./fuze_model.h5",
                         is_test=True)

print(predict_model)
print("evaluate data")
print(predict_model.evaluate(test_data, test_label))
```

**Comment by zhangxingmeng** [comment]
![image](https://github.com/secretflow/secretflow/assets/103552200/73b525e1-bfe8-4bc2-82b3-1b1b84b0f1a3)
base_model_dict是必须项，里面包含的parties意味着这几方有特征输入。预先不知道网络结构可以填None

**Comment by Niclouge** [comment]
好的，已经解决
