### ISSUE TITLE
运行黑名单共享查询示例时显示BRPC连接失败

### ISSUE THREAD

**Issue by l-tang** [secretflow/secretflow#939]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 1.1.0b0

### OS Platform and Distribution

Linux Ubuntu20.04

### Python version

3.8.18

### What happend and What you expected to happen.

```shell
您好，我尝试使用两台通过pypi安装过secretflow的服务器完成星河杯“黑名单共享查询”赛题，参照
https://mp.weixin.qq.com/s/ZXjC88VH0CQlt31E0WVvZw
这篇文章中的步骤运行。

首先在ip为alice和bob的两台机器上都启动了ray：
ray start --head --node-ip-address="alice" --port="6379" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats

ray start --head --node-ip-address="bob" --port="6379" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats

运行后的ray status命令返回：
======== Autoscaler status: 2023-10-10 03:21:42.922522 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_1ec6cfa53de8268c838325be6c2eb6fc395ab30097497e1b748e81e0
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/8.0 CPU
 0.0/16.0 alice
 0.00/6.350 GiB memory
 0.00/3.175 GiB object_store_memory

Demands:
 (no resource demands)

之后，我在bob机器上运行命令
dd if=/dev/urandom of=oprf_key.bin bs=32 count=1
以及
git clone https://github.com/secretflow/spu.git

自己手动在bob服务器上构建了一个数据文件B_PIR_DATA.csv，之后输入
python examples/python/pir/pir_setup.py --in_path B_PIR_DATA.csv \
--key_columns id --label_columns register_date,age \
--count_per_query 1 -max_label_length 18 \
--oprf_key_path oprf_key.bin --setup_path setup_path

B_PIR_DATA.csv的内容为：
id,register_date,age
167019600627484111,2008-10-29,36
623049248851670423,2011-12-14,32
453108121117357944,2008-11-22,43

之后使用使用nc -lp 40222 &命令分别在alice和bob上开启40222和40224端口，然后在bob服务器上输入
python spu/examples/python/pir/pir_server.py --party_ips alice:40222,bob:40224 --rank 1 --oprf_key_path oprf_key.bin --setup_path setup_path --enable_tls True --link_server_certificate server.crt --link_server_private_key server.key --link_server_ca ca.crt --link_client_certificate client.crt --link_client_private_key client.key --link_client_ca ca.crt

出现报错：
id_0 = alice:40222
id_1 = bob:40224
2023-10-10 04:01:35.799 [error] [server.cpp:BRPC:1023] Fail to listen 127.0.0.1:40224
2023-10-10 04:01:35.808 [warning] [channel.h:~Channel:151] Channel destructor is called before WaitLinkTaskFinish, try stop send thread
Traceback (most recent call last):
  File "spu/examples/python/pir/pir_server.py", line 94, in <module>
    app.run(main)
  File "/home/tsingj_ubuntu/anaconda3/envs/sf/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/tsingj_ubuntu/anaconda3/envs/sf/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "spu/examples/python/pir/pir_server.py", line 87, in main
    link_ctx = setup_link(FLAGS.rank)
  File "spu/examples/python/pir/pir_server.py", line 70, in setup_link
    return link.create_brpc(lctx_desc, rank)
RuntimeError: what: 
        [external/yacl/yacl/link/transport/brpc_link.cc:130] brpc server failed start
Stacktrace:
#0 yacl::link::FactoryBrpc::CreateContext()+0x7fc76b24d799
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fc769d74ad6
#2 pybind11::cpp_function::dispatcher()+0x7fc769d571c6
#3 PyCFunction_Call+0x4f5572

stacktrace: 
#0 yacl::link::FactoryBrpc::CreateContext()+0x7fc76b24d799
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fc769d74ad6
#2 pybind11::cpp_function::dispatcher()+0x7fc769d571c6
#3 PyCFunction_Call+0x4f5572

上面提到的Fail to listen 127.0.0.1:40224，我在alice和bob上运行telnet bob 40224显示均为可以连通：
Trying 127.0.0.1...
Connected to bob.
Escape character is '^]'.

请问如何解决该问题？谢谢！
```

### Reproduction code to reproduce the issue.

```shell
Alice侧：
ray start --head --node-ip-address="alice" --port="6379" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats

nc -lp 40222 &

Bob侧：
ray start --head --node-ip-address="bob" --port="6379" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats

dd if=/dev/urandom of=oprf_key.bin bs=32 count=1

git clone https://github.com/secretflow/spu.git

python examples/python/pir/pir_setup.py --in_path B_PIR_DATA.csv \
--key_columns id --label_columns register_date,age \
--count_per_query 1 -max_label_length 18 \
--oprf_key_path oprf_key.bin --setup_path setup_path

nc -lp 40224 &

python spu/examples/python/pir/pir_server.py --party_ips alice:40222,bob:40224 --rank 1 --oprf_key_path oprf_key.bin --setup_path setup_path --enable_tls True --link_server_certificate server.crt --link_server_private_key server.key --link_server_ca ca.crt --link_client_certificate client.crt --link_client_private_key client.key --link_client_ca ca.crt
```

**Comment by zhanglei486** [comment]
上面的脚本中nc -lp 40224 & 已经占用了40224端口

python spu/examples/python/pir/pir_server.py --party_ips alice:40222,bob:40224 --rank 1 。。。
运行pir_server.py 时bob端需要使用40224端口，已经被nc占用了

**Comment by l-tang** [comment]
> 上面的脚本中nc -lp 40224 & 已经占用了40224端口
> 
> python spu/examples/python/pir/pir_server.py --party_ips alice:40222,bob:40224 --rank 1 。。。 运行pir_server.py 时bob端需要使用40224端口，已经被nc占用了

谢谢您的回复。但是如果不运行nc命令的话，比如我直接换成两个新的端口：
python spu/examples/python/pir/pir_server.py --party_ips alice:40226,bob:40228 --rank 1 --oprf_key_path oprf_key.bin --setup_path setup_path --enable_tls True --link_server_certificate s
erver.crt --link_server_private_key server.key --link_server_ca ca.crt --link_client_certificate client.crt --link_client_private_key client.key --link_client_ca ca.crt

运行时根本无法连上
id_0 = alice:40226
id_1 = bob:40228
2023-10-10 07:43:47.757 [info] [default_brpc_retry_policy.cc:DoRetry:52] socket error, sleep=1000000us and retry
2023-10-10 07:43:48.757 [info] [default_brpc_retry_policy.cc:LogHttpDetail:29] cntl ErrorCode '112', http status code '200', response header '', error msg '[E111]Fail to connect Socket{id=0 addr=10.90.4.56:40226} (0x0x1a81d00): Connection refused [R1][E112]Not connected to 10.90.4.56:40226 yet, server_id=0'
2023-10-10 07:43:48.757 [info] [default_brpc_retry_policy.cc:DoRetry:75] aggressive retry, sleep=1000000us and retry
2023-10-10 07:43:49.758 [info] [default_brpc_retry_policy.cc:LogHttpDetail:29] cntl ErrorCode '112', http status code '200', response header '', error msg '[E111]Fail to connect Socket{id=0 addr=10.90.4.56:40226} (0x0x1a81d00): Connection refused [R1][E112]Not connected to 10.90.4.56:40226 yet, server_id=0 [R2][E112]Not connected to 10.90.4.56:40226 yet, server_id=0'
2023-10-10 07:43:49.758 [info] [default_brpc_retry_policy.cc:DoRetry:75] aggressive retry, sleep=1000000us and retry
2023-10-10 07:43:51.788 [info] [default_brpc_retry_policy.cc:LogHttpDetail:29] cntl ErrorCode '112', http status code '200', response header '', error msg '[E112]Not connected to 10.90.4.56:40226 yet, server_id=0'
2023-10-10 07:43:51.788 [info] [default_brpc_retry_policy.cc:DoRetry:75] aggressive retry, sleep=1000000us and retry

而且从bob使用telnet alice 40226也显示无法连接
Trying alice...
telnet: Unable to connect to remote host: Connection refused

我理解nc命令就是用来开启一个端口从而让其他服务器完成连接的吧？

**Comment by wangyixianggogo** [comment]
1、client 用A_PIR_ID.csv，server用B_PIR_DATA.csv，spu whl用0.3.2b12，examples/python/pir/*.py 可以从spu github下载 git clone https://github.com/secretflow/spu.git
2、在server机器执行dd if=/dev/urandom of=oprf_key.bin bs=32 count=1生成安全方案
3、首先在server机器执行setup，对服务端数据文件csv格式，进行预处理；后面在客户端（client）和服务器（server）同时进行server跟client脚本。
PS：--partyips ip0:port0,ip1:port1 --rank 0/1
指定本方是rank 0 时，必须有ip0, 端口port0没有被占用
指定本方是rank 1 时，必须有ip1, 端口port1没有被占用

**Comment by l-tang** [comment]
> 1、client 用A_PIR_ID.csv，server用B_PIR_DATA.csv，spu whl用0.3.2b12，examples/python/pir/*.py 可以从spu github下载 git clone https://github.com/secretflow/spu.git 2、在server机器执行dd if=/dev/urandom of=oprf_key.bin bs=32 count=1生成安全方案 3、首先在server机器执行setup，对服务端数据文件csv格式，进行预处理；后面在客户端（client）和服务器（server）同时进行server跟client脚本。 PS：--partyips ip0:port0,ip1:port1 --rank 0/1 指定本方是rank 0 时，必须有ip0, 端口port0没有被占用 指定本方是rank 1 时，必须有ip1, 端口port1没有被占用

谢谢您的回复。关于1、2两步我应该都完成了，除了spu用的是0.5.0b0
第3点的setup我之前也执行了，忘记写在问题里了：
python examples/python/pir/pir_setup.py --in_path B_PIR_DATA.csv --key_columns id --label_columns register_date,age --count_per_query 1 -max_label_length 18 --oprf_key_path oprf_key.bin --setup_path setup_path

然后运行的
python examples/python/pir/pir_server.py --party_ips alice:40222,bob:40223 --rank 1 --oprf_key_path oprf_key.bin --setup_path setup_path --enable_tls True --link_server_certificate server.crt --link_server_private_key server.key --link_server_ca ca.crt --link_client_certificate client.crt --link_client_private_key client.key --link_client_ca ca.crt

这里报错
id_0 = alice:40222
id_1 = bob:40223
2023-10-10 10:22:18.611 [error] [server.cpp:BRPC:1023] Fail to listen 127.0.0.1:40223
2023-10-10 10:22:18.619 [warning] [channel.h:~Channel:151] Channel destructor is called before WaitLinkTaskFinish, try stop send thread
Traceback (most recent call last):
  File "examples/python/pir/pir_server.py", line 94, in <module>
    app.run(main)
  File "/home/tsingj_ubuntu/anaconda3/envs/sf/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/tsingj_ubuntu/anaconda3/envs/sf/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "examples/python/pir/pir_server.py", line 87, in main
    link_ctx = setup_link(FLAGS.rank)
  File "examples/python/pir/pir_server.py", line 70, in setup_link
    return link.create_brpc(lctx_desc, rank)
RuntimeError: what: 
        [external/yacl/yacl/link/transport/brpc_link.cc:130] brpc server failed start
Stacktrace:
#0 yacl::link::FactoryBrpc::CreateContext()+0x7f9c5001b799
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f9c4eb42ad6
#2 pybind11::cpp_function::dispatcher()+0x7f9c4eb251c6
#3 PyCFunction_Call+0x4f5572

stacktrace: 
#0 yacl::link::FactoryBrpc::CreateContext()+0x7f9c5001b799
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7f9c4eb42ad6
#2 pybind11::cpp_function::dispatcher()+0x7f9c4eb251c6
#3 PyCFunction_Call+0x4f5572

我尝试测试了一下brpc连接，也是失败的。现在正在尝试降低spu版本至0.3.2b12以解决这个问题，但是我觉得似乎不是这个问题，而是我没有掌握spu中brpc连接的构建方式。

**Comment by l-tang** [comment]
已经尝试将spu降为0.3.2b12，报错没有改变。

**Comment by wangyixianggogo** [comment]
看起来不是版本的问题，如果确定端口号没有被占用的话，检查下数据文件的路径和证书试试呢？如果没有证书，可以不添加后面的证书参数

**Comment by wangyixianggogo** [comment]
方便添加一下隐语技术支持的微信号secretflow02吗？可以看看能否线上帮您解决一下～

**Comment by l-tang** [comment]
> 方便添加一下隐语技术支持的微信号secretflow02吗？可以看看能否线上帮您解决一下～

您好，刚刚添加了这个微信号，非常感谢您的帮助。
您指的证书是TLS吗？我之前配置过TLS，但是感觉没有什么用，于是就没有加这个了。
