### ISSUE TITLE
请问在SF的生产模式下中如何使用可联通的两台服务器完成PSI任务？

### ISSUE THREAD

**Issue by from-alice-to-bob** [secretflow/secretflow#940]
### Issue Type

Others

### Source

binary

### Secretflow Version

1.2.0.dev20230918

### OS Platform and Distribution

Linux Ubuntu20.04

### Python version

3.8.18

### What happend and What you expected to happen.

```shell
我和我的同事各自有一台服务器，想完成一次隐私计算求交。两台服务器都是公司内网的，可联通。我的服务器是alice，我通过pypi安装了secretflow，之后启动了ray。之后运行python如下代码

import secretflow as sf


sf.shutdown()
cfg = {
        'parties': {
            'alice': {
                'address': 'localhost:10002'
            },
            'bob': {
                'address': 'bob:10003'
            },
        },
        'self_party': 'alice'
    }

sf.init(
        address='localhost:9000',
        cluster_config=cfg,
    )

alice = sf.PYU('alice')
bob = sf.PYU('bob')

print(alice(lambda x: x)(2))
print(bob(lambda x: x)(2))

服务器一直尝试连接如下：
2023-10-10 10:58:52,583 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: alice:9000...
2023-10-10 10:58:52,593 INFO worker.py:1538 -- Connected to Ray cluster.
2023-10-10 10:58:52 INFO api.py:147 [alice] --  Started rayfed with {'CLUSTER_ADDRESSES': {'alice': 'alice:10002', 'bob': 'bob:10003'}, 'CURRENT_PARTY_NAME': 'alice', 'TLS_CONFIG': {}}
2023-10-10 10:58:52 INFO cleanup.py:58 [alice] --  Start check sending thread.
2023-10-10 10:58:52 INFO cleanup.py:67 [alice] --  Start check sending monitor thread.
2023-10-10 10:58:53 INFO barriers.py:235 [alice] --  Succeeded to create receiver proxy actor.
(ReceiverProxyActor pid=2242535) 2023-10-10 10:58:53 INFO grpc_proxy.py:306 [alice] --  ReceiveProxy binding port 10002, options: (('grpc.enable_retries', 1), ('grpc.so_reuseport', 0), ('grpc.max_send_message_length', 524288000), ('grpc.max_receive_message_length', 524288000), ('grpc.service_config', '{"methodConfig": [{"name": [{"service": "GrpcService"}], "retryPolicy": {"maxAttempts": 5, "initialBackoff": "5s", "maxBackoff": "30s", "backoffMultiplier": 2, "retryableStatusCodes": ["UNAVAILABLE"]}}]}'))...
(ReceiverProxyActor pid=2242535) 2023-10-10 10:58:53 INFO grpc_proxy.py:326 [alice] --  Successfully start Grpc service without credentials.
2023-10-10 10:58:54 INFO barriers.py:283 [alice] --  SenderProxyActor has successfully created.
2023-10-10 10:58:54 INFO barriers.py:438 [alice] --  Try ping ['bob'] at 0 attemp, up to 3600 attemps.
2023-10-10 10:58:57 INFO barriers.py:438 [alice] --  Try ping ['bob'] at 1 attemp, up to 3600 attemps.
2023-10-10 10:59:00 INFO barriers.py:438 [alice] --  Try ping ['bob'] at 2 attemp, up to 3600 attemps.
2023-10-10 10:59:03 INFO barriers.py:438 [alice] --  Try ping ['bob'] at 3 attemp, up to 3600 attemps.
2023-10-10 10:59:06 INFO barriers.py:438 [alice] --  Try ping ['bob'] at 4 attemp, up to 3600 attemps.

同事在bob机器上做了同样的步骤，只是把alice替换成了bob，然后cluster_config里面的self_party替换成了bob。我们几乎同时运行的上面这段python代码，两边都是try ping。是不是secretflow目前还只支持单机的版本？我看spu的文档好像也都是local的例子？

谢谢！
```

### Reproduction code to reproduce the issue.

```shell
ray start --head --node-ip-address="localhost" --port="9000" --resources='{"alice": 16}' --include-dashboard=False --disable-usage-stats
```

**Comment by from-alice-to-bob** [comment]
另外SPU似乎也尚不支持真实的生产场景，比如我使用spu_config构建SPU：

def spu_demo(alice, bob):
    spu_config = {
        'nodes': [
            {
                'party': 'alice',
                'id': 'alice:0',
                'address': 'alice:18881',
                'listen_address': ''
            },
            {
            'party': 'bob',
            'id': 'bob:1',
            'address': 'bob:18882',
            'listen_address': ''
            },
        ],
        'runtime_config': {
            'protocol': spu.spu_pb2.SEMI2K,
            'field': spu.spu_pb2.FM128,
            'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL,
        }
    }
    spu_device = sf.SPU(spu_config)
    # spu_device = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob']))
    data1 = alice(lambda x : x)(2).to(spu_device)
    data2 = bob(lambda x : x)(2).to(spu_device)
    def add(a, b):
        return a + b
    data = spu_device(add)(data1, data2)
    sf.reveal(data)

如果使用sf的parties+address调用这个函数的话，在alice和bob两台机器上同时运行如下代码，会一直报连接错误。
sf.shutdown()
sf.init(
    ['alice', 'bob'],
    address='alice:9000'
)

alice = sf.PYU('alice')
bob = sf.PYU('bob')
spu_demo(alice, bob)

如果改为上面的address+cluster_config的方式初始化sf的话又会遇到上面的问题。不知道是我理解的不对还是目前的secretflow以及SPU都仅支持文档中的单机仿真或者集群仿真模式？除了ray start以外，我的操作流程中并未对上述任何端口做过任何操作，只是通过netstat检查过这些端口号都是未被使用的。我是否需要对这些端口号做什么以使两台服务器完成连接？

谢谢！

**Comment by wangyixianggogo** [comment]
hi，首先请问下您是想实现仿真集群还是生产模式，这两种方式的ray的配置是不同的，出现连接问题，可能跟ray的配置以及sf.init配置、端口号是否占用有关（tips，可以更换端口号试一下，排除端口号重复问题），按照[这里](https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started/deployment#cluster-mode-for-simulation)，修改下试试呢？

**Comment by wangyixianggogo** [comment]
生产模式下每个参与方拥有各自的ray集群，请使用各自节点ray启动时的 node-ip-address 和 port 填充 sf.init 的 address 参数，试试呢？

**Comment by Chrisdehe** [comment]
针对第一个问题，辛苦将alice的所有执行脚本贴一下，另外可以尝试先是否能够ping的到，或者尝试下telnet是否可以连接到，以及将localhost改为真实ip尝试。

针对第二个问题，SPU支持生产模式
具体配置为：
ray start --head --node-ip-address="alice" --port="9394" --include-dashboard=False --disable-usage-stats
ray start --head --node-ip-address="bob" --port="9395" --include-dashboard=False --disable-usage-stats


`cluster_config ={
    'parties': {
        'alice': {
            'address': 'alice:9494',
        },
        'bob': {
            'address': 'alice:9495',     
        },
    },
    'self_party': 'alice'
}


import spu
spu_def = {
  'nodes': [
    {
      'party': 'alice',
      'id': '0',
      'address': 'alice:9594'
    },
    {
      'party': 'bob',
      'id': '1',
      'address': 'bob:9595'
    }
  ],
  'runtime_config': {
    'protocol': spu.spu_pb2.SEMI2K,
    'field': spu.spu_pb2.FM128,
    'sigmoid_mode': spu.spu_pb2.RuntimeConfig.SIGMOID_REAL
  }
}`
  sf.init(address='alice:9395',//(如果是bob就填写bob的ip:port)
        cluster_config=cluster_config, 
    )

    spu = sf.SPU(cluster_def=cluster_def)

**Comment by from-alice-to-bob** [comment]
> 生产模式下每个参与方拥有各自的ray集群，请使用各自节点ray启动时的 node-ip-address 和 port 填充 sf.init 的 address 参数，试试呢？

谢谢您的回复。
address目前指ip和端口就是各自ray的node-ip-address和port。如果是指cluster_config里面的address的话，一旦把端口换成ray的端口，就会报错无法监听：
2023-08-24 16:49:29,267 INFO worker.py:1431 -- Connecting to existing Ray cluster at address: alice:9000...
2023-08-24 16:49:29,278 INFO worker.py:1621 -- Connected to Ray cluster.
2023-08-24 16:49:29 INFO api.py:147 [alice] --  Started rayfed with {'CLUSTER_ADDRESSES': {'alice': 'alice:9000', 'bob': 'bob:9000'}, 'CURRENT_PARTY_NAME': 'alice', 'TLS_CONFIG': {}}
2023-08-24 16:49:29 INFO cleanup.py:58 [alice] --  Start check sending thread.
2023-08-24 16:49:29 INFO cleanup.py:67 [alice] --  Start check sending monitor thread.
Traceback (most recent call last):
  File "demo.py", line 178, in <module>
    sf.init(
  File "/usr/local/lib/python3.8/site-packages/secretflow/device/driver.py", line 557, in init
    fed.init(
  File "/usr/local/lib/python3.8/site-packages/fed/api.py", line 178, in init
    _start_receiver_proxy(
  File "/usr/local/lib/python3.8/site-packages/fed/proxy/barriers.py", line 234, in _start_receiver_proxy
    assert server_state[0], server_state[1]
AssertionError: Grpc server failed to listen to port: 9000 Try another port by setting `listen_addr` into `cluster` config when calling `fed.init`. Grpc error msg: Failed to bind to address [::]:9000; set GRPC_VERBOSITY=debug environment variable to see detailed error message.
