### ISSUE TITLE
本地编译secretflow失败

### ISSUE THREAD

**Issue by mtl802** [secretflow/secretflow#961]
### Issue Type

Build/Install

### Source

source

### Secretflow Version

secretflow-1.2.0.dev20231016-cp311-cp311-manylinux2014_x86_64

### OS Platform and Distribution

centos7

### Python version

Python 3.8.0

### What happend and What you expected to happen.

```shell
使用sudo python setup.py bdist_wheel命令编译后出现问题：
Requirements:  ['#', '# FEATURE=[lite] is a specific comment, indicating that this dependency will be', '# used as a dependency of secretflow-lite.', '#', '# Avoid thead pool fork issue, see https://github.com/grpc/grpc/issues/31772', 'clean-text  # FEATURE=[lite]', 'click  # FEATURE=[lite]', 'grpcio==1.56.2   # FEATURE=[lite]', 'jax<=0.4.12  # FEATURE=[lite]', 'jaxlib<=0.4.12  # FEATURE=[lite]', 'kuscia==0.0.1b2  # FEATURE=[lite]', 'multiprocess  # FEATURE=[lite]', 'networkx==2.8.8', 'numba==0.57.0  # FEATURE=[lite]', 'numpy==1.23.5  # FEATURE=[lite]', '# TODO: onnx and tensorflow have dependency conflicts, waiting for upstream to resolve', '# onnx==1.13.1', 'pandas==1.5.3  # FEATURE=[lite]', '# For security reason.', 'protobuf==3.19.6  # FEATURE=[lite]', 'pyarrow==11.0.0  # FEATURE=[lite]', 's3fs==2022.1.0', 'scikit-learn==1.1.3  # FEATURE=[lite]', 'sdc-apis==0.1.0b0; platform_system != "Darwin"  # FEATURE=[lite]', 'sdc-sdk==0.1.0b0; platform_system != "Darwin"  # FEATURE=[lite]', 'secretflow-rayfed==0.2.0a7 # FEATURE=[lite]', '# For security reason. This is introduced by TensorFlow.', 'setuptools>=65.5.1', 'sparse>=0.14.0', 'spu==0.6.0.dev20230922  # FEATURE=[lite]', 'sf-heu==0.4.4b0  # FEATURE=[lite]', 'tensorflow-macos==2.11.0; platform_machine == "arm64" and platform_system == "Darwin"', 'tensorflow==2.11.1; platform_machine != "arm64"', 'tf2onnx>=1.13.0', 'tqdm', 'validator.py==1.3.0', 'xgboost==1.7.5', '# For security reason.', 'wheel>=0.38.1', 'torch==2.0.0', 'torchmetrics==0.11.4', 'torchvision==0.15.1', 'torchaudio==2.0.1']
Dependency:  ['--extra-index-url https://download.pytorch.org/whl/cpu']
/home/datanet/miniconda2/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running bdist_wheel
running build
running build_py
copying secretflow/version.py -> build/lib.linux-x86_64-cpython-38/secretflow
running build_ext
bazel build //secretflow_lib/binding:_lib.so --symlink_prefix=build/temp.linux-x86_64-cpython-38/bazel- --compilation_mode=opt --config=avx
DEBUG: Rule 'yacl' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1696831165 -0500"
DEBUG: Repository yacl instantiated at:
  /data/project/secretflow/WORKSPACE:5:15: in <toplevel>
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/5934265e10a443484f56787e12221cd0/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //secretflow_lib/binding:_lib.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //secretflow_lib/binding:_lib.so up-to-date:
  build/temp.linux-x86_64-cpython-38/bazel-bin/secretflow_lib/binding/_lib.so
INFO: Elapsed time: 0.253s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
/home/datanet/miniconda2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
copying build/lib.linux-x86_64-cpython-38/secretflow/security/privacy/_lib.cpython-38m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/secretflow/security/privacy
copying build/lib.linux-x86_64-cpython-38/secretflow/version.py -> build/bdist.linux-x86_64/wheel/secretflow
running install_egg_info
running egg_info
writing secretflow.egg-info/PKG-INFO
writing dependency_links to secretflow.egg-info/dependency_links.txt
writing entry points to secretflow.egg-info/entry_points.txt
writing requirements to secretflow.egg-info/requires.txt
writing top-level names to secretflow.egg-info/top_level.txt
reading manifest file 'secretflow.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'secretflow.egg-info/SOURCES.txt'
removing 'build/bdist.linux-x86_64/wheel/secretflow-1.2.0.dev20231018-py3.8.egg-info' (and everything under it)
Copying secretflow.egg-info to build/bdist.linux-x86_64/wheel/secretflow-1.2.0.dev20231018-py3.8.egg-info
running install_scripts
Traceback (most recent call last):
  File "setup.py", line 198, in <module>
    setup(
  File "/home/datanet/miniconda2/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/datanet/miniconda2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/datanet/miniconda2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/datanet/miniconda2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/datanet/miniconda2/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/datanet/miniconda2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/datanet/miniconda2/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 380, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/home/datanet/miniconda2/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 329, in get_tag
    assert (
AssertionError: would build wheel with unsupported tag ('cp38', 'cp38m', 'manylinux2014_x86_64')
```

### Reproduction code to reproduce the issue.

```shell
sudo python setup.py bdist_wheel
```

**Comment by mtl802** [comment]
已解决，更换python虚拟环境即可
