### ISSUE TITLE
bazel build报错

### ISSUE THREAD

**Issue by xiaoqing928** [secretflow/secretflow#985]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

0.6

### OS Platform and Distribution

centos7

### Python version

3.8

### What happend and What you expected to happen.

```shell
使用bazel build c++项目时，找不到外部yacl库，请问该如何解决？
```

### Reproduction code to reproduce the issue.

```shell
(base) [app@localhost cpp]$ bazel build //examples/cpp:simple_psi
Starting local Bazel server and connecting to it...
INFO: Repository yacl instantiated at:
  /data/projects/install/spu-main/WORKSPACE:19:9: in <toplevel>
  /data/projects/install/spu-main/bazel/repositories.bzl:44:10: in spu_deps
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule git_repository defined at:
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl:181:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'yacl':
   Traceback (most recent call last):
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl", line 175, column 35, in _git_repository_implementation
		update = _clone_or_update_repo(ctx)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update_repo
		git_ = git_repo(ctx, directory)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 109, column 10, in _update
		fetch(ctx, git_repo)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 143, column 13, in fetch
		_git(
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 179, column 15, in _git
		_error(ctx.name, start + list(args), st.stderr)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 200, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @yacl:
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
ERROR: /data/projects/install/spu-main/WORKSPACE:19:9: fetching git_repository rule //external:yacl: Traceback (most recent call last):
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl", line 175, column 35, in _git_repository_implementation
		update = _clone_or_update_repo(ctx)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update_repo
		git_ = git_repo(ctx, directory)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 109, column 10, in _update
		fetch(ctx, git_repo)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 143, column 13, in fetch
		_git(
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 179, column 15, in _git
		_error(ctx.name, start + list(args), st.stderr)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 200, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @yacl:
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
ERROR: Error computing the main repository mapping: no such package '@yacl//bazel': error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @yacl:
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
```

**Comment by wangyixianggogo** [comment]
hi，看起来是你的网络问题，网不太好，可以换一下网络试试，如果遇到问题欢迎反馈～

**Comment by xiaoqing928** [comment]
是的，切换网络后大部分依赖都可以正常拉取到，但又出现了新的问题，下载bazel某个库时报了404，问题详情如下：
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository go_sdk instantiated at:
  /data/projects/install/spu-main/WORKSPACE:59:15: in <toplevel>
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/xla/workspace0.bzl:52:19: in workspace
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/tsl/workspace0.bzl:130:20: in workspace
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:56:27: in grpc_extra_deps
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/io_bazel_rules_go/go/private/sdk.bzl:424:24: in go_register_toolchains
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/io_bazel_rules_go/go/private/sdk.bzl:42:17: in go_host_sdk
Repository rule _go_host_sdk defined at:
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/io_bazel_rules_go/go/private/sdk.bzl:36:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/io_bazel_rules_go/go/private/sdk.bzl", line 31, column 30, in _go_host_sdk_impl
		goroot = _detect_host_sdk(ctx)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/io_bazel_rules_go/go/private/sdk.bzl", line 301, column 13, in _detect_host_sdk
		fail("Could not detect host go version")
Error in fail: Could not detect host go version
ERROR: /data/projects/install/spu-main/WORKSPACE:59:15: fetching _go_host_sdk rule //external:go_sdk: Traceback (most recent call last):
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/io_bazel_rules_go/go/private/sdk.bzl", line 31, column 30, in _go_host_sdk_impl
		goroot = _detect_host_sdk(ctx)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/io_bazel_rules_go/go/private/sdk.bzl", line 301, column 13, in _detect_host_sdk
		fail("Could not detect host go version")
Error in fail: Could not detect host go version
ERROR: Analysis of target '//examples/cpp:simple_psi' failed; build aborted: Could not detect host go version
INFO: Elapsed time: 0.534s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @bazel_tools//tools/jdk

**Comment by wangyixianggogo** [comment]
hi，Could not detect host go version，先手动装下go环境试试呢？

**Comment by xiaoqing928** [comment]
嗯嗯，看了报错后自己摸索下，这块的内容我上午已经配好了，感谢。
但现在又遇到了新的问题，在编译时会报如下错误：
-------------------------------------------------------------------------------------
external/yacl/yacl/crypto/primitives/ot/ot_store.cc:94:63:   required from here
external/yacl/yacl/base/dynamic_bitset.h:2294:20: error: division by zero is not a constant expression
 2294 |   constexpr size_t init_val_required_blocks = u128_bits_number / bits_per_block;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~
Target //examples/cpp:simple_psi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4356.700s, Critical Path: 2990.63s
INFO: 378 processes: 22 internal, 356 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
-------------------------------------------------------------------------------------

翻阅spu历史问题，发现可能是gcc版本的问题，但将gcc版本升级至11.2之后，编译仍然报错，请问是什么原因呢？gcc版本如下：
(base) [app@localhost spu-main]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-11/root/usr --mandir=/opt/rh/devtoolset-11/root/usr/share/man --infodir=/opt/rh/devtoolset-11/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.2.1-20220127/obj-x86_64-redhat-linux/isl-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC)

**Comment by xiaoqing928** [comment]
嗯嗯，看了报错后自己摸索下，这块的内容我上午已经配好了，感谢。
但现在又遇到了新的问题，在编译时会报如下错误：
external/yacl/yacl/crypto/primitives/ot/ot_store.cc:94:63: required from here
external/yacl/yacl/base/dynamic_bitset.h:2294:20: error: division by zero is not a constant expression
2294 | constexpr size_t init_val_required_blocks = u128_bits_number / bits_per_block;
| ^~~~~~~~~~~~~~~~~~~~~~~~
Target //examples/cpp:simple_psi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4356.700s, Critical Path: 2990.63s
INFO: 378 processes: 22 internal, 356 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
翻阅spu历史问题，发现可能是gcc版本的问题，但将gcc版本升级至11.2之后，编译仍然报错，请问是什么原因呢？gcc版本如下：
(base) [app@localhost spu-main]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-11/root/usr --mandir=/opt/rh/devtoolset-11/root/usr/share/man --infodir=/opt/rh/devtoolset-11/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.2.1-20220127/obj-x86_64-redhat-linux/isl-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC)

**Comment by xiaoqing928** [comment]
嗯嗯，看了报错后自己摸索下，这块的内容我上午已经配好了，感谢。
但现在又遇到了新的问题，在编译时仍会报错。翻阅spu历史问题，发现可能是gcc版本的问题，但将gcc版本升级至11.2之后，编译仍然报错，发现安装了gcc-11.2，编译时仍然调用的gcc-9，请教该如何解决呢？
1、gcc版本如下：
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-11/root/usr --mandir=/opt/rh/devtoolset-11/root/usr/share/man --infodir=/opt/rh/devtoolset-11/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.2.1-20220127/obj-x86_64-redhat-linux/isl-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC) 
2、编译时，发现仍然时gcc-9的版本
(base) [app@localhost profile.d]$ cd /data/projects/install/spu-main/
(base) [app@localhost spu-main]$ bazel build //examples/cpp:simple_psi
INFO: Analyzed target //examples/cpp:simple_psi (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
ERROR: /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/zlib/BUILD.bazel:24:20: Foreign Cc - CMake: Building zlib failed: (Exit 1): bash failed: error executing command (from target @zlib//:zlib) /bin/bash -c bazel-out/k8-fastbuild/bin/external/zlib/zlib_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library zlib

Environment:______________
TMPDIR=/tmp
LD_LIBRARY_PATH=/opt/rh/devtoolset-11/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib:/opt/rh/devtoolset-11/root/usr/lib64/dyninst:/opt/rh/devtoolset-11/root/usr/lib/dyninst:/opt/rh/devtoolset-11/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib:/opt/rh/devtoolset-11/root/usr/lib64/dyninst:/opt/rh/devtoolset-11/root/usr/lib/dyninst
BUILD_WRAPPER_SCRIPT=bazel-out/k8-fastbuild/bin/external/zlib/zlib_foreign_cc/wrapper_build_script.sh
EXT_BUILD_ROOT=/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib
INSTALLDIR=/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib/bazel-out/k8-fastbuild/bin/external/zlib/zlib
PATH=/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib:/home/app/anaconda3/bin:/opt/rh/devtoolset-11/root/usr/bin:/home/app/anaconda3/bin:/home/app/anaconda3/bin:/home/app/anaconda3/condabin:/home/app/anaconda3/bin:/opt/rh/devtoolset-11/root/usr/bin:/usr/local/cmake/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/go/bin:/home/app/.local/bin:/home/app/bin
BUILD_TMPDIR=/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib/bazel-out/k8-fastbuild/bin/external/zlib/zlib.build_tmpdir
PWD=/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib
EXT_BUILD_DEPS=/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib/bazel-out/k8-fastbuild/bin/external/zlib/zlib.ext_build_deps
SHLVL=3
BUILD_LOG=bazel-out/k8-fastbuild/bin/external/zlib/zlib_foreign_cc/CMake.log
BUILD_SCRIPT=bazel-out/k8-fastbuild/bin/external/zlib/zlib_foreign_cc/build_script.sh
_=/usr/bin/env
__________________________
+ cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_TOOLCHAIN_FILE=/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib/bazel-out/k8-fastbuild/bin/external/zlib/zlib.build_tmpdir/crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib/bazel-out/k8-fastbuild/bin/external/zlib/zlib -DCMAKE_PREFIX_PATH=/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib/bazel-out/k8-fastbuild/bin/external/zlib/zlib.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=ninja -G Ninja /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/sandbox/processwrapper-sandbox/2/execroot/spulib/external/zlib
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_C_COMPILER:

    /opt/rh/devtoolset-9/root/usr/bin/gcc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-fastbuild/bin/external/zlib/zlib_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-fastbuild/bin/external/zlib/zlib_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-fastbuild/bin/external/zlib/zlib_foreign_cc/CMake.log

Target //examples/cpp:simple_psi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.714s, Critical Path: 0.55s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully

**Comment by anakinxc** [comment]
Hi @xiaoqing928 

试一下 `bazel clean --expunge` 然后重新 build

**Comment by xiaoqing928** [comment]
感谢！！这个方法确实有效！
另外请教下，修改某个c++文件后重新编译，使用bazel build的话耗时很久，请问有没有好的方法呢

**Comment by xiaoqing928** [comment]
@anakinxc @wangyixianggogo 
hi~
紧接着上一个问题，我做了如下操作：
1、修改了bucket_psi.cc文件，在文件中新加了几行日志输出；
2、重新bazel build //examples/cpp:simple_psi；
3、执行simple_psi后，发现bucket_psi修改的部分不生效。
我的本意是想要引入或修改协议，从而达到预期的目的，所以修改cpp文件做了简单尝试，发现不行。我对c++以及bazel打包的方式不甚了解，还请帮忙指点一下，感谢！！

**Comment by anakinxc** [comment]
> 3、执行simple_psi后，发现bucket_psi修改的部分不生效。

请问您是怎么执行的呀

**Comment by xiaoqing928** [comment]
1、首次在spu（workspace）路径下执行bazel build //examples/cpp:simple_psi，编译成功后，在当前目录下分别起两个终端执行./bazel-bin/examples/cpp/simple_psi -rank 1 -protocol 1 -in_path ./examples/data/psi_2.csv -field_names id -out_path /tmp/p2.out（两个终端的参数稍有差异）
2、修改了spu/libspu/psi路径下的bucket_psi.cc文件，照猫画虎加了几行日志输出，详情如下：
  MemoryPsiConfig config;
  config.set_psi_type(config_.psi_type());
  SPDLOG_INFO("psi_type set to {}", config_.psi_type());
  config.set_curve_type(config_.curve_type());
  SPDLOG_INFO("curve_type set to {}", config_.curve_type());
  config.set_receiver_rank(config_.receiver_rank());
  SPDLOG_INFO("receiver_rank set to {}", config_.receiver_rank());
  config.set_broadcast_result(config_.broadcast_result());
  SPDLOG_INFO("broadcast_result set to {}", config_.broadcast_result());
3、再次执行步骤1，发现修改的没有生效
