### ISSUE TITLE
安装Secretflow时，无法import Secretflow包

### ISSUE THREAD

**Issue by wind-and-falling-maple-leaf** [secretflow/secretflow#99]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

secretflow        0.6.13b1

### OS Platform and Distribution

centos 7.6

### Python version

Python 3.8.11

### GCC/Compiler version

gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

### What happend and What you expected to happen.

```shell
1.我尝试安装一个secretflow来使用，我确信已经安装了对应的包，当使用pip list时
Package                      Version
---------------------------- ----------
absl-py                      1.0.0
aiobotocore                  2.1.2
aiohttp                      3.8.1
aioitertools                 0.10.0
aiosignal                    1.2.0
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        22.1.0
botocore                     1.23.24
cachetools                   5.2.0
certifi                      2022.6.15
charset-normalizer           2.1.1
click                        8.0.4
cloudpickle                  2.0.0
coverage                     6.4.4
cycler                       0.11.0
distlib                      0.3.5
filelock                     3.8.0
flatbuffers                  2.0.7
fonttools                    4.37.1
frozenlist                   1.3.1
fsspec                       2022.1.0
gast                         0.4.0
google-auth                  2.11.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.47.0
h5py                         3.7.0
idna                         3.3
importlib-metadata           4.12.0
importlib-resources          5.9.0
jax                          0.3.7
jaxlib                       0.3.7
jmespath                     0.10.0
joblib                       1.1.0
jsonschema                   4.14.0
keras                        2.7.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
libclang                     14.0.6
loguru                       0.6.0
lxml                         4.9.1
Markdown                     3.4.1
MarkupSafe                   2.1.1
matplotlib                   3.5.2
msgpack                      1.0.4
multidict                    6.0.2
numpy                        1.22.3
oauthlib                     3.2.0
opt-einsum                   3.3.0
packaging                    21.3
pandas                       1.4.0
Pillow                       9.2.0
pip                          22.2.2
pkgutil_resolve_name         1.3.10
platformdirs                 2.5.2
protobuf                     3.19.4
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pyparsing                    3.0.9
pyrsistent                   0.18.1
python-dateutil              2.8.2
pytz                         2022.2.1
PyYAML                       6.0
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
s3fs                         2022.1.0
scikit-learn                 1.0.2
scipy                        1.9.0
secretflow                   0.6.13b1
secretflow-ray               2.0.0.dev0
setuptools                   65.3.0
sf_heu                       0.1.0b1
six                          1.16.0
spu                          0.1.0b1
tensorboard                  2.10.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.7.1
tensorflow-estimator         2.7.0
tensorflow-io-gcs-filesystem 0.26.0
termcolor                    1.1.0
threadpoolctl                3.1.0
torch                        1.10.1
torchvision                  0.11.2
tqdm                         4.62.3
typing_extensions            4.3.0
unittest-xml-reporting       3.2.0
urllib3                      1.26.12
validator.py                 1.3.0
virtualenv                   20.16.3
Werkzeug                     2.2.2
wheel                        0.37.1
wrapt                        1.14.1
xgboost                      1.5.2
yarl                         1.8.1
zipp                         3.8.1

2.当我在python编译器里执行 import secretflow as sf时：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.8/lib/python3.8/site-packages/secretflow/__init__.py", line 15, in <module>
    from . import data, device, ml, preprocessing, security, utils
  File "/usr/local/python3.8/lib/python3.8/site-packages/secretflow/data/__init__.py", line 15, in <module>
    from . import horizontal, vertical
  File "/usr/local/python3.8/lib/python3.8/site-packages/secretflow/data/horizontal/__init__.py", line 15, in <module>
    from .dataframe import HDataFrame
  File "/usr/local/python3.8/lib/python3.8/site-packages/secretflow/data/horizontal/dataframe.py", line 19, in <module>
    import pandas as pd
  File "/usr/local/python3.8/lib/python3.8/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.core.api import (
  File "/usr/local/python3.8/lib/python3.8/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/usr/local/python3.8/lib/python3.8/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/usr/local/python3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 70, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/python3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 158, in <module>
    from pandas.core.generic import NDFrame
  File "/usr/local/python3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 129, in <module>
    from pandas.core.describe import describe_ndframe
  File "/usr/local/python3.8/lib/python3.8/site-packages/pandas/core/describe.py", line 38, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/usr/local/python3.8/lib/python3.8/site-packages/pandas/io/formats/format.py", line 99, in <module>
    from pandas.io.common import (
  File "/usr/local/python3.8/lib/python3.8/site-packages/pandas/io/common.py", line 4, in <module>
    import bz2
  File "/usr/local/python3.8/lib/python3.8/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

3.非常感谢
```

### Reproduction code to reproduce the issue.

```shell
import secretflow as sf
```

**Comment by anakinxc** [comment]
看起来似乎和这个问题很像 https://stackoverflow.com/questions/22346269/bz2-is-module-not-available-when-installing-pandas-with-pip-in-python-virtual

问一下你的 python 是怎么安装的呀

**Comment by wind-and-falling-maple-leaf** [comment]
非常感谢@anakinxc
我是使用压缩包来安装的。

步骤：
解压 进入
./configure --prefix=/usr/local/python3.8
make
make install

cd /usr/bin
mv python python.bak
ln -s /usr/local/python3.8/bin/python3.8 /usr/bin/python

mv pip pip.bak
ln -s /usr/local/python3.8/bin/pip3.8 /usr/bin/pip

**Comment by anakinxc** [comment]
> 非常感谢@anakinxc 我是使用压缩包来安装的。
> 
> 步骤： 解压 进入 ./configure --prefix=/usr/local/python3.8 make make install
> 
> cd /usr/bin mv python python.bak ln -s /usr/local/python3.8/bin/python3.8 /usr/bin/python
> 
> mv pip pip.bak ln -s /usr/local/python3.8/bin/pip3.8 /usr/bin/pip

ok，那试一下 stackoverflow 里面的解决方法应该管用。安装一下 bz2 然后重新编译 python

**Comment by wind-and-falling-maple-leaf** [comment]
非常感谢，此问题已经解决，如果您有时间可以帮我看看我新提的issue https://github.com/secretflow/secretflow/issues/102 @anakinxc
